### ISSUE TITLE
Allow for self-reported playtime tracking for video games

### ISSUE THREAD

**Issue by UnToobed** [IgnisDa/ryot#101]
Right now there is no way to set the amount of time you have played a video game in hours. Would be a very nice addition. Extending on that, it would be nice to be able to sort your game library on most and least amount played.

### Suggestions
* Add self-reported playtime tracker
* Sort library based on playtime

**Comment by UnToobed** [comment]
> What do you mean by playtime here?
In this case I am thinking hours played. I feel the play history already fills the function you described with 3 months as you can see when you started it and when you finished it over a period of time.

I'm thinking something like this:
![image](https://github.com/IgnisDa/ryot/assets/116106350/5ea34f8d-eba4-43eb-8e88-ed62ef521070)

And yeah I figured sorting mihgt be a bit optimistic this early on so just having a small box for inputting the amount of hours would be nice. Great work so far! 😄

**Comment by IgnisDa** [comment]
So #52 will allow you to edit a media item and set details this parameter. I think this should suffice right?

**Comment by UnToobed** [comment]
Yeah maybe having a menu for custom values where i put the "Set playtime" button so you can add any value you'd like to a game / movie etc. So yeah #52 could definitely fill that void.

**Comment by IgnisDa** [comment]
Cool. Closing this in favor of #52.
