### ISSUE TITLE
[FEATURE REQUEST] - Rating based on emojis ✨

### ISSUE THREAD

**Issue by Mihail-Popescu** [IgnisDa/ryot#1018]
On top of rating from 1 to 5 or 1 to 10. An option to rate with either "happy face" "neuter face" or "sad face" emojis.

How AniList does it:

![Screenshot_20240910_085409_Vivaldi](https://github.com/user-attachments/assets/5d812203-2ac1-44c0-8385-7b23052a108f)

![Screenshot_20240910_085424_Vivaldi](https://github.com/user-attachments/assets/4861e4ea-968e-4541-81c4-f494a5658345)

Thanks for coming to my TED talk.

**Comment by Mihail-Popescu** [comment]
Also this is how it looks when selecting the option in the settings: 

![Screenshot_20240910_092213_Vivaldi](https://github.com/user-attachments/assets/3243571d-3aec-4c01-b7f6-e823bac7357e)

**Comment by IgnisDa** [comment]
The 3 point system will only be used in the frontend. What this means for end users: while exporting data, sad will become: 33.3%, neutral will be 66.6% and happy will be 100%.
