### ISSUE TITLE
UI element for removing an entry or review.

### ISSUE THREAD

**Issue by UnToobed** [IgnisDa/ryot#102]
I would like to be able to remove a game from my library if I accidentally added the wrong entry. Likewise I would want to be able to remove a review.

### Suggestions

On the image below maybe a red box next to "update metadata" saying "delete from library" or something similar?
![image](https://github.com/IgnisDa/ryot/assets/116106350/dc5bbd61-e32a-4d0f-a338-6d7801532d83)

And same here, a red box saying delete review or just a trash can icon to keep it small and simple?
![image](https://github.com/IgnisDa/ryot/assets/116106350/78aba69c-0241-4f4d-8d77-652236df1800)

**Comment by IgnisDa** [comment]
A media item will be automatically removed from your library if it does not support the following conditions:

https://github.com/IgnisDa/ryot/blob/af32a01cea264f14dbbcdb2acbfabbd1b896b3c0/apps/backend/src/migrator/m20230417_000004_create_user.rs#L10-L14

It runs as a cron job, so it might take sometime (10 minutes by default).

> delete review or just a trash can 

Good idea, will work on this.

**Comment by IgnisDa** [comment]
I am curious as to why the font isn't loading in your browser. Do you have the browser forcing a font?
