### ISSUE TITLE
Shows - no way to filter what shows have "pending" aired not yet seen episodes

### ISSUE THREAD

**Issue by dimon222** [IgnisDa/ryot#1023]
Its kind of an interesting problem that Ryot might suffer for a lot of ongoing shows.
Essentially, if upstream TMDB contains information about episodes for future coming season (but not yet released), these episodes are not watchable. Since they're not watchable, its unclear what TV shows in that list of all collections can actually be progressed at current moment (unless you manually monitor calendar).
Perhaps, there should be available an extra filter for Shows that offers to see shows with only aired unwatched episodes (anything prior and including todays date)

**Comment by IgnisDa** [comment]
There is the Unfinished filter for media list pages. Is that not what you need?
![image](https://github.com/user-attachments/assets/3a172097-2fc5-4738-ae02-40554bcf84ee)

**Comment by dimon222** [comment]
Unfinished includes episodes that haven't aired yet.

**Comment by IgnisDa** [comment]
TMDb does not provide enough information to achieve what you want.

**Comment by dimon222** [comment]
Airing (Release time is equivalent) time is shown on most of episodes on TMDB for ongoing shows. If its not shown, then it can assumed unreleased yet.

**Comment by IgnisDa** [comment]
Fair enough. Can you give me instructions to reproduce this on a fresh ryot instance?

**Comment by dimon222** [comment]
I was testing on "The Walking Dead: Daryl Dixon" show.
Marked entire season 1 as watched. Season 2 isn't released yet, and yet its being recognized in "Unfinished" category. If potential new filter is being used (lets say "Unfinished available"), it would not show up in results since Episode 1 of Season 2 isn't yet released (the date of its release is in the future).

**Comment by IgnisDa** [comment]
But there is also the question: why should Ryot consider this show Finished in the first place? There are episodes still left to be watched by the user (regardless of whether released or unreleased) afterall.

**Comment by dimon222** [comment]
That's the problem with this interpretation. "Unfinished" isn't really covering the most general use case - "there's something that can be watched". There likely need extra category like "Unfinished watchable" or such.
Imagine you open Netflix and among 200 movies you see, if you click on 195 on them - it will show they're not actually even released yet. And you can't filter by the ones that are actually available for watching, and have to literally click each of them to find out.

**Comment by IgnisDa** [comment]
Is this problem there with movies as well? The `Finished` tag is applied only to movies once you have atleast one 100% seen entry in your history. If you mark a movie as watched before it is even released, I consider that a user error.

**Comment by dimon222** [comment]
Movies also affected by this kind of behaviour. The tag Finished only applies to movies you did watch, but there is no tag that shows if movie is watchable right now but is in Watchlist.
Sure, I can filter by Release Date, however this release date won't filter what have been released, but is in Watchlist. I would have to manually sort by release date and find out the "cut-off" period.

**Comment by IgnisDa** [comment]
![image](https://github.com/user-attachments/assets/97367bc3-db66-479e-8fa5-2ff7d7e7a8ac)

Does this filter not work for you?

**Comment by dimon222** [comment]
Still shows me the ones that have episodes that haven't been released, for example it finds me Ironheart and Wonder Man in shows, and Blade in Movies.

**Comment by dimon222** [comment]
Assuming it satisfies this requirement (has not yet been watched or haa aired not seen episodes, but is watchable) that could be a way.

**Comment by IgnisDa** [comment]
I have decided to not include this feature since it is not requested by many people.
