### ISSUE TITLE
Workout PR count error

### ISSUE THREAD

**Issue by talkingseedling** [IgnisDa/ryot#1028]
If a set triggers a PR, and you do the same set multiple times in a workout, the PR is counted multiple times. The PR trophy appears against multiple, but not all sets.

Expected behaviour: only the first set counts as a PR.

![image](https://github.com/user-attachments/assets/5dcf5740-a44d-4006-be51-7a4011ea16a3)

![image](https://github.com/user-attachments/assets/23a7e57d-95f5-4c88-a5c5-49cb7ebc3d0d)

**Comment by IgnisDa** [comment]
This is expected behaviour. There are different types of PRs: Weight, Reps etc. If you click on the trophy icon you can see exactly which PRs you achieved.
