### ISSUE TITLE
[Feature Request] Exercise: allow blank weight field

### ISSUE THREAD

**Issue by talkingseedling** [IgnisDa/ryot#1029]
If an exercise can be done with or without weight, it feels more intuitive and quicker to leave the weight field empty, instead of manually entering 0. You currently can't confirm a set until 0 is entered. Is it possible to have 0 be assumed if you tick a set with the weight field empty? If users end up ticking in error before they enter a weight, until they finish the workout the field is still editable.

![image](https://github.com/user-attachments/assets/30998592-6413-4194-b244-30c7546705a9)

**Comment by IgnisDa** [comment]
I'd just recommend you to set in 0 as the weight. These validations do a lot of heavy lifting and removing them would introduce the possibility of the backend messing up big time.

Small tip: if you click on the previous set (20 reps in the second column), it will automatically fill in 0 in the weight column.
