### ISSUE TITLE
Trigger a notification when the workout timer finishes.

### ISSUE THREAD

**Issue by hrmtc** [IgnisDa/ryot#1033]
I think it would be great if the workout timer trigger a notification when the countdown finishes. 
This would improve the timer's functionality, allowing it to be used even with the web app running in the background.

**Comment by IgnisDa** [comment]
![Screenshot_20240929-005712_Ratio](https://github.com/user-attachments/assets/0be6b546-4cc3-4244-b1a6-e03392cdce09)

@hrmtc does this look good?

**Comment by hrmtc** [comment]
Looks great! However, I'm using an iPhone, and I believe Safari doesn't support web notifications. 

Would it be possible to use Apprise or ntfy for this?

Thank you for your excellent work!

**Comment by IgnisDa** [comment]
I'm not sure I want to implement that since logging workout doesn't communicate with the backend at all.

Why can't you use the chrome PWA?

**Comment by hrmtc** [comment]
Hi @IgnisDa,
I was wrong; iOS supports notifications using PWAs with Safari.
I've tested a demo PWA (webpushtest.com), and it works fine. I believe your proposed solution will be sufficient.

I'm eager to try this enhancement. It will be implemented soon?

Thank you!

**Comment by IgnisDa** [comment]
I have not used web push for this feature. I have used the notifications API (though that seems supported by Safari too). https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

This will be released the next weekend.
