### ISSUE TITLE
Activity shows no graph

### ISSUE THREAD

**Issue by iLuckyW** [IgnisDa/ryot#1035]
![image](https://github.com/user-attachments/assets/72a25810-069f-4843-9322-6ff094229a3b)

The activity sections does not show a graph although the time is being calculated correctly.

**Comment by IgnisDa** [comment]
Set `RUST_LOG=ryot=debug` env variable and then Miscellaneous settings and then click on this btn:
![image](https://github.com/user-attachments/assets/5f36c5ef-a381-4f56-9b43-19f88df188be)

Please show me what the docker logs say after you do that.

**Comment by iLuckyW** [comment]
[ryot.log](https://github.com/user-attachments/files/17094125/ryot.log)

These are the logs after restarting with the env and regenerating the summaries.

**Comment by iLuckyW** [comment]
These seem to be all the logs. Here is my database dump
[ryot.file.zip](https://github.com/user-attachments/files/17097561/ryot.file.zip)

**Comment by IgnisDa** [comment]
Thanks for your help. There was a bug in the summary calculation code. Fix will be released this weekend.

**Comment by iLuckyW** [comment]
Amazing project! Thanks for the support.
