### ISSUE TITLE
[FEATURE REQUEST] Grid size options

### ISSUE THREAD

**Issue by Plaged** [IgnisDa/ryot#1036]
It would be great to be able to change the grid size of items (shows, movies...) so we can fit more in the same space, this would be great for mobile as of now there's only 2 items per row, i'd love to be able to switch that to 3 items per row to visualize more items in the screen at once.

**Comment by IgnisDa** [comment]
Can you attach a screenshot of how the grid looks like on your phone? It's look horrible on my phone with 3 columns.

**Comment by Plaged** [comment]
![image](https://github.com/user-attachments/assets/fcad00b6-2f2b-44a8-86c8-854bc7aa6ca4)

**Comment by IgnisDa** [comment]
Not sure why you think 3 columns would look good here?

**Comment by Plaged** [comment]
I'm thinking more like this example, at least on my screen, 2 items can be kinda big and 4 items might result in loss of details, so 3 is the sweet spot for me. 2 gets the job done really well, i just thought it could be nice to change grid size (Like how other platforms like Steam allow you to organize that on your library)
![image](https://github.com/user-attachments/assets/05d86553-0018-4aae-868a-da64523b003c)

**Comment by IgnisDa** [comment]
![image](https://github.com/user-attachments/assets/07e4192d-2310-44c0-812e-acadb3308c31)

You mean like this?

**Comment by Plaged** [comment]
Yeah, exactly! Is that already a thing or some kind of UI Scaling issue on the device settings?
I requested that only because i'm way more used to 3 columns (as an example, the Steam app shows games this way), the only issue i think there could have is text being cut-off more often

**Comment by IgnisDa** [comment]
No this is not inbuilt, i coded it up locally. Can you tell me how steam allows you to configure this value?

**Comment by IgnisDa** [comment]
Aditionally, how does steam handle this option on desktop screen sizes?

**Comment by Plaged** [comment]
On Steam, it's on a setting, under Library, going from Automatic, Small, Medium and Large
![image](https://github.com/user-attachments/assets/4c750017-c71a-49ac-9682-94ea29b0acb1)

That's how it looks like on Automatic (and Large) on a 1440p desktop size
![image](https://github.com/user-attachments/assets/f9da89d4-8ac9-490b-b495-eac60f8cbcff)

Same thing now, but it's set on Small
![image](https://github.com/user-attachments/assets/5be5a0fc-c42d-4acf-86d1-83810301de60)

Unfortunately ever since they released the new Steam app layout and design, the library there is always set to 3 columns on mobile

**Comment by IgnisDa** [comment]
What does automatic do? Is this setting responsive? That is, are you allowed to confiure different settings for mobile and desktop?

**Comment by Plaged** [comment]
Fairly sure that automatic scales to your monitor size based on the pixel-per-inch, on large monitors it will set to medium or small on its own.
As for the second question, no, they have launched a new steam app on mobile and got rid of most settings, it's only account settings and other minor changes you can apply such as notifications and language, so it's a desktop-only thing now.

I'm not sure if that'd work, but I believe that it could be a "local" setting that gets stored as cookies (similar to what Steam does in the desktop executable), this way users can tailor how much information is present on the screen at once for any individual device, as that's all down to personal preference (Disney+, Steam and TV Time shows 3 columns, Max shows 2, Letterboxd shows 4... The example from another app i have included on my second screenshot is pretty much what I was trying to get Ryot grid to look like)

**Comment by Plaged** [comment]
I have made this quick mockup, the text got scaled with the image and is clear enough to read, specially for how many high resolution displays there are (would definitely not work for more than 3 columns i believe unless there's a cap on text size making it more likely to get cut off) It might cause some sizing imbalance and could not be what you're looking for, was just throwing the idea
![image](https://github.com/user-attachments/assets/559392a4-c70b-4c91-b587-587d1f7135cf)

This is the original
![image1](https://github.com/user-attachments/assets/0a083627-a145-470a-ae27-9ecdbffb48d3)

**Comment by IgnisDa** [comment]
What did you change the font sizes to?

**Comment by Plaged** [comment]
Sorry, that was just a mockup on Photoshop, but the text is almost 35% smaller when it's compared the text are from both images if that helps

Thank you for your patience and interest on looking into that!

**Comment by IgnisDa** [comment]
@Plaged 

Does this look fine?

![image](https://github.com/user-attachments/assets/64265006-fada-44e2-8bb1-9537441abbc0)
![image](https://github.com/user-attachments/assets/73222909-572c-403a-82be-b7f86b0a6407)

**Comment by Plaged** [comment]
Yeah, looks perfect!!! Love it

**Comment by IgnisDa** [comment]
This has been merged and will be released next weekend.
