### ISSUE TITLE
Unable to delete OIDC user as admin

### ISSUE THREAD

**Issue by xyrolaith** [IgnisDa/ryot#1039]
While setting up OIDC authentication a user with the wrong name (user@example.com) has been created.

![userlist](https://github.com/user-attachments/assets/73f9e994-cb0c-493a-abfb-d704409c0126)

Trying to delete that user when logged in as an administrator will trigger an "You must be an admin to perform this action" error.
![error](https://github.com/user-attachments/assets/f4b8c865-750f-4591-a8ba-a30b89dfa0ee)

Debugging is already enabled but the log only shows the the request.
```
[frontend] GET /settings/users 302 - - 43.952 ms
[frontend] POST /settings/users.data?intent=delete 200 - - 13.725 ms
```

**Comment by IgnisDa** [comment]
Merged fix. Will be deployed this weekend.
