### ISSUE TITLE
invalid Audiobook plays

### ISSUE THREAD

**Issue by emhl** [IgnisDa/ryot#1042]
I somehow have over 700 plays for one audiobook in ryot that i defnitely only have finished once. 
![image](https://github.com/user-attachments/assets/146776ae-db90-40ee-8031-86a7a61b77ac)
all of the invalid plays don't have the started date set
![image](https://github.com/user-attachments/assets/264b18a0-813f-43ae-a78b-19cbe8604ffa)
![image](https://github.com/user-attachments/assets/be75b6a5-bdec-48dc-bec4-13e90d53ad17)

All those plays were added through the audiobookshelf integration.

i currently have a stuck import job for audiobookshelf running, but that issue has existed before that as well

**Comment by IgnisDa** [comment]
Do you have ABS integration setup? Or were these imported through the importer?

**Comment by emhl** [comment]
> Do you have ABS integration setup? Or were these imported through the importer?

i am not sure through which it came. i have used both

**Comment by IgnisDa** [comment]
According to the discussion you opened, it might be possible that you ran the import multiple times. 

Would it be possible for you to start a fresh Ryot instance and only run the importer once and then setup the integration? If the issue still persists, then I would consider it a bug.

**Comment by emhl** [comment]
I will try to reproduce it from a clean install. copying the docker compose file to a new folder shouldn't be much of an issue :D

**Comment by emhl** [comment]
i set up a new instance and imported audiobookshelf data and added the integration. so far no anomalies.

after that i have started a trakt import just because why not. it is still going but has already imported 207 plays of a movie i have never watched before :D

**Comment by IgnisDa** [comment]
Thats weird. What is your trakt username? 

If possible, please join the Discord (link in readme). It would be easier to debug there.
