### ISSUE TITLE
Allow associating reviewes with seen entries 

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/ryot#1045]

**Comment by rclingman** [comment]
I wrote the following comment in the discord server, and it was recommended that I make a feature request so that we can discuss it in detail. I apologise for recycling the discord message, but I have limited typing capacity at the moment. I will add some further details in the morning.

> Would it be possible to allow users  to include comments for individual watched events? For example, if I watched the first episode of One Piece again today, and had a specific thought like 'Wow! Seeing the washed out artstyle really brings back memories of watching this on my old iPod touch', I would like to be able to add that as a comment for the specific watched event. Hope that makes sense!

**Comment by IgnisDa** [comment]
Here is the UI I am thinking of:

Editing a seen entry:
![image](https://github.com/user-attachments/assets/8ec272eb-cb90-4504-9052-edbe60e124ca)

If a seen entry is associated with the review:
![image](https://github.com/user-attachments/assets/94795139-752a-4f7c-8bfe-6a5b23ca787f)

If a review has any seen entries associated with it:
![image](https://github.com/user-attachments/assets/31a663a3-9b7e-4a5f-ba2f-6ad9bcd804d0)

---

What do you think?

**Comment by rclingman** [comment]
I really like this! Would a user still be able to have a watch and rewatch of the same episode associated with different reviews?  For example: 

S01E01 Watch date 2022-01-01: Associated review: This is one of the best opening episodes I have ever seen!

S01E01 Watch date 2024-06-01: Associated review: This opening was good, but maybe not as good as I remember it being.

**Comment by IgnisDa** [comment]
> Then can each seen entry be associated with its own review as well? 

Not sure what you mean but yeah, any seen entry can be associated with any review (but just one).

**Comment by rclingman** [comment]
> > Then can each seen entry be associated with its own review as well?
> 
> Not sure what you mean but yeah, any seen entry can be associated with any review (but just one).

Perfect! That makes complete sense!
