### ISSUE TITLE
Ryot Pro - Suggestion for video game time tracking

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#1056]
Hey, just started using the time tracking feature for video games in Pro, and I think that the slider is a bit strange to use. 

I would personally say that a simple number input field for a number (e.g. Time spent: 13.6 hours) would be more user friendly. I also believe it would be nicer if it displayed in hours only (e.g. 37.5 hours vs 1 day, 13 hours, 30 minutes) as this is what is how it's displayed on Steam and other game platforms.

In the dashboard summary though, I think it is nice to have it in the x days, y hours style to match the others.

Also, when in the "Edit history record" modal, there is a "Where did you play it?" field, but the only options are Netflix, Amazon Prime etc. which isn't relevant for video games. These options should be: PlayStation, Xbox, Steam, GOG, etc.

Thanks!!

**Comment by IgnisDa** [comment]
You are right, the time manually spent input is pretty useless in its current state. I'll find an alternative.

For "the where did you play it" input, you can edit the possible values in your preferences. But maybe it would be a better idea to allow users to add them on a media type level.

**Comment by kaibagley** [comment]
Does the game playtime get summarised on the dashboard with the movies, etc.? I haven't seen it appear so I'm guessing it doesn't.

**Comment by IgnisDa** [comment]
No it would not be difficult to implement. Please create a separate issue for it.
