### ISSUE TITLE
Any chance of leveraging Docker Secrets to pass Postgres credentials? 

### ISSUE THREAD

**Issue by amrit-venkatesh** [IgnisDa/ryot#1065]
This may be classified as a feature request. I tried the usual method of suffixing _FILE to DATABASE URL to leverage docker secrets but it wouldn't work. Any chance this can be implemented? 

DATABASE_URL_FILE: /run/secrets/ryot_url

**Comment by IgnisDa** [comment]
Are you willing to make a PR for it?

**Comment by amrit-venkatesh** [comment]
I'd have loved to contribute but have no idea how to implement such a PR.
Raised this question based on my reading of docker secrets being a
recommended/best practice.

**Comment by IgnisDa** [comment]
Sorry, it is not a much requested enough feature for me to spend bandwidth on.
