### ISSUE TITLE
Hide mark as seen if not released yet

### ISSUE THREAD

**Issue by dkorecko** [IgnisDa/ryot#1066]
Hey there,

I think it would be great if the button to mark something as seen would not be presented if an episode has not released yet. Example here:
![image](https://github.com/user-attachments/assets/18db3a6a-780d-4c06-b9e7-57e1369c7314)

Thanks ^^

**Comment by IgnisDa** [comment]
THis can not be done. Sometimes TMDb has incorrect data on when an episode was released. In that case, this button will not be activated even if the episode was actually released.
