### ISSUE TITLE
Where did you watch it? dropdown does not work after update

### ISSUE THREAD

**Issue by dkorecko** [IgnisDa/ryot#1067]
It seems like since the 7.5.0 update, the where did you watch it dropdown seems to be empty. After clicking it, nothing happens. I've tried numerous times on various different shows. Logs don't show anything that would suggest the cause of the issue. The issue remains on 7.6.0.
![image](https://github.com/user-attachments/assets/ff851b57-1849-4164-a338-2dbc4dd879c8)

**Comment by IgnisDa** [comment]
Please read the release notes. You can set the watch providers on a media type level.
