### ISSUE TITLE
Error when searching books

### ISSUE THREAD

**Issue by diogovalentte** [IgnisDa/ryot#1071]
Every time I try to search for a book using Openlibrary, Ryot takes a long time to search, and at the end, it throws an error. The error below is trying to search the "film art" book:

```
Error: Unable to decode turbo-stream response from URL: https://domain.com/media/search/book.data?query=film+art
    at ba (https://domain.com/assets/components-BQKTjf5W.js:148:1818)
```

When using Google Books, it throws an error after I finish typing the book name:
![image](https://github.com/user-attachments/assets/f31cc48d-4cac-4c1b-b076-2160f0d99dde)

In the logs, using `RUST_LOG=ryot=trace`, the only thing that seems related are these two lines:
```
GET /media/search/book.data?query=film+art%3A+an+introduction - - - - ms

GET /media/search/book.data?query=film+art&source=GOOGLE_BOOKS 200 - - 433.990 ms
```

**Comment by IgnisDa** [comment]
Openlibrary is under a massive DDoS since the last 5 days. The only thing to do is to wait for it to come back up. https://www.isitdownrightnow.com/openlibrary.org.html

**Comment by IgnisDa** [comment]
If you want to switch to google books, please go to https://ryot.domain.me/media/search/book?source=GOOGLE_BOOKS.

Ref: https://docs.ryot.io/guides/books
