### ISSUE TITLE
Sonarr and Radarr Integration Switched in UI

### ISSUE THREAD

**Issue by c00kiemonstr** [IgnisDa/ryot#1072]
A simple bug - the integration labeled "Sonarr" is using the logic for Radarr and vice versa. See this line in the code: https://github.com/IgnisDa/ryot/blob/1aaf92ab724cb5d42f9a5c6d22c07d554902d054/crates/services/integration/src/lib.rs#L176

**Comment by IgnisDa** [comment]
Thanks for reporting. Will be released with `v7.6.2`.
