### ISSUE TITLE
Time summary for video games

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#1076]
Hey,

I noticed that games don't have a time summary in the dashboard, and I think this would be nice to display alongside the movie time.

Thanks!

**Comment by IgnisDa** [comment]
Movies have a specific runtime associated with them. There is no such thing for video games. How would Ryot calculcate this runtime?

**Comment by kaibagley** [comment]
I mean the user entered play time in the pro version of the software.

**Comment by IgnisDa** [comment]
Merged. Will be released this weekend. You might need to regenerate summary from miscellaneous settings.
