### ISSUE TITLE
[FEATURE REQUEST] When adding a new Media item, prefill the type based on the List you are on

### ISSUE THREAD

**Issue by belthesar** [IgnisDa/ryot#1077]
Hi there! Recently got this stood up for my partner in homeprod with a pro key, and we're loving Ryot. As I was putzing around though, I noticed that when clicking the create button on a media item, I had to select what kind of media I was wanting to add. Given that I was already inside of a Media list, it was odd to me that the List type wasn't pre-selected based on what list I was in. This would save a couple clicks, which when entering lots of media, would help quite a bit. Thanks!

**Comment by IgnisDa** [comment]
Thats a good suggestion, will implement. But I am wondering, why do you need to create so much media in the first place? Do the providers not have the data you want?

**Comment by belthesar** [comment]
Hey, thanks for responding and for accepting the FR!


Re: my providers not having the data I want, I think this is a situation of not having data in any supported providers. For instance, I didn't see a method beyond using IGDB for importing video games. The best collection source for my games is Steam, with GOG being the next best thing. Neither one of those currently have supported import stories. I'm sure I could go about creating an export of my libraries from those systems and get them into the `CompleteExport` schema, but that's a level of work I'm not really willing to do at the moment, and the idea of figuring out some sort of sync from my Steam or GOG library to IGDB for import to Ryot is also less attractive, as I'd prefer less places have information about what I own than more (a core reason why I'm self-hosting).

I think it's fair to assume that folks may want to catalog net new collections that aren't tracked in systems other than Ryot. For instance, if I were a retro media collector, especially if those items are physical. I think it makes sense to me personally for Ryot to make manual data entry fast and lower friction.

**Comment by IgnisDa** [comment]
Makes sense. I have merged the fix for this. Will be fixed this weekend.

Thanks for using Ryot!

**Comment by IgnisDa** [comment]
Also just to confirm, the games you play on steam should still be on igdb. So you can search for them on Ryot and then update progress manually. Unfortunately there's no integration/import options available.

I have over 500 games played (i use steam too) and have never needed to create a custom media.

**Comment by belthesar** [comment]
I guess I'm missing the facility of syncing my Steam library to Ryot then? The only way I see the pipeline working is Sync from Steam -> IGDB through some fashion, then sync from IGDB -> Ryot. If I've missed something in the documentation to set that up, please let me know.

**Comment by IgnisDa** [comment]
Yeah, I plan to get to that eventually. Right now I do not have the bandwidth.
