### ISSUE TITLE
Documentation improvements 

### ISSUE THREAD

**Issue by Jondeli** [IgnisDa/ryot#1079]
Would be nice to have some documentation improvements as it’s a bit puzzling at times. In README there is mentioned well documented Graphql but I can’t find anything related to it from the docs. Also it’s not quite clear based on the docs what tracking means, for example, for books as they seemed to work OK out of the box with Google Books but there still is option to add Google Books API but what benefit would it bring?  So basically the word “tracking” can mean so many things for different people, some think of it as tracking the state of in progress so how much you have done and some, like I, think of it as just tracking what have I watched or read in the past. 

So it would be great to have documentation improvements where things would be explained briefly.

**Comment by IgnisDa** [comment]
I agree, ryot is confusing to new users. Can you give me a list of what all you'd want to see documented?

**Comment by Jondeli** [comment]
Here is a quick list

- This snippet in the Configuration page

`You can specify configuration options via environment variables or via files (loaded from config/ryot.json, config/ryot.toml, config/ryot.yaml). They should be present in /home/ryot/config/ryot.<ext>.`

It is a bit unclear how to use these files. So would be good to open it a bit. Also an example for docker compose .env file would be good as there are so many variables that can be used it would clogg the docker compose yaml easily.

- Config builder link in the configuration page is "404"
- It can be confusing that the parameters list in configuration is in different form than what the environment variables in docker compose so it might be misleading
- Books section and Google Books I mentioned in the first message.
- Pro feature, can't really find an explanation that what is included
- The backend side seems mosly undocumented. I only found mentioning of this backend from the configuration mention of the loaded config. This also includes GraphQL. So would be good to have separate docs page for backend and have all the stuff listed there with examples of GraphQL usage

These are the first things that came to mind when setting things up.

**Comment by IgnisDa** [comment]
> One thing not related to documentation, why is the authentication redirecting to movie search with "avengers" instead of the dashboard?

When you do not have any media logged (or your summary is empty), this happens. Its geared towards new users mainly.

**Comment by IgnisDa** [comment]
Note to self:

-  Document "Admin Access Token"
