### ISSUE TITLE
[Feature Request] - Display media progress inline

### ISSUE THREAD

**Issue by balajsra** [IgnisDa/ryot#1087]
Making this ticket based on some discussion on Discord.

Somewhat related to #996, looking to track progress of items in ryot similar to how services like [Hardcover](https://hardcover.app) and [AniList](https://anilist.co) do it:

![image](https://github.com/user-attachments/assets/9d845908-5a34-4f01-ac30-c6e99f598d68)

![image](https://github.com/user-attachments/assets/10b2eaf8-9445-49d7-8b56-c1651205776c)

This would essentially involve adding a new metadata field for all items where you can specify progress towards some total amount (in units of pages, episodes, minutes/hours, etc.) and then have the progress percentage dynamically calculated and displayed under items on a dedicated page and/or in the usual grid views.

My initial suggestion would be to do something similar to how a special backpack icon shows up for items in the "owned" collection in the grid view. Maybe add progress (as a percentage or fraction or something) to one of the corners:

![image](https://github.com/user-attachments/assets/4f1c0969-401a-49b9-940b-49d81b995834)

See [this comment](https://github.com/IgnisDa/ryot/issues/996#issuecomment-2395292558) for another potential option. Basically, a progress bar underneath the item in the grid view.

**Comment by IgnisDa** [comment]
> you can specify progress towards some total amount (in units of pages, episodes, minutes/hours, etc.) 

Why do you need to specify total amount? Most media already have that.

**Comment by balajsra** [comment]
> > you can specify progress towards some total amount (in units of pages, episodes, minutes/hours, etc.)
> 
> Why do you need to specify total amount? Most media already have that.

True, but sometimes the total amount specified in the database doesn't quite match the version you have. For example, maybe you're reading an ebook where the number of pages changes based on font size, zoom level, screen resolution, etc. It would be nice to be able to manually override the value retrieved from the database.

**Comment by IgnisDa** [comment]
Fair enough. I can provide this value on the seen record level. Would that be fine?

**Comment by balajsra** [comment]
If by "seen record level" you mean the Update Progress button under Actions, that should work and I think that makes the most sense from a UX perspective.

![image](https://github.com/user-attachments/assets/92b22ef5-af0c-47b6-b50a-ca90f15aa0b1)

**Comment by balajsra** [comment]
Additionally, I did want to call out one detail that was slightly annoying about the way Hardcover handled progress for audio books. It asks you to specify progress towards the total, but providers like Spotify only show you progress *remaining* (see below):

![image](https://github.com/user-attachments/assets/fce82ab9-29a1-41ca-a35b-02dcb4f9fbf9)

Which required a little bit of mental math every time I wanted to update the record to subtract the remaining time from the total time. If possible, it would be nice to specify **either** completed progress or remaining progress and have the record automatically calculate the completed progress.

**Comment by IgnisDa** [comment]
For this issue, i will like to just tackle the displaying progress part. For the other part about updating progress (time remaining thing and custom total), please create a separate issue and we can display it there.

**Comment by IgnisDa** [comment]
THis has been merged and will be released this weekend.

This is how it looks like: 
<img width="475" alt="image" src="https://github.com/user-attachments/assets/e585f43b-0d33-4de6-8cca-80e9cc1c1620">

I did not display numbers there since it would look very clutterred.
