### ISSUE TITLE
Add option to limit number per show in upcoming section

### ISSUE THREAD

**Issue by JPsychotic** [IgnisDa/ryot#1088]
Hello. I would like to limit the number of elements for a show in the upcoming section. As of right now I can only limit the sum of all elements in this sections. The current option should still be applied as a limiter for the max element number but a second option to limit the elements of one show in this section would be greatly appreciated!

Thanks in advance if you would consider to implement this feature :)

**Comment by IgnisDa** [comment]
This has been merged and will be released this weekend.

I did not make this an option. Instead, all media items in the upcoming section will be deduplicated and only the first upcoming episode of a show will be displayed.

**Comment by IgnisDa** [comment]
I ended up adding the option to configure it as a new preference in the dashboard settings. By default it is false.
