### ISSUE TITLE
[Bug] Manga / Anime Icons Swapped

### ISSUE THREAD

**Issue by balajsra** [IgnisDa/ryot#1090]
It appears that the icons for manga and anime in the Dashboard summary section are swapped.

Manga should have the books icon and Anime should have the TV icon.

![image](https://github.com/user-attachments/assets/c53f3aef-c7e9-4a9c-a862-a98c7c6f1bc4)

**Comment by IgnisDa** [comment]
Thanks for reporting! This has been merged and will be released this weekend.
