### ISSUE TITLE
[Feature Request] - Add external_identifiers to GraphQL metadataDetails query.

### ISSUE THREAD

**Issue by JoaoVictorLouro** [IgnisDa/ryot#1091]
Hi!
First of all, thanks for the hard work, I have been trying Ryot for a couple weeks and I am absolutely loving it.

I have been integrating it with a bunch of tooling and automated systems I have in my own self-hosted homelab.
But one of the issues I have been having, is the lack of `external_identifiers` in the GraphQL queries. I have to match data using the title of an Anime/Show/Movie, and thats just not very accurate.

I looked pretty extensively through the schema and could not find a way to pull the field.

I was wondering if you were willing to add this field to the GraphQL query `metadataDetails` or provide another query which I could use to pull that data from.

I could also look into opening a PR, but I am not very well versed with Rust. 😅

**Comment by IgnisDa** [comment]
This has been merged and will be released this weekend.

External identifiers only contains tvdb_id. LMK if you need anything else! Also, if you don't mind me asking, what integration are you building?
