### ISSUE TITLE
[Feature Request] - Improve Progress Tracking

### ISSUE THREAD

**Issue by balajsra** [IgnisDa/ryot#1094]
Splitting out sub-tasks from #1087 into a separate ticket per [this comment](https://github.com/IgnisDa/ryot/issues/1087#issuecomment-2452168596).

Improve progress tracking to include **all** media types and add some quality of life features.

For books or audio books (and possibly other media types), it would be useful to get the total number of pages or length from a database, but allow a user to override this if desired (e.g., eBook page lengths can vary wildly depending on display size / text scaling). Also allow user to enter how many pages they have completed out of this total and have ryot automatically calculate percentage completion.

Here is an example of how [Hardcover](https://hardcover.app/) handles progress tracking:
![image](https://github.com/user-attachments/assets/0e9039fe-6579-4c29-9ced-f6872f734ade)

For audio books specifically (and possibly other media with known lengths in units of time), it would be helpful to be able to enter either time completed or time remaining, and have ryot auto calculate time and percentage completion. For example, Spotify audio books show time remaining, but not time completed, so the user has to do a bit of mental time math, which isn't necessarily intuitive.
![image](https://github.com/user-attachments/assets/f7585499-ebc0-482a-8ccc-ff13d31486f3)

It would also be helpful if the user could enter these time amounts in hours, minutes, and seconds rather than total number of minutes as it currently is (again, to avoid extra mental math). Perhaps allow either method (total minutes or hours/minutes/seconds) with a toggle of some kind.

Similar idea for anime (and other media). Get the total number of episodes from a database, but allow them to override the total (sometimes the streaming service splits episodes differently than AniList or MAL track it) and enter how many episodes they have completed.

![image](https://github.com/user-attachments/assets/6983b488-cde4-4a64-9d26-105bbbf23144)

Service providers like Trakt keep track of individual episodes and their metadata. If AniList or MAL or other similar services don't provide such metadata, just the total number of episodes in a season and allowing the user to enter the number of completed episodes should be sufficient.

In terms of where these progress tracking features should "live", the Actions -> Update progress menu seems to make the most sense:
![image](https://github.com/user-attachments/assets/37354bf6-a746-4ba4-b8bf-f8527b9da450)

**Comment by IgnisDa** [comment]
Hi! I have decided to not add support for this since I do not find myself needing this. I might revisit this decision in the future. Thanks for the suggestion!
