### ISSUE TITLE
[Feature Request] - How Long to Beat Import

### ISSUE THREAD

**Issue by limitlessbritt** [IgnisDa/ryot#1095]
Hello,

The game tracking site How Long to Beat https://howlongtobeat.com allows users to export their data to at .csv file. It would be great if Ryot could import this data.

![Screenshot_20241103_014737](https://github.com/user-attachments/assets/99b42a51-2c25-4487-a529-caca2dbf2ac9)

I'm happy to provide a sample export if needed.

Thank you.

**Comment by IgnisDa** [comment]
Since this is not a much requested feature, I do not want to add it to Ryot itself. Instead, I recommend you to use the generic json method (https://docs.ryot.io/importing#generic-json) to import data.

If needed, please join the Discord server and I would be glad to help you.
