### ISSUE TITLE
Notifications not working (properly?)

### ISSUE THREAD

**Issue by Jondeli** [IgnisDa/ryot#1099]
I have setup a Discord notifications and the test messages work fine. But I never get notification when a new episode is released even when I monitor it. How is it supposed to work, when it is released AKA a date to air is confirmed or when the date to air is now? I need to have a notification when the episode is watchable.

Everything shows fine in "Upcoming" list but not notification sent. I have everything toggled on in the settings.

**Comment by IgnisDa** [comment]
It is supposed to send you a notification when "the date to air is now".

I will take a look.

**Comment by IgnisDa** [comment]
Thanks for reporting, there was a bug. Fix will be released this weekend.
