### ISSUE TITLE
Workouts not finishing

### ISSUE THREAD

**Issue by talkingseedling** [IgnisDa/ryot#1105]
Version 7.10.0, using firefox mobile.

When clicking finish on a workout, it logs, but the orange circle on the bottom remains, even when navigating to other pages. Clicking on it takes you back to the workout, clicking finish again this time removes the orange circle, but the workout is logged twice, requiring deletion.

With one of the new updates, rest timers act inconsistently, sometimes triggering or not depending on previous workouts, and (afaik) can't be disabled.

When finishing/ticking a set, the exercise is now minimised, requiring you to click "add set" before finishing the previous to stop the behaviour. The maximise arrow disappears if there is a rest timer running.

**Comment by IgnisDa** [comment]
These have already been fixed with `v7.10.1`. Please upgrade and LMK if you still have problems.
