### ISSUE TITLE
Activity section for video games not realistic

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#1106]
Hey,

If I play a video game for 50 hrs over the course of 2 months, the summary on the dashboard page displays this as if all of that time was spent on the day the game was set as completed. I'm not sure how difficult this is to change, but I think it may be better to distribute the time evenly over the days between the start and finish dates.

E.g. 
- 50 hrs played
- current date 2024-10-25
- start 2024-08-20
- end 2024-10-20

Time summary (set to past 7 days) will show 50 hours played. Since the past 7 days only covers 2 days of playtime, it might make more sense to just display it as `(nhours / ndays) * 2`

Thanks!

**Comment by IgnisDa** [comment]
This feature was implemented according to your created issue (https://github.com/IgnisDa/ryot/issues/1076). Does it not work as expected?

**Comment by kaibagley** [comment]
No it works great, I don't mean to say there is something wrong with the functionality, just that I think it might make more sense as mentioned above. I logged in the other day and saw that I played over 6 days worth of games in the last 7 days, because I just finished a long game which was actually played over the course of a couple months.

**Comment by kaibagley** [comment]
Yes, changed the title to "Activity" rather than "Summary". Sorry for the confusion

**Comment by IgnisDa** [comment]
I'm not sure whether I can implement this. The activity works on the granularity of a day. And each seen entity can only be associated to a one activity item.

I realize the problem you describe will also apply to other media types. Do you have a solution that can solve it for all media types?

**Comment by kaibagley** [comment]
Yeah unsure of an elegant solution, with movies and shows, the vast majority of the time people are consuming the whole thing in one sitting so its maybe fine for those as is, its only really a problem for books and games since they're long running.

I'm not sure sorry. Maybe we can just leave this open for now and see if others have suggestions

**Comment by IgnisDa** [comment]
I like to keep only the issues i want to work on. Closing this. People can still find it and chime in if it is a pressing concern.
