### ISSUE TITLE
[FEATURE REQUEST] - Hide Sidebar Menu

### ISSUE THREAD

**Issue by gilo27** [IgnisDa/ryot#1111]
I think it would be a neat feature to implement a hamburger menu or some sort to have the ability to hide the sidebar for a cleaner look.
This would come in handy to view more content at once.
It would also look nice if using this in a sort of Kiosk mode to display certain collections/media.
Thanks for the awesome software!

**Comment by IgnisDa** [comment]
Hiding the sidebar menu is a good idea. What do you mean by kiosk?

**Comment by IgnisDa** [comment]
I mean, do you have an example screenshot i could take a look at?

**Comment by IgnisDa** [comment]
Merged support for collapsing sidebar. Will be released today or tomorrow. Thanks for the suggestion!

As for the kiosk thing, I would like to discuss it first. Please open a separate issue.
