### ISSUE TITLE
Be able to choose which platform release date to track

### ISSUE THREAD

**Issue by philipjholm** [IgnisDa/ryot#113]
It is impossible to track games for a specific platform today. For example, let's look at the game "Ratchet & Clank: Rift Apart". Adding this game to the app the release date says 2021 (as it was released on PS5 then) but if I want to keep track of the PC version) that is supposed to be released this year in July) it is not possible.

**Comment by IgnisDa** [comment]
I don't think this would be possible. The provider we use (IGDB for video games) returns them as a single game (and 2 different platforms). At best, I think we can start keeping track on which platforms the game was released on.

**Comment by IgnisDa** [comment]
Platforms are now tracked for video games. You can update your games  using the "Update Metadata" button on the actions tab.

**Comment by philipjholm** [comment]
@IgnisDa 
Updated to version 1.0.5 and I can't see any difference. Even wiped the database and started over to make sure. This is how it looks on a game:

![game](https://github.com/IgnisDa/ryot/assets/37110163/3a0c30ab-bc2c-43a5-a05c-7d672a4846f9)

Doing a search I also just find on entry, and not one for each platform if that is how it should work. The game has these platform release dates on IGDB:

![igdb](https://github.com/IgnisDa/ryot/assets/37110163/a65ae19c-cd7f-4256-aff7-b190442b1507)

**Comment by IgnisDa** [comment]
Yep this is how it is supposed to work.
