### ISSUE TITLE
[Feature Request] add webhook to send notification whenever a user finishes a workout

### ISSUE THREAD

**Issue by steffenvan** [IgnisDa/ryot#1130]
For instance, it would be nice to be able to send a message to a discord channel whenever a user in a group finishes a workout. In the message, there should be a (optional) preview of the workout so other people can see what the person did. In addition, it would also be very nice to be able to attach a selfie or some image from the phone.

**Comment by IgnisDa** [comment]
With ryots current architecture, All user notifications are sent at night. Is this acceptable for your use case?

**Comment by steffenvan** [comment]
No it's pretty important that the notification comes as soon as the workout is finished (or not much longer thereafter). My idea is that it replaces the necessity to send a message in something like a WhatsApp group.

**Comment by IgnisDa** [comment]
makes sense. will keep that in mind

**Comment by IgnisDa** [comment]
What details should be sent with the notifications?

**Comment by IgnisDa** [comment]
THis has been merged. Will be released on Sunday.
