### ISSUE TITLE
[FEATURE REQUEST] - Make metadata editeable

### ISSUE THREAD

**Issue by ThirrinDiamond** [IgnisDa/ryot#1139]
Hello.

I would like the metadata of at least custom items you create to be editeable after it has been created.
It would also be nice to be able to locally change the chosen images that show up for the items that are searched once they are added to your list.
Or to be able to add an author's name to books that are currently missing it for example.

Thank you :)

**Comment by IgnisDa** [comment]
> Or to be able to add an author's name to books that are currently missing it for example.

If you are using Openlibrary, then I suggest adding that data to openlibrary itself. That way everyone can benefit from it.

> It would also be nice to be able to locally change the chosen images that show up for the items that are searched once they are added to your list.

Can you explain what you mean by this?

**Comment by earthly-alien** [comment]
I'd also like to add to this, re: cover image. When pulling book metadata, there are multiple covers I can manually cycle through. But I cannot change which one I want to be the main one. It's always the first, lowest quality one that's very pixelated and blurry.

**Comment by IgnisDa** [comment]
@earthly-alien which provider is this happenning for (eg. tmdb, openlibrary etc). I have code which orders images by their quality but i have not applied it to all providers it seems.

**Comment by earthly-alien** [comment]
Openlibrary and Google Books. So just the book metadata providers.

**Comment by ThirrinDiamond** [comment]
@IgnisDa 
> Can you explain what you mean by this?
Sometimes the official artwork of some games or movies can be a bit intense if i'm not mentally ready, especially if it's related to one of my phobias so being able to locally alter the thumbnail image to be of a different poster or a custom screenshot would be helpful :)
At the moment i'm adding the games i'm tracking so i'm like having to actively navigate carefully and avoid looking at some of the titles which is a bit annoying lol

**Comment by IgnisDa** [comment]
Unfortunately I won't be providing a way to edit non custom metadata. It opens a whole can of worms like keeping stuff in sync/overwriting changes/user permissions that I don't won't to deal with.

I'd recommend just creating custom metadata for your use case. I'll provide a way to edit them soon.

**Comment by IgnisDa** [comment]
This has been merged and will be released this weekend.
