### ISSUE TITLE
Suggestions & Tweaks

### ISSUE THREAD

**Issue by phere-x** [IgnisDa/ryot#114]
**Home Page**
Home page should have customisable horizontal sections ("next up, Continue, new entry" etc.) that can be toggled & re-ordered Jellyfin style. 

Maybe a banner section for suggested content based on what a user has watched & rated (9anime is good clean layout I imagine when thinking this). This feature could be a draw in and of itself for a few.

**Media Page**
When actually viewing an entry, a layout that makes most sense would be Trakt's. When clicking into something (a show specifically): https://trakt.tv/shows/one-piece Could do without the large banner that it has & a lot of the other sections aren't needed for sure. And then having the mid section like this https://i.imgur.com/rGfw5g4.png where episodes are listed in a vertical list with smaller episode thumbnails (or size as an option for user) & buttons beside em for actions. 

IMO these makes more sense logically than just having the overview as default only info shown, and having to click through to get to the other parts. 

Or maybe even how Sonarr does theirs: https://imgur.com/BO94SIn TBH Sonarr has it pretty well done in terms of layout & could easily translate over to a media tracker nicely. Can make the design more like trakt's to have it more akin to a media app with thumbnails etc. 

**Additional Feature**

- Trakt's history tab is also a huge thing for me. To be able to have a visual timeline of sorts to see when I watched what. A huge + for me if there are tabs I could collapse 'reddit comment thread' style to quickly go through weeks/months/days

- I've also always craved MyAnimeList's "anime/manga list" for my non anime media - a section where it creates a table of your watched media and you can go through your whole collection & filter & sort by start and finished date etc.

--- 
I haven't really used figma to quickly show things or want to put time into learning it for something that might not be used 💀 so, sorry

**Comment by IgnisDa** [comment]
Thank you very much for the suggestions. I agree with you, Ryot's UI is not optimal. I will definitely be looking back into this after I release Ryot publically.

**Comment by IgnisDa** [comment]
Closing this in favor of the new UI I'm working on.
