### ISSUE TITLE
Fitness tracking feature requests

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/ryot#1141]
From a user on Discord:

> Is there a way to pause the workout timer once it starts?
> Can I also have the workout timer not start automatically but wait for me to click it? I might want to set things up a bit beforehand or pause it because I get a call or something.

**Comment by IgnisDa** [comment]
Also allow pausing a workout.

**Comment by ChocolateDarkMatter** [comment]
Along the same lines, can you have the timer end after a predefined time. Nothing worse then forgetting to end a workout come back and its been going for 56 hours.

Thank you for the great work and continued updates soo far by the way.

**Comment by IgnisDa** [comment]
Good idea. where should that setting be? in the preferences?

Also what do you mean by it ending? Do you want to get a notification or just want the server to finalize the workout?

**Comment by ChocolateDarkMatter** [comment]
> Good idea. where should that setting be? in the preferences?
> 
> Also what do you mean by it ending? Do you want to get a notification or just want the server to finalize the workout?

Preferences -> Fitness 
maybe under default rest timers

something like "Workout inactivity timeout" either a toggle button or an input field 0 is infinite (like it is now) or input a value for user preference

I was hoping to just have it end. But that would be up to you based on your vision I think. Thank you soo much for considering. Happy Holidays btw

**Comment by IgnisDa** [comment]
Please create a separate issue for your use case.
