### ISSUE TITLE
[Feature Request] - Add exercise to Fitness Template without sets having data

### ISSUE THREAD

**Issue by ChocolateDarkMatter** [IgnisDa/ryot#1147]
Problem: Currently when creating a template if you add an exercise that doesn't have a record yet you get the message "Only sets that have data will be added"

Request: If possible please add an option, maybe an environment variable, to make it possible to add exercises that do not have a record yet.

Purpose: I like to create/define my workout routines beforehand. With the current method it makes it a bit cumbersome to experiment with new exercises.

**Comment by IgnisDa** [comment]
makes sense. will see what I can do.

**Comment by IgnisDa** [comment]
THis has been merged and will be released this weekend. THanks for the feature request!
