### ISSUE TITLE
[Feature Request] - Workout Inactivity Timeout Option

### ISSUE THREAD

**Issue by ChocolateDarkMatter** [IgnisDa/ryot#1148]
can you have the timer end after a predefined time. Nothing worse then forgetting to end a workout come back and its been going for 56 hours.

Preferences -> Fitness
maybe under default rest timers

something like "Workout inactivity timeout", "idle workout timeout" either a toggle button or an input field 0 is infinite (like it is now) or choose from a few predefined options 1hr, 2hr, 4hr

Thank you

**Comment by IgnisDa** [comment]
Ryot already has a solution for this. Once you come back to your workout after 56 hours, you can end it. Then in the workout details page, you can adjust the start and end time for it.

**Comment by ChocolateDarkMatter** [comment]
> Ryot already has a solution for this. Once you come back to your workout after 56 hours, you can end it. Then in the workout details page, you can adjust the start and end time for it.

Didn’t know you could adjust the end time. That works for me Ty! Happy holidays !!
