### ISSUE TITLE
Remove workout template visibility

### ISSUE THREAD

**Issue by dbauswel** [IgnisDa/ryot#1155]
Is there a way to make templates public for other users? 
They are marked private by default so I there is a option somewhere I'm not seeing.

<img width="569" alt="Screenshot 2024-12-28 at 1 19 17 PM" src="https://github.com/user-attachments/assets/070ce3bd-72ac-4346-960f-f2e507c7e880" />

**Comment by IgnisDa** [comment]
Yes. You can add it to a collection and then add the other user as a collaborator to the collection. It will then show up in their collection list.
