### ISSUE TITLE
[Bug] Getting shows in the thousands by the week

### ISSUE THREAD

**Issue by StoffelCPR** [IgnisDa/ryot#1158]
Hey,

After fixing my instance I seem to be getting a lot of show episodes every week. I'm currently watching Criminal Minds again and every once in a while I get a few thousand episodes onto my summary.

Started with around 5k two weeks ago and am now at 17k episodes watched.. Pretty sure criminal minds doesn't have that many episodes.

Any idea where to look?

**Comment by IgnisDa** [comment]
This was a bug in an older version. Which one are you on?

**Comment by StoffelCPR** [comment]
Will do. 7.12.0 was the latest I had

**Comment by StoffelCPR** [comment]
Upgraded to latest. Down to 2.1k Episodes now. I'll monitor my count and contact you again should it not be fixed. Closing this in the meantime as technically this is fixed for now.
