### ISSUE TITLE
Error: Failed to read source file.

### ISSUE THREAD

**Issue by muhsinkutay** [IgnisDa/ryot#116]
Docker Log:
```
2023-06-05 12:30:20 documents-ryot-1  | Caused by:
2023-06-05 12:30:20 documents-ryot-1  |     Is a directory (os error 21)
2023-06-05 12:30:24 documents-ryot-1  | 2023-06-05T09:30:24.970829Z  INFO ryot: Running version 1.0.0-beta.54
2023-06-05 12:30:24 documents-ryot-1  | Error: Failed to read source file.
```

I can provide extra information, but mainly...
My OS is Windows 10, 
Used [this](https://www.reddit.com/r/selfhosted/comments/13rehkg/comment/jljuwhn/) docker-compose script. 
I am able to run beta.47 without any problems, but from 48 and onward this error is thrown.

**Comment by IgnisDa** [comment]
You should not need `- ./config/ryot.example.json:/data/config/ryot.json` anymore.

**Comment by muhsinkutay** [comment]
I re-created the docker compose script using [this ](https://www.composerize.com/) website and everything works perfectly now.

```
version: '3.3'
services:
    ignisda:
        container_name: ryot
        ports:
            - '8000:8000'
        environment:
            - WEB_INSECURE_COOKIE=true
        volumes:
            - './ryot/data:/data'
        image: 'ghcr.io/ignisda/ryot:latest'
```

**Comment by muhsinkutay** [comment]
Thank you, the problem is fixed now.
