### ISSUE TITLE
MyAnimeList import not working

### ISSUE THREAD

**Issue by theonekili** [IgnisDa/ryot#1162]
Hi there,

When trying to import from MyAnimeList things just go to a standstill.
The logs states that myanimelist.rs panicked:
```
[backend] thread 'main' panicked at /home/runner/work/ryot/ryot/crates/services/importer/src/myanimelist.rs:24:46:
[backend] called `Result::unwrap()` on an `Err` value: Error { message: "invalid gzip header", extensions: None }
```

Ever since the import is just in this status:
<img width="525" alt="image" src="https://github.com/user-attachments/assets/7f240e01-7fdd-448b-ac53-80061ea2a8ed" />

This issue could be a duplicate for https://github.com/IgnisDa/ryot/issues/773 yet the details are different.

This is on Ryot V 7.13.1 running on Docker.

**Comment by IgnisDa** [comment]
Would it be possible for you to provide me the export file? The one in gzip format

**Comment by theonekili** [comment]
Wow. This is embarrassing. The export was auto-decompressed, hence I uploaded the XML directly.
After I've let gzip compress things again, things worked out fine.
<img width="271" alt="image" src="https://github.com/user-attachments/assets/c7e9f3ab-17f3-4c28-a564-9a7f0f9ed60a" />

Sorry for the hassle!

Maybe as a mild feature request:
Adding the target file format prior to importing from file:
<img width="544" alt="image" src="https://github.com/user-attachments/assets/7dedd510-5c0b-44f7-83c6-c19b49707e38" />
