### ISSUE TITLE
Set default value for: Specifics (JSON) input

### ISSUE THREAD

**Issue by muhsinkutay** [IgnisDa/ryot#117]
Making the default value of Specifics (JSON), `{"source": "CUSTOM"}` would be very helpful for users without JSON knowledge.
![image](https://github.com/IgnisDa/ryot/assets/33558081/d28f4e5c-911c-4c43-b11c-57deb66c03e6)

**Comment by IgnisDa** [comment]
The specifics require a lot more data. You can look at the expected structure here https://ryot.fly.dev/graphql (search `SpecificsInput` in the docs button on the left).

**Comment by muhsinkutay** [comment]
> The specifics require a lot more data, and it is not feasible to auto-populate them. You can look at the expected structure here https://ryot.fly.dev/graphql (search `SpecificsInput` in the docs button on the left).

Oh I see it more clearly now, thank you very much, then for the time being users without JSON knowledge will not be able to create custom media items I guess.

**Comment by IgnisDa** [comment]
I don't think this would be a much used feature anyway, and writing a custom UI for this will take a lot of time.

If you get errors while creating the media item, you can check the logs in the console for the exact error, since they are descriptive enough for people with some JSON knowledge to understand.

**Comment by muhsinkutay** [comment]
> I don't think this would be a much used feature anyway, and writing a custom UI for this will take a lot of time.
> 
> If you get errors while creating the media item, you can check the logs in the console for the exact error, since they are descriptive enough for people with some JSON knowledge to understand.

Yeah, I see your point and you are completely right, thank you for creating this custom media thing, it will be very helpful for me! <3
