### ISSUE TITLE
Support multiarch image

### ISSUE THREAD

**Issue by vnghia** [IgnisDa/ryot#129]
Hello, it seems that `ryot` currently runs only on `am64`. Is there any plan to add support for `arm64` in the future ?

Thank you very much !

**Comment by IgnisDa** [comment]
I would certainly love to do that. Do you have any idea how that can be done?

**Comment by vnghia** [comment]
I will send you a PR. I think it won't be too hard since we usually just need to add a platform to `buildx`

**Comment by vnghia** [comment]
Hey do you think we should have less strict condition for triggering actions. Right now actions only runs on release which makes it less friendly as when external contributors submit a PR, we expect that there are some minimal actions to just to verify that everything is working

**Comment by IgnisDa** [comment]
What would you suggest instead?
