### ISSUE TITLE
Add to watch history - user experience for Shows

### ISSUE THREAD

**Issue by dimon222** [IgnisDa/ryot#144]
Few things that could be improved
* Validation is missing. You can press "Now"/"I do not remember" immediately and it will add "nothing" to watch history
* There's no option to mark entire show as watched. There's a selection of episode/season, but if the point is to mark everything as watched - there's no way to do that. In more flexible version theoretically it could be solved with toggle checkbox-list experience (per episode or show).
* Since there's a tracking of watch history, it also makes sense to have another default category "Finished". The show can be moved from "In Progress" to "Finished" once you have watched it all based on TMDB episode records. If new episodes appear after metadata update the show could be considered to move back to "In Progress" or to "Watchlist" (?).

**Comment by IgnisDa** [comment]
> Validation is missing. You can press "Now"/"I do not remember" immediately and it will add "nothing" to watch history
Can you tell me what exactly you did to get here?

> There's no option to mark entire show as watched.
What kind of UI do you suggest for this?

> Since there's a tracking of watch history, it also makes sense to have another default category "Finished".
Instead of another category, I think it would be better to add a filter on the list pages.

**Comment by dimon222** [comment]
> Can you tell me what exactly you did to get here?

![pic](https://i.imgur.com/0NRSykk.gif)

> Instead of another category, I think it would be better to add a filter on the list pages. Otherwise, the collection would get too huge. For example, I have over 250 books finished, so the collections page would become unmanageable.

That works too. That said, today with pile of shows getting 250 shows watched isn't hard. I've already crossed the mark 600 shows out of which 200 are in "to do". I think as long as the page for collection has support of table view, ALWAYS paginated, and has proper quick searchbar/filtering, it shouldn't be a serious problem.

> What kind of UI do you suggest for this?

Disclaimer - take my opinion with grain of salt, its only how I see it.
The time when the show/movie/book was watched/read doesn't matter - its only about the fact that it was done (and the timestamp when it was done can be directly taken as of current moment if this time matters at all), so instead of offering buttons when it was done concentrate on controls to select what was watched. Remove buttons: "Now", "I do not know". The dropdowns for seasons and episodes replace with table view of all of them and checkmark based way to select what should be marke as watched.

See example how myshows.me has it - I haven't seen any better implementation of this kind of task anywhere.
![image](https://github.com/IgnisDa/ryot/assets/2671025/3dfa89ea-0f96-4658-8429-a15b6367edd2)

**Comment by IgnisDa** [comment]
Thanks for the update. I have already added a “Finished” filter for the list pages. I will get to the rest when I can.

**Comment by IgnisDa** [comment]
Judging by the screenshot, the toggle checkbox-list experience will not be possible with Ryot since a single episode can be marked as seen multiple times. So I will not be implementing the UI suggested in the screenshot.

The other issues have been addressed.

Thanks for your feedback!

**Comment by dimon222** [comment]
> Judging by the screenshot, the toggle checkbox-list experience will not be possible with Ryot since a single episode can be marked as seen multiple times. So I will not be implementing the UI suggested in the screenshot.
> 
> The other issues have been addressed.
> 
> Thanks for your feedback!

It could be accommodated by single extra button "Save" that would set all marked episodes as watched.

**Comment by IgnisDa** [comment]
Since I don't see myself using this feature, I won't work on it myself. But if you have a way to achieve this without breaking existing functionality, then I will accept a PR.

**Comment by IgnisDa** [comment]
@dimon222 
> if the point is to mark everything as watched - there's no way to do that
`v1.5.9` will include a button to mark all episodes of a show/podcast as seen.
