### ISSUE TITLE
Allow customize font

### ISSUE THREAD

**Issue by vnghia** [IgnisDa/ryot#147]
Default font does not work very well with non-european language. In my case it shows something like this:
<img width="616" alt="image" src="https://github.com/IgnisDa/ryot/assets/17511625/2ebe6584-6bd1-42fa-9d9a-2c3817c0c2bd">

**Comment by IgnisDa** [comment]
How do you suggest changing default font will work? Will it be via css imports or...?

**Comment by vnghia** [comment]
Yes maybe we can have a config for injecting custom css for general purpose, not just this case.

**Comment by IgnisDa** [comment]
I don't think I would like this for Ryot #77.

**Comment by vnghia** [comment]
In that case, just a switch to use system font is good enough for me.

**Comment by IgnisDa** [comment]
Would that require changes to the ryot source code?

**Comment by vnghia** [comment]
Probably yes. I am using a css injector extension to inject custom css to any website so I don't think I need this feature anymore.
