### ISSUE TITLE
Show my star rating on movie/tvshow/... main page

### ISSUE THREAD

**Issue by xrfmkrh** [IgnisDa/ryot#163]
I wanna see my star rating on category's main page like mediatracker.
then we can see star ratings at a glance

**Comment by IgnisDa** [comment]
I am not sure what you're talking about. Can you attach a screenshot?

**Comment by xrfmkrh** [comment]
![screenshot](https://github.com/IgnisDa/ryot/assets/113495572/1dd51cb7-e0e4-494e-8932-5cefdb116e09)
like red circle

**Comment by IgnisDa** [comment]
Will work on this when I get time 👍🏽.
