### ISSUE TITLE
Allow import from Movary

### ISSUE THREAD

**Issue by quamok** [IgnisDa/ryot#166]
Movary is a movie tracker software to track watched movies and rate them, similar to Ryot but for movies only. It's possible to export watched status, rating, date watched and comment from Movary to csv files. It'd be great if Ryot would allow importing from Movary using the csv files, or any other method.
[history.csv](https://github.com/IgnisDa/ryot/files/11939907/history.csv)
[ratings.csv](https://github.com/IgnisDa/ryot/files/11939908/ratings.csv)

**Comment by IgnisDa** [comment]
Looks doable, should be possible after #64.

**Comment by IgnisDa** [comment]
@quamok Would it be possible for you to email me your whole export? I would like to iron out some edge-cases (if any).

**Comment by IgnisDa** [comment]
@quamok Released this feature in `v1.10.0`.

**Comment by quamok** [comment]
thanks, that was quick! 

is there any log to the import process? about 1/5 of the movies weren't imported and I'm trying to find out which ones.

**Comment by IgnisDa** [comment]
Please read the notes on the importing docs
