### ISSUE TITLE
Import lists from MediaTracker

### ISSUE THREAD

**Issue by flavorgold1** [IgnisDa/ryot#174]
Can we get a list of things that don't carry through?

In the import process from mediatracker, the entire watchlist is ignored.

And, I don't know if it's missing some other things in the transfer process too.

**Comment by IgnisDa** [comment]
Have you taken a look at the importing guide? You can find it in the readme.

Afaik, lists and watchlist are the only thing that are missing in the media tracker import. I will close this issue when I add support for them.

**Comment by flavorgold1** [comment]
> Have you taken a look at the importing guide? You can find it in the readme.
> 
> Afaik, lists and watchlist are the only thing that are missing in the media tracker import. I will close this issue when I add support for them.

Does video-games importing work?

**Comment by IgnisDa** [comment]
Yes it does

**Comment by IgnisDa** [comment]
@flavorgold1 Almost all media tracker features are now supported (in `v1.7.2`). Please read the updated docs.
