### ISSUE TITLE
[FEATURE REQUEST] - Emby Webhook Integration

### ISSUE THREAD

**Issue by quamok** [IgnisDa/ryot#187]
It would be great if Ryot could accept webhooks from Emby. When a movie finishes in Emby, a webhook could be sent to Ryot to track the date the movie was listened to, minimizing manual input.

Reference: https://emby.media/support/articles/Webhooks.html

Similar to https://github.com/IgnisDa/ryot/issues/67

**Comment by lyz-code** [comment]
I'd love to test the Jellyfin webhook

**Comment by IgnisDa** [comment]
Will ping you when I make a PR.

**Comment by IgnisDa** [comment]
Closing this since I do not have bandwidth to work on this. If anyone wants to work on this, please ping me here and I will happily re-open this issue.

**Comment by IgnisDa** [comment]
Reopening this incase someone wants to complete this as a hacktoberfest task.

**Comment by IgnisDa** [comment]
Emby integration has been released in `v6.9.0` thanks to @Jacob-Tate. Please ping me here if you find any issues.
