### ISSUE TITLE
Authorization error You are not logged in

### ISSUE THREAD

**Issue by lcsfox** [IgnisDa/ryot#188]
As the title states, I'm getting the mentioned error when trying to log in.
I can successfuly create a user, because when I try to create the same user second time I get an error saying the user already exists.
The stack was deployed via docker-compose (portainer).
The browser console says : Cookie “auth” has been rejected because a non-HTTPS cookie can’t be set as “secure”.
WEB_INSECURE_COOKIE=true / false changes nothing.

Any idea what is going on here ?

**Comment by zombiehoffa** [comment]
same issue here. I don't see anything in when I do a docker logs ryot

**Comment by IgnisDa** [comment]
What browsers are you all using

**Comment by zombiehoffa** [comment]
BRave browser

Jul 14, 2023 17:33:54 Diptesh Choudhuri ***@***.***>:

**Comment by IgnisDa** [comment]
What version of ryot?

**Comment by zombiehoffa** [comment]
Whatever was in the docker container an hour ago

Jul 14, 2023 17:44:16 Diptesh Choudhuri ***@***.***>:

**Comment by IgnisDa** [comment]
Can you try the new config that I have added to the readme? Basically change `WEB_INSECURE_COOKIE=true` to `SERVER_INSECURE_COOKIE=true`

**Comment by lcsfox** [comment]
SERVER_INSECURE_COOKIE=true solves the issue for me.
Thank you!

**Comment by IgnisDa** [comment]
Please see #67.
