### ISSUE TITLE
[Suggestion] Kavita

### ISSUE THREAD

**Issue by majora2007** [IgnisDa/ryot#196]
I'm the developer of Kavita and just discovered this project. I would like to see if Kavita integration is doable. If you can point me in the right direction, I don't mind building my own integration.

**Comment by IgnisDa** [comment]
Thank you! I have tried building a Kavita integration before but had to abandon it because the API does not provide the Openlibrary or Google Books ID for the book.

**Comment by IgnisDa** [comment]
I would also prefer that Kavita had a webhook feature that can push the changes to Ryot instead of Ryot having to pull from Kavita. https://ignisda.github.io/ryot/integrations.html

**Comment by majora2007** [comment]
A webhook is what I was looking to do. Openlibrary or Google Books ID isn't something Kavita would be able to supply anyway.

**Comment by IgnisDa** [comment]
> Openlibrary or Google Books ID isn't something Kavita would be able to supply anyway.

Why is this? Does Kavita not get metadata for books?

**Comment by majora2007** [comment]
That is correct. Kavita is a way to explore and consume. I haven't seen any programs actually save these into Comics or Books. Comics don't have the ability to have OpenLibrary id as the spec doesn't allow and I'm not sure where in the epub spec an id like these would fit. 

How have you been able to get those from other applications?

**Comment by IgnisDa** [comment]
Does Kavita not have its own database? Most projects save them in their database and expose them via their API (or their webhook payload).

**Comment by majora2007** [comment]
Kavita doesn't scrape so there is nothing to save. Kavita imports metadata from the underlying files and their respective formats (ComicInfo and OPF). Neither those support arbitrary metadata IDs unfortunately.

That's why I'm curious about other integrations as I haven't seen tools use those IDs before. Usually ISBN is the most universal thing I've seen between all solutions.

**Comment by IgnisDa** [comment]
You can take a look at https://www.audiobookshelf.org/ or https://jellyfin.org/ both of which use the metadata present in the file and then scrape for additional metadata from websites like Openlibrary and TMDb.

As for Kavita, I can make do if the webhook contained the book's ISBN 13.

**Comment by majora2007** [comment]
Thanks I'll take a look. ISBN13 is something I can swing. I'll see if Google books can be implemented, but ISBN is supported in both books and comics/manga.

**Comment by IgnisDa** [comment]
Awesome! [Here](https://github.com/IgnisDa/ryot/blob/bd227e5e0893c1b5650cbdaa6e35f5021abda0cf/apps/backend/src/integrations/mod.rs#L35-L76) is an example structure of data I will need to complete integration.

**Comment by IgnisDa** [comment]
@majora2007 Any updates here? Feel free to ask for help here.

**Comment by majora2007** [comment]
No updates. It will be some time before I get around to this work. I'm working on wrapping up Localization, which is a lot for a large application like Kavita. 

I will comment on this issue once I plan this into a release and start the work.

**Comment by IgnisDa** [comment]
Alright thank you!

**Comment by majora2007** [comment]
Hey just an update, I decided this isn't something I would want to do. Kavita doesn't seem like a good fit. While the concept does, Kavita doesn't have ISBN on most of it's metadata. I will close this out as this is not something I can provide.

**Comment by IgnisDa** [comment]
Makes sense. Thanks for the update!
