### ISSUE TITLE
[Feature Request] Support for serving from basepath / subpath

### ISSUE THREAD

**Issue by bodak** [IgnisDa/ryot#201]
It would be great to add a configuration option allowing to specify a `basePath` the application is served from.
The new url would then look something like: `http://localhost:8000/basePath`. This is usefull when your setup is not supporting subdomains i.e. `http://ryot.mydomain.com:8000` is not an option.

I have attempted this using Traefik (stripPrefix and rewritebody middlewares), but it seems I can't capture GraphQL and auth (routed inside Rust) endpoints correctly.

**Comment by IgnisDa** [comment]
Not sure this would be possible since the front-end is statically built. Will it be possible for you to change some settings and build the dockerfile yourself?

**Comment by IgnisDa** [comment]
This would require some code changes to fix. I could work on this if someone needs it. Closing it for now due to inactivity.

**Comment by IgnisDa** [comment]
Awesome!
