### ISSUE TITLE
[Feature Request] Notifications for newly released media

### ISSUE THREAD

**Issue by Cheeseypop** [IgnisDa/ryot#202]
Just switched over from Media Tracker and it seems like everything I use is replicated and upgraded except for the ability to send notifications (I use Gotify for this) for new episodes / shows ending or getting renewed / newly released films / ect... 
Would it be possible to add support for something like this?

**Comment by IgnisDa** [comment]
Yes makes sense. Can you make a list of what all was actually monitored?

**Comment by IgnisDa** [comment]
Duplicate of #15.
