### ISSUE TITLE
[Feature Request] Add support for media groups

### ISSUE THREAD

**Issue by Cheeseypop** [IgnisDa/ryot#203]
It would be nice to have the ability to group media together. Especially if those groups could be assigned automatically and then monitored for new releases.
The use cases for this that I have found would be something like grouping books by audible series or grouping anime by series (it seems TVDB already groups like this but then all anime would need to be categorised as a "show" rather than an "anime")

**Comment by IgnisDa** [comment]
I don't think it would be possible to group media across sources. For that, it would be better if you just create a collection.

**Comment by Cheeseypop** [comment]
With anime specifically I was more referring to the fact that when an anime is searched for in the _anime_ category it lists all the seasons as individual items while the same anime searched for in the _shows_ category has one item for all the series. 

Anime: 1 show, 3+ items
![image](https://github.com/IgnisDa/ryot/assets/979803/01c8ae34-ac9d-4feb-8eff-ee4815962558)

Shows: 1 show, 1 item
![image](https://github.com/IgnisDa/ryot/assets/979803/712d905e-50f1-45aa-b4f3-038667ecd8c5)

**Comment by IgnisDa** [comment]
Does Anilist allow you to do that?

**Comment by IgnisDa** [comment]
Just looked into this, it doesn't. So the feature you want would not be possible for Anilist. Do you know of any free anime metadata providers that does provide this data?

**Comment by Sazu-bit** [comment]
What about anidb?
