### ISSUE TITLE
feature - automatically track people

### ISSUE THREAD

**Issue by pbogre** [IgnisDa/ryot#210]
i'm not sure whether this should be a category of its own, but personally i find it important to be able to track the creators of the media i'm consuming.

for example when i click on a movie i would like to be able to click on an actor in the list and see other movies from that actor. it would also be neat to be able to give ratings to people. (for reference, see how the project 'movary' does this)

this could of course be extended to authors for books, actors/directors/... for movies, etc.

if it were to be made a category of its own it should be handled automatically and i wouldn't want to look up (for example) a director after watching a movie and have to manually add him to the 'people' category.

**Comment by IgnisDa** [comment]
Earlier (maybe in `v0.*`), Ryot used to keep track of the people that contibuted to a media. I have since removed it since database queries were becoming very expensive. As of now, contributors of media are saved as JSON in the media metadata itself.

As such, I don't think I will add this feature since I have already tried this before, and it did not work out.

I am, however, open to suggestions. Keeping this issue open.

**Comment by IgnisDa** [comment]
> for reference, see how the project 'movary' does this

I like how Movary does it, but since Ryot tracks more than just movies, it would be very difficult to reconcile differences b/w them.

**Comment by pbogre** [comment]
> As such, I don't think I will add this feature since I have already tried this before, and it did not work out.

oh that is unfortunate, but it makes sense. hopefully a solution for this will be found in the future since tracking the people  i follow the most is important to me :)

**Comment by IgnisDa** [comment]
What all features are required for this? I see Movary has a view that sorts most watched actors, actresses, and directors. And then a view for a person's creations where all their movies are displayed. Is there anything else required?

**Comment by pbogre** [comment]
for me what movary does is perfect for my needs, my usual flow for movies is something like:

1. click on movie that i enjoyed
2. click on director/actor and see other works
3. find out he made another movie i liked, click on that
4. repeat

this allows me to navigate between movies freely and find out about a lot of connections between actors and directors which i then use to find other movies i would enjoy. it would be neat to rate people but i get that might be hard to implement, even just a "favorite" button like how it is done in jellyfin would be enough though.

**Comment by IgnisDa** [comment]
Hmm, sounds reasonable. I will probably break the changes into individual PRs since this is a very big feature request. Will get to this once I complete the important things.

**Comment by pbogre** [comment]
sounds great, thanks for the amazing project!

**Comment by IgnisDa** [comment]
@pbogre Most of this is complete. Just need to add creator reviews. Please give feedback.

**Comment by pbogre** [comment]
just looked at it through the demo and it's looking really good, nice work! 

some additional things that might polish this feature:

- add biographies for people, or just basic information like birth/death date, birth place, etc.
- i don't know if this is a bug but i tried adding a movie where the actor was also the director (the water diviner with russell crowe) and the director wasn't displayed, and when looking at russell's page it didn't display any movie in the directing section.
- add ability to add people to collections so you can track your favorite actors, or alternatively add something like a heart option on them to do the same thing


anyway, really nice work i like how it feels in general

**Comment by IgnisDa** [comment]
> add biographies for people, or just basic information like birth/death date, birth place, etc.

I don't think I will do this in the near future. Could you add a separate issue for this?

> if this is a bug

Probably is. I have an idea why it could be. Will look into fixing it.

> add ability to add people to collections

Ryot will allow you to review creators. Is that not enough for you?

>  think the director fetching in general is a little buggy

Yes it seems that directors are not fetched correctly. Will look into it.

**Comment by pbogre** [comment]
ah i thought that the 'reviews' section was supposed to display reviews from movies with that person involved in it, that's my mistake. Yes, that's perfectly fine as a substitution to the ability to add people to collections.

I will create a separate issue about the biographies.

Excellent work! This release definitely scratches my itch about following the work of various actors/directors/writers/...
