### ISSUE TITLE
jellyfin integration only takes effect on play/pause

### ISSUE THREAD

**Issue by pbogre** [IgnisDa/ryot#212]
if i were to watch a movie in its entirety without ever pausing it, the webhook would not take effect and the movie would not get added. the only way it is added is if i pause while watching it, and the only way it is marked as watched is if i pause towards the end like in the end credits, because if i go back to the jellyfin library without pausing, even during the end credits, the movie does not get added/updated/marked as watched.

i saw that movary handles this better, and does so by using the official jellyfin webhooks plugin with "generic destination". the way it works there is that when i start the movie it gets added, and when the playback stops it is marked as watched (i dont have to pause during the end credits)

something similar could be done with ryot, however it would mean to leave the progress updates (which imo are more important for stuff like books than movies), unless you do something like start a timer when the playback starts and stop it when a pause signal is sent from jellyfin, then use tmdb to see what the percentage of that is. However this is pretty complicated and honestly–at least for movies–all that's really needed is marking them as watched when i finish watching them.

**Comment by IgnisDa** [comment]
Blocked by https://github.com/shemanaev/jellyfin-plugin-webhooks/issues/9
