### ISSUE TITLE
[Feature Request] Add importing of Anilist media

### ISSUE THREAD

**Issue by HellsCrimson** [IgnisDa/ryot#214]
It would be really nice to be able to import the media from an Anilist account.
I saw that you already use GraphQL and it would allow to get the account data.

This request allows to get all Anime and Manga in a single request with most of the useful fields (I think)
```
{
  manga: MediaListCollection(userName: "HellsCrimson", type: MANGA) {
    lists {
      name
      status
      entries {
        mediaId
        progress
        score
        completedAt {
          year
          month
          day
        }
        startedAt {
          year
          month
          day
        }
      }
    }
  }
  anime: MediaListCollection(userName: "HellsCrimson", type: ANIME) {
    lists {
      name
      status
      entries {
        mediaId
        progress
        score
        completedAt {
          year
          month
          day
        }
        startedAt {
          year
          month
          day
        }
      }
    }
  }
}

```

It can be tested on the [Anilist GraphiQL](https://anilist.co/graphiql?query=%7B%0A%20%20manga%3A%20MediaListCollection(userName%3A%20%22user%22%2C%20type%3A%20MANGA)%20%7B%0A%20%20%20%20lists%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20status%0A%20%20%20%20%20%20entries%20%7B%0A%20%20%20%20%20%20%20%20mediaId%0A%20%20%20%20%20%20%20%20progress%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20completedAt%20%7B%0A%20%20%20%20%20%20%20%20%20%20year%0A%20%20%20%20%20%20%20%20%20%20month%0A%20%20%20%20%20%20%20%20%20%20day%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20anime%3A%20MediaListCollection(userName%3A%20%22user%22%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20lists%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20status%0A%20%20%20%20%20%20entries%20%7B%0A%20%20%20%20%20%20%20%20mediaId%0A%20%20%20%20%20%20%20%20progress%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20completedAt%20%7B%0A%20%20%20%20%20%20%20%20%20%20year%0A%20%20%20%20%20%20%20%20%20%20month%0A%20%20%20%20%20%20%20%20%20%20day%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) explorer

This is a low priority request as I saw that you are implementing fitness tracking. (For now I am using a small script to change the response from the previous request into the media_json format)

**Comment by HellsCrimson** [comment]
Yeah sure, I made it in one evening so it's not my proudest work (lseek and all), but it works (I might update it later)
The only thing that I wasn't sure was for the seen history array (I must look closer at how it is implemented)

```python
import sys, getopt
import json
from datetime import datetime

def main():
    filePath = ""
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hi:c:", ["ifile="])
    except getopt.GetoptError:
        print(f"{sys.argv[0]} -i <inputfile>")
        sys.exit(2)
    for opt, arg in opts:
        if opt == "-h":
            print(f"{sys.argv[0]} -i <inputfile>")
            sys.exit()
        elif opt in ("-i", "--ifile"):
            filePath = arg
    
    output_path = filePath.strip(".json") + "_fixed.json"
    with open(filePath, "r") as f:
        with open(output_path, "w") as fw:
            fw.write("[\n")
            data = json.load(f)
            data = data["data"]
            for key in data:
                for element in data[key]["lists"]:
                    for entry in element["entries"]:
                        entry["collections"] = [element["name"]]
                        entry["lot"] = key.capitalize()
                        entry["reviews"] = []
                        entry["source"] = "Anilist"
                        entry["identifier"] = str(entry["mediaId"])

                        if entry["completedAt"]["year"] != None:
                            end_date = datetime.now()
                            end_date = end_date.replace(
                                year=entry["completedAt"]["year"],
                                month=entry["completedAt"]["month"],
                                day=entry["completedAt"]["day"],
                                hour=0,
                                minute=0,
                                second=0,
                                microsecond=0)
                        else:
                            end_date = None
                        
                        if entry["startedAt"]["year"] != None:
                            start_date = datetime.now()
                            start_date = start_date.replace(
                                year=entry["startedAt"]["year"],
                                month=entry["startedAt"]["month"],
                                day=entry["startedAt"]["day"],
                                hour=0,
                                minute=0,
                                second=0,
                                microsecond=0)
                        else:
                            start_date = None

                        entry["seen_history"] = [
                            {
                            "ended_on": end_date.isoformat() if end_date != None else None,
                            "podcast_episode_number": None,
                            "show_episode_number": entry["progress"],
                            "show_season_number": None,
                            "started_on": start_date.isoformat() if start_date != None else None,
                            }
                        ]
                        entry.pop("mediaId")
                        entry.pop("completedAt")
                        entry.pop("progress")
                        entry.pop("score")
                        json.dump(entry, fw, indent=4)
                        fw.write(",\n")
            fw.seek(fw.tell() - 3, 0)
            fw.truncate()
            fw.write("\n]")

if __name__ == "__main__":
    main()
```

**Comment by IgnisDa** [comment]
AFAIK anilist doesn't return info about season or episode, so you'll have to pass null in those fields.

**Comment by HellsCrimson** [comment]
But is it really a problem for the season number ?
Because as you can see [here](https://anilist.co/anime/150672/Oshi-no-Ko/) and [here](https://anilist.co/anime/166531/Oshi-no-Ko-2nd-Season/), when there is a season 2 it is always a new entry so it will be 2 separate entry in ryot.
So I guess it's okay to always pass 1 as the season. Except if I really didn't understand what you meant by info about season.

As for the episode, they give the current progress so that's what I've been using.

**Comment by IgnisDa** [comment]
Either way, Ryot tracks season and episode progress only for shows and podcasts. Since Anilist doesn't provide either of them, you can simply put `None` in those places.
