### ISSUE TITLE
Bug: Overview is limited vertically

### ISSUE THREAD

**Issue by Sazu-bit** [IgnisDa/ryot#225]
When looking at say an Anime, I note that the Overview is limited to about 400px in height. 

div class: mantine-1edfrmu seems to limit the height to "18.75rem" there also appears to be something limiting it to 300px but I'm having trouble tracking it down.

There's no scroll bar displayed so it's not clear that there's more content. I don't think there's any need to limit the height here.

https://ryot.fly.dev/media/item?id=1909

**Comment by IgnisDa** [comment]
Yep, the image height is 300px, so I have constrained the right section to have the same, otherwise it looks weird.

**Comment by Sazu-bit** [comment]
No problem, I'll fork and remove it on my version. I have a much larger resolution so I'm basically seeing that part limited to the top quarter of my screen. It's like trying to read a book in a view port that's only one line high. Doesn't look weird at all to me.

**Comment by IgnisDa** [comment]
I could look into providing a config parameter for this. Can you attach a screenshot of how it looks like and what you want it to look like?

**Comment by Sazu-bit** [comment]
![Ryot-Current](https://github.com/IgnisDa/ryot/assets/57875915/5c2eb014-21e6-4ed4-852c-df92cd7f29c4)
![Ryot-Preferred](https://github.com/IgnisDa/ryot/assets/57875915/89dc2eed-1184-40ce-b3fe-9ddc785a3f15)

Here you go. The change is straight forward from a style point of view.
