### ISSUE TITLE
feature - fetch more information about people

### ISSUE THREAD

**Issue by pbogre** [IgnisDa/ryot#226]
When viewing a person's page display some of their information, such as but not limited to: 

- Birth Date
- Death Date
- Birth Place
- Still active?

Context: https://github.com/IgnisDa/ryot/issues/210#issuecomment-1660341706 
> add biographies for people, or just basic information like birth/death date, birth place, etc.

I don't think I will do this in the near future. Could you add a separate issue for this?

**Comment by IgnisDa** [comment]
- [ ] Allow sorting by name, number of media items in list people page

**Comment by IgnisDa** [comment]
The people section is now complete, and I will not come back to it for some time. Though I would still like to work on suggestions for people. Will make it a separate issue.
