### ISSUE TITLE
Support Apprise as notification platform

### ISSUE THREAD

**Issue by schklom** [IgnisDa/ryot#231]
Instead of implementing every notification service, support [Apprise-API](https://github.com/caronc/apprise-api) instead and let it link to most notification services.

**Comment by IgnisDa** [comment]
@schklom This looks like an awesome project. I would like to implement it. Can you give me some pointers on how it works?

What is the difference b/w https://github.com/caronc/apprise-api and https://github.com/caronc/apprise ? Which part would I self host on my server to get apprise working?

**Comment by schklom** [comment]
https://github.com/caronc/apprise-api = https://github.com/caronc/apprise + configuration webpage + API.
I host only Apprise-API on a server, and make calls from anywhere like
```sh
# Notifies all points tagged "mytag1" with attachments
# Requires a configuration to be loaded (typically on the service's webpage)
curl -X POST \
    -F 'title=test title' \
    -F 'body=test body' \
    -F 'tag=mytag1'
    -F attach1=@/path/to/attachment.doc \
    -F attach2=@Screenshot-2.png \ 
    "http://myapprise.mydomain/notify/KEY"
# KEY is by default equal to "apprise"

# Notifies an email address with attachments
# Does not require any configuration to be loaded
curl -X POST \
    -F 'urls=mailto://user:pass@gmail.com' \
    -F 'title=test title' \
    -F 'body=test body' \
    -F attach1=@/path/to/attachment.doc \
    -F attach2=@Screenshot-2.png \ 
    "http://myapprise.mydomain/notify/"
```
Apprise itself does not handle SSL, so you need a reverse-proxy to be able to use HTTP.
Personally, I also added Basic-Auth and opened this to the Internet, so the `curl` need to be slightly adjusted.

**Comment by IgnisDa** [comment]
How does it do authentication?

**Comment by schklom** [comment]
Apprise-API does not have any authentication and protection, see https://github.com/caronc/apprise-api#api-notes:
> There is no authentication (or SSL encryption) required to use this API; this is by design. The intention here is to be a light-weight and fast micro-service.

I personally add Basic Auth from my reverse-proxy. It is completely optional, and is not provided by Apprise.
Typically, I execute
```sh
curl -u 'username:password' \
    -X POST \
    -F 'title=test title' \
    -F 'body=test body' \
    -F 'tag=mytag1'
    -F attach1=@/path/to/attachment.doc \
    -F attach2=@Screenshot-2.png \ 
    "http://myapprise.mydomain/notify/KEY"
```
where `username:password` are the Basic Auth username and password.

**Comment by schklom** [comment]
PS: Alternatively, the content can be passed in JSON with the `Content-Type` header
´´´sh
curl -X POST \
    -d '{"tag":"mytag1", "body":"test body", "title":"test title"}' \
    -H "Content-Type: application/json" \
    http://myapprise.mydomain/notify/KEY
´´´

**Comment by IgnisDa** [comment]
So if I add apprise support to Ryot, then will I have to take authentication into consideration?

**Comment by schklom** [comment]
You can if you want to, but it is absolutely not necessary. Apprise by itself has no authentication.

What I meant is that some people like me add Basic Auth to have some protection. In shell, adding a username and password is trivial.

**Comment by IgnisDa** [comment]
Cool. LMK how the new integration works out for you.

**Comment by schklom** [comment]
Ok, the request makes it to Apprise-API, but fails to trigger any notification endpoint. Apprise-API logs a 424 error (I think HTTP 424 code).

In addition, if I understand correctly, I can notify based on the KEY in the URL h"ttp://myapprise.mydomain/notify/KEY".
Typically, a KEY represents a configuration file with many endpoints. By default, a request triggers all notification endpoints.
Ideally, I would love a way to only use one endpoint by specifying a tag :)

**Comment by schklom** [comment]
After testing, it seems the KEY field can take `KEY?tag=TAG` and works.
For some reason, no tag at all results in a 424 error.

Using multiple tags is explained in more detail at https://github.com/caronc/apprise-api#tagging.

I think you can just add an information somewhere that says we can put the tag in the KEY field

**Comment by IgnisDa** [comment]
Could you make a PR for this?
