### ISSUE TITLE
Ryot container refusing to run

### ISSUE THREAD

**Issue by TechnoMaverick** [IgnisDa/ryot#236]
Hello.

I recently tried to get Ryot up and running via docker compose using portainer. I'm admittedly new to selfhosting in general, so I apologize if I made a mistake.

I used the docker compose from the installation info in the documentation. However, when things started up, the actual "ryot" container is exited using exit code 101. Grabbing the logs from it gave me this:

`thread 'main' panicked at 'failed to create appender: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-appender-0.2.2/src/rolling.rs:499:53`

`note: run with` `RUST_BACKTRACE=1` `environment variable to display a backtrace`

The postgres database is running just fine.

Thank you for any help in advance.

**Comment by IgnisDa** [comment]
It seems you have not given correct permission to your volume. Please take a look into the installation docs.

**Comment by IgnisDa** [comment]
Did you chmod your container?

**Comment by akshara-tg** [comment]
No, not after creating ryot folder. I have a folder named **docker** on a SSD drive and created folder **ryot** in that.. The docker-compose.yml is inside this..
When I run the docker compose up, it's creating the folder for the bind volumes..
Can you please elaborate on your comment?

**Comment by IgnisDa** [comment]
Please read the docs 
![image](https://github.com/IgnisDa/ryot/assets/60938164/b1945e8d-1db1-4a0a-973e-92b620d360b3)

**Comment by akshara-tg** [comment]
@IgnisDa  Thanks. I was able to get it working.

@TechnoMaverick This is what I had done
before starting the container create the folder for bind volume
mkdir ryot-data
sudo chown 1001:1001 ryot-data
