### ISSUE TITLE
Slow action, huge bandwidth spike and other things

### ISSUE THREAD

**Issue by vutsalsinghal** [IgnisDa/ryot#243]
Hi @IgnisDa 

Thanks for `ryot`. It's a great tool with lot of potential! Love the super small cpu/memory footprint 💯 

There were few things I wanted to discuss and suggest.

1. Slow action - When you mark a season as seen, it takes lot of time. Not sure if its because of the - slow hardware (raspberry 4) or unoptimised DB query or something else. Possible short-term solution could be to update the frontend right away and use a queue or message broker to run slow DB queries in the background. (Also maybe something like redis could be optionally used for caching). EDIT - I noticed, that when you mark a season as seen, `ryot` makes 1 graphql query for each episode! This can be made ~10x faster (assuming 10 episode) if there was just 1 bulk update query. This would also help with no.3 
2. Huge bandwidth spike - When you mark a season as seen, the loading animation comes up and towards the end of this action, there is almost 10x spike in network activity. You can reproduce this on windowsOS (or macOS) by opening task manager "activities -> wifi/ethernet" tab in the background while you perform "mark as seen" action. You will observe the HUGE spike! Correct me if I'm wrong, this could be because ryot is fetching a LOT of images from tmdb. If thats the case, maybe cache images locally (enabled/disabled via env var) and/or lazy load images so frontend doesnt get blocked (and the bandwidth spike is spread)
3. When you mark the latest episode as seen the default behaviour should be that all episode before should be "marked as seen" or there could be a pop-up that confirms that. Same goes for seasons. When you mark latest season as seen then all seasons before it should be marked as seen (or there could be a pop-up that confirms that).
4. The "seasons" tab could have a better UI/UX. It feels too small/congested. (Not sure of its a popular opinion)
5. "Start monitoring" should be by default "on" when adding a TV show.
6. Make reviews an option feature. Maybe in the settings or env variable.
7. Enable/disable user signup. 
8. Critical (if any) settings should be in "admin" account only and "admin" creds can be defined via env vars (or the very first acc created can be admin acc)
9. Customise global header/footer/title.
10. Mark show/movie as "unseen".

**Comment by Sazu-bit** [comment]
Small footprint? Mine is using approx 1.5GB, may I ask what yours is using?

**Comment by vutsalsinghal** [comment]
<img width="1415" alt="image" src="https://github.com/IgnisDa/ryot/assets/7466579/1187c59a-9ef0-4a2e-be1d-6cdaf8c1d689">

This is my `ryot` container last 24hr trend. (I started using 2 days ago and have added maybe total ~15 shows/movies)

**Comment by IgnisDa** [comment]
5) what do you mean by adding a show?
6) what do you mean by this?
7) this is already possible. Please look at the configuration docs. Its somewhere under the `users` key.
8, 9, 10) I don't see a point to these.

The rest i agree with.

As for the network usage, most of the providers have a way to set the image resolution. Perhaps you can try lowering them. I remember I haven't put an option to change image resolution for tmdb, but I'll add it.

You're right, it does take a lot of bandwidth. I'll see if I can find a strategy to agressively cache images.

**Comment by IgnisDa** [comment]
@Sazu-bit 1.5GB of what? If this is network calls, then see above. If it's memory, there's something terribly wrong.

**Comment by Sazu-bit** [comment]
I'm locally hosting but yes 1.5GB. I install from source, I'll reinstall.

**Comment by IgnisDa** [comment]
That's weird. Are you using the docker container?

**Comment by vutsalsinghal** [comment]
> 3. this does make sense. But this is pretty cumbersome on a database level and I don't really want to make that change. You can just use mark seasons as seen until a season, and then individually mark episodes as seen for the remaining one. (Maybe I'll look into doing this, but this would be a breaking change and I'm loath to add this behaviour).

This would be very helpful feature. For example the show _family guy_ has I think 22 seasons. And If I mark S22 as seen then  s01-s21 should automatically be marked as seen instead of manually doing it. I assume one of the objective of `ryot` is to make it _super convenient/easy_ to tracker media related consumption for a person.... This feature will be in line with that imho :)

> 4. any suggestions on how it can be made better?

Sorry I'm no UI/UX engineer. This is not a big concern for now. Over time with the community's suggestion it might improve.

> 5. what do you mean by adding a show?

"Start monitoring" should be by default "on" when you add a show to "My Shows". I'm assuming "start monitoring" will message you when a new episode is about to air. So if I add a show to "My shows" then by default I would want timely notification about the net episode.

> 6. what do you mean by this?

"Post a review" action could be disabled via config (like maybe `users.allow_reviews`) similar to `users.allow_registration`. But its not a big deal. 

> 7. this is already possible. Please look at the configuration docs. (`users.allow_registration`).
Awesome!

**Comment by IgnisDa** [comment]
5) a media is automatically added to my shows under the following condition. https://github.com/IgnisDa/ryot/blob/9be620487c0e5bd621cbba6415c660f3744bb78e/apps/backend/src/migrator/m20230417_create_user.rs#L16

**Comment by IgnisDa** [comment]
3) maybe I'll add a select btn on the update page that will allow adding seen for just that season or all before it.

**Comment by IgnisDa** [comment]
You can disable reviews by setting `users.disable_reviews` to `true`.
