### ISSUE TITLE
[suggestion] UI improvements

### ISSUE THREAD

**Issue by DameGAD** [IgnisDa/ryot#250]
I've been using ryot for a few days now, and I have some suggestions make.
- It would be a improvement to be able to keep open by default chosen sections of the menu on the left. For instance, I use a lot Movie and Show and it would make them accessible with only one click instead of two. A setting could be added in Preferences bellow "Enabled features" to keep open the desired sections.
- Long descriptions on content pages are partially hidden. It can even hide the cast list. The TV series "The Crown" (2016) is a good exemple of that. I never coded anything so don't really know how it works, but I guess the area used to display description and cast could adapt to the quantity of information to display. There is nothing bellow that anyway.
- On a 13" computer laptop there is an empty space bellow the content poster that could be used to display action buttons and make them easier to access.

**Comment by IgnisDa** [comment]
1. I'm not really sure what you meant by this. Can you attach screenshots to explain?
2 and 3) you can increase the viewport width for the content area. I don't remember the exact key, but it's under the `frontend.` key. Please look into the configuration docs.

**Comment by IgnisDa** [comment]
Or maybe it would be better to hide long descriptions (let's say more than 10 lines long) behind a [spoiler](https://mantine.dev/core/spoiler/) .

**Comment by IgnisDa** [comment]
1) Makes sense. Will look into "remembering" state.
2) Please read the configuration docs. All keys have a corresponding env variable. In your case, you can set `FRONTEND_ITEM_DETAILS_HEIGHT=400` to set the height to 400 pixels.

**Comment by DameGAD** [comment]
I read the documentation and tried to use the environment variable FRONTEND_ITEM_DETAILS_HEIGHT with various values, but without any success. Anyway, it's not a big deal.

And thank you for #251 !

**Comment by IgnisDa** [comment]
Can you set the environment variable and show the output of `https://<instance_url/config`. The config variable should work.

**Comment by DameGAD** [comment]
> FRONTEND_ITEM_DETAILS_HEIGHT

The output:

`{"anime":{"anilist":{}},"audio_books":{"audible":{"locale":"us"}},"books":{"openlibrary":{"cover_image_size":"M"},"google_books":{}},"database":{"auth_db_path":"****","url":"****"},"exercise":{"db":{"json_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json","images_prefix_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises"}},"file_storage":{"s3_access_key_id":"****","s3_bucket_name":"****","s3_region":"****","s3_secret_access_key":"****","s3_url":"****"},"frontend":{"item_details_height":300},"integration":{"pull_every":2,"hasher_salt":"****","minimum_progress_limit":2,"maximum_progress_limit":95},"manga":{"anilist":{}},"media":{},"movies":{"tmdb":{"access_token":"****","locale":"en"}},"podcasts":{"listennotes":{"api_token":"****"},"itunes":{"locale":"en_us"}},"scheduler":{"database_url":"****","rate_limit_num":5,"user_cleanup_every":12},"shows":{"tmdb":{"access_token":"****","locale":"en"}},"users":{"allow_changing_password":true,"allow_changing_preferences":true,"allow_changing_username":true,"allow_registration":true,"reviews_disabled":false,"token_valid_for_days":90},"video_games":{"igdb":{"image_size":"t_original"},"twitch":{"client_id":"****","client_secret":"****"}},"server":{"config_dump_path":"****","cors_origins":["****"],"default_credentials":false,"insecure_cookie":true,"progress_update_threshold":2}}`

And this is my docker-compose file:

version: "3.9"
services:
  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    container_name: ryot
    network_mode: bridge_postgres
    user: userid:groupid
    environment:
      - SERVER_INSECURE_COOKIE=true
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - FRONTEND_ITEM_DETAILS_HEIGHT=600
    ports:
      - "8001:8000"
    volumes:
      - /mnt/ssd1/docker/ryot:/data

**Comment by IgnisDa** [comment]
That's weird. You have set the correct env variable but Ryot does not seem to have picked it up.

**Comment by IgnisDa** [comment]
Fixed in `v2.5.3`.
