### ISSUE TITLE
helm chart support

### ISSUE THREAD

**Issue by yodatak** [IgnisDa/ryot#259]
Hi thanks a lot for your app it look awsome

Did you plan on make a helm chart for K3/k8 homelabs or ask for a helm chart from people from truechart ?

Thanks and keep rusting !

**Comment by IgnisDa** [comment]
I have no idea about kubernetes. Will you be able to make a PR for it?

**Comment by IgnisDa** [comment]
Closing this since I do not have bandwidth to address it. Feel free to reopen if interested in working.
