### ISSUE TITLE
[request] Pushover & disable Fitness

### ISSUE THREAD

**Issue by glottisfaun0000** [IgnisDa/ryot#266]
Finally got around to trying out Ryot and it's awesome, thanks for the continued work on it. Jellyfin integration is working for me which is so cool.

1. I use pushover for notifications and I notice Ryot only asks for the User Key and uses that to send a generic notification with no spot for an App Key. Adding the App Key would be nice for customization, or you could build-in apprise ([like Bazarr does](https://wiki.bazarr.media/Additional-Configuration/Settings/#notifications)) and add support that way https://github.com/caronc/apprise/wiki/Notify_pushover

2. Add Fitness altogther to the Enabled features section so it can be disabled.

**Comment by IgnisDa** [comment]
Both should be easy enough to do. Will do

**Comment by IgnisDa** [comment]
@glottisfaun0000 I could not find any documentation on the pushover app key. Can you link me to it?
