### ISSUE TITLE
Error on Login with Newest Update

### ISSUE THREAD

**Issue by nealhead** [IgnisDa/ryot#270]
Looks like I am receiving the following error after updating to the newest 2.7.1 release upon trying to login. Are there upgrade notes I may have missed?

> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `measurements`", line: 1, column: 47) }))', apps/backend/src/miscellaneous/resolver.rs:3312:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

I tried moving back to 2.6.0 but it wouldn't start. Would a full backtrace be helpful?

**Comment by IgnisDa** [comment]
No this is a regression on my end. I will fix it in the next update. Thanks for reporting.
