### ISSUE TITLE
Support 5 star rating

### ISSUE THREAD

**Issue by lyz-code** [IgnisDa/ryot#283]
I've been rating all my media with a 5 star rating system, so switching to a 100% system is not something I'd like to do.

What are your thoughts on creating a settings option to use one system or the other?

Thanks!

**Comment by IgnisDa** [comment]
Sounds resonable. Would you prefer it to be a user level or instance level setting?

**Comment by lyz-code** [comment]
I'd say that whatever is easier to implement. If there's no difference, the ideal scenario would be to have an instance level setting that can be overridden by the users themselves.
