### ISSUE TITLE
[Question] Easier media rating

### ISSUE THREAD

**Issue by lyz-code** [IgnisDa/ryot#284]
I'm thinking on migrating from mediatracker to ryot, but there are some UI interactions that I still feel more comfortable with in mediatracker. Probably is because I'm not experienced enough on Ryot usage so I'd like to share with you my current workflow and ask you how you'd do it in Ryot.

Whenever I finish seeing a movie:

- Mediatracker's jellyfin plugin registers the scrob
- I go into mediatracker's main web page, there I see the latest elements that have not been rated
- I click on the star icon
- I enter the rating and optionally enter a review.

From what I've seen, on Ryot the process would be:

- Ryot's jellyfin plugin registers the scrob
- I go into the movies ryot page (you can't see the unrated elements in the home, right?)
- I click on the movie
- I click on post a review
- I click on the %, then type the number (I guess it would be more uncomfortable to type it on the mobile keyboard, unless it's defined as a numeric field (I haven't tried yet)), optionally enter a review

I feel that rating movies so far is still more user friendly in mediatracker as it requires many less clicks and manual typing due to the quickness of the [5 star workflow](https://github.com/IgnisDa/ryot/issues/283) available on the home page of the site.

Whenever I finish seeing a tv show episode:

- Mediatracker's jellyfin plugin registers the scrob
- I go into mediatracker's main web page, there I see the latest elements that have not been rated
- I click on the tv show
- Then I scroll and search for Episodes
- Then I scroll and search for the last episode that is not rated but is marked as seen
- I click on the star icon of the episode
- I enter the rating and optionally enter a review.

This workflow is a bit more cumbersome on mediatracker in comparison with the movies rating because you can't do everything from the home page.
 
From what I've seen, on Ryot the process would be:

- Ryot's jellyfin plugin registers the scrob
- I go into the series ryot page (you can't see the unrated elements in the home, right?)
- I search the tv show in the list (I've seen that even if you manually update the process of a tv show, it doesn't show as the first one in the list of Last seen, which is the default page. It does show first in the Last updated, but only after you click on the `tabler-icon-refresh` button. So if I have the page preloaded, I'd have to click that button to see the latest state of the tv shows, it won't auto-update when I get in)
- I click on the tv show
- Click on the History to see which has been the latest episode seen
- Click on Reviews to se which has been the latest episode rated
- Click on Actions
- Click on Post a review
- Click on the Episode and select the correct one (By default it selects the first unseen episode, so if the plugin scrobs the S01E03, here it will appear the S01E04 which has not yet been viewed)
- I click on the %, then type the number (I guess it would be more uncomfortable to type it on the mobile keyboard, unless it's defined as a numeric field (I haven't tried yet)), optionally enter a review

Thus I also feel that rating tv shows so far is still more user friendly in mediatracker due to the quickness of the [5 star workflow](https://github.com/IgnisDa/ryot/issues/283) and the fact that even though it's cumbersome to reach the episode you want to rate, it's still faster than the ryot's process.

In an ideal scenario, I'd see the unrated episodes sorted by last seen in the home page, click an element of the poster (like the star in mediatracker), enter the rating,  optionally the  review and click submit.

I don't want to sound negative, I think Ryot's web design is much prettier than mediatracker's and I also love the detail that the rating of the Tv show is automatically calculated based on the ratings of the episodes <3. If the rating process becomes easier I'd definitely do the switch.

Thanks for maintaining and developing Ryot :)

**Comment by IgnisDa** [comment]
Thanks for the extensive report. I agree that Ryot needs to be more functional, but I am not a UI designer, so I find that work boring. I just rolled with whatever that made sense to me at that time.

I like your advice. Maybe I can have a star icon on the top right on the list page that directly takes you to the review page. Does that sound good?

**Comment by lyz-code** [comment]
> I am not a UI designer, so I find that work boring. I just rolled with whatever that made sense to me at that time.

I feel you, I do the same with my programs, it's more than enough that you're sharing the code itself!

> Maybe I can have a star icon on the top right on the list page that directly takes you to the review page. Does that sound good?

I'm not sure that I understand you well, but it does sound good. A star icon on the top right (or wherever) on each of the posters of the items (similar to how mediatracker does) that either brings you to the review page or opens a pop-up with the review page content would be wonderful.

What do you think on the rest of the suggestions?

- A view to quickly see which items haven't been rated
- A more user friendly way to set the rating: Maybe a slider with stops each 10% beside the prompt?

**Comment by IgnisDa** [comment]
> A view to quickly see which items haven't been rated

This is possible by apply the "Unrated" filter

> A more user friendly way to set the rating: Maybe a slider with stops each 10% beside the prompt?

Sounds reasonable. Maybe I will create a setting for this.

**Comment by IgnisDa** [comment]
Hmmm just noticed that the Unrated filter does not work. Will fix it.

**Comment by IgnisDa** [comment]
For some reason the "Unrated" filter does not work on the demo instance. But it does work on mine. IDK why 🤷🏽‍♂️.

**Comment by IgnisDa** [comment]
Some other things I would like to address:

> you can't see the unrated elements in the home, right?

Yes. I do not want the homepage cluttered. Somewhere down the line, I would like the homepage to be configurable, but right now, I think it is fine. 

> I guess it would be more uncomfortable to type it on the mobile keyboard, unless it's defined as a numeric field

It is defined as number :)

>  So if I have the page preloaded, I'd have to click that button to see the latest state of the tv shows, it won't auto-update when I get in

The query made to the database is pretty heavy so I had disabled auto refresh. But since there are only 20 elements, it does not matter. Will enable it.
