### ISSUE TITLE
[Suggestion] RSS reading status tracker and backup location tracker

### ISSUE THREAD

**Issue by grapemix** [IgnisDa/ryot#286]
1) RSS reading status tracker
Besides of feedly which is a commercial product, there has no good product that can let you track which RSS items you have read in **multiple devices**.  Even most of commercial product don't make the cut in my opionion. I haven't seen an open source solution for RSS feeds tracking for **multiple devices**. And even for feedly, they can't track on ebook reader which suppose to be an excellent choice to read RSS feeds.

2) backup location tracker
Most people has backup or even multiple backups, but it will be so easy to forget which items(movies, tv, books, videos....) have been backed up and where do we backup (like in Gcloud or hdd1 in garage or hddXXX in somewhere else). Some of the resources I would like to **move** to cold storage, instead of copy to cold storage because of the storage size. So forgetting an items have been backed up or not can be a big deal. 

In both use cases, I hope there will be APIs for other dev to hook up to their existing project. And I hope we don't have to rely some technologies like multicast and DLNA in favor the k8s setup.

Finally, thanks for your work. Keep this project going.

**Comment by IgnisDa** [comment]
Honestly I have no idea what you mean. Do you have any documentation i can read to see what all this is?

**Comment by grapemix** [comment]
For RSS reading status tracker:
With https://feedly.com/, you can subscribe the RSS feeds to their site and when you use their web or mobile client, you can read and mark a feed news as read. There have lots open source RSS readers app like https://gnome.eu.org/index.php/Evolution_RSS_Reader_Plugin, https://github.com/koreader/koreader/wiki/News-downloader, https://f-droid.org/en/packages/com.nononsenseapps.feeder/ and more, but none of them sync with the progress. If you marked a feed news in one app or device as read, your "read record" won't be known/sync when you switch to another app or device. Isn't your app try to track various resources? So I think it is very good show case.

For backup location tracker:

We have lots of streaming server for homelabs: plex, jellyfin, kodi.... And we have lots of opensource solutions like: bacula.org, syncthing.net.... But none of them connect to each other. Ideally, when I am in jellyfin, I can tag/mark a movie needs to be moved from NAS to cold storage like another HDD. After a trigger (no matter pulling or pushing), ryot saves a reference id and path. And other dev like me can integrate other backup solution to move the movie away. Of course, we can directly hook up a backup solution and a media browser without middleware like ryot. But I think ryot can also be a resource manager to track the location and state(in NAS, cold storage like another HDD....) of resources.

I hope these use cases make sense to you and the others. I can also predict there will be lots of co-ordination required during integrations, so the progress will be really slow. BUT, there has no alternative solution in the open source world. In other word, the above solutions won't be another "yet another XXXX" project. It will be unique and meaningful.

**Comment by IgnisDa** [comment]
> But I think ryot can also be a resource manager to track the location and state(in NAS, cold storage like another HDD....) of resources.

Ryot is meant to be a media tracker and not a media asset manager. It will not support this feature. I think a better idea would be to write a Jellyfin plugin for it (if I understand you correctly).

> For RSS reading status tracker:

I am still not sure what this will really entail, but I am interested in supporting it. Is this something that webhooks can fix?

**Comment by IgnisDa** [comment]
@grapemix any inputs?

**Comment by grapemix** [comment]
1) Too bad. I just think an app as middleman like Royt is a good candidate for de-coupling the backup tracking feature from others app, but it is your app and your call.

2) I think so. The tricky part is the primary key of the RSS.  The guid might not be there in the client side. 

And I don't know if who generate the guid, if it is generated by the creator, we don't have to worry the GUID is different in different clients, but we will have problem if the RSS source don't have GUID. If the GUID is NOT generated by the creator, different clients might generate different GUID when they download the RSS feed from the source.

**Comment by IgnisDa** [comment]
I will look into it.

**Comment by IgnisDa** [comment]
I have decided not to go forward with this. Instead, this can be implemented via #73.
