### ISSUE TITLE
Doc: Cosmos installer 

### ISSUE THREAD

**Issue by azukaar** [IgnisDa/ryot#290]
We added a one click installer to Cosmos for Ryot, in case you want to mention it somewhere in the install process for example.
There's also a link that gives you the app on the market directly: https://cosmos-cloud.io/proxy#cosmos-ui/market-listing/cosmos-cloud/Ryot

![image](https://github.com/IgnisDa/ryot/assets/7872597/c2b73744-e4a9-4c14-945b-9405e00129a5)

Feel free to close this ticket if irrelevant!
Thanks!

![image](https://github.com/IgnisDa/ryot/assets/7872597/97b33671-3435-4aa9-9d1d-277873d97959)

**Comment by IgnisDa** [comment]
> If you need / want to change how Ryot appears in the marketplace, all the files are here, and it's under Apache licence: https://github.com/azukaar/cosmos-servapps-official/tree/master/servapps/Ryot

All seems good. Just that `SERVER_INSECURE_COOKIE` is only required in development mode/localhost. I think it can be removed from the cosmos image.

**Comment by azukaar** [comment]
Ah thanks for the tips
