### ISSUE TITLE
[Suggestion] Aggregate user review scores for a single movie and show value next to other ratings.

### ISSUE THREAD

**Issue by jakesmorrison** [IgnisDa/ryot#295]
When you have selected a movie or tv show display the aggregated review score of all users. For example if I give it 4 stars and someone else gives it 5 stars it would show an aggerated value of 4.5 stars.

Blocked by #294.

**Comment by IgnisDa** [comment]
I don't really see the point to this, in addition to not having any ideas on what a good UI for this will look like. With the addition of Provider ratings (#294), the page looks very cluttered and I don't want to add more stuff to it without it having real meaning.

**Comment by jakesmorrison** [comment]
Cool. You should do whatever you want. A quick explanation below of why I wanted the suggestion. 

The purpose is if you have multiple users you see your Ryot instance overall score for a given piece of media. Along with other ratings systems this could help other users decide if they should watch something. It is a float value and an icon. Not sure how it is looking that cluttered. The movie page on my screen looks pretty barren compared to something like Overseer; I have not looked at it on mobile though.

![image](https://github.com/IgnisDa/ryot/assets/14865171/7652594b-73b8-4cd4-a3b3-78239a52f259)
![image](https://github.com/IgnisDa/ryot/assets/14865171/c31435fb-2a2f-4c48-97ff-291893f659a2)

**Comment by IgnisDa** [comment]
Can you attach the overseer page for a movie with a long title?

**Comment by jakesmorrison** [comment]
This was the longest I could find. 

![image](https://github.com/IgnisDa/ryot/assets/14865171/fd15b875-0fd4-4620-9636-af15deea15fd)

**Comment by IgnisDa** [comment]
Now can you edit what you would expect it to look like on Ryot like you did [here](https://user-images.githubusercontent.com/14865171/266776654-7652594b-73b8-4cd4-a3b3-78239a52f259.png).
