### ISSUE TITLE
[Suggestion] Toggle between movie posters and table view. 

### ISSUE THREAD

**Issue by jakesmorrison** [IgnisDa/ryot#297]
Similar to how radarr and sonarr allows you to switch between posters
![image](https://github.com/IgnisDa/ryot/assets/14865171/4a06f0b3-66c6-4aa8-a143-9598dc768eb9)

and table format

![image](https://github.com/IgnisDa/ryot/assets/14865171/c5a4a5be-c34f-46c6-b1a8-dceb39cf6070)

Some table info that I would like to see:
1. Title
2. Year
3. Count of users who have watched.
4. Count of users who have reviewed. 
5. User aggregated review, RT, Metacritc, imdb. 
6. Maybe a row highlight to show if you have watched a movie or not.

**Comment by IgnisDa** [comment]
Reply from [reddit](https://www.reddit.com/r/selfhosted/comments/1613x3w/comment/jxs1lj4/?utm_source=share&utm_medium=web2x&context=3):

> Ryot used to support a table view back in the day. However, I am not a UI developer and it looked horrible. I got rid of it. If you have a good suggestion for a UI for this, I can implement it.

**Comment by IgnisDa** [comment]
I don't really want to implement this. UI is not my specialty and I feel the poster view serves needs well enough,
