### ISSUE TITLE
Import Anime and Manga from MyAnimeList

### ISSUE THREAD

**Issue by dityb** [IgnisDa/ryot#298]
Using http://myanimelist.net/panel.php?go=export , users can export their anime and manga lists to an XML file. Being able to import this list would help those people coming to RYOT from MAL.

**Comment by IgnisDa** [comment]
@dityb Are you the same person that sent me their export on Reddit? If not, can you send me your MAL export, since I want to account for all the edge cases. My email id is in my profile.
