### ISSUE TITLE
[Suggestion] MAL Sync

### ISSUE THREAD

**Issue by dityb** [IgnisDa/ryot#299]
It would be cool for RYOT to use the MAL API to keep itself synchronized with any changes that occur on either side.

**Comment by IgnisDa** [comment]
I don't understand why ryot would need this feature. As far as I can see, MAL is a tracker (and does not allow you to read manga directly). So one would use either Ryot or MAL not both (after importing data into their tracker of choosing).

Do correct me if I am wrong.

**Comment by dityb** [comment]
Correct, MAL is another tracker but it acts as a sort of social platform as
well where other friends who have MAL accounts will watch, rate, and
recommend shows based on what you have watched and rated. For me, there is
the appeal of using RYOT on my end for a self hosted and centralized
tracker, not necessarily for privacy or security for anime, and I would
like to use MAL as well to keep my list up to date so other friends can see
what I've been watching.

 I agree there is significant overlap, otherwise though.

**Comment by IgnisDa** [comment]
For me, when I use self hosted software, I understand that I have to give up the social aspect of tracking. I understand where you come from, but I don't think this (i.e, syncing data from another tracker to Ryot) is something I want in this project.

That being said, if you create a project which allows one to do it, I am willing to implement necessary APIs needed in Ryot to achieve this.

**Comment by IgnisDa** [comment]
Ryot does have a slight social aspect to it, but I doubt your friends will be willing to switch to Ryot :).
