### ISSUE TITLE
[Suggestion] Add MangaUpdates as a metadata provider for Mangas

### ISSUE THREAD

**Issue by OutageOctopus** [IgnisDa/ryot#300]
Request to add MangaUpdates as an additional or alternative metadata  source for mangas.

For manhwas (Korean comics) AniList is missing many titles (as is MyAnimeList another requested source). For manhwas, MangaUpdates is the most comprehensive resource available.

The API can be found here: https://api.mangaupdates.com

**Comment by IgnisDa** [comment]
Interestingly, this API does not have an endpoint for searching.

**Comment by IgnisDa** [comment]
Helpful: https://github.com/kirtanp98/mangaupdates-graphql-api

**Comment by IgnisDa** [comment]
Huh it looks like I was wrong. The API does have a search endpoint. However it uses POST method. Go figure. Thanks for helping me figure it out. WIll implement this ASAP.

**Comment by IgnisDa** [comment]
@OutageOctopus Any idea on what a difference b/w a release and series in the context of mangaupdates.com?

**Comment by IgnisDa** [comment]
So if I understand correctly, a series can be equated to a media item in ryot. Is there any notion of a group (as described in #203)?

**Comment by IgnisDa** [comment]
Published in `v2.9.4`. Feel free to reopen if there are features missing.
