### ISSUE TITLE
[Suggestion] Youtube Watched Videos

### ISSUE THREAD

**Issue by mmarquezs** [IgnisDa/ryot#304]
Basically be able to track which videos you have watched.
Could be organized by channels.

**Comment by IgnisDa** [comment]
If I remember correctly, Youtube does not have a documented API for this.

**Comment by mmarquezs** [comment]
Sorry, for what? I am confused.
I don't mean to sync watched status with YouTube if you understood that.

**Comment by IgnisDa** [comment]
Sounds reasonable. I will think about how to implement this after https://github.com/IgnisDa/ryot/issues/226 is complete since it will contain a major overhaul to the creator code.

**Comment by Attacler** [comment]
Maybe you could also do it the other way around, allow you to watch/search yt inside of the tracker and track it that way

**Comment by IgnisDa** [comment]
So... reimplement youtube? I'd rather not.

**Comment by IgnisDa** [comment]
i have decided not to implement this.
