### ISSUE TITLE
[Bug] MAL Import Fails, No Report Generated

### ISSUE THREAD

**Issue by howtedious** [IgnisDa/ryot#308]
There appears to be a bug with the recently added MAL import https://github.com/IgnisDa/ryot/pull/307.

The import functionality does not work on a fresh install.

**Environment**
Fresh install with Docker on Ubuntu 22.04, using the docker-compose file from the documentation.
./ryot-data in the folder has been chown 1001:1001

**Reproduce**
Fresh install -> Go to Imports -> Select MAL as Source -> Select Anime File -> Select Manga File -> Import -> Dialog appears -> OK.

**What I expect to happen**
New entries are generated in the manga and anime collections.

**What actually happens**
Nothing.

**Potential Fix**
Check for a /tmp directory in the mapped directory, and if it does not exist create one before upload_file tries to use it in apps/backend/src/routes.rs

I tested the fix by creating a ./ryot-data/tmp folder manually, which then let me import.

**Comment by IgnisDa** [comment]
That's interesting. I think the reason is that a scratch docker image does not have that directory created.
