### ISSUE TITLE
[Bug] AverageRating calculated incorrectly when using "Out Of Five" scale

### ISSUE THREAD

**Issue by bretthysuik** [IgnisDa/ryot#319]
Environment:
v2.14.1, my own instance (not https://ryot.fly.dev/)

Query:
```
query MediaList($input: MediaListInput) {
  mediaList(input: $input) {
    items {
      averageRating
      data {
        identifier
        title
        publishYear
      }
    }
  }
}
```

Query variables:
```json
{
  "input": {
    "page": 1,
    "lot": "MOVIE",
    "query": "Spider-Man: Across the Spider-Verse"
  }
}
```

Response:
```json
{
  "data": {
    "mediaList": {
      "items": [
        {
          "averageRating": "4",
          "data": {
            "identifier": "29",
            "title": "Spider-Man: Across the Spider-Verse",
            "publishYear": 2023
          }
        }
      ]
    }
  }
}
```
<br>
<br>

I expect `"averageRating": 3.5` because there's a single review with rating 3.5, but instead returns `"averageRating": "4"`:

![image](https://github.com/IgnisDa/ryot/assets/2490331/fc0e32f4-ff41-4d8d-a158-ca1b55f51cf5)

**Comment by bretthysuik** [comment]
@IgnisDa, thanks that fixed the API query, but the UI needs to be updated as well to round to 1 decimal place instead of 4:

![image](https://github.com/IgnisDa/ryot/assets/2490331/ed3f2bf8-015a-4c9f-9c95-add72cb716e8)

**Comment by IgnisDa** [comment]
COuld you make a PR for this?

**Comment by bretthysuik** [comment]
I don't have any rust experience, but I suppose I could try.

**Comment by IgnisDa** [comment]
This wont be a rust change, just a small change in the frontend codebase. `rating.toFixed(1)` or something similar.
