### ISSUE TITLE
UI only takes up a third of the screen

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#322]
![image](https://github.com/IgnisDa/ryot/assets/94771708/b181550e-fe7c-48bf-9eb3-3549643b9024)
I think the scroll wheel is kind of awkward with it leaving a bunch of empty space below it.

**Comment by IgnisDa** [comment]
I am not that good with UI designing. I will accept PRs for this, but won't work on it.

**Comment by IgnisDa** [comment]
If anyone wants to take this up, please feel free to do so. Closing to keep keep relevant issues on the tracker.
