### ISSUE TITLE
[Feature Request] VNDB tracker

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#323]
https://vndb.org/

vndb is the best visual novel database out there and it would be cool to see it in ryot.

**Comment by IgnisDa** [comment]
@reitenth Could you please confirm? I would like to work on this.

**Comment by reitenth** [comment]
visual novels are separate from manga and anime, even anilist/mal dont track them, so probably a new category.

**Comment by IgnisDa** [comment]
Right now, it is not possible to track suggestions and staff creators. One of the issues is here: https://vndb.org/t19740.

**Comment by IgnisDa** [comment]
@reitenth Please test this when you can. I would appreciate if you could provide feedback for it.

**Comment by reitenth** [comment]
it seems as though its not pulling the cover art for the poster right now.

**Comment by IgnisDa** [comment]
Can you give an example of what Ryot is pulling and which image you expect it to pull?
