### ISSUE TITLE
[Feature Request] Trailer for shows/movies/anime

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#324]
would be nice to pull trailers from tmdb to watch

**Comment by IgnisDa** [comment]
Good idea! Do you have suggestions as to where the videos should go in the UI? Placing them in place of images won't really look good.

**Comment by reitenth** [comment]
![image](https://github.com/IgnisDa/ryot/assets/94771708/8b199c2f-1b18-49c0-9ca7-a6bbbdee32d4)
i would remove the max height on the right container and try below the poster or maybe a tab next to suggestions?

**Comment by IgnisDa** [comment]
You can increase the max height of the container by setting the `frontend.item_details_height` key. (https://ignisda.github.io/ryot/configuration)
