### ISSUE TITLE
MySQL issue 42000

### ISSUE THREAD

**Issue by NoxRare** [IgnisDa/ryot#326]
I'm trying to setup ryot using mysql and getting this error:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Exec(SqlxError(Database(MySqlDatabaseError { code: Some("42000"), number: 1059, message: "Identifier name 'fk_partial-metadata-to-metadata-group_id-metadata-partial-metadata_id' is too long" })))', apps/backend/src/main.rs:137:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

any ideas?

**Comment by IgnisDa** [comment]
BruH MySql always be disappointing. I will probably drop support for it next major release. Will it be possible for you to switch to Postgres?

**Comment by NoxRare** [comment]
> BruH MySql always be disappointing. I will probably drop support for it next major release. Will it be possible for you to switch to Postgres?

I can switch to postgres, however all my currently hosted projects use mariadb and I would like to keep the containers to a minimum. If you like I can def look into switching to postgres.

**Comment by IgnisDa** [comment]
I would definitely suggest you do. I won't be able to fix this anyway without https://github.com/IgnisDa/ryot/issues/294#issuecomment-1694327029 being resolved.

**Comment by IgnisDa** [comment]
Blocked by https://github.com/SeaQL/sea-orm/issues/1839

**Comment by NoxRare** [comment]
Quick question, would this affect SQLite aswell? and what are the downsides of using SQlite, I've heard a lot of bad things about it lol.
