### ISSUE TITLE
[Feature Request] Board game tracker

### ISSUE THREAD

**Issue by bretthysuik** [IgnisDa/ryot#344]
API: https://boardgamegeek.com/wiki/page/BGG_XML_API2

Example search API call: https://boardgamegeek.com/xmlapi2/search?query=Gloomhaven&type=boardgame
Example details API call: https://boardgamegeek.com/xmlapi2/thing?id=174430&stats=1

**Comment by IgnisDa** [comment]
I think this would better fit under #73, right?

**Comment by bretthysuik** [comment]
Sure, however you want to track it. I figured it was along the same lines as #323

**Comment by IgnisDa** [comment]
I could put visual novels under media, can't do it for Board games. Closing in favor of #73.
