### ISSUE TITLE
Authorization Error You are not logged In

### ISSUE THREAD

**Issue by killerdraft** [IgnisDa/ryot#345]
After I create a username and password. When i try to login I get this error "Authorization Error You are not logged In" Also please see screenshot.

Any assistance would be greatly appreciated.

![2023-09-15_04-51-11](https://github.com/IgnisDa/ryot/assets/75647740/3557675b-153e-4931-9668-0b6cc6f872c1)

Docker Compose

version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres # recommended
      # - DATABASE_URL=sqlite:./ryot-db.sqlite # SQLite database
      # - DATABASE_URL=mysql://mysql:mysql@mysql:6749/mysql # MySQL database
      # - SERVER_INSECURE_COOKIE=true # only needed in localhost or non-https
    ports:
      - "18030:8000"
    # volumes:
    # - ./ryot-data:/data # only needed if using sqlite database
    pull_policy: always
    container_name: ryot

volumes:
  postgres_storage:

OS 
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

Browser 
Chrome
Version 116.0.5845.188

**Comment by IgnisDa** [comment]
Can you share a screenshot of the developer console (right click on the web page and click on inspect)?

**Comment by killerdraft** [comment]
Sorry dev console is here
![2023-09-15_04-58-04](https://github.com/IgnisDa/ryot/assets/75647740/ce8649d0-ed44-47d9-994f-f30a5d8717ca)

**Comment by killerdraft** [comment]
Sorry this is the dev console.

[image: 2023-09-15_04-58-04.png]

**Comment by IgnisDa** [comment]
You need to login with the dev console open so I can see if the cookie is being rejected.

**Comment by killerdraft** [comment]
Sorry, while the dev console is opened, tried logging in. 
![2023-09-15_05-09-15](https://github.com/IgnisDa/ryot/assets/75647740/04747a32-95d0-43eb-9622-3ae4f6d76724)

**Comment by IgnisDa** [comment]
Nope, nothing here. Try the network tab.

Click on the network tab and clear all previous requests and then try logging in. You should see a request. Show me its response.

Are you hosting it on a domain or on an IP address?

**Comment by killerdraft** [comment]
Hosting it on a local, accessing by IP
![2023-09-15_05-16-16](https://github.com/IgnisDa/ryot/assets/75647740/687f0ad9-0bcf-4a64-ad7f-e9181b7b4dc8)

**Comment by IgnisDa** [comment]
There is a line in your docker compose:
```
 # - SERVER_INSECURE_COOKIE=true # only needed in localhost or non-https
```

Please uncomment it.

And read what you are running on your server.

**Comment by killerdraft** [comment]
That was the magic, thanks soo much.
Works
