### ISSUE TITLE
GoodReads import fails: missing field `book_description`

### ISSUE THREAD

**Issue by vitormarcal** [IgnisDa/ryot#348]
Good day!

When I try to import goodreads feed ([with this link](https://www.goodreads.com/user/updates_rss/145546633)) I get a successful toast:  "Success Your import has started. Check back later." but when I check the logs:

> 2023-09-18T12:31:33.277866Z  INFO ryot: Listening on [::]:8000
ryot    | thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("missing field `book_description`")', apps/backend/src/importer/goodreads.rs:64:62

Maybe I missed something, but the feed doesn't have a book_description.

**Comment by IgnisDa** [comment]
I haven't touched the goodreads integration for a long time so maybe it doesn't work anymore. Thanks for bringing it to my notice!

**Comment by vitormarcal** [comment]
Sorry. I just realized that the rrs feed I got is from the "My Profile" page and not the "My Books" page on Goodreads as the documentation describes. In “My Profile” the rss feed is in another format, but in “My Books” it works as expected.
Thank's for your time :)
