### ISSUE TITLE
Trakt import only marks S1-E1 as seen

### ISSUE THREAD

**Issue by SinTan1729** [IgnisDa/ryot#351]
While importing from Trakt, only S1-E1 of a series is marked as seen. There's no error in logs except for 5 errors for Movies, which are ```"missing field `id` at line 1 column 100", extensions: None```.

**Comment by IgnisDa** [comment]
Can you share your trakt username so that I can reproduce the errror?

**Comment by SinTan1729** [comment]
Sure. It's SinTan1729.

**Comment by IgnisDa** [comment]
It seems to be working fine for me.

**Comment by IgnisDa** [comment]
It did take the import about 10 minutes to finish. If you want more logging, you can set `RUST_LOG=debug` and try again once this new release is out.

**Comment by SinTan1729** [comment]
I'm still getting these. I'll try again once the new update is out. For the failed items, how do I figure out what those are?

**Comment by IgnisDa** [comment]
![image](https://github.com/IgnisDa/ryot/assets/60938164/15018770-514f-4e76-8f92-96b7d8e3dfb2)

The URL will be https://trakt.tv/<lot>/<identifier>

Eg:

For the first one: https://trakt.tv/movies/401887
Similarly the 2nd last (which is a show): https://trakt.tv/shows/197596

**Comment by IgnisDa** [comment]
Can you confirm once if these are in your history?

**Comment by IgnisDa** [comment]
Turns out there was a bug in the importing code, lol.

**Comment by SinTan1729** [comment]
I was able to add 4 of these. trakt.tv/movies/782072 cannot be added.

**Comment by IgnisDa** [comment]
Are you using the latest release? The action is still running.

**Comment by SinTan1729** [comment]
I'm in 2.17.5, I'll try out 2.17.6 once it's out.
