### ISSUE TITLE
Feature request: Customize upcoming section

### ISSUE THREAD

**Issue by SinTan1729** [IgnisDa/ryot#356]
It'll be nice if the upcoming section could be customized. I have a few suggestions, any one of which will be an improvement in my view:

- [ ] Add option to remove the upcoming section, since it can already be seen in the calendar page.
- [ ] ~Only show upcoming for items in a suitably named collection. It can also apply to the Calendar section.~
- [ ] Move the upcoming section below the In Progress section, since those are the shows that I mostly care about (probably true for most others as well).

In the current situation,the top of my frontpage in filled with dropped shows.

**Comment by IgnisDa** [comment]
I plan to implement a dashboard customization page where you can specify the order of sections (summary, upcoming, in progress etc) and the number of elemets that show up there. I will also add the option of removing a section completely.

This should satisfy 1, 3.

Implementing 2 would be a big task and I am not sure I want to undertake it. It will be won't fix for the time being and I will come back to it if I feel like it.

**Comment by SinTan1729** [comment]
That'll be great.
