### ISSUE TITLE
Performance Optimisations

### ISSUE THREAD

**Issue by tomcollis** [IgnisDa/ryot#361]
I've got two scenarios where I believe there are opportunities for improvements.

1) When opening a search result for the first time the delay on my docker install is 6 seconds, when I open it again it is under 1 seconds.
The second time is great, but the first time is too slow. I believe the issue might be downloading all the images related to the media item. Is it possible to either download the first image and then download the rest, alternatively. I would be happy to simply download the cover image and if I want more I can open the link to TMDB. I appreciate, not everyone may want this option so it may need to be a configurable option. It would be great to know your thoughts on this, I may be wrong in my assumptions of the download from TMDB.

2) When searching for TV and Movies, the search results are returned automatically.
This may cause additional TMDB API calls, and while this doesn't cause me any performance issues, I think that if it is performing too many API calls, it is not performant and potentially causing a larger load on TMDB's servers.

**Comment by IgnisDa** [comment]
1. This seems like a bug. Is the search query empty?
2. The query is debounced and also cached. I doubt it is causing any load since TMDb otherwise returns a `429 Retry later` error if you make too many queries

**Comment by tomcollis** [comment]
That was a quick turnaround, I'll update and try again later. Here is a video of 1.

https://clipchamp.com/watch/0lRaAgkl22Q

The delay I'm referring to is from 0:16 to 0:54, this is a particularly bad example because it seems to be worse if the program has lots of episodes. Many small series are only 6 seconds, but larger ones are worse.

**Comment by IgnisDa** [comment]
Ah yes, this is a different beast to tackle altogether. Right now ryot downloads all seasons data at once. I will have to see how to tackle it.

- [ ] Separate media specifics to a different query

**Comment by IgnisDa** [comment]
Released `v2.18.6`. LMK if this fixes the problem.

**Comment by IgnisDa** [comment]
> first time you open the show (and this can not really be fixed)

Actually this can be addressed by downloading the seasons data as a background job but this will blow up the complexity and I do not really want that right now, so it will stay this way for now.
