### ISSUE TITLE
Remove NSFW content from demo

### ISSUE THREAD

**Issue by Petemir** [IgnisDa/ryot#362]
Hello,

I think the title is self-explanatory :). Just opened the demo in a room full of people and it wasn't a nice sight to see some dubious content (e.g. I think it was in the "visual novels" category) in some of the categories.

Thanks!

**Comment by IgnisDa** [comment]
Hi!

Yeah, it's definitely a problem. I have the NSFW filter on for the demo instance, but most metadata providers don't label NSFW as such. And it is impossible for me to manually remove them.

I don't think there's anything to be done about this situation. Sorry for the embarrassment that might have been caused to you, though 😅.

**Comment by Petemir** [comment]
Ok, I guess I'll close this then :).
