### ISSUE TITLE
Incorrect image pulled for person

### ISSUE THREAD

**Issue by tomcollis** [IgnisDa/ryot#364]
When looking at the following example:

https://ryot.fly.dev/media/item?id=7287

The image under 'Acting' for 'Jill Scott' is the wrong 'Jill Scott', the related info when clicking on the 'Actor' is also related to the wrong 'Jill Scott'. When viewed on TMDB, the data and images are correct.

NOTE: I'm not concerned about this particular show, but it might highlight an issue with how the data is pulled in.

**Comment by IgnisDa** [comment]
I have been working on https://github.com/IgnisDa/ryot/pull/355 which should fix the problem. It will take some time to implement since it is turning out to be pretty complicated.

Thanks for bringing this to my notice.
