### ISSUE TITLE
[Suggestion] Use goodreads for books instead of openlibrary

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#369]
The issue with *openlibrary* is that it is a database for ISBNs rather than a single title.
I.e. "Siddhartha by Hermann Hesse" will likely have many editions/ISBNs to chose from.
Using *goodreads* a book is not a specific edition but all of them bundled up as "Siddhartha".
This has the advantages

- No need to know the exact edition you read, and you don't have to decide on an arbitrary one if yours is not included
- By clicking on a certain edition you did not read, you cannot infer if you read any other edition of that title
- It's consistent with how movies are handled (you also cannot track what exact Blu-ray or cut you watched)
- more clarity
- you seem to be already using the goodreads API for the Import-feature (though I don't even know whether the API supports looking up books)

That being said, it might be useful to be able to track what translation/language your read though.

**Comment by LnLcFlx** [comment]
Oh right they dropped API support some time ago.
This would still be a useful addition but I don't know of any other similar service

**Comment by IgnisDa** [comment]
Yep it's a big nitpick of mine too but openlibrary is the best we've got. I'll happily add support if a better free API comes along. Maybe Storygraph?

**Comment by LnLcFlx** [comment]
Storygraph would be great but it has no API either (yet).
