### ISSUE TITLE
Execution Error on Upgrade

### ISSUE THREAD

**Issue by tomcollis** [IgnisDa/ryot#380]
I've just upgraded my docker image from v2.18.5 to v2.19.7, unfortunately the app no longer runs, and these are the logs:

FYI I'm not reviewing/using people data, so I've not done any steps to migrate my ratings as per the release notes.

> 2023-09-30T19:39:47.955481Z  INFO ryot: Running version 2.19.7
> 2023-09-30T19:39:47.970789Z  INFO ryot: Using database backend: "SQLite"
> 2023-09-30T19:39:47.971706Z  INFO sea_orm_migration::migrator: Applying all pending migrations
> 2023-09-30T19:39:47.983865Z  INFO sea_orm_migration::migrator: Applying migration 'm20230927_change_faulty_index_person_table'
> Error: Execution Error: error returned from database: (code: 1) no such index: person-identifier-source__unique_index
> Caused by:
>     error returned from database: (code: 1) no such index: person-identifier-source__unique_index

**Comment by tomcollis** [comment]
Reverted to v2.19.0 by using docker image: ignisda/ryot:v2.19.0

App now loads, but getting the following log message:

> 2023-09-30T20:47:29.241203738Z thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "missing field `id` at line 1 column 100", extensions: None }', apps/backend/src/background.rs:154:18

**Comment by IgnisDa** [comment]
I strongly suggest you switch to postgres. Someone has already opened an issue for this and I am unable to fix it. https://github.com/IgnisDa/ryot/issues/370#issuecomment-1737494079
