### ISSUE TITLE
Support password-protected topics in Ntfy

### ISSUE THREAD

**Issue by thelazyoxymoron** [IgnisDa/ryot#381]
Self-hosted ntfy users typically add password protection to all topics. Currently, we cannot push notifications to protected topics.

This can be enabled by making Topic an optional variable, as ntfy allows you to push to protected topics via [access tokens in query params](https://docs.ntfy.sh/publish/#query-param).

**Comment by IgnisDa** [comment]
Reading the link you specified, shouldn't it be: Topic (required), Auth (optional)? 

Or am i missing something?

**Comment by thelazyoxymoron** [comment]
There are multiple ways to send request to a protected topic. 

The one I suggested might require the least amount of changes - as we can specify the auth token inside "server url" itself, using query param (This url would also contain the topic name, as in `https://ntfy.domain.com/topic?auth=auth_token`, hence no need to specify topic separately)

Of course, a more customizable approach would be to give a toggle for auth protected topics and then having another field for auth token itself.

**Comment by IgnisDa** [comment]
The easiest would be the `Bearer` auth since there is no base64 encoding involved.

I will just add a new optional field called auth token wherein you can set the header as specified in the first code sample [here](https://docs.ntfy.sh/publish/#access-tokens).
