### ISSUE TITLE
Sort by last seen

### ISSUE THREAD

**Issue by mtricht** [IgnisDa/ryot#39]
Hey, good job working on this. What I am missing what MediaTracker has is sorting by the last seen date of a movie, any chance this could be added?

**Comment by IgnisDa** [comment]
The query to do this would be
```rs
SELECT m.*
FROM metadata AS m
JOIN (
    SELECT metadata_id, MAX(last_updated_on) AS last_seen
    FROM seen
    GROUP BY metadata_id
) AS s ON m.id = s.metadata_id
ORDER BY s.last_seen DESC;
```

However, I can not really get this working in sea orm. Maybe someone can help? I have already created a PR with related changes.
