### ISSUE TITLE
Unable to run on latest release

### ISSUE THREAD

**Issue by tomcollis** [IgnisDa/ryot#404]
I'm using docker compose, and only get the following error logs:

> 2023-10-18T10:35:09.591657Z  INFO ryot: Running version: 2.24.0
> 2023-10-18T10:35:09.652675Z  INFO ryot: Using database backend: PostgreSQL
> 2023-10-18T10:35:09.654635Z  INFO sea_orm_migration::migrator: Applying all pending migrations
> 2023-10-18T10:35:09.671826Z  INFO sea_orm_migration::migrator: No pending migrations
> 2023-10-18T10:35:09.683491Z  INFO ryot: Instance does not have exercises data. Deploying job to download them.
> thread 'main' panicked at apps/backend/src/fitness/resolver.rs:295:14:
> called `Result::unwrap()` on an `Err` value: failed to lookup address information: Try again
> stack backtrace:
> 0:     0x7f9f7a5e5901 - <unknown>
> 1:     0x7f9f795ddd2c - <unknown>
> 2:     0x7f9f7a5e249e - <unknown>
> 3:     0x7f9f7a5e56e4 - <unknown>
> 4:     0x7f9f7a5ec5c3 - <unknown>
> 5:     0x7f9f7a5ec30f - <unknown>
> 6:     0x7f9f7a5ecab6 - <unknown>
> 7:     0x7f9f7a5ec9c4 - <unknown>
> 8:     0x7f9f7a5eb516 - <unknown>
> 9:     0x7f9f7a5ec752 - <unknown>
> 10:     0x7f9f7930c443 - <unknown>
> 11:     0x7f9f7930c82a - <unknown>
> 12:     0x7f9f79cf5340 - <unknown>
> 13:     0x7f9f79d1982b - <unknown>
> 14:     0x7f9f79cac1e2 - <unknown>
> 15:     0x7f9f7a339355 - <unknown>
> 16:     0x7f9f7a36eb78 - <unknown>
> 17:     0x7f9f7a080a67 - <unknown>
> 18:     0x7f9f7a5db6d2 - <unknown>
> 19:     0x7f9f7a339ab5 - <unknown>

I've moved from SQLite to Postgres, and I'm starting with a blank database. My docker compose file is:

> version: "3.9"
> 
> services:
>   ryot_db:
>     image: postgres:15-alpine
>     networks: 
>       - network1
>     restart: unless-stopped
>     volumes:
>       - data_ryot_db:/var/lib/postgresql/data
>     environment:
>       POSTGRES_PASSWORD: postgres
>       POSTGRES_USER: postgres
>       POSTGRES_DB: postgres
> 
>   ryot:
>     image: "ghcr.io/ignisda/ryot:latest" # v2.20.0
>     networks: 
>       - network1
>     restart: unless-stopped
>     environment:
>       - "DATABASE_URL=postgres://postgres:postgres@ryot_db:5432/postgres"
>       - "RUST_BACKTRACE=full"
>     labels:
>       - "traefik.enable=true"
>       - "traefik.http.routers.ryot.entrypoints=websecure"
>       - "traefik.http.routers.ryot.rule=Host(`ryot.example.com`)"
>       - "traefik.http.routers.ryot.tls=true"
>       - "traefik.http.services.ryot.loadbalancer.server.port=8000"
>     container_name: ryot
>     depends_on:
>     - ryot_db
> 
> volumes:
>   data_ryot_db:
> 
> networks:
>   network1:
>     name: private_network #bridge network used for Traefik
>     external: true

**Comment by IgnisDa** [comment]
Can you try without the labels?

**Comment by tomcollis** [comment]
This issue was caused by my primary container not having internal access. Obviously this is a problem, and RYOT will not function in the way.
