### ISSUE TITLE
Copy webhook Url

### ISSUE THREAD

**Issue by icetail** [IgnisDa/ryot#409]
when I create an integration for jellyfin a slug is created. according to the manual, the webhook URL must be copied with what I assume is the green button next to the delete button. however, this button does nothing. I run the installation in docker with the image ghcr.io/ignisda/ryot:latest I also tried v3.0.2. Makes no difference

**Comment by IgnisDa** [comment]
It just copies the URL to the clipboard. Is that not hapenning? In that case 

- what browser are you using?
- are there any errors in the console?

**Comment by icetail** [comment]
nothing is copied to the clipboard. I am using an edge browser Version 119.0.2151.12. nothing is visible in the console.
![image](https://github.com/IgnisDa/ryot/assets/2303224/458fcfec-e439-42cb-b15a-61b1289dfd9a)

**Comment by IgnisDa** [comment]
Can you check on anotherr browser too?

**Comment by icetail** [comment]
chrome Version 118.0.5993.89 same.... noting on the clipboard, Nothing is the console

**Comment by IgnisDa** [comment]
> noting on the clipboard

What do you mean?

**Comment by icetail** [comment]
nothing is being placed on the clipboard if i push the button

**Comment by IgnisDa** [comment]
How are you tesing if something is being placed on the clipboard?

**Comment by icetail** [comment]
paste it in a text editor

**Comment by icetail** [comment]
> Thats weird. I will look into it. Until then, you can manually construct the URL using this https://ignisda.github.io/ryot/integrations.html#jellyfin.

how. it says at jellyfin only Copy the newly generated webhook Url. but that button doesn't work

**Comment by IgnisDa** [comment]
Ah sorry. `https://ryot.fly.dev/webhooks/integrations/jellyfin/nBrzjdbd--kejdnH`.

Just replace the relevant bits with yours.

**Comment by IgnisDa** [comment]
I was not able to reproduce in any of the browsers you mentioned. You will probably have to construct URLs manually.

I did add a notification when URL gets copied successfully to the clipboard.

**Comment by makanimike** [comment]
fwiw, I experienced this as well.  
docker-compose installation, tried it both from Brave browser v1.59.120 Chromium 118.0.5993.88, and Chrome 118.0.5993.89 on Windows 10.

**Comment by IgnisDa** [comment]
> not directly related to the topic, but I am not sure it deserves its own, but is the documentation for the jellyfin webhook out of date? I cannot see Payload format, nor Pause or Resume. Play is called 'Playback Start' for me.

You have probably installed the wrong plugin. Follow the correct URL in the guide.

**Comment by makanimike** [comment]
oh man. of course it was something super dumb from my end ;)  
  
for other users that may run into this in the future:  
correct: webhooks (plural), unofficial, with the red/green/blue interlocking hooks in the logo
not correct: webhook (singular) with the white on black logo

**Comment by IgnisDa** [comment]
You could just screenshot the logos instead of going through the effort of describing them but thanks!

**Comment by fiveball02** [comment]
I'm having the same problem copying to the clipboard.  I've tried Chrome, Firefox, and Edge on Linux, Windows, and Android.  Can you provide the URL needed for Plex?

**Comment by tomdh76** [comment]
Just want to add that I also cannot copy the link with the green button (edge browser). I see a popup that url link is copied but when I paste in a text editor nothing is there. Or sometimes even more weird it pastes the password of the user login (I am using bitwarden)

**Comment by MikeBishop** [comment]
Same here. Could there please be a way to *display* the required URL in the UI?

FWIW, I'm using Brave on Android 13, accessing Ryot over cleartext. Is it possible only HTTPS sites can access the clipboard?

Also, why is this issue Closed if so many folks are seeing it?

**Comment by IgnisDa** [comment]
> Is it possible only HTTPS sites can access the clipboard?

Ahh that must be the issue. Thanks, I'll fix it.
