### ISSUE TITLE
Error After Upgrade to V3

### ISSUE THREAD

**Issue by SiskoUrso** [IgnisDa/ryot#411]
I followed the steps provided for upgraded from here: https://ignisda.github.io/ryot/migration.html#from-v2-to-v3

Was previously on V2. Once I completed the steps and pull the new version and run it ,no errors till I attempt to login to my account. The login page loads but after login nothing happens. 

Checking the logs I found this constant error: 

ryot-postgres-1  |
ryot-postgres-1  |
ryot-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
ryot-postgres-1  |
ryot-postgres-1  |
ryot             | 2023-10-19T23:57:41.263623Z  INFO ryot: Running version: 3.0.2
ryot-postgres-1  | 2023-10-19 23:57:41.374 UTC [1] LOG:  starting PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
ryot-postgres-1  | 2023-10-19 23:57:41.375 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
ryot-postgres-1  | 2023-10-19 23:57:41.375 UTC [1] LOG:  listening on IPv6 address "::", port 5432
ryot-postgres-1  | 2023-10-19 23:57:41.381 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ryot-postgres-1  | 2023-10-19 23:57:41.388 UTC [24] LOG:  database system was shut down at 2023-10-19 23:57:38 UTC
ryot-postgres-1  | 2023-10-19 23:57:41.399 UTC [1] LOG:  database system is ready to accept connections
ryot             | 2023-10-19T23:57:41.583377Z  INFO ryot: Using database backend: PostgreSQL
ryot             | 2023-10-19T23:57:41.587488Z  INFO sea_orm_migration::migrator: Applying all pending migrations
ryot             | 2023-10-19T23:57:41.595476Z  INFO sea_orm_migration::migrator: No pending migrations
ryot             | 2023-10-19T23:57:41.610534Z  INFO ryot: Using timezone: Etc/GMT
ryot             | 2023-10-19T23:57:41.635979Z  INFO ryot: Listening on: [::]:8000
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:305:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:292:10:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/miscellaneous/resolver.rs:4301:14:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/miscellaneous/resolver.rs:4301:14:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))
ryot             | thread 'tokio-runtime-worker' panicked at apps/backend/src/miscellaneous/resolver.rs:4301:14:
ryot             | called `Result::unwrap()` on an `Err` value: Query(SqlxError(ColumnDecode { index: "\"preferences\"", source: Error("missing field `num_genres_display`", line: 1, column: 1050) }))

Let me know what other information you need.

Thanks

**Comment by IgnisDa** [comment]
https://ignisda.github.io/ryot/migration.html#from-v2-to-v3

I am 95% sure you did not follow steps 1 and 2 here.

**Comment by IgnisDa** [comment]
I suggest you restore the database backup and start over again.
