### ISSUE TITLE
[Suggestion] Use `publish_date` to sort by "Release date" instead of `publish_year`

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#421]
I noticed if your sort by "Release date" some content released in the same year appear out of order.
I figured this must be because ryot is sorting by the `publish_year` field only rather than `publish_date` which would make sense according to the values in my database.

**Comment by IgnisDa** [comment]
I am not sure how feasible this is, since many metadatas do not have the publish date and only publish year associated with them.

**Comment by IgnisDa** [comment]
I changed the name of the filter to make it clearer. But the filter still uses release year.

**Comment by LnLcFlx** [comment]
> I am not sure how feasible this is, since many metadatas do not have the publish date and only publish year associated with them.

Would it be feasible to sort by date and just use the year as fallback when no date is specified?

Maybe all content with only `release_year` would just come after those of the same year which have an associated date. Or is that too sketchy?

**Comment by IgnisDa** [comment]
> Would it be feasible to sort by date and just use the year as fallback when no date is specified?

Can you try with the latest version? This is the behaviour now.

**Comment by LnLcFlx** [comment]
Yes it seems to sort according to `release_date`.
I was confused at first, since `release_date` did not match my local release date shown in TMDB.
