### ISSUE TITLE
[Suggestion] Support for local release dates

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#425]
Right now there is only one release date for each 'content' which is often the release date in the country a movie was produced in for example.
But it would be useful to see the release date in your own country or maybe both.

One could accomplish this with a setting where you can specify the locations ("Original, Country A, Country B") that you want considered when grabbing the release date and displaying them in the calendar.
In the calendar one could then append a (Original) or (Country A) behind a release date to indicate where it releases on that date.

**Comment by IgnisDa** [comment]
This is a reasonable request (though difficult to implement). What would you say the UI would look/behave like?

**Comment by IgnisDa** [comment]
I don't see any point to implementing this anymore.

**Comment by LnLcFlx** [comment]
> What would you say the UI would look/behave like?

Sorry for not answering, I read over that part.

> I don't see any point to implementing this anymore.

Why the change of mind?

**Comment by IgnisDa** [comment]
I personally wouldn't use this feature.

If am open to a PR for this, though.

**Comment by IgnisDa** [comment]
You probably won't need to know a lot of rust to do this. The code is pretty simple. The more challenging part will be integration with all the existing providers.
