### ISSUE TITLE
Release dates for Rick and Morty season 7, episode >1 missing although on TMDB

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#426]
The release dates for Rick and Morty season 7 episode >1 are missing in the calendar, although they are specified on TMDB and the release date for season 7, episode 1 is present.
This might be a problem for other shows but the ones I checked work as intended.

**Comment by IgnisDa** [comment]
Yeah this happens sometimes. I think the api does not return the correct data, though the UI displays it. Happened to me with Loki too. Don't think there's anything I can do to fix it.

**Comment by LnLcFlx** [comment]
Thats unfortunate but thanks

**Comment by IgnisDa** [comment]
Do LMK if you find other media behaving like this. I'll try to investigate.

**Comment by LnLcFlx** [comment]
Fyi this is no longer an issue. Also many new releases appeared in my calendar that weren't there before. Noticed it in v3.2.2

**Comment by IgnisDa** [comment]
Yeah there was a bug that prevented new calendar entries from being created.
