### ISSUE TITLE
Bug: Update Progress action does not list next unwatched episode

### ISSUE THREAD

**Issue by thespad** [IgnisDa/ryot#429]
The Update Progress action always seems to show S1E1 regardless of the Seen progress:
![image](https://github.com/IgnisDa/ryot/assets/8425502/37c6c3de-7d16-41ce-a57d-b67a4baae884)
![image](https://github.com/IgnisDa/ryot/assets/8425502/8bd7f3e8-410e-48d0-9c16-a15576f37f8c)

If the show hs Specials listed and they are marked as Seen then the Update Progress action always seems to show the last special instead:
![image](https://github.com/IgnisDa/ryot/assets/8425502/b8abf407-94d7-4b21-9e05-71592c933281) 
![image](https://github.com/IgnisDa/ryot/assets/8425502/1f563635-b665-4b09-a8b8-9e380c535bfd)

v3.0.13 w/postgresql in Docker.

**Comment by IgnisDa** [comment]
Can you provide an export of your database as described in https://ignisda.github.io/ryot/guides/exporting.html so that I can reproduce this?

**Comment by thespad** [comment]
Will do, if it helps everything (so far) was imported from a Mediatracker instance rather than added new.

**Comment by IgnisDa** [comment]
Can you attach a screenshot of the entire seasons tab for the above?

**Comment by thespad** [comment]
A bit fiddly because of the max size of the seasons box but...

![image](https://github.com/IgnisDa/ryot/assets/8425502/c1def509-955e-4832-b6eb-39835bbbd7fc)

![image](https://github.com/IgnisDa/ryot/assets/8425502/7c9e3156-3b8a-4712-bf2f-aa344d534ec1)

![image](https://github.com/IgnisDa/ryot/assets/8425502/ad2c3a63-7e27-4821-8a86-92d8e2dd9386)

**Comment by IgnisDa** [comment]
Can you show the history tab? Just the top few entries would suffice.

**Comment by thespad** [comment]
Everything up to S2E3 was marked seen prior to the import from Mediatracker, which I assume is why the history is "backwards" for them.

![image](https://github.com/IgnisDa/ryot/assets/8425502/d55c8684-b262-474b-9ef2-9ad688e72a2c)

![image](https://github.com/IgnisDa/ryot/assets/8425502/05588fb1-e1c1-49ff-a692-7e5c07323d55)

**Comment by IgnisDa** [comment]
Can you also make a media type export of your current database and send that?

**Comment by thespad** [comment]
[ryot.json](https://github.com/IgnisDa/ryot/files/13113134/ryot.json)

**Comment by thespad** [comment]
Oh, it's suddenly dawned on me, it's looking at the last marked watched episode and using that as the next Mark Seen in the action menu.

The reason it's S1E1 for all the imported shows is that the import puts the history in "backwards" so S1E1 is always the most recent item in the history. When you mark a new episode as watched that goes into the top of the history, so that then becomes the next Mark Seen.

**Comment by IgnisDa** [comment]
Ah, so import is the problem? I do not think it is that big a problem (i.e, not importing elements in the right order), so I won't fix that.

But yeah even after manually marking an episode as seen, it does not pick up the correct "next episode". That needs to be fixed.

**Comment by IgnisDa** [comment]
I have been able to reproduce it, so I will fix it.

**Comment by IgnisDa** [comment]
Will be fixed in `v3.2.2`.
