### ISSUE TITLE
Feature Request: Add Filter/Sort to Collections

### ISSUE THREAD

**Issue by thespad** [IgnisDa/ryot#430]
Right now Collections are one big mess of all media types with no way to filter or sort them; being able to filter at least by media type, as well as sort by the same criteria as other media pages would be very helpful.

**Comment by thespad** [comment]
I was just thinking something very simple like transplanting the existing Filter button into each collection, e.g.

![image](https://github.com/IgnisDa/ryot/assets/8425502/383bf83d-4d4c-4b02-a3bc-5b5374de3d5f)

**Comment by IgnisDa** [comment]
Hmm makes sense. What kind of filters would you think will be needed here

**Comment by thespad** [comment]
So this is just my personal take, but I don't think you need filters like Seen/On Hold/In Progress, etc. because the default collections are specifically for things like Watchlist and In Progress so they already filter themselves in that way and custom collections will likely filter for whatever the user wants, but you probably want filters for media type (Shows/Movies/Audiobook/Games), and perhaps Rated/Unrated and Explicitly Monitored. 

As for Sorts, probably just like the existing media groups (Name, last seen/updated, release date, etc.).

In looking through this I did notice (which I'd missed before) that you can also filter by Collection under the Media but it doesn't seem to work properly - it says there are results but doesn't show them unless you go and click on one of the page numbers.

![image](https://github.com/IgnisDa/ryot/assets/8425502/045b95c8-36e1-47b8-ad8d-18233a8e095c)

**Comment by IgnisDa** [comment]
> but doesn't show them unless you go and click on one of the page numbers.

This is a long standing bug that I haven't been able to fix (I'm not very good with react). 

Refreshing the page will make the collections filter visible.

**Comment by IgnisDa** [comment]
- General filters: All (default), Explicitly monitored, Rated
- Sort: Last updated (default), Title, Release Date
