### ISSUE TITLE
Bug: Plex integration not marking episodes as seen

### ISSUE THREAD

**Issue by thespad** [IgnisDa/ryot#431]
Plex webhook correctly filters non-matching users but then generates an error when trying to update the status:
```
ryot  | 2023-10-23T19:57:47.519617Z ERROR ryot::routes: Error { message: "Error during JSON payload deserialization missing field `duration` at line 1 column 1631", extensions: None }
ryot  | 2023-10-23T19:58:38.976464Z ERROR ryot::routes: Error { message: "Error during JSON payload deserialization missing field `duration` at line 1 column 1632", extensions: None }
ryot  | 2023-10-23T20:08:42.059583Z ERROR ryot::routes: Error { message: "Error during JSON payload deserialization missing field `duration` at line 1 column 1628", extensions: None }
ryot  | 2023-10-23T20:10:25.638924Z ERROR ryot::routes: Error { message: "Error during JSON payload deserialization missing field `duration` at line 1 column 1624", extensions: None }
```
I'm also seeing occasional
```
ryot  | 2023-10-23T19:51:10.360904Z ERROR ryot::routes: Error { message: "No position associated with this media", extensions: None }
```
messages, but I'm not sure if they're related and my Rust isn't good enough to figure it out from reading the source.

v3.0.13 w/postgresql in Docker.
Plex Version 1.32.7.7571

**Comment by IgnisDa** [comment]
Is this a show?

**Comment by thespad** [comment]
Yes, the shows in question are already present in Ryot (for the first set of errors at least, I can't corrolate the `No position` message with a specific watched episode so I can't say for sure either way).

**Comment by IgnisDa** [comment]
As long as they're in the database, it should work.

Can you send me the webhook payload? Maybe use https://webhooks.site?

**Comment by thespad** [comment]
I've not tried a movie yet. It's happened with the first 2 shows I've tried with the webhook configured.

Payload is
```json
{"event":"media.scrobble","user":true,"owner":true,"Account":{"id":xxxxxx,"thumb":"https://plex.tv/users/42311xxxxxxxx779/avatar?c=169xxxxx06","title":"xxxx"},"Server":{"title":"Plex","uuid":"4c67d7cxxxxxxxxxxxxxxxxxxxxxxxx5dde0a5f"},"Player":{"local":true,"publicAddress":"xx.xxx.xx.xx","title":"XXXXXX","uuid":"ruongxxxxxxxxxxxxxxxxxxrvl9rl"},"Metadata":{"librarySectionType":"show","ratingKey":"459345","key":"/library/metadata/459345","parentRatingKey":"459137","grandparentRatingKey":"38994","guid":"plex://episode/64f195a54927cb535e9b875c","parentGuid":"plex://season/64e795945a05acd2e5697516","grandparentGuid":"plex://show/5d9c08382192ba001f30a9c7","type":"episode","title":"The Jerrick Trap","titleSort":"Jerrick Trap","grandparentKey":"/library/metadata/38994","parentKey":"/library/metadata/459137","librarySectionTitle":"TV Shows","librarySectionID":6,"librarySectionKey":"/library/sections/6","grandparentTitle":"Rick and Morty","parentTitle":"Season 7","contentRating":"gb/15","summary":"Gotta be mindful, broh. Big brain stuff here.","index":2,"parentIndex":7,"viewCount":2,"lastViewedAt":1698137141,"year":2023,"thumb":"/library/metadata/459345/thumb/1698115832","art":"/library/metadata/38994/art/1698116954","parentThumb":"/library/metadata/459137/thumb/1697853876","grandparentThumb":"/library/metadata/38994/thumb/1698116954","grandparentArt":"/library/metadata/38994/art/1698116954","grandparentTheme":"/library/metadata/38994/theme/1698116954","duration":1380000,"originallyAvailableAt":"2023-10-22","addedAt":1698031934,"updatedAt":1698115832,"chapterSource":"media","Guid":[{"id":"imdb://tt28252882"},{"id":"tmdb://4694201"},{"id":"tvdb://9986630"}]}}
```
PII redacted with X's

**Comment by IgnisDa** [comment]
Can you set `RUST_LOG=ryot=trace` env variable and try shows again?

ALso please try the movies integration so that I can check if that works.

**Comment by IgnisDa** [comment]
@psyko-gh Does the Ryot show integration still work for you? The payload that @thespad attached does not match what you had initially coded. Maybe the payload has changed since then?

**Comment by thespad** [comment]
So in the process of enabling trace logging I accidentally pulled the latest version (3.2.1) and it now seems to be working correctly. I can't see any obvious changes between 3.0.13 and 3.2.1 that would cover it though.

Problem is I can't roll back to 3.0.13 to do more tests because the database migrations have been applied and I don't have a backup of the DB from yesterday.

**Comment by thespad** [comment]
Fully tracking progress as well as watched state too

![image](https://github.com/IgnisDa/ryot/assets/8425502/cc1f2c9b-9238-41c7-bed6-758d5be8827c)

**Comment by IgnisDa** [comment]
Ha, great! I don't have a Plex premium anyway, so it'd have been difficult for me to debug (@psyko-gh wrote the entire plex integration initially).

**Comment by thespad** [comment]
> Ha, great! I don't have a Plex premium anyway, so it'd have been difficult for me to debug (@psyko-gh wrote the entire plex integration initially).

@IgnisDa OK I just had this happen again and I've figured out the cause.

If the metadata for a new episode hasn't updated and so Ryot doesn't have a Duration for it yet then when Plex sends the webhook to mark it as watched it's causing it to throw the
```
ryot  | 2023-10-30T20:54:35.190887Z ERROR ryot::routes: Error { message: "Error during JSON payload deserialization missing field `duration` at line 1 column 2626", extensions: None }
```
Errors.

The most recent occurrance was mapped to episode 15 here
![image](https://github.com/IgnisDa/ryot/assets/8425502/78b66a1d-583a-446c-9e36-8543da9a1c7d)

**Comment by IgnisDa** [comment]
Great. Thanks for letting me know.

**Comment by thespad** [comment]
I imagine it'll end up being a fairly common issue if people are watching things when they're released because there probably won't be a duration in the ryot DB yet, especially for shows on streaming services where the episode information isn't usually made public until airtime.

**Comment by thespad** [comment]
Is it possible to reopen this as it's still an issue.

**Comment by IgnisDa** [comment]
What's the issue?

**Comment by thespad** [comment]
If an episode doesn't have a Duration in Ryot (for example it's a brand new episode that Ryot hasn't been able to pull full metadata for yet because it only just aired) then the Plex webhook for the episode being played will fail to be processed with:
```
ryot  | 2023-11-15T16:56:08.560119Z ERROR ryot::routes: Error { message: "Error during JSON payload deserialization missing field `duration` at line 1 column 1760", extensions: None }
```
And this manifests as episodes not being marked as played. I would imagine the simplest fix would be to either always have a duration (of say 0) for every episode until it can update with the real one, or to handle a missing duration when trying to process the Plex webhook so that it doesn't fail.

**Comment by IgnisDa** [comment]
> or to handle a missing duration when trying to process the Plex webhook

What should Ryot assume that missing duration to be?

**Comment by thespad** [comment]
Well, that's a good question, I don't have a good answer. But it's going to be common that new episodes don't have durations yet and some niche content doesn't have a duration at all (think web specials and other content that might not get a full set of metadata), so it probably needs *something*.

Maybe just store it as `-1` and render as `Unknown` in the UI?

**Comment by IgnisDa** [comment]
I will look into it.

**Comment by RealFascinated** [comment]
any updates on this?
