### ISSUE TITLE
Cannot add new shows

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#441]
I am trying to add a new show, and I am getting this error only visible in the browser console.

I tried different ones, and it seems like right now I cannot add new shows. I was in version 3.0.6, and I updated to 3.2.4, but still the same error. I didn't have time yet, to try to search in the database and see what happened there.

```
Uncaught (in promise) Error: Query Error: error returned from database: duplicate key value violates unique constraint "metadata_pkey": {"response":{"data":null,"errors":[{"message":"Query Error: error returned from database: duplicate key value violates unique constraint \"metadata_pkey\"","locations":[{"line":2,"column":3}],"path":["commitMedia"]}],"status":200,"headers":{"map":{"access-control-allow-credentials":"true","content-length":"205","content-type":"application/json","date":"Wed, 25 Oct 2023 14:34:25 GMT","server":"openresty","vary":"origin, access-control-request-method, access-control-request-headers","x-served-by":"ryot.izlo.es"}}},"request":{"query":"mutation CommitMedia($lot: MetadataLot!, $source: MetadataSource!, $identifier: String!) {\n  commitMedia(lot: $lot, source: $source, identifier: $identifier) {\n    id\n  }\n}","variables":{"identifier":"207311","lot":"SHOW","source":"TMDB"}}}
    at makeRequest (_app-c64e0fb50b9f44a7.js:13:30101)
    at async Object.mutationFn (4437-ac9cbdac475f02eb.js:1:1061)
```

**Comment by IgnisDa** [comment]
Is this happening for everything? Can you try doing with movies and see if they can be added to database?

**Comment by SirMartin** [comment]
Yes, same for movies.

The latest show that could be added was yesterday and it was automatically from the jellyfin webhook.

I don't use ryot for movies, so it was completely clean, I tried and this is the error from the graphql.

` {"query":"mutation CommitMedia($lot: MetadataLot!, $source: MetadataSource!, $identifier: String!) {\n  commitMedia(lot: $lot, source: $source, identifier: $identifier) {\n    id\n  }\n}","variables":{"identifier":"425","lot":"MOVIE","source":"TMDB"},"operationName":"CommitMedia"}`

**Comment by IgnisDa** [comment]
This is all very weird. Could you make a video recording of adding a show and movie?

**Comment by SirMartin** [comment]
Yes, it is kind of weird.

Here you have a small video with all the 3 options and the fails.

https://github.com/IgnisDa/ryot/assets/854646/7040795f-4b69-43b1-a9c3-e77c69f2191b

**Comment by IgnisDa** [comment]
I think the sequence generator in your db somehow went out of sync. Can you email a dump of your database? You can find my ID in my GH profile.

**Comment by SirMartin** [comment]
Done

**Comment by IgnisDa** [comment]
Yep it was the problem of a faulty sequence. Connect to your DB and run this: `SELECT setval('metadata_id_seq', 280);`

**Comment by IgnisDa** [comment]
Not sure why the sequence got corrupted in the first place since Ryot does not touch them at all. Feel free to chime back here if you get other problems. Closing for now.

**Comment by SirMartin** [comment]
Ok, I ran that and it works, I could added it. I added the movie, and appears, not issue at all, but I added the show which I had some issues yesterday, and I can added, I can see it in the DB, also I can see in the DB that is correctly assigned to the "In Progress" collection, but I cannot mark as watched, and it does not appear in the shows lists, or in the in progress list.

It's pretty weird, but there is something not working properly.

**Comment by IgnisDa** [comment]
Try:
```
select max(id) from seen;
SELECT setval('seen_id_seq', <the above output> + 1);
```

Did you tamper with the database manually at some point?

**Comment by SirMartin** [comment]
Nothing apart that the scripts from the migration to version 3, that's true that I had some issues and restored the database sometimes during that migration. I would try to reset all the sequences as you said, and I will comment it here.

**Comment by SirMartin** [comment]
I made for all the sequencies, but still same issue, cannot mark as seen, is not visible, etc. Is anyway to delete a show/movie, without playing in the database? Probably should try to export all my data, and just create a new instance from zero.

**Comment by IgnisDa** [comment]
if you know the id of the show/movie, you can do `delete from metadata where id = <here>;`. Just make a backup of your DB before you do anything destructive.

**Comment by SirMartin** [comment]
Ok, after removing it by hand, and adding again, I could mark as watch the episodes. Let's see, but probably I would check to make an export and import in a free new instance.
