### ISSUE TITLE
Running / walking exercises are not showing correctly at the workout details

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#442]
Running / walking exercises are not showing correctly at the workout details.
Additionally, it's more common to represent the pace as min/km, not the opposite.
It should be cool if it calculate also the average speed in km/h.

![image](https://github.com/IgnisDa/ryot/assets/64137913/77f967d4-7e77-4a45-a0db-47d21ab98dac)

**Comment by IgnisDa** [comment]
What version are you using? The calculations seem to be correct for me.

**Comment by edersong** [comment]
It's not an import.
I put those values manually yesterday after a workout.
I'm running 3.2.4 version.
![1000049994](https://github.com/IgnisDa/ryot/assets/64137913/245dd6f4-589f-4f1e-9929-db32fe5977a1)

**Comment by IgnisDa** [comment]
I added the same workout to the demo instance with the same values and it seems fine: https://ryot.fly.dev/fitness/exercises/workouts/details?id=484473060980711746.

**Comment by edersong** [comment]
So, it seems to be due locale settings.
I'm from Spain and the locale settings are different.

**Comment by IgnisDa** [comment]
What's locale settings got to do anything with this?

**Comment by edersong** [comment]
Confirmed on demo that it's a locale settings
![image](https://github.com/IgnisDa/ryot/assets/64137913/794ddef6-45d6-47ce-be46-5e6e1aae0b01)

Locale settings are settings where your computer (or mobile) is configured to show settings based on your country, for example, here in Spain the decimal separators are , "comma" not . "dot"

**Comment by IgnisDa** [comment]
I am not aware of anything like this. The Ryot code does not take locale into account for calculations so I can't understand.

**Comment by IgnisDa** [comment]
Hey @edersong, this was an actual big in the frontend which i discovered today. Really sorry for not taking it seriously. It'll be fixed today.
