### ISSUE TITLE
[Suggestion] Exclude content from being shown in calendar

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#447]
I have started a show but dropped it.
I don't want to continue it but I still see the release dates of new episodes in the calendar.
Is there a way to prevent this?

I thought "Stop/Start monitoring" would do this but it doesn't.
What exactly is this button for and could you add an option to exclude content from being shown in calendar?

**Comment by IgnisDa** [comment]
Those buttons will basically update the media item everyday and send you notifications (can be configured in settings) in case there are changes (for eg, new episode released, release date changed).

**Comment by IgnisDa** [comment]
Maybe I should add a tooltip to the actions to make these things clearer.

**Comment by LnLcFlx** [comment]
Thank you.
But the actual issue of not being able to exclude content from calendar remains unfixed.
Did you close this because you don't think it's useful?

**Comment by IgnisDa** [comment]
I personally don't encounter this as a problem so I don't have much use for implementing it.

What exactly do you need? Maybe if it is a small feature, I will implement it.

**Comment by LnLcFlx** [comment]
Basically just a toggle to avoid a show i.e. from showing up in the calendar.

My issue right now is, that my entire calendar is filled with release dates of new episodes of shows that I barely even watched and don't wish to continue.

**Comment by IgnisDa** [comment]
I don't think adding a new button is a good idea. I'm thinking maybe I should create a new default collection. I'll see.

**Comment by IgnisDa** [comment]
@LnLcFlx Will it work if only media that are in InProgress and Watchlist show up there?

**Comment by LnLcFlx** [comment]
I don't think this would be very elegant.
I can imagine realistic scenarios where I want to see release dates of a show that is not on my watchlist or not in progress.
For example a shows that I completed but now receives a new season would neither be in my watchlist (I already watched it) nor in progress (I finished it).

I think a better solution would be to revamp the "monitor" button and change its purpose for this sake such that only release dates of monitored content is shown.

**Comment by IgnisDa** [comment]
> I think a better solution would be to revamp the "monitor" button and change its purpose for this sake such that only release dates of monitored content is show

Good idea. Do you have any particular UI in mind?

**Comment by LnLcFlx** [comment]
I did not have a UI change in mind. I just thought to keep the existing Start/Stop monitoring button and simply add the behavioure that only content that is being monitored is shown in the calendar.
Does this make sense?

**Comment by IgnisDa** [comment]
Yeah it does. Right now all media that are in the watchlist and in progress are shown there. Should I remove those criteria?

**Comment by LnLcFlx** [comment]
Yes I think that would allow for better control :)
