### ISSUE TITLE
Audiobookshelf Integration

### ISSUE THREAD

**Issue by HStep20** [IgnisDa/ryot#45]
[Audiobookshelf](https://github.com/advplyr/audiobookshelf) (a popular selfhosted Audiobook + Podcast server) is likely the main application people within the community using this app would be using as well. It would be amazing if ryot could read Audiobook and Podcast data from the ABS API, and track data based on that.

The API offers an endpoint for [getting media items in progress](https://api.audiobookshelf.org/#get-library-items-in-progress) by library, so you should be able to read both Podcast status and Audiobook status from the one endpoint in order to scrobble that data from ABS to Ryot.

While I personally don't use its 'Ebook' features, it does also support synced reading of ebooks across its browser and mobile apps, so you could get 3 potential media item type locations from the one application alone

**Comment by IgnisDa** [comment]
Thank you. I plan to add various integrations to Ryot and will keep this in mind!

**Comment by IgnisDa** [comment]
Blocked by https://github.com/advplyr/audiobookshelf/issues/1857

**Comment by IgnisDa** [comment]
@HStep20 Working on this. I need your opinion. The Ryot Kodi plugin works by tracking progress of media only if they have more than 2% of progress and marks it as completed when it gets above 90%. Do you think the same would work for ABS?

**Comment by IgnisDa** [comment]
Looking at the ABS API, I do not think it would be possible to detect whether a media item was ever finished, since the endpoint you linked to does not return items once they are finished. Please correct me if I am wrong.
