### ISSUE TITLE
Typos in Create Exercise and Create Media

### ISSUE THREAD

**Issue by makanimike** [IgnisDa/ryot#457]
In Create Exercise the Field "Muscles" is mistyped as "Mucles".  
  
<img width="813" alt="Capture" src="https://github.com/IgnisDa/ryot/assets/88232673/07313e74-6220-4f3b-9793-b39bdad77045">

There is another typo in "Create Media". The code taggeed "Specifics" is mistyped as "Specfics".
<img width="850" alt="Capture1" src="https://github.com/IgnisDa/ryot/assets/88232673/58a1b54d-50bd-468e-8005-7dbb3c65890e">

**Comment by IgnisDa** [comment]
Thnaks! Would be great if you open a PR fixing this.

**Comment by Asymtode712** [comment]
I want to fix this. Please assign me

**Comment by IgnisDa** [comment]
@Asymtode712 I recommend you run https://cspell.org/ on the codebase and fix all spelling errors. I am sure I have made many more.

**Comment by Asymtode712** [comment]
@IgnisDa Please review my PR
