### ISSUE TITLE
Exercises are not being listed

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#462]
Exercises are not being listed after the last version upgrade even all filters are cleared.
Additionally, tried to create a new exercise and it is not progressing when I click on save button.
Current version is 3.3.7

**Comment by IgnisDa** [comment]
Any relevant logs? Exercises are downloaded automatically on startup.

**Comment by IgnisDa** [comment]
This might also be related to the changes in https://github.com/IgnisDa/ryot/releases/tag/v3.3.0. Please read the important notes there.

**Comment by edersong** [comment]
> This might also be related to the changes in https://github.com/IgnisDa/ryot/releases/tag/v3.3.0. Please read the "Important" section there.

Worked, thanks! ;-)
