### ISSUE TITLE
[Bug] error in sqlite migration

### ISSUE THREAD

**Issue by jbonadiman** [IgnisDa/ryot#465]
I'm not sure if this is a bug but here are the steps for reproduction:
- I set out to have a new installation of ryot, using sqlite.
- I used these commands to get the volume working:
  - mkdir /ryot
  - sudo touch /ryot/ryot.sqlite (I had to `touch` the database file, because ryot was not creating it in the first run)
  - sudo chown -R 1001:1001 /ryot
- I mapped /ryot to /data

And these are the logs I got:

> 
> 2023-11-03T11:03:35.683135Z  INFO ryot: Running version: 3.4.0
> 2023-11-03T11:03:35.701470Z  INFO ryot: Using database backend: SQLite
> 2023-11-03T11:03:35.705439Z  INFO sea_orm_migration::migrator: Applying all pending migrations
> 2023-11-03T11:03:35.707085Z  INFO sea_orm_migration::migrator: Applying migration 'm20230410_create_metadata'
> 2023-11-03T11:03:35.714393Z  INFO sea_orm_migration::migrator: Migration 'm20230410_create_metadata' has been applied
> 2023-11-03T11:03:35.716098Z  INFO sea_orm_migration::migrator: Applying migration 'm20230413_create_person'
> 2023-11-03T11:03:35.722917Z  INFO sea_orm_migration::migrator: Migration 'm20230413_create_person' has been applied
> 2023-11-03T11:03:35.731513Z  INFO sea_orm_migration::migrator: Applying migration 'm20230417_create_user'
> 2023-11-03T11:03:35.736909Z  INFO sea_orm_migration::migrator: Migration 'm20230417_create_user' has been applied
> 2023-11-03T11:03:35.739461Z  INFO sea_orm_migration::migrator: Applying migration 'm20230419_create_seen'
> 2023-11-03T11:03:35.741906Z  INFO sea_orm_migration::migrator: Migration 'm20230419_create_seen' has been applied
> 2023-11-03T11:03:35.744505Z  INFO sea_orm_migration::migrator: Applying migration 'm20230502_create_genre'
> 2023-11-03T11:03:35.751975Z  INFO sea_orm_migration::migrator: Migration 'm20230502_create_genre' has been applied
> 2023-11-03T11:03:35.754413Z  INFO sea_orm_migration::migrator: Applying migration 'm20230901_create_metadata_group'
> 2023-11-03T11:03:35.759121Z  INFO sea_orm_migration::migrator: Migration 'm20230901_create_metadata_group' has been applied
> 2023-11-03T11:03:35.760934Z  INFO sea_orm_migration::migrator: Applying migration 'm20230507_create_collection'
> 2023-11-03T11:03:35.768692Z  INFO sea_orm_migration::migrator: Migration 'm20230507_create_collection' has been applied
> 2023-11-03T11:03:35.770926Z  INFO sea_orm_migration::migrator: Applying migration 'm20230505_create_review'
> 2023-11-03T11:03:35.774224Z  INFO sea_orm_migration::migrator: Migration 'm20230505_create_review' has been applied
> 2023-11-03T11:03:35.776285Z  INFO sea_orm_migration::migrator: Applying migration 'm20230509_create_import_report'
> 2023-11-03T11:03:35.779880Z  INFO sea_orm_migration::migrator: Migration 'm20230509_create_import_report' has been applied
> 2023-11-03T11:03:35.782291Z  INFO sea_orm_migration::migrator: Applying migration 'm20230622_create_exercise'
> 2023-11-03T11:03:35.784630Z  INFO sea_orm_migration::migrator: Migration 'm20230622_create_exercise' has been applied
> 2023-11-03T11:03:35.786763Z  INFO sea_orm_migration::migrator: Applying migration 'm20230804_create_user_measurement'
> 2023-11-03T11:03:35.789031Z  INFO sea_orm_migration::migrator: Migration 'm20230804_create_user_measurement' has been applied
> 2023-11-03T11:03:35.791056Z  INFO sea_orm_migration::migrator: Applying migration 'm20230819_create_workout'
> 2023-11-03T11:03:35.793693Z  INFO sea_orm_migration::migrator: Migration 'm20230819_create_workout' has been applied
> 2023-11-03T11:03:35.795740Z  INFO sea_orm_migration::migrator: Applying migration 'm20230901_create_partial_metadata'
> 2023-11-03T11:03:35.804963Z  INFO sea_orm_migration::migrator: Migration 'm20230901_create_partial_metadata' has been applied
> 2023-11-03T11:03:35.807220Z  INFO sea_orm_migration::migrator: Applying migration 'm20230912_create_calendar_event'
> 2023-11-03T11:03:35.812034Z  INFO sea_orm_migration::migrator: Migration 'm20230912_create_calendar_event' has been applied
> 2023-11-03T11:03:35.814758Z  INFO sea_orm_migration::migrator: Applying migration 'm20231003_create_partial_metadata_to_person'
> 2023-11-03T11:03:35.817598Z  INFO sea_orm_migration::migrator: Migration 'm20231003_create_partial_metadata_to_person' has been applied
> 2023-11-03T11:03:35.820539Z  INFO sea_orm_migration::migrator: Applying migration 'm20231016_create_collection_to_entity'
> 2023-11-03T11:03:35.848958Z  INFO sea_orm_migration::migrator: Migration 'm20231016_create_collection_to_entity' has been applied
> 2023-11-03T11:03:35.852140Z  INFO sea_orm_migration::migrator: Applying migration 'm20231017_create_user_to_entity'
> 2023-11-03T11:03:35.883975Z  INFO sea_orm_migration::migrator: Migration 'm20231017_create_user_to_entity' has been applied
> 2023-11-03T11:03:35.887117Z  INFO sea_orm_migration::migrator: Applying migration 'm20231024_add_metadata_group_id_field_to_review'
> 2023-11-03T11:03:35.887961Z  INFO sea_orm_migration::migrator: Migration 'm20231024_add_metadata_group_id_field_to_review' has been applied
> 2023-11-03T11:03:35.891704Z  INFO sea_orm_migration::migrator: Applying migration 'm20231025_add_collection_id_field_to_review'
> 2023-11-03T11:03:35.892508Z  INFO sea_orm_migration::migrator: Migration 'm20231025_add_collection_id_field_to_review' has been applied
> 2023-11-03T11:03:35.895944Z  INFO sea_orm_migration::migrator: Applying migration 'm20231025_remove_duplicate_calendar_events'
> 
> Found 0 duplicate calendar events. Removing them...
> thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-query-0.30.2/src/backend/sqlite/table.rs:135:17:
> Sqlite not support modifying table column
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by IgnisDa** [comment]
Hey. Please use postgres.
