### ISSUE TITLE
Bug: Some audio books cause a panic

### ISSUE THREAD

**Issue by philw07** [IgnisDa/ryot#466]
Some audio books cause a panic when trying to view them or mark as played.
An example is So Long and Thanks for All the Fish by Douglas Adams (both of them).

![image](https://github.com/IgnisDa/ryot/assets/42705066/180548ad-bb8f-4eff-b31d-9de18679048a)

See here on demo instance: https://ryot.fly.dev/media/item/commit?identifier=B00AAZEQK0&lot=AUDIO_BOOK&source=AUDIBLE

Log from docker container:
```
2023-11-04 19:11:08 thread 'tokio-runtime-worker' panicked at apps/backend/src/providers/audible.rs:308:47:
2023-11-04 19:11:08 called `Option::unwrap()` on a `None` value
```

Referenced line:
https://github.com/IgnisDa/ryot/blob/175849b0c2b13c86bac8f9c9e12ad246df3dcb11/apps/backend/src/providers/audible.rs#L308

Seems `sim.product_images` is `None` here which is not handled.

**Comment by IgnisDa** [comment]
Thanks for reporting this. I'll fix it.
