### ISSUE TITLE
deleted database to start fresh, now white screen

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#472]
i deleted my ryot database to start fresh imports but now all i get is a white screen.

**Comment by IgnisDa** [comment]
I need more information than that. Can you show the logs?

**Comment by reitenth** [comment]
![image](https://github.com/IgnisDa/ryot/assets/94771708/87f72975-ea8a-4313-9861-a694a91d6581)
![image](https://github.com/IgnisDa/ryot/assets/94771708/6a3b0d64-df7d-4d7a-803d-9fec1ddb89a1)
logs dont show anything

**Comment by reitenth** [comment]
its just a white or black screen when i load webui. 
![image](https://github.com/IgnisDa/ryot/assets/94771708/e5c8e0af-f750-4838-a628-f16d805d590f)

**Comment by reitenth** [comment]
thank you that worked!
