### ISSUE TITLE
[Feature Request] Manga/anime english name

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#475]
could we get an option to have english name? 
![image](https://github.com/IgnisDa/ryot/assets/94771708/98d07e05-346a-44f0-ab5f-cc57ad2dd3f3)

(also the plural of anime is anime not animes, just a heads up)

**Comment by IgnisDa** [comment]
I'm not sure about this. Does anilist (or whichever provider you're using) have a title in alternate language?

**Comment by reitenth** [comment]
anilist has a setting for english or roman title

**Comment by IgnisDa** [comment]
Once #479 is merged, you can set env variable `ANIME_AND_MANGA_ANILIST_PREFER_ENGLISH=true` to enable this behavior.
