### ISSUE TITLE
[Bug] Searching for anime/manga/visual novel shows banner instead of poster

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#476]
they pull banners instead of poster.

![image](https://github.com/IgnisDa/ryot/assets/94771708/518baf5f-775a-412f-b380-de630d3be678)
![image](https://github.com/IgnisDa/ryot/assets/94771708/0f543be6-1d42-4504-b7bd-88a3a50080e7)
![image](https://github.com/IgnisDa/ryot/assets/94771708/e5ff9f79-676d-4149-bc5d-4e1a508cf097)

movie, book, tv search is fine.
![image](https://github.com/IgnisDa/ryot/assets/94771708/fdeaba4d-9030-4616-b169-d220942e1feb)

**Comment by IgnisDa** [comment]
I don't really remember but i think these were the only available attributes that I could pull. Either way, you can take a look at the source from anilist itself and see whether the correct image is being pulled.
