### ISSUE TITLE
dashboard stuck loading

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#480]
![image](https://github.com/IgnisDa/ryot/assets/94771708/2c177af0-5351-4627-a47b-b4ae898ed57f)

**Comment by IgnisDa** [comment]
Please give more information while making issues. The least you could've done was show the error in the developer console.

**Comment by reitenth** [comment]
this is the log...
![image](https://github.com/IgnisDa/ryot/assets/94771708/e0484662-877c-405b-b3b0-416bafbcf3ba)

**Comment by IgnisDa** [comment]
No as I said, I need logs for browser developer console when you get the error.

**Comment by reitenth** [comment]
i think this is correct? 
![image](https://github.com/IgnisDa/ryot/assets/94771708/b79a0abd-4618-45a3-abed-0f675e2158c3)
![image](https://github.com/IgnisDa/ryot/assets/94771708/8b5fc0d0-df89-4e5b-8621-f4028ea01401)

**Comment by IgnisDa** [comment]
None of these logs are from Ryot. Are you able to reproduce the error?

**Comment by reitenth** [comment]
the dashboard just doesnt load on page refresh it just continuously loads. i can log out and log in and it still just loads. it was working before i upgraded earlier this week. i want to say it was working before this issue was resolved/added. might have been one of the 3.4.x tags.

https://github.com/IgnisDa/ryot/issues/474

**Comment by IgnisDa** [comment]
Did you try clearing your local storage?

**Comment by reitenth** [comment]
i deleted all data/cookies in firefox from the ip ryot is installed on and still nothing.

**Comment by reitenth** [comment]
![image](https://github.com/IgnisDa/ryot/assets/94771708/cd690f11-b442-4b13-b235-8fbfd7739d09)
all of them are green, the responses all say in progress however.

**Comment by IgnisDa** [comment]
No that's just the name of the collection. Show me the response tab.

**Comment by reitenth** [comment]
![image](https://github.com/IgnisDa/ryot/assets/94771708/3c5b7115-bba2-4d81-9bf0-2fdfc9bec348)
![image](https://github.com/IgnisDa/ryot/assets/94771708/4edc7bc2-4cb3-4afc-9226-882f81631dfb)
![image](https://github.com/IgnisDa/ryot/assets/94771708/eae0b666-99e1-4edf-bf78-3fbf73e60c5b)
most of them look like the last one

**Comment by reitenth** [comment]
i let it run for 5 minutes and compared to the demo version. there are no errors. this is the biggest change, the demo has collections list in responses and my instance does not. it just cycles through the same requests/responses.
 
data	Object { userCollectionsList: [] }
userCollectionsList	[]

**Comment by IgnisDa** [comment]
Did you try logging in and out again?

**Comment by reitenth** [comment]
yep tried that multiple times. is my database bad perhaps? also some of my entries that dont have watch data or a review are not removing which makes me think they arr stuck in a collection i cant see because od this issue.

**Comment by reitenth** [comment]
i deleted the database and appdata folder. remade container, getting exact same thing occurring with google books not retrieving anything either.

**Comment by IgnisDa** [comment]
Did you tamper with the Ryot database at any point?

**Comment by reitenth** [comment]
just deleting and remaking it. never changed anything in it. im kind of at a loss now. i completely started fresh and its still not working.

**Comment by reitenth** [comment]
well it is now showing dashboard, ive deleted the database about 3 times and for some reason it started working this time.

**Comment by IgnisDa** [comment]
Alright. I have no idea as well.
