### ISSUE TITLE
google books doesnt get any results

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#481]
![image](https://github.com/IgnisDa/ryot/assets/94771708/a6be21dc-57ac-4720-9f74-0408b2bd48cf)

**Comment by IgnisDa** [comment]
Please give more information while making issues. The least you could've done was show the error in the developer console.

**Comment by reitenth** [comment]
this is the log...
![image](https://github.com/IgnisDa/ryot/assets/94771708/0131b5bc-e9f0-4ff4-9c72-09fb143a2ceb)

**Comment by reitenth** [comment]
not sure if these are correct but im getting a bunch of stuff like this 
![image](https://github.com/IgnisDa/ryot/assets/94771708/a94fc8ae-bcb5-4bbe-9dc8-04546811ec80)
![image](https://github.com/IgnisDa/ryot/assets/94771708/7f65de97-0d2a-428a-a401-c6216ff47d7d)

**Comment by IgnisDa** [comment]
Thats the stack trace, I need the response.

**Comment by reitenth** [comment]
this loooks like what ur looking for? 
![image](https://github.com/IgnisDa/ryot/assets/94771708/2e068f4c-7883-4457-9e29-ee995149351d)

**Comment by IgnisDa** [comment]
Yep. Can you show the request for the same request?

**Comment by reitenth** [comment]
![image](https://github.com/IgnisDa/ryot/assets/94771708/49704b60-0fc1-4648-a7fd-58131562f4da)
![image](https://github.com/IgnisDa/ryot/assets/94771708/1651d6ce-ea57-47c8-a77f-141dd6539cde)

**Comment by IgnisDa** [comment]
I am not able to reproduce this 
![image](https://github.com/IgnisDa/ryot/assets/60938164/979540dd-1bf2-4fef-8fe4-0585354feec3)
