### ISSUE TITLE
Script to import data from TvTime

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#484]
Hi @IgnisDa 

I improved the script I used for myself to move my data from TvTime platform to Ryot, and I published in Github (https://github.com/SirMartin/TvTimeToRyot).

It is just in case you want to add it somehow to the documentation, or maybe create some kind of custom import for it, you can based on it.

It will be useful for other users trying to move data from TvTime to the awesome Ryot.

Thanks :wink:

**Comment by IgnisDa** [comment]
It would be great if you can make a PR adding it to the importing docs.

**Comment by SirMartin** [comment]
Ok, I will try

**Comment by IgnisDa** [comment]
@SirMartin I was looking at the readme. Instead of asking your users to get an API key from TMDb, you can use the one Ryot has (https://github.com/IgnisDa/ryot/blob/1deaf25e330cd46ae2d316ad7cf5c7f113a21573/libs/config/src/lib.rs#L9).

**Comment by SirMartin** [comment]
Thanks for the offer, but I am not sure I will be able to do it, because the library I am using does not support accessing via token, only with the ApiKey, I checked other libraries, and neither was an option, so I suppose I need to make the queries manually, instead of using the library, so not sure if I want to spend time to do that, if no one uses it.

**Comment by SirMartin** [comment]
Documentation added here https://github.com/IgnisDa/ryot/pull/493

**Comment by IgnisDa** [comment]
> Thanks for the offer, but I am not sure I will be able to do it, because the library I am using does not support accessing via token, only with the ApiKey, I checked other libraries, and neither was an option, so I suppose I need to make the queries manually, instead of using the library, so not sure if I want to spend time to do that, if no one uses it.
> 
> I am working on the doc.

Alright. No issues.
