### ISSUE TITLE
[Bug] Mal/Media Json not importing

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#485]
fresh database that was just made.

1, go to imports and exports
2. choose mal/media json
3. import xml file for anime manga for mal or json file for media json
4. check reports, nothing imported.
5. goodreads import works fine.

![image](https://github.com/IgnisDa/ryot/assets/94771708/b2724648-30c8-4304-9dac-0e55ddf9668b)

**Comment by IgnisDa** [comment]
What about logs in the terminal? You can also set `RUST_LOG=ryot=trace` env variable before starting the import.

**Comment by reitenth** [comment]
not sure what im looking for in the terminal. i added trace. didnt notice anything in the browser console.
![image](https://github.com/IgnisDa/ryot/assets/94771708/f381c9fc-871e-47c9-a4f1-efc1a9143e22)
![image](https://github.com/IgnisDa/ryot/assets/94771708/aac9b81d-3057-421e-83db-8278389c8c0c)

**Comment by IgnisDa** [comment]
Is your export file big? The import will take a long then.

**Comment by reitenth** [comment]
its 500 anime, but it has worked in previous versions in about a few minutes. i have one that tried from 7hrs ago so i think its just not working.

**Comment by IgnisDa** [comment]
Does it work on the public demo?

**Comment by reitenth** [comment]
nope, tried for a few minutes now looks like same thing is happening

**Comment by IgnisDa** [comment]
Can you send me the media json file?

**Comment by reitenth** [comment]
[AnilistAnimeList.json](https://github.com/IgnisDa/ryot/files/13324627/AnilistAnimeList.json)

**Comment by reitenth** [comment]
i also tried mal xml and those are not working

**Comment by IgnisDa** [comment]
Ryot does not support importing from Anilist. Importing from a source that is not supported is obviously going to fail.

**Comment by reitenth** [comment]
its just a json file what is a "media json" then? i thought it was a generic json file. also xml from mal is not working

**Comment by IgnisDa** [comment]
The "Generic json" still needs an input format https://ignisda.github.io/ryot/importing.html#media-json.

Send me your mal export. It should be 2 files ending with `.xml.gz`.

**Comment by reitenth** [comment]
oh, its the zipped file. import works with that now, but it fails missing a column on almost all entries 
![image](https://github.com/IgnisDa/ryot/assets/94771708/b42e553b-5615-473c-bc3e-c7164d3faffa)

**Comment by IgnisDa** [comment]
Send me the files.

**Comment by reitenth** [comment]
[animelist_1699392940_-_16031904.xml.gz](https://github.com/IgnisDa/ryot/files/13324660/animelist_1699392940_-_16031904.xml.gz)
[mangalist_1699393232_-_16031904.xml.gz](https://github.com/IgnisDa/ryot/files/13324661/mangalist_1699393232_-_16031904.xml.gz)

**Comment by IgnisDa** [comment]
You will have to import them manually.
