### ISSUE TITLE
shows arent removing after removing history and rating

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#486]
removed rating and history and nothing is removing after 10 minutes.

![image](https://github.com/IgnisDa/ryot/assets/94771708/07ff47de-5a8a-4830-8213-05917a30329e)
![image](https://github.com/IgnisDa/ryot/assets/94771708/194175f0-a01f-4f27-b91d-5b482ce93392)

**Comment by IgnisDa** [comment]
It will be done via a cron job. It runs once a day.
