### ISSUE TITLE
[Feature Request] Easier way to remove entry from ryot

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#487]
waiting 24 hrs for an unknown timed task that cant be set is not the greatest. i think a "remove entry" would work well in this field. 
![image](https://github.com/IgnisDa/ryot/assets/94771708/e7dbeb81-03ab-4087-94e5-cbe766d095f3)

**Comment by IgnisDa** [comment]
I don't see any point to this. The UI is already very complicated. Also, you don't have to "wait 24 hours". It will disappear automatically.
