### ISSUE TITLE
[Help] trakt import did not mark some rated shows as watched, how to change in postgres?

### ISSUE THREAD

**Issue by reitenth** [IgnisDa/ryot#488]
every rated show i have seen, they just were not in watch history. not sure where to change data in postgres for them. doesnt look like they in review/metadata/seen.

![image](https://github.com/IgnisDa/ryot/assets/94771708/8d8fd002-4d6a-4652-9258-d302ba831542)
![image](https://github.com/IgnisDa/ryot/assets/94771708/8fb7672f-963b-420c-a7d8-966bf6ee0d3b)

**Comment by IgnisDa** [comment]
Just add them via the UI. why do you need to do it through postgres?

**Comment by reitenth** [comment]
cause u can bulk do it in postgres, changing a few hundred items without a bulk editor or easier ui to click will take hours.

**Comment by IgnisDa** [comment]
You should write a custom script to call the `bulkProgressUpdate` graphql mutation. Directly changing postgres rows is not a good idea and was probably the cause of data inconsistencies that you reported in other issues.
