### ISSUE TITLE
[FEATURE REQUEST] - Music tracker

### ISSUE THREAD

**Issue by DaFlowah** [IgnisDa/ryot#49]
Hi there,
It would be cool to have also a music tracker, so that you can see which albums you've already listened to and see when new albums get released :D

**Comment by IgnisDa** [comment]
Ah alright. I will keep this in mind. Another possible solution is adding integration with Spotify, Youtube music etc and using those.

**Comment by chunned** [comment]
> Thats a great idea. What sources can Ryot get the music data from? For example TMDB for movies, IGDB for video games etc.

Check out MusicBrainz, they've got a pretty robust and easy to use API

**Comment by HStep20** [comment]
You could review [Maloja](https://github.com/krateng/maloja), as its basically a selfhosted last.fm. It doesn't do any scrobbling, but [Multi-Scrobbler](https://github.com/FoxxMD/multi-scrobbler) acts as an 'API Linker' to pull data from *x*, *y*. or *z* API, and push the music scrobbles to *x*, *y*, or *z* platform. 

I could see this project evolving into a 'plugin' style system where anyone could create an integration to scrobble data out of, and into here.

**Comment by IgnisDa** [comment]
@DaFlowah Looking into this. What exactly would a music integration look like? What would you track?

**Comment by DaFlowah** [comment]
> @DaFlowah Looking into this. What exactly would a music integration look like? What would you track?

Not sure about anyone else preferences, but to me it would be nice to be able to track what I've already listened to (songs, albums, EPs, etc) and, most importantly, I'd like to be able to see when the bands I like release something new.

**Comment by IgnisDa** [comment]
Note to self: Audiobookshelf has an [integration for MusicBrainz](https://github.com/advplyr/audiobookshelf/blob/master/server/providers/MusicBrainz.js) that I can shamelessly port to rust.

**Comment by IgnisDa** [comment]
Hello. I plan to work on music integration for Ryot next. In relation to #203, I am a bit divided. Should I allow the search for just a single release, and then put an album (or EP) in a media group?

@DaFlowah @chunned @HStep20 I would appreciate your feedback here.

**Comment by chunned** [comment]
> Should I allow the search for just a single release, and then put an album (or EP) in a media group?

That sounds good to me. I would like to be able to search for a specific release, or for an artist (media group containing all that artist's releases).

**Comment by IgnisDa** [comment]
Artist support will be a long way off since the people management vide for Ryot needs a complete overhaul.  I'm talking only about music here.

**Comment by chunned** [comment]
I'm kinda confused what the purpose of the media grouping for music would be then. Are you talking about grouping various editions of a single release, i.e. the way MusicBrainz uses release groups?

**Comment by IgnisDa** [comment]
A group will be an album or an EP. And the music tracker itself will allow you to look up a single track.

**Comment by DaFlowah** [comment]
Hi @IgnisDa :D
So, if I look for a song (i.e. Bohemian Rhapsody), it will pop up along with its album (A Night at the Opera)?
If so, it would be cool for me 😎

**Comment by IgnisDa** [comment]
When you look up bohemian Rhapsody, only that would show up. When you open the details, you'll see something like "Belongs to A night at the Opera". You can click on that to view the entire album (this will happen when #203 is implemente).

**Comment by DaFlowah** [comment]
> When you look up bohemian Rhapsody, only that would show up. When you open the details, you'll see something like "Belongs to A night at the Opera". You can click on that to view the entire album (this will happen when #203 is implemented).

Sounds good to me 😎

**Comment by lyz-code** [comment]
It would be nice if we could also add ratings to the songs

**Comment by IgnisDa** [comment]
That should be possible, though you should be aware that I don't plan to work on music tracking RN. The quality of data from the various sources was awful, and I was discouraged.

**Comment by IgnisDa** [comment]
Note to self: look into Discogs API.

**Comment by chunned** [comment]
> Note to self: look into Discogs API.

I've had pleasantly surprising results with the Discogs API in my own music tracker project. Often it's a better source of data than MusicBrainz, definitely a good idea to check it out.

**Comment by IgnisDa** [comment]
Can you share a link to that project?

**Comment by chunned** [comment]
Sure, but be warned it's quite a bit different from Ryot (and also still very rough around the edges) - [Databass](https://github.com/chunned/databass)

**Comment by IgnisDa** [comment]
I released initial music tracking with YoutubeMusic (`v7.12.0). It is still rough around the edges (for eg. an integration, album tracking is still missing). But please take the new version for a spin and let me know whether it works for you.

**Comment by Grim73** [comment]
Just an idea, would there be a way to integrate your own YouTube music api through google console? I have no idea how this would be done, but it could work round about like the google books integration

**Comment by IgnisDa** [comment]
Unfortunately YouTube music doesn't have a google supported api

**Comment by Grim73** [comment]
could do something similar to [Music Assistant](https://music-assistant.io/music-providers/youtube-music/) though, there seems to be instability with this.

Could a music endpoint be added to jellyfin?

**Comment by IgnisDa** [comment]
Right now I am talking to the Rustypipe (which is the library ryot uses to get YoutubeMusic data) dev. https://codeberg.org/ThetaDev/rustypipe/issues/17

I will see where those talks go.

**Comment by Procuria** [comment]
@IgnisDa would you be so kind to point into the direction of configuring this enhancement? 
What should be added into the `music: { }` part? 
Thank you for your good work!

**Comment by IgnisDa** [comment]
There's no configuration options for music tracking as of yet.

**Comment by Grim73** [comment]
@IgnisDa possibly something with [ListenBrainz](https://listenbrainz.org/data/), just deployed [Navidrome](https://www.navidrome.org/) and it can utilize this for tracking data.

**Comment by IgnisDa** [comment]
Listenbrainz looks good. I will take a look.

**Comment by royaltongue** [comment]
+1 For Navidrome support

**Comment by IgnisDa** [comment]
Please create a new issue for this.

**Comment by IgnisDa** [comment]
Also for everyone else subscribed to this issue, the Youtube Music integration is now live!
