### ISSUE TITLE
Global filters

### ISSUE THREAD

**Issue by orrrrn** [IgnisDa/ryot#490]
Implement global filter so you could use all browsing features with these filters. For example browse media by genres that belong to certain collection. Maybe this could be even expanded so you could use people or genres as a filter as well.

This is based on discussion in [here](https://github.com/IgnisDa/ryot/discussions/489).

**Comment by IgnisDa** [comment]
Not sure what features you want? The original discussion was about marking media as owned, right?

**Comment by orrrrn** [comment]
Sure. I just thought it would've been easier to implement by using collections since those are already there. Also this filter would be more useful if you could use other properties as well.

This would make it possible to create collections like "DVD", "BD", "VHS", "owned in Apple TV" or whatever and then use those as a filter. Of course just "owned" field in DB would work and that would fill my use case.

**Comment by IgnisDa** [comment]
There is already a filter for collection. Does it not work for you?

**Comment by orrrrn** [comment]
I can't use any filter when browsing genres or people. What I'd like was to be able to select collection (or "owned" field) in the genre page. So I could only see genres from the selected collection.
To make this even more versatile it would be great to select other filters as well. Like select an actor/actress in the genre view.

**Comment by IgnisDa** [comment]
Ahh that's a big ask. I think what I would like to do is implement a "mark as owned" btn. 

Global filters I would like to tackle later.

**Comment by IgnisDa** [comment]
I have decided that i don't want a global filter system. Closing for now, will reopen if I find myself wanting to implement it in the future.

If anyone has any related suggestions, feel free to drop them here.
