### ISSUE TITLE
Add a way to create workouts for older dates

### ISSUE THREAD

**Issue by sahinakkaya** [IgnisDa/ryot#503]
I was tracking my progress in Telegram messages and now I find out ryot exists. Great project! It would be really nice if there was a way to add older workouts manually. I have roughly 20 workouts and adding them manually wouldn't be a big deal especially with a way to duplicate them (just like repeat workout feature).

**Comment by IgnisDa** [comment]
Yeah I want to add the ability to edit workouts too. For the time being, i suggest you to add in the workout and use SQL to change the `started_at` and `ended_at`.

**Comment by IgnisDa** [comment]
@sahinakkaya this has been released in `v3.4.14`. Once you are done adding all workouts, I recommend you deploy a "Re-evaluate all workouts job" from the miscellaneous settings.

**Comment by sahinakkaya** [comment]
Wow, that was fast. Thank you so much!

**Comment by sahinakkaya** [comment]
@IgnisDa I have added older workouts and deployed a "Re-evaluate all workouts job" but workouts are not ordered based on starting date. They are still ordered based on insertion date. Can you fix that too?

**Comment by IgnisDa** [comment]
Can you show a screenshot of the workouts and the expected order. The workouts are ordered by their `end_time`.

**Comment by sahinakkaya** [comment]
<img width="629" alt="image" src="https://github.com/IgnisDa/ryot/assets/32161460/007d8081-fb16-4e68-8110-a4a6a407d2c4">
The last workout is a dummy workout that I created and set its starting and ending date as Nov 1. It should be last on the workout list as the list is sorted by newest first.

**Comment by sahinakkaya** [comment]
I also think that "Re-evaluate all workouts job" doesn't work as expected. If it would work, I should have seen Personal Records on first day of workouts. But I don't see it. Why it says 0 PRs?

<img width="629" alt="image" src="https://github.com/IgnisDa/ryot/assets/32161460/1b4f20c2-6990-4f65-b362-f8453eeba4ae">

**Comment by IgnisDa** [comment]
Yep something wrong. Can you make a dump of your database and email it to me? My email is in mu GH profile.

**Comment by sahinakkaya** [comment]
Uhhm, I'm afraid I can't because of privacy concerns. But I think it is reproducible. On an empty instance:

- Create a workout with heavy weights and high repetitions. Do not edit date. (Nov 21)
- Create a workout even heavier weights and higher repetitions. Do not edit date (Nov 22, meaning later than the first workout)
- Create a workout with lighter weights and low repetitions and set date to Nov 1 (earlier than the all workouts).  

Observe that workout list is sorted based on creation date:
- Nov 1
- Nov 22
- Nov 21

Correct order should have been:

- Nov 22
- Nov 21
- Nov 1

My workaround for this was deleting Nov 22 and Nov 21 and recreating them to fix the sorting order. But even after this workaround Personal Records were not calculated correctly after "Re-evaluate all workouts job"

**Comment by IgnisDa** [comment]
Alright, I am able to reproduce it.
