### ISSUE TITLE
Show exercise image and muscle group in workout exercises

### ISSUE THREAD

**Issue by sahinakkaya** [IgnisDa/ryot#506]
In workout detail and during workout, exercises are only represented with their name:

<img width="629" alt="image" src="https://github.com/IgnisDa/ryot/assets/32161460/7ebbaa8b-ec9f-4d13-a130-fcc458e652cb">

I suggest changing it to something similar like in Exercises list (image and muscle group is also visible):

<img width="307" alt="image" src="https://github.com/IgnisDa/ryot/assets/32161460/3a350de8-857a-4202-bf52-80e2e3dfe388">

I think this would make tracking exercises easier especially those whose native language is not English.

**Comment by IgnisDa** [comment]
Hmm this is an interesting idea. I see how this would be useful, but when i implemented the workout tracking feature, i wanted it to be as close to the Strong Android app as possible. Would it be a good idea to digress from a tried and tested UI?

**Comment by sahinakkaya** [comment]
I've never used the Strong App so I didn't know this project was trying to replicate its UI. If most of the users are OK with the current design it should stay like this. Let's leave this issue open and see if people want such thing.

**Comment by IgnisDa** [comment]
I will implement an alternate UI and see how it works.
