### ISSUE TITLE
[FEATURE REQUEST] Show public collections by users

### ISSUE THREAD

**Issue by jakesmorrison** [IgnisDa/ryot#507]
I would like to see the public collections of my users (and show mine). I am able to access another users collection via a url that they share with me, but I am not sure how to determine that url from the UI. Maybe something like this could work?

![image](https://github.com/IgnisDa/ryot/assets/14865171/2c16ac36-6567-43b4-b44d-e9eaca8aefff)

Or add another drop here with "Users"? 
![image](https://github.com/IgnisDa/ryot/assets/14865171/c3cc7f3e-c4ef-4a07-b7d3-8bd94639c5d6)

**Comment by IgnisDa** [comment]
Hmm, sounds like a good idea. I'll implement it after #373.

**Comment by IgnisDa** [comment]
I will be removing collection visibility (in #816) in favor of #552.
