### ISSUE TITLE
Documentation for Binary Install

### ISSUE THREAD

**Issue by Charlielx** [IgnisDa/ryot#509]
Hi! Submitting this as requested over on reddit. Would love to get some instructions for a non-docker install. Let me know if there's anything I can do to be of assistance.

Thanks!

**Comment by IgnisDa** [comment]
I'm assuming you have already setup the `DATABASE_URL` env variable. In addition to that, you'' have to set to `SERVER_CONFIG_DUMP_PATH`. By default, it is set to `/data/ryot-config.json` which likely does not exist on your setup.

LMK if that works.
