### ISSUE TITLE
Export Data is Missing Public/Private Reviews

### ISSUE THREAD

**Issue by jakesmorrison** [IgnisDa/ryot#515]
I ended up creating a JSON export, and moving my DB to start fresh. I imported my JSON and everything worked well except now all my reviews are marked "Private". 

I think the JSON export is missing the private/public field boolean. 
![image](https://github.com/IgnisDa/ryot/assets/14865171/d5a616f1-f196-4ae4-8825-c76aa3417e08)

By default is the JSON importer making the reviews private?

**Comment by IgnisDa** [comment]
Yep, you are right. The exporter does not contain visibility information. I will look into it.
