### ISSUE TITLE
"Mark as seen" doesn't accurately reflect next episode

### ISSUE THREAD

**Issue by Alzarath** [IgnisDa/ryot#520]
When marking Battlestar Galactica (2004) Season 1 as seen episode-by-episode, after I marked the last episode in the season (episode 13) as seen, the context for the Mark as Seen button became "S1-E14", which does not exist. I would expect it to display "S2-E1" since that's the next episode in the series. Marking season 2 episode 1 as seen then correctly shows the next episode as "S2-E2".

If a series has ended it will show an imaginary next episode similar to above. I might expect a completed series to then show "S1-E1", or not show a next episode at all.

When importing from Trakt, the Mark as Seen for shows is set to "S1-E2" regardless of the progress. I would expect it to be the first un-seen episode (excluding season 0).

Ryot 3.5.4

Related to #429

**Comment by IgnisDa** [comment]
> I would expect it to display "S2-E1" since that's the next episode in the series.

I was aware of this bug, but never got around to fixing it. Will do.

As for Trakt, I can't really fix it since the API does not return episodes in the order. And I do not want to add code for sorting since its a one time operation.
