### ISSUE TITLE
Goodreads imports are limited to 100 books

### ISSUE THREAD

**Issue by aidengindin** [IgnisDa/ryot#521]
When importing books from Goodreads, only the 100 most recent books that I've shelved on Goodreads are imported into Ryot.

This appears to be an inherent limitation of the Goodreads RSS URL that Ryot uses for importing. Instead, it could use Goodreads' [CSV export](https://www.goodreads.com/review/import).

**Comment by IgnisDa** [comment]
Can you share your CSV export? I remember that I did not implement Goodreads CSV because the file does not have much data so the media details page for the book looks very incomplete.

**Comment by aidengindin** [comment]
[goodreads_library_export.csv](https://github.com/IgnisDa/ryot/files/13785529/goodreads_library_export.csv)

I don't see any metadata that's obviously missing, and it includes the ISBN, so anything that is missing can be pulled in from OpenLibrary/Google Books.

**Comment by IgnisDa** [comment]
It does not have details about the book itself (description, cover, etc). Nonetheless, I can use the ISBN to fetch details. Thanks for the export.

(wow you have read a lot of books!)

**Comment by aidengindin** [comment]
more than half that export is my TBR - there's no way I'm ever getting to all of those books :)

I'd be happy to contribute some backend code if that will help move things along faster.

**Comment by IgnisDa** [comment]
A contribution will be welcome. Take a look at the `storygraph.rs` file which uses ISBN for import.

Also make sure you create the new branch from the `partial-metadata` one.
