### ISSUE TITLE
[Feature Request] Oauth / OpenID

### ISSUE THREAD

**Issue by Drakon74** [IgnisDa/ryot#522]
Hello,

i am in the search for a media tracker and i like this one the most so far, however are there any plans for supporting OAuth / OpenID? Since this is also something which i didn't saw on any other tracker or general collection tracker at all.

**Comment by IgnisDa** [comment]
Yep this is something that has been on my mind for quite some time. I plan to implement it soon.

**Comment by LIRIKKER** [comment]
Hey, just wondering if you’ve made any progress on this? 

Been watching this for a while and it’s the only thing that’s currently stopping me from installing this on my home lab!

**Comment by IgnisDa** [comment]
I really want to implement this but I don't have any experience with oauth etc. are you aware of any self hosted software (preferably rust) that does this stuff? I'd like to take a look at the codebase and see how this works.

**Comment by alexanderadam** [comment]
I'm not a Rust developer but it seems that there's [an OIDC crate](https://github.com/ramosbugs/openidconnect-rs?tab=readme-ov-file#openid-connect-library-for-rust) (is it the same one like [this](https://docs.rs/openidconnect/latest/openidconnect/)? 🤔) and [this blog post seems helpful too](https://www.shuttle.rs/blog/2023/08/30/using-oauth-with-axum).

**Comment by IgnisDa** [comment]
Ah thanks, that blog post is really helpful. I'll take a look into that and start implementing oauth soon.

**Comment by IgnisDa** [comment]
@alexanderadam I have made some progress on the oidc integration. Would you be willing to test it out with your OpenID provider? You will have to set up a separate Ryot instance of course.

Anyone else following this issue, willing to test it would also be welcome.

**Comment by alexanderadam** [comment]
That's amazing news!

I can't test right now since I'm in a busy phase but there's also a compliant Rust based server called [Kanidm](https://kanidm.com/) that can be easily set up via [docker compose](https://github.com/kanidm/kanidm/discussions/2583#discussioncomment-8581442).

There's also [a quickstart page that describes how to create a login](https://kanidm.github.io/kanidm/stable/quickstart.html) for tests.

**Comment by IgnisDa** [comment]
This has been released! Please follow the [guide](https://github.com/IgnisDa/ryot/releases/tag/v4.4.0) in the `v4.4.0` release to port exisiting users.
