### ISSUE TITLE
Error opening media assets in Firefox

### ISSUE THREAD

**Issue by carsanbu** [IgnisDa/ryot#524]
Hello,
Every time I click in an asset in media I get an error using Firefox:
![imagen](https://github.com/IgnisDa/ryot/assets/6189864/4e349eef-7d9c-4829-ba80-85297e4f1807)

But using Chrome this is what I get:
![imagen](https://github.com/IgnisDa/ryot/assets/6189864/2ee4a968-fd78-4ddb-bc12-613c5e72c387)

Ryot v3.5.4

**Comment by IgnisDa** [comment]
Clicking on an asset should do nothing at all. What are you clicking on exactly?

**Comment by IgnisDa** [comment]
NVM I got the issue. You seem to be using an older firefox version. I will fix it anyway.

**Comment by carsanbu** [comment]
> Clicking on an asset should do nothing at all. What are you clicking on exactly?

For example clicking in this page in the cover image:
![imagen](https://github.com/IgnisDa/ryot/assets/6189864/70a9300a-7ef7-4465-936b-0f5b29a99f6b)

I'm using Firefox 109.0 (64-bit), I will try updating it, thanks.
