### ISSUE TITLE
[FEATURE REQUEST] - Plex and game collection

### ISSUE THREAD

**Issue by sahara101** [IgnisDa/ryot#525]
Hi! I assume it is not possible to somehow show our game collections in plex as a library? Not interested to play, just the see the collection of games added via igdb.

Thanks!

**Comment by IgnisDa** [comment]
Its not possible yet, but I am open to contributions.

**Comment by sahara101** [comment]
I am no programmer so hope that others who know such stuff are also interested in the function :D

**Comment by IgnisDa** [comment]
I would implement it, but I do not have a plex premium pass.

Will leave this open if someone wants to take this up.

**Comment by IgnisDa** [comment]
Closing since there is not enough demand for this feature.
