### ISSUE TITLE
game not found

### ISSUE THREAD

**Issue by sahara101** [IgnisDa/ryot#526]
Hi!

I cannot find this game: https://www.igdb.com/games/journey-collectors-edition

Thanks!

**Comment by IgnisDa** [comment]
Probably because this is a collector's game. I think the IGDB search filters those out (by setting `version_parent = null`).

You can visit this URL: `<your-instance>media/item/commit?identifier=23411&lot=VIDEO_GAME&source=IGDB` to commit the game to your db.

**Comment by sahara101** [comment]
ty that worked. As ex, this one was found https://www.igdb.com/games/heavy-rain-and-beyond-two-souls-collection

**Comment by IgnisDa** [comment]
Ryot hands over the query to igdb and that's all. If you ever have a problem like this, you can just replace the identifier in the above URL.
