### ISSUE TITLE
MediaTracker Import

### ISSUE THREAD

**Issue by TWART016** [IgnisDa/ryot#527]
Hi,

I want to import my movies and series from MediaTracker.

I created a Token and set it in the importing tab
![image](https://github.com/IgnisDa/ryot/assets/29805669/46c241bc-da5b-46ea-92ac-0050ece8aae6)

I get a lot of errors
```
[33mpostgres_1  |[0m 2023-12-30 14:53:12.769 UTC [4631] ERROR:  duplicate key value violates unique constraint "pk-metadata_to_partial-metadata"
[33mpostgres_1  |[0m 2023-12-30 14:53:12.769 UTC [4631] DETAIL:  Key (metadata_id, partial_metadata_id)=(6, 3284) already exists.
[33mpostgres_1  |[0m 2023-12-30 14:53:12.769 UTC [4631] STATEMENT:  INSERT INTO "metadata_to_partial_metadata" ("metadata_id", "partial_metadata_id", "relation") VALUES ($1, $2, $3) RETURNING "metadata_id", "partial_metadata_id", "relation"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.107 UTC [4632] ERROR:  duplicate key value violates unique constraint "pk-person_to_partial-metadata"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.107 UTC [4632] DETAIL:  Key (person_id, partial_metadata_id)=(252, 4651) already exists.
[33mpostgres_1  |[0m 2023-12-30 14:53:13.107 UTC [4632] STATEMENT:  INSERT INTO "person_to_partial_metadata" ("person_id", "partial_metadata_id", "relation", "role") VALUES ($1, $2, $3, $4) RETURNING "person_id", "partial_metadata_id", "relation", "role"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.346 UTC [4630] ERROR:  duplicate key value violates unique constraint "pk-person_to_partial-metadata"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.346 UTC [4630] DETAIL:  Key (person_id, partial_metadata_id)=(254, 6407) already exists.
[33mpostgres_1  |[0m 2023-12-30 14:53:13.346 UTC [4630] STATEMENT:  INSERT INTO "person_to_partial_metadata" ("person_id", "partial_metadata_id", "relation", "role") VALUES ($1, $2, $3, $4) RETURNING "person_id", "partial_metadata_id", "relation", "role"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.373 UTC [4633] ERROR:  duplicate key value violates unique constraint "pk-person_to_partial-metadata"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.373 UTC [4633] DETAIL:  Key (person_id, partial_metadata_id)=(254, 6407) already exists.
[33mpostgres_1  |[0m 2023-12-30 14:53:13.373 UTC [4633] STATEMENT:  INSERT INTO "person_to_partial_metadata" ("person_id", "partial_metadata_id", "relation", "role") VALUES ($1, $2, $3, $4) RETURNING "person_id", "partial_metadata_id", "relation", "role"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.395 UTC [4631] ERROR:  duplicate key value violates unique constraint "pk-person_to_partial-metadata"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.395 UTC [4631] DETAIL:  Key (person_id, partial_metadata_id)=(254, 6407) already exists.
[33mpostgres_1  |[0m 2023-12-30 14:53:13.395 UTC [4631] STATEMENT:  INSERT INTO "person_to_partial_metadata" ("person_id", "partial_metadata_id", "relation", "role") VALUES ($1, $2, $3, $4) RETURNING "person_id", "partial_metadata_id", "relation", "role"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.446 UTC [4632] ERROR:  duplicate key value violates unique constraint "pk-person_to_partial-metadata"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.446 UTC [4632] DETAIL:  Key (person_id, partial_metadata_id)=(254, 6420) already exists.
[33mpostgres_1  |[0m 2023-12-30 14:53:13.446 UTC [4632] STATEMENT:  INSERT INTO "person_to_partial_metadata" ("person_id", "partial_metadata_id", "relation", "role") VALUES ($1, $2, $3, $4) RETURNING "person_id", "partial_metadata_id", "relation", "role"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.461 UTC [4632] ERROR:  duplicate key value violates unique constraint "pk-person_to_partial-metadata"
[33mpostgres_1  |[0m 2023-12-30 14:53:13.461 UTC [4632] DETAIL:  Key (person_id, partial_metadata_id)=(248, 6399) already exists.
[33mpostgres_1  |[0m 2023-12-30 14:53:13.461 UTC [4632] STATEMENT:  INSERT INTO "person_to_partial_metadata" ("person_id", "partial_metadata_id", "relation", "role") VALUES ($1, $2, $3, $4) RETURNING "person_id", "partial_metadata_id", "relation", "role"
```

v3.5.4

**Comment by IgnisDa** [comment]
These are database errors, and are expected behaviour. Please show me the Ryot logs.

**Comment by TWART016** [comment]
Sadly there is no entry after trying to import the data. There are just the logs from the startup
`docker-compose logs ryot
Attaching to ryot
[36mryot        |[0m [2m2023-12-29T01:15:52.305428Z[0m [32m INFO[0m [2mryot[0m[2m:[0m Running version: 3.5.4
[36mryot        |[0m [2m2023-12-29T01:15:52.504702Z[0m [32m INFO[0m [2msea_orm_migration::migrator[0m[2m:[0m Applying all pending migrations
[36mryot        |[0m [2m2023-12-29T01:15:52.525330Z[0m [32m INFO[0m [2msea_orm_migration::migrator[0m[2m:[0m No pending migrations
[36mryot        |[0m [2m2023-12-29T01:15:52.564653Z[0m [32m INFO[0m [2mryot[0m[2m:[0m Using timezone: Etc/GMT
[36mryot        |[0m [2m2023-12-29T01:15:52.575066Z[0m [32m INFO[0m [2mryot[0m[2m:[0m Migrating custom data to S3...
[36mryot        |[0m [2m2023-12-29T01:15:52.602522Z[0m [32m INFO[0m [2mryot[0m[2m:[0m Migrating custom data to S3... Done
[36mryot        |[0m [2m2023-12-29T01:15:52.649528Z[0m [32m INFO[0m [2mryot[0m[2m:[0m Listening on: [::]:8000
[36mryot        |[0m thread 'tokio-runtime-worker' panicked at apps/backend/src/importer/media_tracker.rs:149:44:
[36mryot        |[0m called `Result::unwrap()` on an `Err` value: failed to lookup address information: Name does not resolve
[36mryot        |[0m note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[36mryot        |[0m thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:258:10:
[36mryot        |[0m called `Option::unwrap()` on a `None` value
[36mryot        |[0m thread 'tokio-runtime-worker' panicked at apps/backend/src/importer/media_tracker.rs:145:70:
[36mryot        |[0m called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase
[36mryot        |[0m thread 'tokio-runtime-worker' panicked at apps/backend/src/importer/trakt.rs:74:62:
[36mryot        |[0m called `Result::unwrap()` on an `Err` value: EOF while parsing a value at line 1 column 0
[36mryot        |[0m thread 'tokio-runtime-worker' panicked at apps/backend/src/importer/media_tracker.rs:145:70:
[36mryot        |[0m called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase`

**Comment by IgnisDa** [comment]
Can you show me what you're trying to fill in the trackt form?

**Comment by TWART016** [comment]
Import type is Media Tracker. A screenshot is in my first post

**Comment by IgnisDa** [comment]
Ah sorry.

Is your media tracker instance accessible from the Ryot container?

**Comment by TWART016** [comment]
From db I can ping the ryot container. How can I check from ryot to db? bash in not available there.

**Comment by IgnisDa** [comment]
Can you ping Ryot from media tracker Container?

Will it be possible to expose your media tracker instance to the internet for the duration of the import?

**Comment by IgnisDa** [comment]
I releases Ryot v4 in which curl will be installed in the Ryot container.

**Comment by TWART016** [comment]
I reinstalled the server with newest version 4.0.6. Now the import is working fine. 
I just saw on the old instance the import was successful but not visible yesterday. Maybe a cache issue.

Thanks for your help and for the great app. Need to look deeper into it.

**Comment by IgnisDa** [comment]
> I think Your data is not very intuitive

Fair enough. What do you suggest?

**Comment by TWART016** [comment]
I don't know what the API tokens are used for. Normally they are for each user, so I would move that to "Profile". 
Alternatively to "Integration", as the heading is also called "API Integration"
![image](https://github.com/IgnisDa/ryot/assets/29805669/ff01623c-a8c5-4db2-a448-6aefb7f84b4b)

I would then rename "Your Data" to "Import & Export"
