### ISSUE TITLE
Connecting to a bare-metal PostgreSQL socket leads to some bugs/performance issues. 

### ISSUE THREAD

**Issue by CaptainJawZ** [IgnisDa/ryot#528]
I have a bare-metal PostgreSQL database, which I use for a bunch other self-hosted stuff already (Nextcloud, paperless, etc) therefore I thought, why not mount the socket and let Ryot use that.

Now, I know that it's the PostgreSQL database causing the issues, because when I run it mounting the database (like the documentation recommends) it works really well.

The issues are as follows:

- Searching for a show/movie takes a really long time, and a bunch of them wont load (or let them be added) throwing multiple 500/504 errors on the console when inspected. One of which for example, is American Dad.
- Importing shows from Trackt constantly stops, after inserting one or two shows (well actually this one fails regardless, but one issue at the time)
- Jellyfin integration, also won't add some of those shows, like American dad won't be tracked, other shows will add a season, but miss another.
- The site, is incredibly incredibly slow, constantly hangs.

None of these happen when using a the PostgreSQL docker image. 

Worth mentioning, I am attempting to run PostgreSQL bare-metal and Ryot on a docker container, mounting the bare-metal PostgreSQL socket, and using this string to connect:

DATABASE_URL = "postgres:///ryot?host=/run/postgresql"

My PostgreSQL is set, so that users with the same database name can connect password-less through the socket.

Another thing I've tried, is copying some lines from the docker PostgreSQL config file into my bare-metal, it made no difference.

I know this may be out of the scope for support, and it's fair if it is! I'm trying to use it on an unorthodox way so it's kind of on me heh. But if you can help me get to the bottom of this, I would love to create a module for Ryot to be installable under NixOs, which is my intention.

**Comment by IgnisDa** [comment]
I would love to help you debug this.

My first thought is that this might be a bug in the database connection library that Ryot uses (`sqlx`). Maybe try looking through their issues?

**Comment by CaptainJawZ** [comment]
whatever the issue was, is mostly fixed with the newest 4 version, I did many tests with installing version 3, and version 4, and yeah, I feel like I can proceed with packaging this for nix!

thanks! and sorry for opening an issue for something that fixed itself the next day lol

**Comment by IgnisDa** [comment]
@CaptainJawZ would you be willing to add nix as an installation method in the docs?

**Comment by CaptainJawZ** [comment]
> @CaptainJawZ would you be willing to add nix as an installation method in the docs?

Sure! I'll be glad to, I don't think it'll be done anytime soon since it'll probably be packaged with the 24.05 release. But I'll get to work on it as soon as I can.

**Comment by szethh** [comment]
hi @CaptainJawZ did you get around to making that module? could you share your nix config?

i'm also looking to get it set up in nixos but only found docker instructions

**Comment by CaptainJawZ** [comment]
@szethh oh sorry no, is not hard to get it to package, but the issue is that because often times the updates of Ryot need to be done in a specific order so that the database is updated & remains compatible, or else  happened to me a lot of times) I figured that between the quick development of Ryot and the slow PR approval speed of nixpkgs, a lot of people could've been at risk of having their ryot db messed up, specially if they went ahead and made an overlay for the newest version.

So I figured it may be wiser to wait for Ryot development to slow down a bit before I started the nix PR. that way I can try to make sure updates happen without disrupting users or filling IgnisDa discord with users whose DB got messed up.

**Comment by szethh** [comment]
ahh I see. I will wait until it's on nixpkgs then, it's not super urgent for me :)

**Comment by CaptainJawZ** [comment]
I guess I could just send the nixpkg this weekend, and show you the template for the module, but you would have to be extra careful when it comes to installing a new version/overlay to older versions if you miss one. 

my advice is to keep it in a podman/docker for a while.
