### ISSUE TITLE
Application error when setting progress

### ISSUE THREAD

**Issue by MattPainter01** [IgnisDa/ryot#537]
Hi, 

Just updated to 4.0.5 and I'm getting an application error in my browser whenever I try to set progress on any media. 

I can recreate this on the demo site:
Go to any in progress media -> Actions -> Set Progress -> Click Update 

This error seems to occur on any in progress media, I tried with a book, audiobook and movie. 
In my postgres docker logs, I am seeing a lot of `duplicate key value violates unique constraint` and `Key already exists` but I'm not sure if these are related to this issue. 

Btw, big fan of the new update, media thumbnails load way quicker now!

**Comment by IgnisDa** [comment]
Yep i can reproduce it. Thanks for reporting.
