### ISSUE TITLE
[FEATURE REQUEST] - Radarr/Sonarr integration

### ISSUE THREAD

**Issue by Nom4** [IgnisDa/ryot#54]
Hi,
Regarding the exchange on Reddit, i post here an issue as requested to integrate Radarr/Sonarr in the roadmap of ryot.
Best regards

**Comment by IgnisDa** [comment]
@Nom4 Looking into this. What exactly would an integration with Radarr/Sonarr entail?

**Comment by Nom4** [comment]
Hi, if i remember (i was not using Ryot until this feature was available), the goal is to integrate Radarr/Sonarr as a media source for monitor watching.
Hope i explain well.

**Comment by IgnisDa** [comment]
I do not think this should be a part of Ryot since it is a media tracker (not monitor). I do not use Radarr/Sonarr myself but I believe the normal flow of using them is Radarr (for monitoring) -> Plex/Jellyfin (for viewing the movie) -> Ryot (for tracking).

Is there any other way you use Radarr/Sonarr?

**Comment by Nom4** [comment]
Hi,My workflow is the following :Overseerr > radarr / sonarr > PlexDid you see ryot in this workflow ?Regards Envoyé de mon iPhoneLe 12 juil. 2023 à 18:54, Diptesh Choudhuri ***@***.***> a écrit :﻿
I do not think this should be a part of Ryot since it is a media tracker (not monitor). I do not use Radarr/Sonarr myself but I believe the normal flow of using them is Radarr (for monitoring) -> Plex/Jellyfin (for viewing the movie) -> Ryot (for tracking).
Is there any other way you use Radarr/Sonarr?

**Comment by IgnisDa** [comment]
Yes looks like you use Plex too. I think it would be better to add integration with it, yes?

**Comment by Nom4** [comment]
Really good idea !Regards 🙏Envoyé de mon iPhoneLe 12 juil. 2023 à 19:28, Diptesh Choudhuri ***@***.***> a écrit :﻿
Yes looks like you use Plex too. I think it would be better to add integration with it, yes?

**Comment by IgnisDa** [comment]
Will create a separate issue for Plex/Jellyfin.

**Comment by IgnisDa** [comment]
Related to #67.

**Comment by reitenth** [comment]
i would like the ability to add watchlist of movies/tv to radarr/sonarr. right now any time i add something as planning in trakt it auto adds to radarr and sonarr with the use of their "lists." its the big thing keepjng me on trakt for the moment

**Comment by IgnisDa** [comment]
Are you aware of any open source projects that does something similar? I would like to take a look into their code and see if it is feasible for Ryot.

Moreover can you send me the trakt docs which describe this feature?

**Comment by reitenth** [comment]
https://wiki.servarr.com/sonarr/supported#customimport
https://github.com/noggl/AniPlanrr/

aniplanrr adds shows from anilist to sonarr. they ended up implementing anilist support in sonarr so i dont use this anymore, but it is along the same lines.

**Comment by IgnisDa** [comment]
I will re-open this issue since it is something Ryot should support. However, I don't plan to work on it since I do not use the *arr services myself. 

Maybe someone else (or a future me) can take this up if they feel like it 😝.

**Comment by MikeBishop** [comment]
If I understand correctly, the Plex integration doesn't send the IDs of the item you're watching, so it needs to be in the watch list already? Integration with *arr would fundamentally be a way to seed that list, since the media played by Plex is almost guaranteed to be the same media available in *arr.

**Comment by IgnisDa** [comment]
I have never used Sonarr/Radarr so I don't know what they do. That's why I haven't gotten around to integrating then.

**Comment by MikeBishop** [comment]
Short version: You populate them with a list of movies (Radarr) and shows (Sonarr) you're interested in, and a collection of download providers to search. They monitor available releases and download them if they see something matching your selections, either something you don't have or something in a better quality than your current version. Ryot won't care about the downloads at all, just the list of movies/shows the user either has or is interested in having.

**Comment by IgnisDa** [comment]
So basically Ryot will forward the "Watchlist" collection to *arr instances right?

**Comment by MikeBishop** [comment]
I would think the it would pull anything in the *arr library into the Watchlist collection, but I'm still trying to get Ryot set up well enough to be sure I'm using the correct terminology.

**Comment by SimplicatedGamesStudio** [comment]
https://www.reddit.com/r/sonarr/comments/13od1ns/custom_list_in_sonarr/

According to the discussions here, syncing lists to *arr needs an endpoint to just send a list of tvdb Ids:
`[{ "tvdbId": "75837" }, { "tvdbId": "77847" }, { "tvdbId": "78299" }, { "tvdbId": "72756" } ]`

**Comment by IgnisDa** [comment]
Ryot doesn't have tvdb support (it's paid).

**Comment by darthShadow** [comment]
Not really, it's free for anything with less than $50k in revenue but requires attribution: https://thetvdb.com/api-information

**Comment by IgnisDa** [comment]
Will look into it.

Though TMdb works fine for me so i doubt I'll add tvdb support.

**Comment by ertugrullKara** [comment]
https://developer.themoviedb.org/reference/tv-series-external-ids

This looks promising. Sample output:
`{
  "id": 1399,
  "imdb_id": "tt0944947",
  "freebase_mid": "/m/0524b41",
  "freebase_id": "/en/game_of_thrones",
  "tvdb_id": 121361,
  "tvrage_id": 24493,
  "wikidata_id": "Q23572",
  "facebook_id": "GameOfThrones",
  "instagram_id": "gameofthrones",
  "twitter_id": "GameOfThrones"
}`

I don't know how comprehensive their data is, but should be pretty good I'm assuming.

**Comment by IgnisDa** [comment]
I have been working on the Radarr integration. I have come up with this UI:

![image](https://github.com/user-attachments/assets/272223f1-b3b8-4b99-8351-b1d155ecd687)

Every 5 minutes, all movies in these collections will be sent to Radarr.

Is this correct?

**Comment by elvis0288** [comment]
so is this already functioning?

**Comment by IgnisDa** [comment]
Hi. Yes this is working. There's some problem with arm builds and a PR is being worked on. If you have x86, then it should be fine for you.

**Comment by elvis0288** [comment]
I am using unraid

**Comment by IgnisDa** [comment]
That does not matter. What is your CPU arch? You can show me the output of `uname -ar`.

**Comment by elvis0288** [comment]
Linux FBIDataVault 6.1.99-Unraid #1 SMP PREEMPT_DYNAMIC Tue Jul 16 10:06:03 PDT 2024 x86_64 AMD Ryzen 5 5600G with Radeon Graphics AuthenticAMD GNU/Linux

**Comment by IgnisDa** [comment]
It should work fine for you then. Just run the latest ryot release.
