### ISSUE TITLE
Break Ryot services into separate images and a more streamlined release process

### ISSUE THREAD

**Issue by vnghia** [IgnisDa/ryot#544]
@IgnisDa 

From https://github.com/IgnisDa/ryot/issues/540#issuecomment-1873311294 and https://github.com/IgnisDa/ryot/issues/129#issuecomment-1586036161, I want to suggest a more streamlined release process. Right now I think we are releasing too frequently (and a lot of them have empty changelog), maybe the reason is to have the docker image built for that change immediately.

I am suggesting:
- have the docker image build for master (tag: `dev`), pr (tag: `pr-123`) and for release (tag: `1.2.3`)
- having a separate commit for release, where you should just edit the `changelog.md` and version number.

I can send a PR to adding build docker image for master, pr and release

**Comment by LnLcFlx** [comment]
Also I would suggest adding additional tags for just a major version.
For example the tags `v3`, `v3.5` and `v3.5.4` would all point to version 3.5.4.
And `v4` would then point to the latest release of `v4.*` similar to the `latest` tag.

This would prevent accidentally `docker compose pull`ing a new major version without having gone through backing up and migration first.

**Comment by IgnisDa** [comment]
This sounds like a good idea. The reason the changelog is empty because it is generated (I have described the release process in architecture.md).

I would appreciate a PR improving the structure.

**Comment by IgnisDa** [comment]
This would require a breaking release (https://github.com/IgnisDa/ryot/issues/540#issuecomment-1873377067).

**Comment by vnghia** [comment]
Since we will break the image to backend, and frontend. I guess we can reuse the Dockerfile for the backend and stick with `musl`, so there is no point to switch to `glibc` anymore.

**Comment by IgnisDa** [comment]
Wont switching to `glibc` make the backend more performant? Maybe even end up addressing https://github.com/IgnisDa/ryot/issues/440.

**Comment by vnghia** [comment]
it seems that breaking this into smaller images is the right decision because one of the reason makes our image quite large is that fact that `supervisord` need a full-blown python environment to run on.

**Comment by IgnisDa** [comment]
Yes, but that change will be made 4 months later with v5. Till then will this work with the supervisord setup we have currently?

**Comment by IgnisDa** [comment]
Notes to self:
- [ ] Look into replacing apalis-cron with dkron.

**Comment by IgnisDa** [comment]
I decided to not go forward with breaking into separate images.
