### ISSUE TITLE
[Feature Request] Sort by Rating

### ISSUE THREAD

**Issue by chunned** [IgnisDa/ryot#55]
Pretty self explanatory, it'd be nice if we could sort things in our collections by their rating. 

Absolutely love the project btw - great job

**Comment by IgnisDa** [comment]
Thank you very much. Will try to get to this.

**Comment by IgnisDa** [comment]
@chunned Here, by rating, you mean the number of stars that were given to a media item right? What if the same user has reviewed the same media multiple times? Do I just take the average?

**Comment by chunned** [comment]
Yep, that's what I mean. I hadn't considered what would happen if there were multiple reviews tbh. 

Taking the average seems reasonable. I think it would also be acceptable to take the most recent review if an item has multiple.
