### ISSUE TITLE
"You do not have any saved yet" on My Books

### ISSUE THREAD

**Issue by mycroftsnm** [IgnisDa/ryot#550]
Hello! i'm mostly interested on using ryot for tracking my readings, the ui looks great and it seems to be the project i was looking for, sadly i don't fully undestand how to add books to 'My books' (in Media-Book). 

I added different books to different collections, but when i click on Books in the summary (3 books, 900 pages) it tooks me to 'My books' which is empty. I find the experience to be quite convoluted but im pretty sure it is a bug.

Great project !

last version on docker, pi 400.

**Comment by IgnisDa** [comment]
@mycroftsnm Go the the general preferences and enable the "Display NSFW" switch and your books should appear.

I will push a fix to disable the nsfw filter by default for new users.
