### ISSUE TITLE
[FEATURE REQUEST] - Collection collaboration

### ISSUE THREAD

**Issue by TWART016** [IgnisDa/ryot#552]
Currently it is possible to change the collection from Private to Public. With public all users can see the list in read only.

It would be nice if I can share a collection to specific users. In addition add a permission to read / write / owner. With write these users can add a item to the collection to collaborate.
Owners can manage the collection e.g. share permission or remove permission to users.

**Comment by IgnisDa** [comment]
@TWART016 Do you have an example of a project/tool that does this well? I am looking for inspiration.

**Comment by TWART016** [comment]
Not directly.

1) Some type of collections (inside organisations) also exists in vaultwarden.
![image](https://github.com/IgnisDa/ryot/assets/29805669/647d8f54-31ce-4806-be26-1dcf70062860)

![image](https://github.com/IgnisDa/ryot/assets/29805669/b87e0107-2612-427b-aeab-24980c59dc03)

![image](https://github.com/IgnisDa/ryot/assets/29805669/4c626d84-ffef-4503-bb86-6575d1ce3c09)

2) Tandoor Recipe has spaces and two different roles: admin and guest
https://github.com/TandoorRecipes/recipes
![image](https://github.com/IgnisDa/ryot/assets/29805669/391f9ab7-7ca2-41a2-bc07-50f53257190f)

3) Grafana
![image](https://github.com/IgnisDa/ryot/assets/29805669/b37266ba-1c84-4493-bd25-b2f032eaabc1)

4) phpipam
![image](https://github.com/IgnisDa/ryot/assets/29805669/849d319d-e5f0-4631-b984-615f110729e5)

5) Portainer
![image](https://github.com/IgnisDa/ryot/assets/29805669/8e34d46a-0f5c-40ff-8b80-18fa021dd2c3)

6) Otherwise fileservers (e.g. Windows) or similar to that.

**Comment by IgnisDa** [comment]
Released as part of [Ryot Pro](https://ryot.io).
