### ISSUE TITLE
notification configuration

### ISSUE THREAD

**Issue by TWART016** [IgnisDa/ryot#553]
Move Notifications tab inside `Settings / Preferences / Tab: Notification` to `Settings / Notification` to have a more streamline configuration
![image](https://github.com/IgnisDa/ryot/assets/29805669/7dddb098-820f-4832-b3cc-cde1e0dc1d5e)

Is  could be integrated above the platforms
![image](https://github.com/IgnisDa/ryot/assets/29805669/7d950bdf-b75c-4fb8-996a-65c66e2e5389)

**Comment by IgnisDa** [comment]
The first screenshot is notifications preferences and the second one is settings. They are not the same.

**Comment by TWART016** [comment]
Ok thanks for your feedback. Both is notification so I thought it would make sense.
