### ISSUE TITLE
iOS icon PWA

### ISSUE THREAD

**Issue by TWART016** [IgnisDa/ryot#554]
I added the website as an PWA to my home screen on iOS. The icon is just black just for less than a second while starting or closing the app the icon is correct

![image](https://github.com/IgnisDa/ryot/assets/29805669/12010823-fb73-423c-81c3-a0e1cee7e34b)

![image](https://github.com/IgnisDa/ryot/assets/29805669/d8578a68-29a3-4915-96f2-37a83f89923b)

**Comment by IgnisDa** [comment]
I can't fix this since I do not own an iOS device. If someone want to fix this, feel free to ping me here and I will re-open it.

**Comment by TWART016** [comment]
Is the icon transparent? Maybe this is the problem.
https://stackoverflow.com/questions/22858501/ios-app-icon-with-transparent-background-showing-black-background-on-device
https://stackoverflow.com/questions/26014461/black-border-on-my-ios-icon

**Comment by IgnisDa** [comment]
Yep it's transparent.
