### ISSUE TITLE
anime data from tmdb (as an addition to anlist/mal)

### ISSUE THREAD

**Issue by user9931** [IgnisDa/ryot#555]
trying the app and stuck with anime, its strange that its not possible to view or mark episodes, no info available. In the already closed issues found mentions that anlist dont provide episode data (in api?). Ok, but tmdb does if just use "shows" instead of "anime". Please add an option to add data from tmdb in "anime" tab

**Comment by IgnisDa** [comment]
> Please add an option to add data from tmdb in "anime" tab

TMDb does not have the concept of anime. If you want, you can just search for the anime in the shows tab (which is what I do since I watch very common anime which have complete data on tmdb, eg death note).
