### ISSUE TITLE
Track "works" not "books" using Open Library

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#556]
In #369 I described the disadvantages of tracking single editions of books (2nd edition, translations etc.) rather than the "work" (title, author) itself.

I did a little research and apparently [openlibrary.org does this distinction as well](https://openlibrary.org/dev/docs/api/books):
> A Work is a logical collection of similar Editions. "Fantastic Mr. Fox" could be a Work which contains a Spanish translation edition, or perhaps a 2nd edition which has an additional chapter or corrections. Work metadata will include general umbrella information about a book, whereas an Edition will have a publisher, an ISBN, a book-jacket, and other specific information. 

I suggest that Ryot should track "works" not "books" in the sense of specific ISBNs.
Searching for a book title should then only yield multiple results if they are different works and not merely different editions of the same work.

Alternatively one could also do both or a sort of mixture.
For example one could have a "Works vs Books" switch next to the API selection in the book search tab.
Then, in the rest of the UI books should only be represented as works and when clicking on one there could be additional info on what specific editions you read...

**Comment by IgnisDa** [comment]
Closing, since there is nothing Ryot can do about the mess that is Openlibrary.
