### ISSUE TITLE
S3 file storage not working after setting variables

### ISSUE THREAD

**Issue by mycroftsnm** [IgnisDa/ryot#559]
Hello, i find multiple books wich are not loaded in the google books database so i would like to manually add them, i followed the documentation and setted the variables but i still receiving the same `Please set the S3 variables required to enable file uploading` message when creating a custom media

I never used s3 storage before so im very noob about this, i used minio in a docker container, i tested from a windows pc with the minio-client and it seems to be working. 

These are my variables in the compose file:
`

      - S3_URL=http://192.168.100.220:9000/
      - S3_SECRET_ACCESS_KEY=userpass
      - S3_ACCESS_KEY_ID=username
      - S3_BUCKET_NAME=ryot
`
i checked in the container (run -it /bin/bash) and the variables are all setted, but could not found any log related to the s3 storage and it simply not working, im probably missing something , maybe the url syntax? i dont know. 
Thanks in advance :)

**Comment by IgnisDa** [comment]
https://ignisda.github.io/ryot/guides/exporting.html#one-time-file-storage

**Comment by mycroftsnm** [comment]
Thanks, indeed the problem was the variables names, forget to add the `FILE_STORAGE_` part before every variable. its working now :)
