### ISSUE TITLE
Custom media images not working

### ISSUE THREAD

**Issue by mycroftsnm** [IgnisDa/ryot#560]
Im trying to add a custom media (book) and im struggling with the 'specifics' part, the **Graphql endpoint** hyperlink returns 404 in my instance but also in the demo one _https://ryot.fly.dev/graphql_ , is this deprecated?
Im interested on setting the number of pages of the book so i can track progress correctly. Also when i upload an image it works (s3 configured ok) but after creating the custom media, the image never shows

**Comment by IgnisDa** [comment]
its https://ryot.fly.dev/backend/graphql, forgot to update.

**Comment by IgnisDa** [comment]
> Also when i upload an image it works (s3 configured ok) but after creating the custom media, the image never shows

Can you run the `mediaDetails` gql query and see if the images are present as expected?

**Comment by IgnisDa** [comment]
https://github.com/IgnisDa/ryot/blob/main/libs/graphql/src/backend/queries/MediaAdditionalDetails.gql this one

**Comment by mycroftsnm** [comment]
Sorry i take some time to understand how to do it, clearly the image/s are not present, im sure the minio/s3-storage credentials are good because it wont allow me to click on upload image if they don't work (i tested it), and im pretty sure the user used has permissions to upload files because it works from minio-client so is not a permissions problem. 
let me know if i can do something to help debugging!

`
{
  "data": {
    "mediaDetails": {
      "lot": "BOOK",
      "creators": [
        {
          "name": "Creator",
          "items": [
            {
              "id": null,
              "name": "test-author",
              "image": null,
              "character": null
            }
          ]
        }
      ],
      "assets": {
        "images": [],
        "videos": []
      },
      "animeSpecifics": null,
      "audioBookSpecifics": null,
      "bookSpecifics": {
        "pages": 666
      },
      "movieSpecifics": null,
      "mangaSpecifics": null,
      "podcastSpecifics": null,
      "showSpecifics": null,
      "visualNovelSpecifics": null,
      "videoGameSpecifics": null
    }
  }
}
`

**Comment by mycroftsnm** [comment]
Maybe this is useful, the first 4 lines are from uploading a file via minio-client, and the last line appears when i try to create a custom media with some images 

![imagen](https://github.com/IgnisDa/ryot/assets/58491232/7cc3216c-e3dd-41ca-b802-8e85104eb90a)

**Comment by IgnisDa** [comment]
Where have the images been uploaded in the minio instance?

**Comment by mycroftsnm** [comment]
> Where have the images been uploaded in the minio instance?

No

**Comment by IgnisDa** [comment]
Alright I'll take a look at it later.

**Comment by IgnisDa** [comment]
@mycroftsnm Can you screen record and upload the video of you doing this? It is working fine for my own instance as well as the demo one.

**Comment by mycroftsnm** [comment]
I could screen record later if you want, but its simply that when i upload a image (or video) i never receive the notification of _**Success! uploaded one file**_
i tried setting the playground of minio (https://play.min.io) and it is working on my ryot instance, i receive the notification and the image appears, so probably the problem is on my side , something with my minio instance, and so the issue should be closed.

Just one last question, could be a problem the fact that im not using https? the minio and ryot containers are in the same docker network and im setting `FILE_STORAGE_S3_URL=http://minio:9000`, from a third container (also in the same docker network ) running minio-client i can upload files using that url so the docker network  seems to be working

Thanks for all

**Comment by IgnisDa** [comment]
What are you setting the ACCESS_KEY and SECRET_KEY

**Comment by mycroftsnm** [comment]
> What are you setting the ACCESS_KEY and SECRET_KEY?

 To the access key pair that i created from the minio web gui (i did the same when i tried the play.min.io instance)

**Comment by IgnisDa** [comment]
Open the network tab in the browser dev tools and then try to upload an image. Show me the response.

**Comment by mycroftsnm** [comment]
![imagen](https://github.com/IgnisDa/ryot/assets/58491232/1840fce9-a72a-4667-9af1-d8af7f1b12ad)

192.168.100.220 is the ip of the raspberry where im hosting everything via docker, ryot is on port 8600

192.168.16.3 is the ip of my minio instance inside the docker network 
192.168.16.2 is the ip of my ryot instance inside that same network
i have setted `  FILE_STORAGE_S3_URL=http://192.168.16.3:9000` in the compose file of ryot

the pc from with im taking the screenshot is on my lan (192.168.100.0)

I dont fully understand whats happening but it seems like the browser should be available to reach the minio instance and since the ip is the one from the docker network it cant? 

btw i can access the minio web gui in 192.168.100.220:9201

**Comment by IgnisDa** [comment]
I think the problem is that the minio instance is not accessible to the frontend.

The images are uploading directly to S3 without them going through the backend. So please make sure to expose minio to the frontend.

**Comment by mycroftsnm** [comment]
i installed mc (minio-client) inside the docker container of ryot frontend, and :


`
me@raspi: /docker/ryot $ docker exec -it ryot /bin/bash
ryot@5e2a30faad7b: $ curl https://dl.min.io/client/mc/release/linux-arm64/mc \
  --create-dirs \
  -o  /minio-binaries/mc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.3M  100 24.3M    0     0   210k      0  0:01:58  0:01:58 --:--:-- 3714k
ryot@5e2a30faad7b: $ chmod +x $HOME/minio-binaries/mc
export PATH=$PATH:$HOME/minio-binaries/


ryot@5e2a30faad7b:$ mc alias set ryot http://minio:9000 username password
Added ryot successfully.
ryot@5e2a30faad7b:$ touch a
ryot@5e2a30faad7b:$ mc cp a ryot/test
 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━
ryot@5e2a30faad7b:~$

`

the file 'a' uploads without issue and i can see it from the minio webgui , inside the bucket test.
now the same container with the same url and the same credentials cannot upload to the same bucket from the ryot web gui

**Comment by IgnisDa** [comment]
As i said, the upload will work from inside the containe. But since the file upload is happening from the frontend (the browser), your minio client test is not relevant.

You'll have to expose your minio instance to the internet for it to work.

The CORs you configured is for the backend so again, it won't be relevant to file uploads (which effectively doesn't communicate with the backend at all).

**Comment by mycroftsnm** [comment]
> You'll have to expose your minio instance to the internet for it to work.

Done and working now, thanks. 

Just for being curious: this is a ryot limitation? it will be possible to get the browser uploading things to minio via the internal docker network by changing the ryot code or it is plain impossible?
Or maybe explore the possibility of ryot having its own storage. I feel like is a pretty complicated setup (extra container and exposed to internet) to just get custom images loaded

will keep educating myself in this topic and hope i can contribute soon.

Feel free to close the issue and thanks for all the help!

**Comment by IgnisDa** [comment]
I use an s3 compatible storage primarily for the custom metadata capabilities. Ryot could have it's own file storage solution but I didn't feel like re-implementing that feature.

Glad to know you got it working!

**Comment by IgnisDa** [comment]
Hey @mycroftsnm! What changes did you have to make to get Ryot running on Raspberry Pi? Someone on reddit asked me.

**Comment by mycroftsnm** [comment]
> Hey @mycroftsnm! What changes did you have to make to get Ryot running on Raspberry Pi? Someone on reddit asked me.

To get ryot itself working? no changes needed, i just followed the docker compose file u provided in the docs and changed the postgres credentials , nothing fancy. 

btw its a raspberry pi 400 running RaspberryPi OS (debian 11)  64 bit

**Comment by JakubCerven** [comment]
> As i said, the upload will work from inside the containe. But since the file upload is happening from the frontend (the browser), your minio client test is not relevant.
> 
> You'll have to expose your minio instance to the internet for it to work.
> 
> The CORs you configured is for the backend so again, it won't be relevant to file uploads (which effectively doesn't communicate with the backend at all).

Is there any possible workaround for this other than exposing minio outside of my network?
