### ISSUE TITLE
Rewatching a series

### ISSUE THREAD

**Issue by DrSpaldo** [IgnisDa/ryot#561]
Is there a way to re-watch a TV series for example and retain the different watched dates?

**Comment by IgnisDa** [comment]
Just start marking the series as watched again, by choosing it from the seasons tab.

**Comment by DrSpaldo** [comment]
> Just start marking the series as watched again, by choosing it from the seasons tab.

Thanks for the reply @IgnisDa. Will that then allow it to unwatched again in Plex for example?

**Comment by IgnisDa** [comment]
The Plex integration will just tell Ryot that you're watching a movie or show. It does not support anything related to "unwatching".
