### ISSUE TITLE
Strong import broken?

### ISSUE THREAD

**Issue by rbritton** [IgnisDa/ryot#570]
I am having difficulty importing data from Strong.

I've followed the directions [here](https://ignisda.github.io/ryot/importing.html#strong-app) and [here](https://gist.github.com/IgnisDa/c21c28dd83571ca07f1a7a824b5e8139?permalink_comment_id=4725066), but I'm thinking they may not have been updated to reflect recent changes to Ryot.

By searching through the issue history, I was able to figure out that the GraphQL had moved from `/graphql` to `/backend/graphql`, but following the instructions in the Gist just returns the error "User was not logged in" (I am logged in to the front end). 

Similarly, I have tried to just use the import UI alone and see one of these two errors in the Docker log:

```
[backend] called `Result::unwrap()` on an `Err` value: Error { message: "No such file or directory (os error 2)", extensions: None }
....
[backend] called `Result::unwrap()` on an `Err` value: Error(Deserialize { pos: Some(Position { byte: 104, line: 2, record: 1 }), err: DeserializeError { field: None, kind: Message("missing field `Date`") } })
```

Any suggestions? It's the current version of Strong and of Ryot.

**Comment by rbritton** [comment]
I've managed to eliminate the errors by creating a mapping explicitly tailored to only my listed exercises, but nothing ever seems to actually import anything. The server responds to an import UI submission with `{"status":"success","generateAuthToken":false}`, but no record of the import appears in the history and no workout data shows up.

**Comment by IgnisDa** [comment]
@rbritton Can you send me your strong export? I suspect your file is different. Make sure the android application is updated to the latest version too.

**Comment by rbritton** [comment]
> @rbritton Can you send me your strong export? I suspect your file is different. Make sure the android application is updated to the latest version too.

[strong-single.csv](https://github.com/IgnisDa/ryot/files/13930032/strong-single.csv)

Here's a single-workout CSV file that replicates my problem. This is from the iOS version of Strong (5.15.23) and the current `latest` Ryot docker image. Does column ordering matter? I do notice they're different [here](https://github.com/IgnisDa/ryot/blob/main/apps/backend/src/importer/strong_app.rs#L21-L38), but I'm not overly familiar with Rust yet.

**Comment by IgnisDa** [comment]
The column ordering should not matter but your column names are different. Maybe because of iOS vs Android (I use the android app, v2.7.9).

It would be better if you could send me the entire export so that I can account for all edge cases. If you don't want to attach it here, you can email it to me (ID is in my GH profile).

**Comment by rbritton** [comment]
[strong.csv](https://github.com/IgnisDa/ryot/files/13930108/strong.csv)

Here it is -- nothing sensitive in there.

**Comment by IgnisDa** [comment]
Thanks, I will push a fix with #571.

**Comment by IgnisDa** [comment]
Hi @rbritton! Would it be possible for you to resend your strong export? I noticed they have changed their export format on Android and want to make sure that iPhone exports are working fine too.

**Comment by stusemple** [comment]
[strong.csv](https://github.com/user-attachments/files/18284962/strong.csv)
Hi @IgnisDa, I am having the same issue with Strong imports from iOS. Ryot recognises the import, but doesn’t get past 0%. I’ve attached my strong export data (exported yesterday)

**Comment by IgnisDa** [comment]
@stusemple are you on the latest version of the strong app? Your export data seems quite outdated and it seems to have a lot of difference from the android export format.

**Comment by stusemple** [comment]
@IgnisDa yes I just checked and the Strong app is up to date. The data is
from a while ago, I was actually using Hevy recently, and managed to import
all my data from that app without any problems. But the app is up to date
and the export date is yesterday.

**Comment by IgnisDa** [comment]
Btw ryot does have an option to import from hevy. I would suggest using that since the import data is more consistent on that app.
