### ISSUE TITLE
Unclear Error Message for Short Passwords on First-Time User Registration

### ISSUE THREAD

**Issue by wowitsmartin** [IgnisDa/ryot#574]
**Description:**
When attempting to register a new user, if the provided password is shorter than the required minimum length, the server responds with a 400 Bad Request error. However, the error message does not clearly specify that the issue is related to the password length, leading to potential confusion for the user.

**Steps to Reproduce:**

1. Navigate to the user registration page via "Create a new account" button on the main page.
2. Fill in the user details, using a short password.
3. Submit the registration form.

**Expected Behaviour:**
The application should return a clear error message indicating that the password is too short and specifying the minimum required length.

**Actual Behavior:**
The application returns a 400 Bad Request error with no clear indication that the error is due to the short password.

**Possible Solution:**
Implement a more descriptive error message that specifically mentions the inadequacy of the password length.

**Additional Information:**

- This issue was encountered on 14/01/2024.
- Application version: 4.1.2, running from the official docker image.

**Comment by IgnisDa** [comment]
Nice catch, thanks!
