### ISSUE TITLE
Book searches API enhancements

### ISSUE THREAD

**Issue by StoffelCPR** [IgnisDa/ryot#575]
I'm trying to add a book I own but it's a paperback, so I can't find it on Google Books.

https://github.com/IgnisDa/ryot/blob/7cb9669630c2a1fd5c3f7355aa2d21647616b1c6/apps/backend/src/providers/google_books.rs#L112C1-L112C38 

This part is the problem.. The provider only searches for type 'book'. It'd be a nice enhancement if I could either search for more book types or generalize the search.

One option would be to add a dropdown allowing to select Paperback 
https://www.google.de/books/edition/The_Atlas_Paradox/5abvzgEACAAJ?hl=en <- example book.

In addition it'd be nice to enable ISBN searches for google books

**Comment by IgnisDa** [comment]
I don't want to add the dropdown thing since it would require me to implement filters support for other providers too.

Would it work if I added a [configuration variable](https://ignisda.github.io/ryot/configuration) to pass the raw query to google books provider?

**Comment by StoffelCPR** [comment]
Understandable.. Sure a configuration variable would work..

Wouldn't it be possible to default to searching for all entities that are essentially 'books'? Not sure about the google books api tbh.

The ISBN search thing for google books would be helpful though

**Comment by IgnisDa** [comment]
> Wouldn't it be possible to default to searching for all entities that are essentially 'books'? Not sure about the google books api tbh.

I didn't understand what you mean by thism

**Comment by IgnisDa** [comment]
Released `v4.1.14`. Set env variable `BOOKS_GOOGLE_BOOKS_PASS_RAW_QUERY=true`.
