### ISSUE TITLE
App feels unresponsive and slow

### ISSUE THREAD

**Issue by StoffelCPR** [IgnisDa/ryot#579]
So after some use I noticed that even when I'm clicking on `Mark as seen` for shows and movies and even though I get the toast saying the app did mark it as seen it doesn't show.. Sometimes I have to add it to collections or wait hours before it registers properly. My question is why? Since it's self-hosted we don't need to slow down traffic or give sync intervals ( or at least make these intervals configurable so we don't have to wait hours for an action to happen on our own servers ).

The very least would be to document the cycles and functionalities of the app:

- What's needed to mark something as seen
- Which exact time frames are configured for things
- e.g. Not being able to mark a movie or smth. in progress when I marked it as complete in the last few hours, why and write it down somewhere so people know about it.
- Maybe change toasts to actually say what happens 
  - Don't show an `Everything worked we saved your input` toast when the input hasn't been saved yet
  - `Job has been deployed and could take a bit` is a good toast. That one helps knowing it will still happen
  - Add an event log somewhere so I can debug what my app did -> Did the app say it was successful, did it deploy a job, did that job finish and when!?

**Comment by StoffelCPR** [comment]
FYI; I think people are willing to help you more with your issues.. If possible maybe structure the issues you went through so people know open topics that are open for strangers to work on. Define your thoughts and wishes ( Still your app; don't wanna ruin your project for you ). I'd like to contribute but haven't had the time yet to dive through Issues and search for things I could take off your hands.

**Comment by IgnisDa** [comment]
I am not sure what you mean by "registers properly".

You are welcome to contribute! People don't do that often enough for me to spend time structuring issues etc. If you see something you'd like to work on, please ping me there and I'll help however needed.

**Comment by StoffelCPR** [comment]
Okey so It works most of the time.

I just searched for Percy Jacksons Lightning thief and clicked on `Mark as watch` ( which has a typo doesn't it? `Mark as watched` would be correct?? ) And it worked like a charm.. Clicked it, got redirected into the movie page and had the `History` tab there with my move marked as `Completed` I've then tried the second percy Jackson and had problems again.

I now tried it with the Harry Potter movie and recorded it -> Is it possible, that I can't mark things as completed during the cooldown period of any movie as in -> Does marking `Percy Jackson ` as `completed` I need to wait for `2 hours ( default setting` before marking `Harry Potter` as `completed`? 

Video uploaded to my youtube. 

[Bug video on Youtube](https://youtu.be/suBYE_eIBkk)

P.S. please give me a ping when you watched it and have an idea of what I mean. I'd like to take the link out of the post for privacy reasons.

I also were able to reproduce this on your demo instance I think.

As for the issue strcuturing. I understand. I, like others probably, need the time to get through your code and understand it well enough and then go through tickets and see which ones we can help in.. It take a lot of time. I'd like to help though.

**Comment by IgnisDa** [comment]
I have watched the video. You can remove it.

Let me see if I can reproduce it.

> which has a typo doesn't it? Mark as watched would be correct?? 

Yeah the handling code for this is pretty complicated and the typo does not bother me so I have left it as it is.

**Comment by IgnisDa** [comment]
Okay I can reproduce it. I will see what is causing it.

**Comment by StoffelCPR** [comment]
Yeah. Didn't feel like opening up an Issue for that typo.. If you're aware of it that's fine.. If you want I'll open an Issue and try to be descriptive. If you're lucky someone picks it up and helps.

Thanks.

**Comment by IgnisDa** [comment]
Someone opened a PR for it long ago https://github.com/IgnisDa/ryot/pull/208 but as I said the code is not very simple https://github.com/IgnisDa/ryot/pull/208/

**Comment by IgnisDa** [comment]
Notes to self:

THe reason this issue is happenning is because all application jobs are under one single queue which are throttled to 5 jobs per second. When user marks something as watched, it deploys a background job which get added to the queue. Meanwhile the `commitMedia` has already deployed a lot of jobs for `assosiatePersonWithMetadata` jobs so the `updateProgress` job gets throttled.

Fix is to break the essential background jobs to a separate queue and remove throttling from them. This will likely introduce a lot of duplicated code. Find a way to abstract this if possible.
