### ISSUE TITLE
Track new movies/series of selected actors

### ISSUE THREAD

**Issue by saschabrockel** [IgnisDa/ryot#580]
Hey there :)

I come from https://www.reddit.com/r/selfhosted/comments/198pmgy/comment/ki9b6z3/?context=3 and I would be very happy to have this feature because it's something that is not available yet. No matter if self-hosted or even a service on the internet.

For example, I can name flickfocus.com. They have a functionality to follow actors and have a feed where new stuff is listed but there is no chance of getting a notification, so I have to actively click on the page which leads to more manual work.

**Comment by IgnisDa** [comment]
Cool will keep this mind. I wanted to add this feature but was putting it off since it will be a bit of a work.

**Comment by saschabrockel** [comment]
Don't worry. No need to hurry. But if it will be done, I will create a video showing and promoting it!

**Comment by IgnisDa** [comment]
@saschabrockel Does this look good?
![image](https://github.com/IgnisDa/ryot/assets/60938164/aa485cd8-d45b-4da2-bbbb-15560f9ee8a5)

**Comment by saschabrockel** [comment]
@IgnisDa looks awesome! Is it possible to only get notifications on specific roles like only when he or she is actor in that movie? Because honestly I don't think neither me nor the most people care if the person is executive producer 😂

**Comment by IgnisDa** [comment]
Thats great!

> Is it possible to only get notifications on specific roles

Please create another issue for that. This PR has already become to big.
