### ISSUE TITLE
TMDB Show episodes not synced

### ISSUE THREAD

**Issue by mrdev023** [IgnisDa/ryot#585]
When i add show / anime, episodes list is not synced.

For example, https://www.themoviedb.org/tv/220150/season/1 i get only 
![image](https://github.com/IgnisDa/ryot/assets/11292703/b2d4a198-4939-4d53-a115-fd95bd46b830)

Version: [v4.1.4](https://github.com/ignisda/ryot/releases/v4.1.4)

**Comment by IgnisDa** [comment]
Ryot first downloads very little information about a media so that it can be shown on the UI soon. It downloads the rest of it in the background.

Did the seasons for this show not update after some time?

**Comment by IgnisDa** [comment]
Closing since it works for the public instance and mine too. You can also use the "Update metadata" under "More actions" to force a sync.

Feel free to ping me here if it still does not work.

**Comment by mrdev023** [comment]
It make nothing in my side

**Comment by IgnisDa** [comment]
Please provide logs for the Ryot container.

**Comment by mrdev023** [comment]
> er.

Now i can't access to interface ....
https://github.com/IgnisDa/ryot/issues/590

**Comment by mrdev023** [comment]
It seem to be fixed.

It don't know why now is synced after some weeks ....

After migration to 4.1.5, with problem in login, i remove all browser data and now i see episodes.
Maybe sync is processed during migration

Thx for you reply
