### ISSUE TITLE
Make deleting media items more obvious

### ISSUE THREAD

**Issue by oderyn** [IgnisDa/ryot#587]
Deleting items was very confusing for me.

After some digging, I found this issue, which explains the process for deleting media items.
https://github.com/IgnisDa/ryot/issues/102

I think I get it, now. It would be great to have an actual delete button in the More Actions menu followed by a confirmation.

![Delete](https://github.com/IgnisDa/ryot/assets/142800967/4f952b34-624a-4cbb-bba0-71392c880305)

**Comment by IgnisDa** [comment]
I mentioned that (probably in a different issue) that i won't add this button since the UI is already very complicated.

The cron job to delete media runs every 12 hours. You can set `SCHEDULER_USER_CLEANUP_EVERY=1` to change it to every hour if you want to speed up the job.
