### ISSUE TITLE
Add media to collection from search results page

### ISSUE THREAD

**Issue by oderyn** [IgnisDa/ryot#588]
- [ ] Add media from search results page
- [ ] Add media to multiple collections simultaneously

This will make it easier to keep collections organized as you are adding items. Currently, when you add an item, it takes 6 clicks to add the item to a collection and then 3 clicks to get back to the search page and clear out the current search term from the search field. 

The approach shown below would reduce that to 3 clicks to add an item to a collection. You could collect additional books from your search results very quickly. And restarting your search is now on the same page.

![Add to Collection](https://github.com/IgnisDa/ryot/assets/142800967/8e9aee6d-a994-4cd3-a5d7-004f9ac1d2a7)

**Comment by IgnisDa** [comment]
Pretty good idea. Thanks! Will look into a better UI for this.

**Comment by oderyn** [comment]
Happy to help with the UI. I did this as a way to not mess with the existing UI components. If you'd like the help, just let me know what you're thinking and I can mock it up for you.

**Comment by IgnisDa** [comment]
I'm open to all idea. Haven't gotten around to thinking what I want for this. Do you have anything particular in mind?
