### ISSUE TITLE
[Feature Request] Mark multiple seasons (for shows) and episodes (for podcasts) as seen

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [IgnisDa/ryot#59]
When a show has multiple seasons, it is quite cumbersome to mark each one as seen manually. Add the ability to select multiple seasons at once to mark as read.

**Comment by IgnisDa** [comment]
Good idea. Will work on this.

**Comment by IgnisDa** [comment]
I am marking this as wontfix since the code to mark item as seen is pretty convoluted and I don't think changing it makes sense to save a few clicks.
