### ISSUE TITLE
Allow export with following source

### ISSUE THREAD

**Issue by mrdev023** [IgnisDa/ryot#591]
Add possibility to export data for any source. Like in import.

**Comment by IgnisDa** [comment]
I do not understand what you mean.

**Comment by mrdev023** [comment]
![image](https://github.com/IgnisDa/ryot/assets/11292703/ea266b03-d9fc-4320-8c01-df6c7fe5345a)

I feature like this but for export. I don't know if it's possible.
It can be useful if we want test another media tracker.

**Comment by IgnisDa** [comment]
I do not even understand what feature you want.

Do you want Ryot to provide an API that can be used by other software (like mediatracker) to import media?

**Comment by mrdev023** [comment]
Something like Movary export.

![image](https://github.com/IgnisDa/ryot/assets/11292703/bd568cd7-4a76-4128-8805-1a84332be41b)

Import csv directly from Ryot export.


It's possible to import also Ryot format ? If i encountered error during future migration and i can't keep current state of DB. It can be useful to had fallback to export in generic format et reimport in fresh install of Ryot. It's just a question, i don't know if a feature like this already exist.

**Comment by IgnisDa** [comment]
Ryot's data export is too complainted to be exported as CSV.

And yes, you can import the Ryot export at any point of time using the "Generic Json" option.

**Comment by mrdev023** [comment]
Okay i close the issue ^^
