### ISSUE TITLE
Application error with specific movie search

### ISSUE THREAD

**Issue by nickthemenace** [IgnisDa/ryot#596]
I get an application error when I search for either "sorority r" or "sorority c" in the add movie section. Other letters after "sorority" don't seem to cause this, and no other search I've done seems to trigger it either. 
Repro:
- Go to the demo instance of ryot ( https://ryot.fly.dev )
- On the left hand menu click Media -> Movie
- Change to the search tab
- Start typing sorority row

Alternatively just go directly to this url: https://ryot.fly.dev/media/search/movie?query=sorority+ro
Please don't judge the questionable movie choice 😅

**Comment by IgnisDa** [comment]
Can reproduce. Will fix.
