### ISSUE TITLE
[FEATURE REQUEST] - Better manga tracking

### ISSUE THREAD

**Issue by Robin-Sch** [IgnisDa/ryot#609]
The current tracking of manga is "lacking", as storing % read isn't the correct/best way to track manga.

For example, suppose I'm reading a manga which is still releasing with (as of right now) 10 chapters, and so far I've read 2 chapters. Right now, I'd manually have to store 2/10 = 20%. But now imagine a new chapter is released tomorrow, my actual percentage would now be 2/11, so the stored % isn't correct anymore.

For manga which is not releasing anymore (there won't be more chapters), you can input an amount of chapters and it will automatically convert this to a percentage. However, it would be way better to track you progress in terms of chapters than percentage.

What I propose is something similar to shows. You would track when (at which date), you've read chapter 1. Then when you've read a new chapter you would add this again to Ryot, similar to shows.
However, with shows there is metadata available about the actual episode. This might? not be the case for manga, but imo it won't be a problem. You can just store the number of the chapter(s) as a number (just like percentage) and a date with it.

Also, I'm not sure if you it's done on purpose but whenever I set a new percentage it overwrites the old one. I'd like to see the history at which date I read which chapter (just like with shows), and not that it just keeps track of how many chapters I've read in total.

**Comment by IgnisDa** [comment]
@Robin-Sch I have decided to go with tracking like shows. Each chapter would be one entry. I have a couple of questions:

1. would the same happen for anime, ie, each episode be one seen entry?
2. what about previous entries? ideally if there are seen items for a manga, that one should get deleted and then a new entries be added for each chapter. Does this sound right?

**Comment by Robin-Sch** [comment]
1. For anime it's exactly the same as a show, so yes.
2. You mean after you've re-read a chapter? Uhm... I'm not so sure of this actually. People might read a chapter (or a compete) manga twice for whatever reason and they want to track both. But I'm not so sure. How does this happen with shows, can you view one episode multiple times?

Also I just realised but for some manga they like to publish some "extra's" in between chapters (like a "behind the scence" ish). Most of the times they get a chapter number with one decimal, for example 5.5. (Meaning after chapter 5, but before chapter 6). These are seen as completely new chapters, but their numbering scene messing things up.
So I guess being able to store chapter numbers with one decimal would be nice, but the majority is going to be just a full integer.

**Comment by IgnisDa** [comment]
> can you view one episode multiple times

Yes

> some manga they like to publish some "extra's"

So it would work if I allowed the chapter number to be a decimal?

**Comment by Robin-Sch** [comment]
So then it'd be the best if it would be similar/the same as shows, that you can read a chapter multiple times.
And allowing a chapter number to be a decimal should work

**Comment by IgnisDa** [comment]
@Robin-Sch 

> what about previous entries? ideally if there are seen items for a manga, that one should get deleted and then a new entries be added for each chapter. Does this sound right?

What about previously marked as read anime/manga that do not have num chapters/episodes information associated with them? How would entries be created for them?

**Comment by Robin-Sch** [comment]
Yeah that could work, or maybe -1 ?

**Comment by IgnisDa** [comment]
Ehhh, -1 does not convey any meaning on the database level. I will just stick with `null`.

Thanks for the help.

**Comment by IgnisDa** [comment]
@Robin-Sch This was released with `v4.2.0`. Please try it out and let me know if the UI feels intutive enough.

**Comment by Robin-Sch** [comment]
I have just taken a look at it, and it seems like I can only mark the whole manga is finished/read, but not individual chapters.

**Comment by IgnisDa** [comment]
Which manga?

**Comment by IgnisDa** [comment]
![Screenshot_20240207-234732_Firefox](https://github.com/IgnisDa/ryot/assets/60938164/f3bb719a-24f8-4c48-aa34-c71e037a21a1)

Here is what updating One Piece looks like. Does this not work for your use case?

**Comment by Robin-Sch** [comment]
It does not work for me like this.

actions -> update progress -> add to read history:
![image](https://github.com/IgnisDa/ryot/assets/46354497/e59efa0e-d877-4894-ada7-bc26a1f681a4)

history -> edit:
![image](https://github.com/IgnisDa/ryot/assets/46354497/9f1ad8db-73eb-4ae2-b877-ff4ce3ce64cd)

Version: v4.2.3

**Comment by IgnisDa** [comment]
This is under the manga section, right?

**Comment by Robin-Sch** [comment]
yes it is under manga, not anime or something else

**Comment by Robin-Sch** [comment]
Even after updating the metadata (and waiting some time) it does not work

**Comment by IgnisDa** [comment]
Okay I will push a change with https://github.com/IgnisDa/ryot/pull/634 which might fix it.

**Comment by IgnisDa** [comment]
@Robin-Sch Please upgrade to the latest version and see if the issue still persists.

**Comment by Alzarath** [comment]
Tested on Ryot 4.2.4 with two manga from Anilist—a finished manga and an ongoing manga.

I have clicked "Update metadata" for all scenarios.

Attempting to set progress on a manga with existing progress from before 4.2 only allows me to set the progress to a percentage.

After clearing a manga's history, I no longer have any options under "Update progress" besides "Add to read history", even when it's in the In Progress collection.

Clicking "Add to read history", I can specify a chapter. It will mark that chapter as "Completed" in the history and remove the manga from the In Progress category entirely despite the chapter not being the final chapter in a complete series.

Briefly trying a MAL-sourced manga, I got similar results.

Additional comments:

When I read "Add to read history", I imagine it's going to mark the entire manga as read. The "Set Progress" label was more clear to me. I imagine it's meant to have all of the options from before, anyways.

It would be useful to be able to "Mark all *unread* chapters before this as watched".

**Comment by Robin-Sch** [comment]
I just updated my instance and agree with @Alzarath 's points above. Especially with the last part, I think "Mark all chapters before this as ~~watched~~ read" should be omitted completely, and replaced with "Mark all unread chapters before this one". This could work in a way that it just skips duplicated entries, and should be good.

**Comment by IgnisDa** [comment]
I won't be able to provide a "Mark all chapters before this as read" provide button due to how the action handler is written.

**Comment by Robin-Sch** [comment]
So if I read chapter 1-5 on the 1st of January, 6-10 on the 2nd and so on until chapter 100. Adding this manga to my history would require 100 individual steps... Now multiply this by multiple manga or manga with even more chapters and have fun adding all of it I guess.

**Comment by IgnisDa** [comment]
> Also, doesn't the same thing hold for shows?

Yes it does.

The concerns you raise are totally valid. I just don't have a lot of motivation to work on fixing this 😅.

**Comment by IgnisDa** [comment]
@Robin-Sch Wanted to ask: are volumes and chapters while tracking manga mutually exclusive? That is, if you are tracking progress on manga, is there ever a valid use case where you would store both the chapter and volume number?

**Comment by Robin-Sch** [comment]
Kinda... They are related. See chapter like chapter and volume as book (in a serie with multiple books), where the chapters only increment.

Like harry potter 1: chapter 1-20
Harry potter 2: chapter 21-60
Etc..

Imo, tracking the chapters (and not volumes) is how I always do it. However, when reading physical manga (where one volume is one physical book), it might be preferred to track via volume numbers. But in the latter, you can also track by chapters. With non-physical manga everything goes by chapters and volumes don't (really) matter.

**Comment by IgnisDa** [comment]
So can I safely assume that a user at any point of time will only want to input either chapter or volume and not both? I am asking in the context of manga, not books. While reading books, I would always track by page numbers/percentages.

**Comment by Robin-Sch** [comment]
The books was an example how chapters and volumes are related.

I mean.... Theoretically yes, but you never really know. Some other manga trackers allow you to input both, but for me personally only chapters is fine.

**Comment by IgnisDa** [comment]
I will go with the mutually exclusive model, and if someone opens an issue, then we will see.

**Comment by Alzarath** [comment]
It makes sense to me to make them mutually exclusive. I have also only tracked using chapters.

**Comment by IgnisDa** [comment]
@Alzarath @Robin-Sch released a new version with the fix. Please lmk if you find any problems.
