### ISSUE TITLE
[Login] Login Failing - Docker

### ISSUE THREAD

**Issue by Kornster** [IgnisDa/ryot#61]
I have pulled the docker container as per the deployment instructions. The container runs and i can access the WebGUI. When i register/create an account i get a "user created successfully" and then am redirected back to the login page. When i use my account name and password i get "Autorisation Error, you are not logged in"

Have i missed a step?

**Comment by IgnisDa** [comment]
I have seen this problem myself but it always gets fixed after I try to login a couple of times. I would appreciate it if you could help me debug. For example: 
- Browser, OS
- Is a cookie named `auth` being set

**Comment by Kornster** [comment]
Hey @IgnisDa 

- Browser = Microsoft Edge (Version 113.0.1774.50 (Official build) (64-bit)
- OS = Windows11 + 22H2

No cookie name Auth is being set. I can also see console errors. unsure if they are useful or not.

![ScreenShot443](https://github.com/IgnisDa/ryot/assets/48738003/7680c951-2a88-44e1-8e35-14d3e470e6ad)

**Comment by IgnisDa** [comment]
Can you open the devtools console, try to login and then send me a screenshot?

**Comment by Kornster** [comment]
What specifically are you after?  It opens into the first tab "Elements" See below
![ScreenShot446](https://github.com/IgnisDa/ryot/assets/48738003/9f185860-dee5-4174-9100-1009a98dc820)

**Comment by IgnisDa** [comment]
I meant just open the "Console" tab (you have already attached a screenshot). Then login using the normal process and send me a screenshot.

**Comment by Kornster** [comment]
As requested
![ScreenShot447](https://github.com/IgnisDa/ryot/assets/48738003/2351280b-ab59-4db9-8752-97f0328d1ac5)

**Comment by IgnisDa** [comment]
Are there any warnings related to cookies? Im specifically looking for ones like "auth cookie rejected".

**Comment by Kornster** [comment]
I dont see anything relating to "auth cookie rejected"
I have tried both Chrome and Firefox and i get the same error.

Chrome Console below
![ScreenShot449](https://github.com/IgnisDa/ryot/assets/48738003/c61251be-12fc-47dd-8096-5dcae94a2d83)

**Comment by IgnisDa** [comment]
Can you try logging in and then capture the screenshot. Also are you running this on localhost or over HTTPs?

**Comment by Kornster** [comment]
Screenshot attached as requested.

Using HTTP, im accessing it from my private network, So Docker/Portainer running on a server and im accessing that from my personal pc on the same network
![ScreenShot450](https://github.com/IgnisDa/ryot/assets/48738003/ef44b169-3e4d-48fa-bc4e-5ec51ac3848b)

**Comment by Kornster** [comment]
Your comment about localhost intrigued me. Given my role in I.T i should have thought of this first. Directly on the host the login works.

![ScreenShot452](https://github.com/IgnisDa/ryot/assets/48738003/c5b9256d-3324-46cb-bf26-b687b516f6fd)

**Comment by IgnisDa** [comment]
That is probably be the issue. I think the auth cookie is being rejected. 
Can you describe your setup a bit more. Perhaps i can replicate it.

**Comment by IgnisDa** [comment]
If you are using the example config, you might have to change this value https://github.com/IgnisDa/ryot/blob/124b5d9cda663f5103d5bfd4984122c4f56956f7/config/ryot.example.json#L3

**Comment by Protinon** [comment]
I've just run into this exact issue on my end. I have Ryot running on my server, and I was accessing it on my desktop computer like this: `192.168.0.55:2230`. It's on the same network, but I am running it on a different port. Not sure if the port matters.

I just setup a reverse proxy using my domain, adding an https cert, and using Nginx as the proxy. I can login using the reverse proxy URL, but I still get a failed login when accessing via direct IP/port. I plan on using the reverse proxy so I'm all set, but I figured I should comment my fix.

**Comment by Kornster** [comment]
> That is probably be the issue. I think the auth cookie is being rejected. Can you describe your setup a bit more. Perhaps i can replicate it.

I have a server that i use for other docker containers i use on a daily basis. I use portainer to manage those containers. I ssh`d into the server and pulled the image down as per the instructions, then on portainer i added the container and set the port ids as port 8000 is being used by something else, so im using port 25076 to get to 8000 in the container. Apart from that i dont have a fairly extensive setup. My network is flat, i dont use managed switches at home with everything being connected via a Mesh network so no ACLs, VLANs or anything like that.

**Comment by IgnisDa** [comment]
Can you try running the container using:

```sh
$ docker run --pull always \
  --detach \
  --publish 25076:25076 \
  --volume ./ryot-data:/data \
  --volume ./config/ryot.example.json:/data/config/ryot.json \
  --env PORT=25076 \
  --name ryot \
  ghcr.io/ignisda/ryot:latest
```

**Comment by Kornster** [comment]
I pulled that container and i have the same issue. 

I was hunting the [ryot/config/ryot.example.json]
 "cors_origins": ["http://localhost:3000"]
Im not seeing any files in any ryot.json folder. 

administrator@white-forest:/opt/ryot$ ls
config  ryot-data
administrator@white-forest:/opt/ryot$ cd config/
administrator@white-forest:/opt/ryot/config$ ls
ryot.example.json
administrator@white-forest:/opt/ryot/config$ ls -l
total 4
drwxr-xr-x 2 root root 4096 May 26 13:23 ryot.example.json
administrator@white-forest:/opt/ryot/config$ cat ryot.example.json/
cat: ryot.example.json/: Is a directory
administrator@white-forest:/opt/ryot/config$ cd ryot.example.json/
administrator@white-forest:/opt/ryot/config/ryot.example.json$ ls
administrator@white-forest:/opt/ryot/config/ryot.example.json$ cd ..
administrator@white-forest:/opt/ryot/config$ cd ..
administrator@white-forest:/opt/ryot$ ls
config  ryot-data
administrator@white-forest:/opt/ryot$ cd ryot-data/
administrator@white-forest:/opt/ryot/ryot-data$ ls
computed-config.ron  config  ryot.db
administrator@white-forest:/opt/ryot/ryot-data$ cd config/
administrator@white-forest:/opt/ryot/ryot-data/config$

**Comment by Kornster** [comment]
I found the cors_origins line in "computed-config.ron" If i change that line to reference ["http://localhost:25076"] and then start the container it wipes out the localhost statement

**Comment by Kornster** [comment]
I tried change CHOWN -R on the ryot-data folder i am pointing the container to from root:root to administrator:administrator and this didnt resolve the problem. 

I may be barking up the wrong tree here but i cant make changes to the "computed-config.ron" but then if i restart the container the changes are removed and revert to 

    web: (
        cors_origins: [],
        insecure_cookie: false,

**Comment by Kornster** [comment]
Happy to keep being a tester on this if you have any ideas. 

I tried changing the container from bridged network to host and i got the same error, as to eliminate bridge networking.

**Comment by IgnisDa** [comment]
If you want to make changes to the ryot config. You need to change `/path/to/ryot-data/config/ryot.json`. The `computed-config.ron` is just there for debugging purposes and will be always overwritten.

**Comment by Kornster** [comment]
im having a little difficulty following this. the ryot.json is a directory. Where are is expected file you edit the config you mentioned?

> If you want to make changes to the ryot config. You need to change (or create) `/path/to/ryot-data/config/ryot.json`. The `computed-config.ron` is just there for debugging purposes and will be always overwritten.

**Comment by IgnisDa** [comment]
It should be a file. Can you delete the `ryot-data` directory completely and try again?

**Comment by Kornster** [comment]
Did you per chance push a change to the docker image? Container is failing to start after a re-install

**Comment by Kornster** [comment]
Yep, i can see a change 33 minutes ago and i pulled the latest to start from scratch. 

Logs show the following 

Error: Permission denied (os error 13)

**Comment by IgnisDa** [comment]
Yeah, you will have to `chown 1001:1001 /path/to/ryot-data`. (#51)

**Comment by IgnisDa** [comment]
I'd recommend you delete the `ryot-data` directory completely and start again.

**Comment by Kornster** [comment]
Sorry mate, yeah i just looked and saw ryot was the user it was trying to run as. Fixed that up.  I deleted the directories and the latest pull re-created them. Created my user on the WebGUI and then tried logging in and got the same result.

**Comment by IgnisDa** [comment]
From what your folder structure looks like, I think you should create the config file at `/opt/ryot/ryot-data/config/ryot.json`.

**Comment by Kornster** [comment]
I checked and it is already there? 

```
administrator@white-forest:/opt/ryot/ryot-data$ ls
computed-config.ron  config  ryot.db
administrator@white-forest:/opt/ryot/ryot-data$ cd config/
administrator@white-forest:/opt/ryot/ryot-data/config$ ls
ryot.json
```

**Comment by IgnisDa** [comment]
What URL are you accessing the website from? Is it a domain name or a static IP?

**Comment by Kornster** [comment]
Its a static IP, Going straight to the server via IP

`http://192.168.68.5:25076/auth/login`

**Comment by chunned** [comment]
I'm experiencing the same issue. Compose file:

```yaml
---
version: '3.9'
services:
  ryot:
    container_name: ryot
    image: ghcr.io/ignisda/ryot:latest
    restart: unless-stopped
    ports:
      - 999:8000
    volumes:
      - './ryot-data:/data'
      - './config/ryot.example.json:/data/config/ryot.json'
```

- If I start the container in an empty directory, `./config/ryot.example.json` and `./ryot-data/config/ryot.json` are created as directories
- If I manually create `./config/ryot.example.json` before I start the container, `./ryot-data/config/ryot.json` is created as a file, but it is empty
- The container is constantly restarting

FWIW, I had the app up and working last night, and this morning it was down with the following error (*before I pulled the new Docker image*):

```
Error: Unable to construct application configuration
Caused by:
    Permission denied (os error 13) in config/ryot.json JSON file
```

After pulling the new image you pushed, it looks like the same error but the output is slightly different: `Error: Permission denied (os error 13)`

**Comment by chunned** [comment]
> Yep, i can see a change 33 minutes ago and i pulled the latest to start from scratch.
> 
> Logs show the following
> 
> Error: Permission denied (os error 13)

How did you fix this? My container is constantly restarting so I can't chown

**Comment by IgnisDa** [comment]
Just stop the container and run the command on the volume.

**Comment by chunned** [comment]
Ah I thought you meant to run chown within the container. It's working now. 

@Kornster I had the same issue where `/config/ryot.example.json` and `/data/config/ryot.json` were being created as directories - I fixed this by manually creating `config/ryot.example.json` (using the contents of the same file in this repository), deleting the data directory, and recreating the container

**Comment by bretthysuik** [comment]
> Ah I thought you meant to run chown within the container. It's working now.
> 
> @Kornster I had the same issue where `/config/ryot.example.json` and `/data/config/ryot.json` were being created as directories - I fixed this by manually creating `config/ryot.example.json` (using the contents of the same file in this repository), deleting the data directory, and recreating the container

Yes, the documentation needs to be updated to explain that `ryot.example.json` needs to be created before running the docker container, otherwise docker assumes the path is a directory and creates it as a directory: 

https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume
https://stackoverflow.com/questions/54657370/mount-single-file-from-volume-using-docker-compose

**Comment by Kornster** [comment]
> > Ah I thought you meant to run chown within the container. It's working now.
> > @Kornster I had the same issue where `/config/ryot.example.json` and `/data/config/ryot.json` were being created as directories - I fixed this by manually creating `config/ryot.example.json` (using the contents of the same file in this repository), deleting the data directory, and recreating the container
> 
> Yes, the documentation needs to be updated to explain that `ryot.example.json` needs to be created before running the docker container, otherwise docker assumes the path is a directory and creates it as a directory:
> 
> https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume https://stackoverflow.com/questions/54657370/mount-single-file-from-volume-using-docker-compose

This did it. It took me a little to understand but i havnt had a coffee yet.
For those wondering here are the steps.
This assumes you have the ryot container already pulled and running
I was on Windows when i did all this using putty to access the server via SSH and WinSCP for to access the Linux Server where my docker containers are running.

```
Stop the container. 
Access the data volume where ryot was pulled. For myself i created a folder under /opt called ryot. I then when into that directory and pulled the container inside that folder. This creates a config and ryot-data folder inside the directory.
Grab the latest release from releases pages "https://github.com/IgnisDa/ryot/releases" which will download a zip file.
Open the zip file and extract the folder config.
Using putty, delete /opt/confg/ryot.example.json. You may need to execute sudo rm -rf /opt/ryot/config/* as ryot.example.json will have been created as a folder under the config directory.
Using something like WinSCP, copy the ryot.example.json file to the /opt/ryot/config/ folder "This assumes you have permission".
Delete /opt/ryot/ryot-data spefically the ryot-data folder and nothing else.
I was using Portainer to do the docker works. In portainer, go into ryot and choose Duplicate/Edit.
Choose deploy container which will re-deploy the container. If done correctly the container will re-deploy and be in a running state
Access the ryot webGUI, create your account and re-try logging in.
```

Note: I did edit /opt/ryot/ryot.example.json with nano and change the "cors_origins" port on the localhost to :8000 from :3000. Am unsure if this helped resolve but the container is now working for me.

**Comment by Kornster** [comment]
> > Yep, i can see a change 33 minutes ago and i pulled the latest to start from scratch.
> > Logs show the following
> > Error: Permission denied (os error 13)
> 
> How did you fix this? My container is constantly restarting so I can't chown

re-created container to run as root. Use at your own risk. IgnisDa did provide instructions on setting the perms for the ryot data https://github.com/IgnisDa/ryot/issues/61#issuecomment-1564171955
![Screenshot 2023-05-27 083344](https://github.com/IgnisDa/ryot/assets/48738003/e6c38dbc-64cf-4129-b290-12ffbcf50d4c)

**Comment by IgnisDa** [comment]
@bretthysuik and @Kornster could you make a PR with the chages you would like to see in the README?

**Comment by bretthysuik** [comment]
> @bretthysuik and @Kornster could you make a PR with the chages you would like to see in the README?

Done: https://github.com/IgnisDa/ryot/pull/93
