### ISSUE TITLE
Cannot delete or edit an exercise 

### ISSUE THREAD

**Issue by JahFyahh** [IgnisDa/ryot#615]
I made a mistake in an exercise I wish to fix and want to add an image to another. How can i edit or delete an exercise I created? The only action I have is "add to collection", there are no other buttons for exercises.

**Comment by IgnisDa** [comment]
Editing custom media and exercises is something very low on my roadmap. If it's really important to you, I can give you database commands to edit it.

**Comment by JahFyahh** [comment]
@IgnisDa please do, I was going to look into doing that, but if you have them at hand I would very much appreciate it. Also editing workouts if possible.

BTW is there an API to use and if so, any docs on how to?

**Comment by IgnisDa** [comment]
```sql
-- find user_id
select id, name from "user";

-- use the below to see the schema and then edit the exercise you want 
select * from exercise where id = '<name>';
```

> Also editing workouts if possible.

I suggest you repeat the workout using the button and then make the edits. After you submit, you can adjust the workout times to the original. Then delete the original.

> BTW is there an API to use and if so, any docs on how to?

I haven't gotten around the creating an API for these actions.

**Comment by JahFyahh** [comment]
Thank you very much for your time in creating this project and replying to me as well. Much appreciated.
