### ISSUE TITLE
FEMA Importer

### ISSUE THREAD

**Issue by phrogg** [IgnisDa/ryot#616]
Hey,

sorry for opening an issue yet again. But I finished writing a program with python that converts an export from FemaStudios (MoviesFAD & SeriesFAD) (https://export.femastudios.com/) to RYOT. Is there anywhere I can share this so that people can find it? Do you have any idea?

Cheers

**Comment by IgnisDa** [comment]
You can add it to the importing docs. Please make a PR for this.
