### ISSUE TITLE
Importing from MAL does not work

### ISSUE THREAD

**Issue by phrogg** [IgnisDa/ryot#618]
I imported my library from myanimelist. And a lof of anime that I have watched completely are set to "in Progress" with status 0%. Interestingly other anime that I have set "Plan to Watch" in myanimelist. Have been imported as completed in RYOT. That is very weird. It seems as all of them are wrong. Maybe the mapping is faulty. So that "Plan to Watch" in MAL is mapped to "Completed" ind RYOT. And the same with "Completed" and "Progress 0%".

**Comment by phrogg** [comment]
> I'm a bit tied up at the moment. If you're up for it, feel free to jump in and submit a PR – I'd really appreciate the help. If you're not sure where to start, I can give you some pointers.
> 
> Alternatively, if coding isn't your thing but you still want to support the project, a donation would be super helpful.

I already donated. But since then the amount of issues is a bit high I understand. I would love to help out. And I'm grateful if you give me some pointers to start :)
Cheers

**Comment by IgnisDa** [comment]
there would be a file called `mal.rs`. You can start from there.

**Comment by IgnisDa** [comment]
@phrogg Please share the files that you're trying to import. You can share them on my email (in my GH profile).

**Comment by kaibagley** [comment]
Also having this issue, if I have time over the weekend I might try a pr

**Comment by phrogg** [comment]
> Also having this issue, if I have time over the weekend I might try a pr

Hey, sorry I had a lot stuff coming up. I did however look over it for a bit right now. Did not test it through but this could be the issue file `importer\mal.rs`:
![image](https://github.com/IgnisDa/ryot/assets/1367949/98b32b60-98c5-41d0-a4f2-ae43e170bdd7)

This is my edited file in the code it says in this line 44:
```perl
let progress = if item.done != 0 && item.total != 0 {
```
But i can't find `done` or `total` in the exported files from MAL.

**Comment by phrogg** [comment]
> > Also having this issue, if I have time over the weekend I might try a pr
> 
> Hey, sorry I had a lot stuff coming up. I did however look over it for a bit right now. Did not test it through but this could be the issue file `importer\mal.rs`: ![image](https://private-user-images.githubusercontent.com/1367949/309419753-98b32b60-98c5-41d0-a4f2-ae43e170bdd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjM5ODUsIm5iZiI6MTcwOTQ2MzY4NSwicGF0aCI6Ii8xMzY3OTQ5LzMwOTQxOTc1My05OGIzMmI2MC05OGM1LTQxZDAtYTRmMi1hZTQzZTE3MGJkZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMTEwMTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmY1MWI1MDlmMGIyNzMyNjlmZWM3YTQ4M2E1NDE1YTJiNmM4OTM5YzJkYjMzOWNmMTUwYjU4YjY0MzEzMDYwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dBIS74iQ1geBV4Tir35bopbjSrpfHvrDuLuS25xCHO0)
> 
> This is my edited file in the code it says in this line 44:
> 
> ```perl
> let progress = if item.done != 0 && item.total != 0 {
> ```
> 
> But i can't find `done` or `total` in the exported files from MAL.

If this is indeed the error. I could open a pr. I do not have a plan on how to test this though.

**Comment by IgnisDa** [comment]
You can consult the docs on running the project locally.

**Comment by IgnisDa** [comment]
@kaibagley Could you please email me your mal export? I would like to fix this issue.

**Comment by kaibagley** [comment]
Sorry for the late response, let me know if you still need it

**Comment by IgnisDa** [comment]
@kaibagley I would be glad if you could send it, I am encountering a few edge cases that I would like to fix.

**Comment by kaibagley** [comment]
Sent

**Comment by IgnisDa** [comment]
@kaibagley Your issues should be fixed with #773.
