### ISSUE TITLE
Can not add watch a show episode (after some running time)

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#620]
Hi,

I am having an issue with Ryot (I only use this instance for TV Shows). At some time I am not any longer able to mark a new episode as seen in the app. The website responds fine, fast enough, and if I mark an episode, I can see the notification about what was saved, but after it, I cannot see the register in the history tab. I cannot find any error/problem on the logs, and if I restart the container it works perfectly again.

I was checking the CPU consumption, and I start to think that maybe is related to this https://github.com/IgnisDa/ryot/issues/440

Because here are my Grafanas information about the _ryot_ container and the _ryot postgress_ container.

![image](https://github.com/IgnisDa/ryot/assets/854646/f5703ee8-c1f7-4f92-a382-17fb09d3b972)
The green is Ryot and the red the Ryot postgres

**Comment by IgnisDa** [comment]
Please set `RUST_LOG=Ryot=debug` env variable and reproduce the problem. I doubt that it is related to #440.

**Comment by SirMartin** [comment]
Ok, I added the envvar, I will reply when I can reproduce the issue again

**Comment by SirMartin** [comment]
It's failing, but I am not sure the envar worked correctly.

These are the logs that appear on the container.

```
[frontend] GET /media/item/49?_data=routes%2F_dashboard.media.item.%24id._index 200 - - 292.555 ms
[frontend] POST /media/item/49?intent=progressUpdate&_data=routes%2F_dashboard.media.item.%24id._index 200 - - 1020.790 ms
[frontend] GET /media/item/49?intent=progressUpdate&_data=root 200 - - 2.208 ms
[frontend] GET /media/item/49?intent=progressUpdate&_data=routes%2F_dashboard 200 - - 47.767 ms
[frontend] GET /media/item/49?intent=progressUpdate&_data=routes%2F_dashboard.media.item.%24id._index 200 - - 187.906 ms
[frontend] GET /media/item/49?intent=progressUpdate 200 - - 526.363 ms
[frontend] Error: No route matches URL "/sw.js"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4487:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2933:19)
[frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:180:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:105:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend] ErrorResponseImpl {
[frontend]   status: 404,
[frontend]   statusText: 'Not Found',
[frontend]   internal: true,
[frontend]   data: 'Error: No route matches URL "/sw.js"',
[frontend]   error: Error: No route matches URL "/sw.js"
[frontend]       at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4487:5)
[frontend]       at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2933:19)
[frontend]       at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:180:35)
[frontend]       at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:105:24)
[frontend]       at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28

[frontend] }
[frontend] GET /sw.js 404 - - 5.741 ms
```

Here is how I have configured the `envvar`, I tried to check it on the configuration, but I couldn't find.

![image](https://github.com/IgnisDa/ryot/assets/854646/08fb023f-34f3-4f3b-beb3-f38c8129f8b9)

**Comment by IgnisDa** [comment]
Ryot should not be capital.

**Comment by IgnisDa** [comment]
Nope postgres logs are not relevant.

**Comment by IgnisDa** [comment]
@SirMartin Any updates?

**Comment by SirMartin** [comment]
Nope, still works since my last restart to add the debug logs.

**Comment by IgnisDa** [comment]
You didn't post the logs.

**Comment by IgnisDa** [comment]
So the regenerate summary is working now?

**Comment by SirMartin** [comment]
It was not a problem of regenerate the summary, the problem was to mark an episode as viewed. When it fails, it says it worked correctly, but it didn't appear on the history, so it is not registered properly. But it happens after some days (2-3 days), so probably if it repeats the cycle tonight or tomorrow should be able to reproduce it.

**Comment by IgnisDa** [comment]
@SirMartin were you able to reproduce it?

**Comment by SirMartin** [comment]
Nope, I am closing it, still works, maybe something from last updates fixed, because still works for more than a week, if some day happens again, now I know how to enable debugging logs.

Thanks for the help.
