### ISSUE TITLE
Update metadata does not work?

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#621]
I am trying to understand what the Update Metadata function, is because I started to store in Ryot my comic collection via Openlibrary, and I was at the same time adding some pictures, information, etc, on the Openlibrary website, but for example, I see the same author differently on different books on Ryot, maybe because when I add the book A was not picture on Openlibrary, and when add book B the author has a picture. So on Ryot, even if I try to update the metadata, book A's does not have a picture and the one from book B's author does.

I appreciated the same, I updated on TMDB a TV show, to add the titles of episodes, and when I ask for updated metadata, it does not show the titles, still the old ones.

Thanks

**Comment by IgnisDa** [comment]
In my experience Open library is a bit slow with returning the updated information. Try again after 12 hrs and see if it works.

To answer your question, "update metadata" fetches the latest information from the provider and updates the fields.

**Comment by SirMartin** [comment]
When update metadata, how long should take the background work? Is there any place where can see background works (like Sonarr, Radarr does FX.) 

The update metadata should update the title of the book? And it should add author pictures if not appear in ryot but it does on Openbooks?

**Comment by IgnisDa** [comment]
> The update metadata should update the title of the book? And it should add author pictures if not appear in ryot but it does on Openbooks?

Yeah it should. Is it still not working? If that is the case, please give me the steps to reproduce this on a fresh instance.

> When update metadata, how long should take the background work? 

Update task normally takes 2 seconds. You can set `RUST_LOG=ryot=trace` env variable to see background job timings.

**Comment by SirMartin** [comment]
It does not work. Not sure what the reproduction steps are, more than adding a book with an author without a picture for example, and adding the picture later on Openlibrary.

I can show you an example of mine.

![image](https://github.com/IgnisDa/ryot/assets/854646/b9498996-3882-4f40-8c13-1aee39952e42)

This one refers to this book on Openlibrary: https://openlibrary.org/works/OL20890738W/Ariol_2._El_caballero_caballo

If you click on the _Marc Boutavant_'s author name it refers to this page https://openlibrary.org/authors/OL3892283A/Marc_Boutavant 

![image](https://github.com/IgnisDa/ryot/assets/854646/b7db09a1-c483-4d7f-97aa-d30729aa9eaa)

Here the author has an image (I added this one a few days ago), but with the **Update Metadata** command I could for example update the title, and it worked fine, but the picture still did not appear.

**Comment by IgnisDa** [comment]
Wait are you talking about updating the media or the person details?

**Comment by SirMartin** [comment]
It was different things, but some of them work, so it was me (probably not wait the needed time), this one, I suppose is the person details, but I cannot see how to update metadata for a person details (if it's possible).

**In this case I am trying to update (the rest works fine) the author of a book.**

**Comment by IgnisDa** [comment]
>  (if it's possible).

it is not
