### ISSUE TITLE
Option to get metadata in one language

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#622]
Maybe it's me, and I didn't found, but I have an issue, I think Ryot is making queries to TMDB and always on English, like for some country local shows, which could be that the information is not so complete. Could be possible to choose if the petitions to TMDB API should be in one specific language? Even better, like TMDB configuration, could be possible to mark a fallback language to the API calls, and if there is no information in one language, try the second one?

Thanks

**Comment by IgnisDa** [comment]
You can use the `MOVIES_AND_SHOWS_TMDB_LOCALE` env var to set the language. Search for `movies_and_shows` on https://ignisda.github.io/ryot/configuration#all-parameters for more information.

**Comment by SirMartin** [comment]
Great thanks, I will try
