### ISSUE TITLE
"crypto.randomUUID is not a function" error adding exercise to workout

### ISSUE THREAD

**Issue by amedcalf** [IgnisDa/ryot#623]
Thank you for your recent change enabling Ryot to start workouts even when I am not using https, that's great.

I'm having a problem adding an exercise to the started workout though in the latest version. When I choose to add an exercise, select the exercise and click the blue tick to confirm I want to add it nothing seems to happen. It remains on the exercise selection screen and nothing is added to the workout.

The console shows this error on each click:

```
workout-65xHAvFJ.js:1 Uncaught (in promise) TypeError: crypto.randomUUID is not a function
    at Be (workout-65xHAvFJ.js:1:12081)
    at async onClick (_dashboard.fitness.exercises.list-YB43egp-.js?client-route:1:6769)
```

However I can add exercises to the demo version on fly.io so I'm not sure if that's also something to do with https?

Thank you again for your great app.

**Comment by IgnisDa** [comment]
thats weird. Crypto should be built into the browser. What version of the browser are you using?

**Comment by amedcalf** [comment]
Thanks, I tried a few browsers - Firefox 122.0 (64-bit) on Linux Mint
Google Chrome Version 121.0.6167.139 (Official Build) (64-bit) on Linux Mint
And Safari on iOS 17.3

All seemed to have the same issue to me (although I don't know how to check the error message on iOS)

**Comment by IgnisDa** [comment]
@amedcalf Please upgrade to `v4.2.2` which addresses this. I also would a donation :).

**Comment by amedcalf** [comment]
awesome, thanks @IgnisDa  - and of course, happy to.
