### ISSUE TITLE
Feature request: click details of previous exercise to copy the previous kg/rep/set info

### ISSUE THREAD

**Issue by amedcalf** [IgnisDa/ryot#624]
I'm often constructing a workout repeating a small selection of exercises I already did. It is great that in the workout screen it shows the details (e.g. reps and kg) of my last one as often I want to do the same again.

The iOS app "Strong" also does this but it has a feature I wonder if you would also consider implementing. Instead of having to type in the kg and Reps if you want the same numbers you can click on the details of the "Previous" column and it copies it into the current workout's entry.

This is at a per-exercise level so you don't have to duplicate the entire workout. It's not actually obvious it works like that in Strong as it isn't formatted as a button - but I do like and use that feature so wonder if you could do something similar here. 

For example, in the attached image, if I was to click on where it already says "1.00 min" in the Previous column it would automatically fill in 1 minute into the Duration (min) column.

![exercise](https://github.com/IgnisDa/ryot/assets/7243484/59df724d-0ba4-4e2c-aa12-0a5e5b7d7086)

Thank you for your consideration

**Comment by IgnisDa** [comment]
Thats sounds like a pretty useful feature. Where would be the best place to add the button?

**Comment by IgnisDa** [comment]
This is weird, if you had a previous entry, the field should automatically be populated.

**Comment by amedcalf** [comment]
Thanks! The way it works in Strong is you would click the number 1.00 in the above screenshot and it would automatically fill the same number into the empty duration box (and same for sets, weights when appropriate). The same might work here for your app?

It took me a while to discover that worked in Strong, I suppose maybe it is a "power user" feature?!
It might be more obvious I suppose if there was a button between the Previous and Duration box you could click to copy it across, but also I know that would add more things to your UI so not sure if you'd want to do that.

**Comment by IgnisDa** [comment]
I was thinking about a "Fill from previous" btn in the three dots menu. This would just add all the sets done in the previous workout with the values filled in.

How does that sound?

**Comment by IgnisDa** [comment]
I don't want to introduce "power user" features because they can be only discovered by accident. I used strong for 3 years and didn't know about that feature.

**Comment by amedcalf** [comment]
Thanks very much - I think a "fill from previous" button as you describe would work great.

**Comment by IgnisDa** [comment]
I decided to go with your idea original instead of the "Fill from previous" button.
