### ISSUE TITLE
[FEATURE REQUEST] - Expose calendar as iCal feed to use it in an calendar

### ISSUE THREAD

**Issue by alexanderadam** [IgnisDa/ryot#627]
I'm not sure whether this is already possible or not but it would be nice to have the possibility to integrate upcoming shows into a calendar (i.e. via ical feed).

**Comment by IgnisDa** [comment]
I'm a bit tied up at the moment. If you're up for it, feel free to jump in and submit a PR – I'd really appreciate the help. If you're not sure where to start, I can give you some pointers.

Alternatively, if coding isn't your thing but you still want to support the project, a donation would be super helpful.

**Comment by IgnisDa** [comment]
@alexanderadam Are you aware of any self hosted application which expose its data via iCal?

**Comment by alexanderadam** [comment]
Hi @IgnisDa,

are you asking regarding implementation details or whether it is generally a thing that self hosted applications do?

Regarding the implementation you might find something [here](https://github.com/Peltoche/ical-rs/network/dependents).
There might be some projects [that could generate ics files](https://github.com/Peltoche/ical-rs?tab=readme-ov-file#generator).

For instance [this](https://github.com/ssemtner/webreg_calendar), [this](https://github.com/trobanga/notion-calendar/tree/main) or [this](https://github.com/kurtlawrence/pical).

If you're asking whether it's generally a thing that self hosted applications do, then it might be worth to [mention Nextcloud](https://docs.nextcloud.com/server/19/user_manual/pim/calendar.html#publishing-a-calendar), I guess.

**Comment by IgnisDa** [comment]
Thanks. I will take a look into these.

**Comment by IgnisDa** [comment]
@alexanderadam I am thinking about providing ICal feed as an [exporting](https://docs.ryot.io/guides/exporting) option. Is that fine?

**Comment by IgnisDa** [comment]
Closing due to no response. Feel free to ping me.
