### ISSUE TITLE
[FEATURE REQUEST] - Import of Garmin activities

### ISSUE THREAD

**Issue by alexanderadam** [IgnisDa/ryot#628]
This might be a difficult topic but it seems that others did it before, like [Rust-Garmin](https://github.com/poster515/Rust-Garmin) or [gliberator](https://github.com/djk121/gliberator/blob/master/src/main.rs).

**Comment by IgnisDa** [comment]
I'm a bit tied up at the moment. If you're up for it, feel free to jump in and submit a PR – I'd really appreciate the help. If you're not sure where to start, I can give you some pointers.

Alternatively, if coding isn't your thing but you still want to support the project, a donation would be super helpful.

**Comment by IgnisDa** [comment]
Closing this since there is not enough people interested in this.
