### ISSUE TITLE
[FEATURE REQUEST] - Import of Strava activities

### ISSUE THREAD

**Issue by alexanderadam** [IgnisDa/ryot#629]
This might be difficult too but it seems that [there are some libraries available](https://github.com/search?q=strava+language%3ARust&type=Repositories&ref=advsearch&l=Rust&l=&s=updated&o=desc).

**Comment by IgnisDa** [comment]
I'm a bit tied up at the moment. If you're up for it, feel free to jump in and submit a PR – I'd really appreciate the help. If you're not sure where to start, I can give you some pointers.

Alternatively, if coding isn't your thing but you still want to support the project, a donation would be super helpful.

**Comment by IgnisDa** [comment]
Closing this since there is not enough people interested in this.
