### ISSUE TITLE
Duplicate calendar element

### ISSUE THREAD

**Issue by mrdev023** [IgnisDa/ryot#631]
![Screenshot_20240208_065920_Opera.jpg](https://github.com/IgnisDa/ryot/assets/11292703/3ef46513-a82b-4d8a-b1cf-255fe920a256)

![Screenshot_20240208_065929_Opera.jpg](https://github.com/IgnisDa/ryot/assets/11292703/6134d725-bf4d-4dee-a4b3-f34dae7d46e4)

**Comment by IgnisDa** [comment]
Yep i have already noticed this. Thanks!

**Comment by IgnisDa** [comment]
Note to self:
- create indices for the `*_extra_information` columns

**Comment by mrdev023** [comment]
i confirm it's fixed in my side
