### ISSUE TITLE
[bug] Unable to create exercises

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#632]
When trying to create an exercises, it's reporting the following error:

![image](https://github.com/IgnisDa/ryot/assets/64137913/59ab5dd4-acf4-4c05-af32-2bb1ba16a090)

```
Failed to load resource: the server responded with a status of 500 ()
Error: Unexpected Server Error
console.error @ /assets/root-cOWLZTPP.js?client-route:13
```

**Comment by IgnisDa** [comment]
Does it still persist after reloading the page?

If yes, please post the logs of the ryot container (not the database one).

**Comment by IgnisDa** [comment]
Please upgrade to `v4.2.4` and see if the error still persists.
