### ISSUE TITLE
[bug] Unable to access the Users section

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#633]
When just click Users under Settings, it's report the following error:

![image](https://github.com/IgnisDa/ryot/assets/64137913/19987e23-cde5-4020-8c65-3fb017e57479)

```
Failed to load resource: the server responded with a status of 500 ()
root-cOWLZTPP.js?client-route:13 Error: Unexpected Server Error
console.error @ root-cOWLZTPP.js?client-route:13
users:1 
Failed to load resource: the server responded with a status of 500 ()
```

**Comment by IgnisDa** [comment]
Same as https://github.com/IgnisDa/ryot/issues/632#issuecomment-1933647974.

**Comment by IgnisDa** [comment]
Did you upgrade from an old release?
