### ISSUE TITLE
Database migration error when correcting events index

### ISSUE THREAD

**Issue by arigold22** [IgnisDa/ryot#636]
![Screenshot_20240210_170938_Brave](https://github.com/IgnisDa/ryot/assets/33474861/55335019-3590-4952-979a-335af2c67acb)
Hey I am getting this error after updating my docker container

This is my database and the last migration failed to apply. If I missed anything please lmk 

![Screenshot_20240210_172016_Brave](https://github.com/IgnisDa/ryot/assets/33474861/7a2522dc-f457-4e07-89bc-0c1fedf3f691)

**Comment by IgnisDa** [comment]
What version of postgres database are you using?

**Comment by arigold22** [comment]
Postgres 14.10, I just read the release change logs for previous versions of ryot and I did not manually make any migration changes I just clicked the update button on unraid and it stopped working. I must have messed up somehow, I did not have much data in the app so I can just start over with a new container

**Comment by IgnisDa** [comment]
Ah the newest migration needs postgres 15 or later (`not nulls not distinct` index).

Closing this. Feel free to ping if you have other problems.

**Comment by IgnisDa** [comment]
@arigold22 Also I'd be really grateful if you could tell me the instructions (or make a PR) to deploy Ryot to Unraid. I remember someone in reddit asking me for help and i couldn't since I have no experience with it 😅.

**Comment by arigold22** [comment]
After a bit of research someone has already deployed ryot on unraid. Here is the xml file link
 https://github.com/Homelabbers/unraid-templates/blob/main/templates%2Fryot.xml

**Comment by IgnisDa** [comment]
Thanks!
