### ISSUE TITLE
How do I add shows and movies manually

### ISSUE THREAD

**Issue by Jacob-Tate** [IgnisDa/ryot#639]
Maybe Ive missed it in the documentation but Im not clear on how to create a new show manually for addition to something like my watchlist. For example if I want to add https://www.themoviedb.org/tv/213134-pepsi-where-s-my-jet to my watch list it appears I either have to import it from something like trakt or select the `Create Media` button which requires that I know all the correct information about the show and generate a correctly formatted graphiql json. While this works if im at home if im say on my phone and someone mentions a show im interested in its not easy to add the new show to my watchlist on the fly.

Is it possible to create a show given a url to something like themoviedb.org?

**Comment by IgnisDa** [comment]
Go to this URL: https://ryot.fly.dev/media/search/show?query=Pepsi%2C+Where%27s+My+Jet%3F (the domain name will change according to your installation) and then click on the show name.

As a general rule:
- on the sidebar select the media type: ("show" here)
- on the main page, select the search tab
- search for the name
- click on the correct media item

**Comment by IgnisDa** [comment]
Closing this. Feel free to ping me here if you have any problems.

**Comment by IgnisDa** [comment]
> While this works if im at home if im say on my phone and someone mentions a show im interested in its not easy to add the new show to my watchlist on the fly.

This sounds like a feature request, what do you have in mind?

Ideally, most shows are available on TMDB so you wouldn't have to manually create them at all.

**Comment by Jacob-Tate** [comment]
This was a misunderstanding I didnt realize the search bar did that should have tried it first. When I was looking I saw the Create button and though that was how I added new shows!

I was doing a quick search for IMDB api / other apis and realized how expensive they are so I dont think an addition of a converter would be required. That being said some sites ive used in the past you can search for a movie with the IMDB ID similar to the TMDB id of 213134 for pepsi wheres my  jet. In this case being able to search the ID has a benefit of being precise when there are shows that have been released multiple times with the same name.

https://www.themoviedb.org/tv/85991?language=en-US
https://www.themoviedb.org/tv/36941-fruits-basket?language=en-US

While not a feature most will use it may be helpful for the few. Sadly unlike imdb they dont prefix the ID numbers with tt to make it easy to identify but maybe a checkbox or just telling users in the docs to prepend id to the numbers would work. I can look into adding this myself I attempted to pull up the devcontainer but ran into some issues but maybe im doing something wrong ive never worked with devcontainers.

The following occurs on Windows Docker with WSL2 Engine via vscode `Dev containers: clone repository in container volume`. It appears but containers are running I just cant get the actual clone to work but being unfamilar with docker dev container im not sure if this is something ive done wrong in my setup.
```
[10121 ms] Start: Run in container: /bin/sh -c . /workspaces/ryot/.devcontainer/scripts/post-create.sh
/bin/sh: line 1: /workspaces/ryot/.devcontainer/scripts/post-create.sh: No such file or directory
[10197 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
```

In a separate terminal:
```
[archlinux@cd4126464894 ryot]$ ls -l
total 0
```

**Comment by IgnisDa** [comment]
> This was a misunderstanding I didnt realize the search bar did that should have tried it first. When I was looking I saw the Create button and though that was how I added new shows!

The UX is certainly lacking in this front. I should add an alert box that introduces new users to search functions.

I've had many requests to allow for more fine grained searching, but i don't plan to (or want to) implement it since it would require a massive refactoring of the search implementation. However I'll keep those requests in mind and see if I can come up with a good compromise.

For development purposes, i suggest you use http://devpod.sh/. If the problem still persists, feel free to ping me here.

---

Notes to self:
- make the specifics field for creating custom media nullable. If it is null, treat it as a partial metadata.
