### ISSUE TITLE
Cannot import from Audiobookshelf

### ISSUE THREAD

**Issue by StuartMorrisAU** [IgnisDa/ryot#641]
Hi there,

When I go to settings > Imports and Exports > Import Data and set Source to Audiobookshelf, enter my ABS URL an API key, I get the following in the import log:

```
    {
        "lot": "AUDIO_BOOK",
        "step": "MEDIA_DETAILS_FROM_PROVIDER",
        "identifier": "Heretics of Dune",
        "error": "missing field `title` at line 1 column 822"
    }
```

But when I go to ABS and check the audiobook, the title is `Heretics of Dune`. I get the same output for every book that's marked as finished.

Any ideas what's causing this?

Thanks.

**Comment by IgnisDa** [comment]
Would it be possible for you to give me access to the instance URL for your ABS instance and the token? I do not use ABS myself so it is proving difficult for me to reproduce this.

You can email them to me (ID in my GH profile).

**Comment by IgnisDa** [comment]
Someone else helped me debug this, but I think you probably have your audiobooks associated with metadata from Amazon instead of Audible.

Change your matcher in ABS to audible if you want Ryot to be able to track properly. I'll look into providing more descriptive error messages.

**Comment by nellistc** [comment]
Apologies for commenting on a long closed issue, however, if this isn't resolved, it could be that your ABS and ryot are using different audible regions. For me, setting them to the same region resolved import errors. (In a lot of cases, the same audiobook will have a different ASIN in different regions.)
