### ISSUE TITLE
Application Error when attempting to search for audiobooks

### ISSUE THREAD

**Issue by Oosmus** [IgnisDa/ryot#643]
Hey there!

I found this after my wife was using something she found to track her personal media consumption and thought to find a self-hosted solution that may tie into all of our services such as plex, kavita, etc. In an attempt to test this out, I wanted to add some audiobooks that I had read, but noticed many of the authors that I searched for would not appear. Rather than manually create individual media items, I checked documentation and manually set my audible locale to US. Now I'm getting an application error when I begin to type anything, but only under audiobooks. I can provide logs if it would help, but I'm mainly curious as to where metadata is obtained and why very popular authors are missing from the source being pulled from. 

Is there a discord or something similar that I could join to keep track of progress updates and hop in discussions, or is all of it handled via github here? 

Either way, I look forward to seeing this app grow!

**Comment by IgnisDa** [comment]
It's all handled through GitHub discussion. Though I do reply to DMs on discord regarding Ryot.

I would like to see the logs. What exactly did you change the audible locale to?

**Comment by Oosmus** [comment]
Ah gotcha, good to know! I've attached what looks to be the start of audiobooks up to the error. If you need more, just let me know. As for the locale, I set it to US through environment variables. If I remove the locale, it works just fine, but I feel like its scraping incomplete data. There are authors that appear on audible just fine, but aren't appearing when I search them in Ryot. 

`[frontend] GET /media/list/audio%20book?_data=root 200 - - 1.889 ms
[frontend] GET /media/list/audio%20book?_data=routes%2F_dashboard 200 - - 18.043 ms
[frontend] GET /media/list/audio%20book?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 21.948 ms
[frontend] GET /media/search/audio_book?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 8.596 ms
[frontend] GET /media/search/audio_book?query=t&_data=root 200 - - 1.723 ms
[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/providers/audible.rs:177:18:
[backend] internal error: entered unreachable code
[backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[frontend] GET /media/search/audio_book?query=t&_data=routes%2F_dashboard 200 - - 17.652 ms
[frontend] ClientError: GraphQL Error (Code: 500): {"response":{"error":"Service panicked","status":500,"headers":{}},"request":{"query":"query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {\n  mediaSearch(lot: $lot, source: $source, input: $input) {\n    details {\n      total\n      nextPage\n    }\n    items {\n      databaseId\n      hasInteracted\n      item {\n        identifier\n        title\n        image\n        publishYear\n      }\n    }\n  }\n}","variables":{"lot":"AUDIO_BOOK","input":{"page":1,"query":"t"},"source":"AUDIBLE"}}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at file:///home/ryot/build/server/index.js?t=1707798215000:10400:43
[frontend]     at loader$d (file:///home/ryot/build/server/index.js?t=1707798215000:10361:36)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4011:16)
[frontend]     at async Promise.all (index 0)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3298:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3076:20)
[frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3016:18) {
`

**Comment by IgnisDa** [comment]
You will have to set the env variable to `us` not `US`. Or not set it at all since that is the default locale.

You are hitting this code path: https://github.com/IgnisDa/ryot/blob/eef016490ebda1729dec18206858393f49bbb4b8/apps/backend/src/providers/audible.rs#L177
