### ISSUE TITLE
Do not allow enabling video games in preferences if correct env variables not set

### ISSUE THREAD

**Issue by matthieurosset** [IgnisDa/ryot#648]
Hi there,

I just installed a fresh instance of Ryot, today. But I'm not able to enable "Video game" in Preferences / Media. If I enable "Video game" and I save, everything is back at disable status. For others medias, everything works fine !

![Animation](https://github.com/IgnisDa/ryot/assets/3691705/80bcc4e2-95cc-437d-9bd7-cf4f43939ad9)

Could you please help me ? Thanks a lot !

Matthieu

P.S : I join my logs if you need it. I saw nothing in it. 

[_ryot-db_logs.txt](https://github.com/IgnisDa/ryot/files/14330893/_ryot-db_logs.txt)
[_ryot_logs.txt](https://github.com/IgnisDa/ryot/files/14330894/_ryot_logs.txt)

**Comment by IgnisDa** [comment]
Have you set the environment variable required to enable video games?

**Comment by matthieurosset** [comment]
Oh, sorry. I didn't try to deep configure my instance yet. Thought that was a bug because there is no error message in UI or in logs. 

I will give it a try soon.

**Comment by IgnisDa** [comment]
> Thought that was a bug because there is no error message in UI or in logs.

Yeah, I should disable it by default if the correct env variables are not configured.

**Comment by IgnisDa** [comment]
Just realized that implementing this will require me to create additional endpoints. I do not feel that is worth it.

For anyone stumbling on this issue, these are the env variables required to get video games tracking working (https://ignisda.github.io/ryot/configuration):
![image](https://github.com/IgnisDa/ryot/assets/60938164/38710d75-8b1e-42f6-bca1-664476c9f699)

**Comment by matthieurosset** [comment]
Yes, I understand @IgnisDa. With your configuration, everything is all right now.

Just to be sure. Is this the way of declaring a full config file, with a volume ? Doesn't seem to work for me when I access to your endpoint /backend/config. Always show me default config file.

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    volumes:
      **- ./config/ryot.json:/config/ryot.json**
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
    ports:
      - "8282:8000"
    pull_policy: always
    container_name: ryot

Thanks for your time !

**Comment by IgnisDa** [comment]
@matthieurosset I think you edited your original comment but just in case you need it later, the config files need to be mounted to `/home/ryot/config/ryot.json`.
