### ISSUE TITLE
[Feature Request] Add support for multiple watchings

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [IgnisDa/ryot#65]
A lot of people rewatch shows/movies/ re-read books etc. Having an option to add to the watch count would be pretty cool :)

**Comment by IgnisDa** [comment]
I don't really understand what you mean by this. You can add a single item to history multiple times.

**Comment by Gandalf-the-Blue** [comment]
Ah, I see. I think a better UI for history is what is needed then, grouping by seasons and showing a count outside (based on number of episodes seen * no of watches)

**Comment by IgnisDa** [comment]
If you go to the seasons tab, you can see how many times you have seen an episode.
![Uploading image.png…]()

**Comment by Gandalf-the-Blue** [comment]
I guess I didn't notice this. My bad.
