### ISSUE TITLE
Updating Metadata not Working

### ISSUE THREAD

**Issue by rr151panda** [IgnisDa/ryot#650]
The service has been working great for me, however a few weeks ago, all metadata for media wont update, with shows and podcasts not showing new or updated episodes. I have tried updating metadata for both individual media, as well as all items, but neither works.
A few examples with the demo, which is working correctly, and then my instance with old/out of data info:
![image](https://github.com/IgnisDa/ryot/assets/62541886/eff4459a-3a3c-4905-b257-5913355b81d6)
![image](https://github.com/IgnisDa/ryot/assets/62541886/16a2f03c-45d4-41c9-97a9-dfa79e89d364)

![image](https://github.com/IgnisDa/ryot/assets/62541886/51cd6459-54b0-40da-bcf8-577a693d8c9d)
![image](https://github.com/IgnisDa/ryot/assets/62541886/8453065a-e069-4243-b0a1-5d7fc9b7bc06)

Ive checked the logs for both frontend and backend, but they dont seem to be showing any errors:
[frontend] GET /media/item/788?intent=deployUpdateMetadataJob&_data=routes%2F_dashboard.media.item.%24id._index 200 - - 241.200 ms
[frontend] POST /media/item/788?intent=deployUpdateMetadataJob&_data=routes%2F_dashboard.media.item.%24id._index 200 - - 24.301 ms
[frontend] GET /media/item/788?intent=deployUpdateMetadataJob&_data=root 200 - - 4.420 ms
[frontend] GET /media/item/788?intent=deployUpdateMetadataJob&_data=routes%2F_dashboard 200 - - 35.024 ms

Not quite sure whats happening here, especially as I'm not getting error per se, so sorry if this has some easy fix I'm missing
Thanks so much!

**Comment by IgnisDa** [comment]
Set env variable `RUST_LOG: ryot=debug` and then update any one metadata and then show me the logs.

**Comment by rr151panda** [comment]
The issue seems to have resolved itself somehow, however I added RUST_LOG=debug to my env, and the logs now show the same message being repeated about 20 times a second:
`[backend] 2024-02-21T18:50:42.383819Z DEBUG sqlx::query: summary="SELECT * FROM Jobs ..." db.statement="\n\nSELECT\n  *\nFROM\n  Jobs\nWHERE\n  (\n    status = 'Pending'\n    OR (\n      status = 'Failed'\n      AND attempts < max_attempts\n    )\n  )\n  AND run_at < ?1\n  AND job_type = ?2\nLIMIT\n  ?3\n" rows_affected=0 rows_returned=0 elapsed=51.237µs` 
Not sure is this is any kind of serious issue, but if it is, I cant find any direct problems it's causing.
Thanks so much!

**Comment by IgnisDa** [comment]
Let me know if you see other problems! Thanks for reporting.
