### ISSUE TITLE
Make better use of real estate with high res screens

### ISSUE THREAD

**Issue by makanimike** [IgnisDa/ryot#655]
The main content you are interacting with uses a quite small area when using a 4k screen. It makes it tricky keeping an overview and easily updating your progress. 

![image](https://github.com/IgnisDa/ryot/assets/88232673/aaf0309e-1150-4f14-933b-ef7a097a79ef)

Regardless of which page you are on, it basically only ever uses a frame about the size of the red box. 

I would love to see ryot use more of available screen real estate. It would greatly improve usability and seems like a relatively easy fix to me.

**Comment by IgnisDa** [comment]
What is your screen size?

**Comment by IgnisDa** [comment]
You can try setting the `FRONTEND_ITEM_DETAILS_HEIGHT` env var. The default is 300.

**Comment by makanimike** [comment]
> What is your screen size?

3840 x 2160 px aka 4k

> You can try setting the `FRONTEND_ITEM_DETAILS_HEIGHT` env var. The default is 300.

Tried it out with 1200, 1400 and 1500.
It does not seem to change anything. Certainly not for the detail view, i.e. a specific show or movie. (I restarted the container each time I made a change)

**Comment by makanimike** [comment]
ok sorry. restarting is not enough :)  
a fresh "docker compose up -d" was needed.  
  
It is a huge improvement and will make my life much easier. But it still feels just a little bit awkward still. More  width could be used :)

But mostly, thanks for the amazing work and for being so responsive.

**Comment by IgnisDa** [comment]
Can you show me a screenshot with the updated height.

**Comment by makanimike** [comment]
sure!

![image](https://github.com/IgnisDa/ryot/assets/88232673/ecd5566d-dec2-4fe8-86f2-081417bccd69)


So the content that is relevant for me right now (the episode list) is barely using 1/4 of the available screen width - and that is already after deducting the side bar.

**Comment by IgnisDa** [comment]
Hmm that indeed looks bad.

Are you aware of any method I can use to simulate 4k screens?

**Comment by makanimike** [comment]
I am not sure. A VM should be possible?

**Comment by IgnisDa** [comment]
Alright I will research about it. Thanks for reporting the issue. I couldn't have found it myself.

**Comment by tboby** [comment]
> Hmm that indeed looks bad.
> 
> Are you aware of any method I can use to simulate 4k screens?

Chrome dev tools does this. F12, then Ctrl-shift-M to open the device tools, then in the bar open the dropdown and create a custom screen size.

**Comment by IgnisDa** [comment]
I'd appreciate if someone makes a PR for this. I don't have the bandwidth to work on this.
