### ISSUE TITLE
Error opening TV Show

### ISSUE THREAD

**Issue by StoffelCPR** [IgnisDa/ryot#657]
Heyo,

I get an error trying to open Star wars the clone wars on my ryot. App version is 4.2.10

```console
ryot     | [backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/miscellaneous/resolver.rs:1745:72:
ryot     | [backend] called `Option::unwrap()` on a `None` value
```

![image](https://github.com/IgnisDa/ryot/assets/32580372/94c20167-7301-4f4a-b91b-3f7fb6a4929c)

**Comment by IgnisDa** [comment]
Can you try following https://github.com/IgnisDa/ryot/issues/638#issuecomment-1945239011 and LMK if it works?

**Comment by StoffelCPR** [comment]
That indeed fixed the error;

As to it's occurence:

I think I was using the `Mark as seen` feature with `mark all previous seasons as seen` and during that it kinda fucked up.

The seasons are now all marked as seen whatsoever and I am gonna try to do it again ( as I have watched to show multiple times already :D )

Thanks ;)

**Comment by IgnisDa** [comment]
Yep, this has already been fixed by a recent version, the once that you just deleted were probably from a previous version.
