### ISSUE TITLE
ERROR ryot: Database migration failed: Execution Error: error returned from database: relation "metadata_to_metadata" already exists

### ISSUE THREAD

**Issue by Dornisaurio** [IgnisDa/ryot#658]
Hello! the other day I experienced this [issue](https://github.com/IgnisDa/ryot/issues/638)
I ran the querie suggested there, and it fixed the issue for me!

However now after a reboot, I encountered this error:
`
Feb 25 19:09:27 server docker-ryot-start[33648]: [backend] 2024-02-26T01:09:27.897621Z  INFO ryot: Running version: 4.2.10
Feb 25 19:09:27 server docker-ryot-start[33648]: [backend] 2024-02-26T01:09:27.906030Z  INFO sea_orm_migration::migrator: Applying all pending migrations
Feb 25 19:09:27 server docker-ryot-start[33648]: [backend] 2024-02-26T01:09:27.907100Z  INFO sea_orm_migration::migrator: Applying migration 'm20231219_change_column_types'
Feb 25 19:09:27 server docker-ryot-start[33648]: [backend] 2024-02-26T01:09:27.912590Z  INFO sea_orm_migration::migrator: Migration 'm20231219_change_column_types' has been applied
Feb 25 19:09:27 server docker-ryot-start[33648]: [backend] 2024-02-26T01:09:27.913138Z  INFO sea_orm_migration::migrator: Applying migration 'm20231219_create_metadata_relations'
Feb 25 19:09:27 server docker-ryot-start[33648]: [backend] 2024-02-26T01:09:27.914078Z ERROR ryot: Database migration failed: Execution Error: error returned from database: relation "metadata_to_metadata" already exists
Feb 25 19:09:27 server docker-ryot-start[33648]: [backend] Error: There was an error running the database migrations.
Feb 25 19:09:27 server docker-ryot-start[33648]: [proxy] {"level":"info","ts":1708909767.9184244,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Feb 25 19:09:27 server docker-ryot-start[33648]: [backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 1
Feb 25 19:09:27 server docker-ryot-start[33648]: --> Sending SIGTERM to other processes..
Feb 25 19:09:27 server docker-ryot-start[33648]: node:events:492
Feb 25 19:09:27 server docker-ryot-start[33648]:       throw er; // Unhandled 'error' event
Feb 25 19:09:27 server docker-ryot-start[33648]:       ^
Feb 25 19:09:27 server docker-ryot-start[33648]: Error: spawn ps ENOENT
Feb 25 19:09:27 server docker-ryot-start[33648]:     at ChildProcess._handle.onexit (node:internal/child_process:286:19)
Feb 25 19:09:27 server docker-ryot-start[33648]:     at onErrorNT (node:internal/child_process:484:16)
Feb 25 19:09:27 server docker-ryot-start[33648]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Feb 25 19:09:27 server docker-ryot-start[33648]: Emitted 'error' event on ChildProcess instance at:
Feb 25 19:09:27 server docker-ryot-start[33648]:     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
Feb 25 19:09:27 server docker-ryot-start[33648]:     at onErrorNT (node:internal/child_process:484:16)
Feb 25 19:09:27 server docker-ryot-start[33648]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
Feb 25 19:09:27 server docker-ryot-start[33648]:   errno: -2,
Feb 25 19:09:27 server docker-ryot-start[33648]:   code: 'ENOENT',
Feb 25 19:09:27 server docker-ryot-start[33648]:   syscall: 'spawn ps',
Feb 25 19:09:27 server docker-ryot-start[33648]:   path: 'ps',
Feb 25 19:09:27 server docker-ryot-start[33648]:   spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 17 ]
Feb 25 19:09:27 server docker-ryot-start[33648]: }
Feb 25 19:09:27 server docker-ryot-start[33648]: Node.js v20.10.0
Feb 25 19:09:28 server systemd[1]: docker-ryot.service: Main process exited, code=exited, status=1/FAILURE`

Is there anything I could do to fix it?

**Comment by IgnisDa** [comment]
Which was the first version you started? This migration is very old (was written 2 months ago).

**Comment by IgnisDa** [comment]
Please connect to the database and run the following query:
```sql
select * from seaql_migrations;
```

**Comment by Dornisaurio** [comment]
I installed it back in December, this is the output of that command. I  worry that I may have ran migration queries when I am not entirely sure I needed to, is there any way to recover my database?
                   version                   | applied_at 
---------------------------------------------+------------
 m20230410_create_metadata                   | 1684693316
 m20230413_create_person                     | 1684693316
 m20230417_create_user                       | 1684693316
 m20230419_create_seen                       | 1684693316
 m20230501_create_metadata_group             | 1697640078
 m20230502_create_genre                      | 1684693316
 m20230504_create_collection                 | 1684693316
 m20230505_create_review                     | 1684693316
 m20230509_create_import_report              | 1684693316
 m20230622_create_exercise                   | 1697640078
 m20230804_create_user_measurement           | 1697640078
 m20230819_create_workout                    | 1697640078
 m20230901_create_partial_metadata           | 1697640078
 m20230912_create_calendar_event             | 1697640078
 m20231003_create_partial_metadata_to_person | 1697640078
 m20231016_create_collection_to_entity       | 1697640078
 m20231017_create_user_to_entity             | 1697640078

**Comment by IgnisDa** [comment]
I will need access to your database.

Please dump your database and email it to me (email in my GH profile).

`docker exec -u postgres -i ryot-db pg_dump -Fc --no-acl --no-owner > /tmp/ryot.file.sql`

**Comment by Dornisaurio** [comment]
I much appreciate it! 

I shared a google drive link to you with it.

**Comment by IgnisDa** [comment]
@Dornisaurio I was able to get it working! Run this SQL:

```sql
DELETE FROM public.seaql_migrations;
INSERT INTO public.seaql_migrations (version, applied_at) VALUES
('m20230410_create_metadata', 1704032601),
('m20230413_create_person', 1704032601),
('m20230417_create_user', 1704032601),
('m20230419_create_seen', 1704032601),
('m20230501_create_metadata_group', 1704032601),
('m20230502_create_genre', 1704032601),
('m20230504_create_collection', 1704032601),
('m20230505_create_review', 1704032601),
('m20230509_create_import_report', 1704032601),
('m20230622_create_exercise', 1704032601),
('m20230804_create_user_measurement', 1704032601),
('m20230819_create_workout', 1704032601),
('m20230901_create_partial_metadata', 1704032601),
('m20230912_create_calendar_event', 1704032601),
('m20231003_create_partial_metadata_to_person', 1704032601),
('m20231016_create_collection_to_entity', 1704032601),
('m20231017_create_user_to_entity', 1704032601),
('m20231219_change_column_types', 1704032601),
('m20231219_create_metadata_relations', 1704032601);
```

**Comment by Dornisaurio** [comment]
WORKED like a charm!!!!!!
THANK YOU so much!!

**Comment by IgnisDa** [comment]
You have more data than me, haha. I love seeing people using Ryot. Thanks!

**Comment by Dornisaurio** [comment]
It's a really handy application! and I plan to migrate a lot more data i have on some spreadsheets manually later, your application makes looking at all your media consumptions in retrospective feel very organized, satisfactory, and overall professional, thank you so much for the help!
