### ISSUE TITLE
"thread 'tokio-runtime-worker'" when marking full season as seen

### ISSUE THREAD

**Issue by equignon** [IgnisDa/ryot#659]
# Description

Marking a whole season as seen is causing this error:

```
[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/miscellaneous/resolver.rs:2539:60:
[backend] called `Option::unwrap()` on a `None` value
```

# Steps to reproduce

1. Open any show
2. Mark a full season as seen, with or without the option to mark also past seasons

# Environment

- Ubuntu 22.04.4 LTS
- Docker version 25.0.3
- Stack handled through Portainer 2.19.4
- Changed ports to 7000:8000

# Notes

I've tried to follow this comment but in my case, nothing is detected: https://github.com/IgnisDa/ryot/issues/638#issuecomment-1945239011

Here are the last lines of the logs: [_ryot_logs.txt](https://github.com/IgnisDa/ryot/files/14411753/_ryot_logs.txt)

**Comment by IgnisDa** [comment]
Thanks for reporting!
