### ISSUE TITLE
[Feature Request] Add a calendar for upcoming TV episodes/movies

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [IgnisDa/ryot#66]
Adding a calendar (especially with CalDAV support) would allow the user to be on top of any new episodes of their shows. Adding CalDAV support would allow it to be a full fledged alternative to other apps such as SeriesGuide and Simkl.

**Comment by IgnisDa** [comment]
@Gandalf-the-Blue Working on this. Do you have any example of movies and TV shows that are upcoming?

**Comment by dimon222** [comment]
@IgnisDa 
TMDB samples:
Shows - can pick any show with future coming season. Loki season 2
https://www.themoviedb.org/tv/84958-loki/season/2
Or movie
Openheimer
https://www.themoviedb.org/movie/872585-oppenheimer

**Comment by IgnisDa** [comment]
Makes sense. Thanks.

**Comment by IgnisDa** [comment]
@Gandalf-the-Blue Do you have an example in mind on what the UI for this should look like?

**Comment by Gandalf-the-Blue** [comment]
Something similar to what sonarr has?
As long as you can subscribe to the calendar outside the app - it shouldn't be a huge UI specific component.

**Comment by IgnisDa** [comment]
> you can subscribe to the calendar outside the app

What does this mean?

**Comment by Gandalf-the-Blue** [comment]
So you can look at sonarr and other related arr projects, they include an **iCal link** to their calendars - that way you can subscribe to that calendar from your main calendar app be it Google, Apple, Proton etc.

**Comment by dimon222** [comment]
Perhaps, something could be created with this library on new endpoint call dynamically or cached for 1 hour period on call.
https://github.com/hoodie/icalendar-rs#example
