### ISSUE TITLE
[FEATURE REQUEST] - Notifications for different roles of actors

### ISSUE THREAD

**Issue by saschabrockel** [IgnisDa/ryot#661]
I am following up on this feature/issue: https://github.com/IgnisDa/ryot/issues/580#issuecomment-1965881587

It would be lovely to differentiate between the roles of actors in movies/series because not everybody cares if, for example, Jason Statham is the executive producer of a movie but if he is an actor in that movie.

So a difference between these roles would be really nice.

**Comment by IgnisDa** [comment]
Closing this since this will introduce too much complexity to the application.
