### ISSUE TITLE
PushOver Notification not working

### ISSUE THREAD

**Issue by NoxRare** [IgnisDa/ryot#672]
I'm getting a fully white page with the code "200" and title changes to "Unhandled Thrown Response!" when attempting to add a Push Over notification agent. Discord works fine, but Pushover doesnt seem to work correctly, running on docker and fresh install.

**Comment by IgnisDa** [comment]
So it doesn't get created at all?

**Comment by NoxRare** [comment]
> So it doesn't get created at all?

Nope, it does not get created at all, I've filled in the information as required and it does not create, just redirects me to the white page with the code 200

**Comment by IgnisDa** [comment]
Can you make a video and email it to me? I tried it with my own pushover key. it works fine.

**Comment by NoxRare** [comment]
> Can you make a video and email it to me? I tried it with my own pushover key. it works fine.

I would need to figure out a way to record etc, would you like to url to my instance and just register an account and try it?
Its a public instance anyways, I'm planing on disabling registration in the future anyways.

**Comment by IgnisDa** [comment]
Yeah sure. Before that, can you confirm if there is something in the docker logs that might be related?

**Comment by NoxRare** [comment]
`[frontend] GET /settings/preferences?_data=routes%2F_dashboard.settings.preferences 200 - - 50.228 ms
[frontend] GET /settings/notifications?_data=routes%2F_dashboard.settings.notifications 200 - - 18.559 ms
[frontend] POST /settings/notifications?intent=create&_data=routes%2F_dashboard.settings.notifications 200 - - 48.712 ms`

This is all the logs say when I try to do it, here is the url anyways: https://ryot.majjoduran.xyz/

**Comment by IgnisDa** [comment]
I created an account called `testing` and tried adding my key to it. It works fine.

**Comment by IgnisDa** [comment]
> EDIT: setting my userkey ONLY. works fine!

Yep I am able to reproduce it.

**Comment by NoxRare** [comment]
But I need to specify a appkey aswell, and that breaks it lol.

**Comment by IgnisDa** [comment]
YeP i will push a fix.

**Comment by IgnisDa** [comment]
Upgrade to `v4.2.13` once it is realeased.
