### ISSUE TITLE
Trakt not completing the import

### ISSUE THREAD

**Issue by bonny1992** [IgnisDa/ryot#673]
It seems that the import from Trakt cannot be finished, for some reason.

![image](https://github.com/IgnisDa/ryot/assets/1154368/850d4acb-88c7-4cba-9f93-1763608ee8cb)

**Comment by IgnisDa** [comment]
What is your trakt username?

**Comment by bonny1992** [comment]
Oh the same as my Github's one, `bonny1992`

**Comment by IgnisDa** [comment]
Thanks, found the problem. Will be fixed with the next released.
