### ISSUE TITLE
Add Emby Integration

### ISSUE THREAD

**Issue by Kornster** [IgnisDa/ryot#679]
I`ve come back to this app which is looking great after not using it for a while, Are there plans to add Integration for Emby, i dont use Jellyfin but am using Emby as a daily driver.

Also would you add integration for Kavita (Books) ?

**Comment by IgnisDa** [comment]
I use neither of them myself. So unless I get a sizeable donation for this, I do not think I will work on this. I also do not have an Emby premium account, so that is a hindrance too.

**Comment by IgnisDa** [comment]
As for kavita, the author does not want to add support (#196).

**Comment by IgnisDa** [comment]
Closing as duplicate of #187.
