### ISSUE TITLE
Video games not appearing in Media - Video Games menu

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#681]
Hey,

When viewing games via Media -> Video Games like usual, none of my games show up, saying "You do not have any saved yet". However, I added many games over the last few days, and they still exist in the db somewhere, since I can see a few in the Dashboard, and can see some when looking at the entries of a collection in the collections screen, from the genres section, etc.

Just cant see them from the main Video Games screen.

Thanks!

**Comment by IgnisDa** [comment]
The media will show up there only if one the following conditions is satisfied: https://github.com/IgnisDa/ryot/blob/5fa024be98de46c9b40b01c926fa8fb21317793d/libs/database/src/migrations/m20231017_create_user_to_entity.rs#L24-L29

**Comment by IgnisDa** [comment]
Please confirm if you have done this for a video game

**Comment by kaibagley** [comment]
All of my games should meet at least one of those. They showed up for the last week and I only noticed they weren't showing today.

**Comment by IgnisDa** [comment]
Please send me a dump of your database. My email is in my GH profile.

**Comment by IgnisDa** [comment]
Thanks I have found the issue. Will be fixed in the next release.

**Comment by IgnisDa** [comment]
For the time being, as a workaround, you can re-enable "display nsfw" in your preferences.

**Comment by kaibagley** [comment]
Very interesting, thanks for your hard work!
