### ISSUE TITLE
Plex integration throws error 404

### ISSUE THREAD

**Issue by NoxRare** [IgnisDa/ryot#682]
`[frontend] POST /backend/webhooks/integrations/plex/nBrLZdk53g--6EVbs 404 - - 25.598 ms
[frontend] Error: No route matches URL "/backend/webhooks/integrations/plex/nBrLZdk53g--6EVbs"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4496:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2935:19)
[frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:182:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:107:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend] ErrorResponseImpl {
[frontend]   status: 404,
[frontend]   statusText: 'Not Found',
[frontend]   internal: true,
[frontend]   data: 'Error: No route matches URL "/backend/webhooks/integrations/plex/nBrLZdk53g--6EVbs"',
[frontend]   error: Error: No route matches URL "/backend/webhooks/integrations/plex/nBrLZdk53g--6EVbs"
[frontend]       at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4496:5)
[frontend]       at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2935:19)
[frontend]       at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:182:35)
`

I've generated a url for my plex using both full name and username and I always end up getting 404 errors. any ideas?

**Comment by IgnisDa** [comment]
Would it be possible for you to give me access to your Plex premium account temporarily. Since I do not have a membership, I have no way to reproduce and fix this error.

**Comment by NoxRare** [comment]
I can invite you to my plex home, that will give you plex pass on your own account.

**Comment by IgnisDa** [comment]
That sounds great. My email is ignisda2001@gmail.com

**Comment by IgnisDa** [comment]
@NoxRare  I gave you the wrong email. Please add my username "ignisda" to your Plex pass. Sorry for the confusion. You can revoke the earlier access you sent.

**Comment by NoxRare** [comment]
> @NoxRare I gave you the wrong email. Please add my username "ignisda" to your Plex pass. Sorry for the confusion. You can revoke the earlier access you sent.

Gotcha, invite has been sent.

**Comment by IgnisDa** [comment]
I still dont have access to webhooks.
![image](https://github.com/IgnisDa/ryot/assets/60938164/b80ef06e-848c-4ae5-8591-550c549c33f6)

On the "switch user" button, I do find your username but when I click on that, it asks for a pin.
![image](https://github.com/IgnisDa/ryot/assets/60938164/40322dae-8296-4094-88d1-a4ca8d303c68)

**Comment by NoxRare** [comment]
Log out of your account and back in, it should share the plex pass with you once you've done that. I sadly have a lot of people on my server with personal data I cannot share my account. None of the people in my plex home have plex pass on their own but they still have all the features thru the plex home.

**Comment by IgnisDa** [comment]
> Log out of your account and back in

I did that. Nothing changed.

**Comment by NoxRare** [comment]
After reading the plex wiki, youre correct. Only access is given to plex apps not other plex pass features, alternatively you can give me a webhook and I can use it on my account. But sharing my account with my family and friends IP's and other personal data accessable will not work sadly. I'm open to adding you on discord and using any webhook you provide.

**Comment by IgnisDa** [comment]
My discord username is ignisda.

**Comment by NoxRare** [comment]
it was skill issue on my end, I configured my cloudflare tunnel to use the port 3000 instead of 8000.
