### ISSUE TITLE
ryot with kodi question

### ISSUE THREAD

**Issue by staufl** [IgnisDa/ryot#686]
Not sure if this is an issue or a question.  I have ryot deployed locally and it appears to work fine.  I generated a kodi slug via the integrations page and put it in the kodi integration.  Nothing happens though.  What should I expect to see?  I was hoping my watched history on kodi would get sent to the ryot database but I can't even seem to prove the kodi box is connecting to ryot.  What is the format of what I enter on kodi?  Any specifics more that "fill in the correct details" in the docs might be helpful.

Thank you.

**Comment by IgnisDa** [comment]
The integrations are meant to sync just the currently in progress media.

**Comment by IgnisDa** [comment]
It does not sync old shows that you have already watched.

**Comment by staufl** [comment]
Ok thanks for the attempt.  Guess I will keep looking elsewhere.
