### ISSUE TITLE
Movies stopped updating and Summary stopped calculating

### ISSUE THREAD

**Issue by makanimike** [IgnisDa/ryot#688]
Has anyone else come across this?  
My movies stopped updating, and the Summary stopped calculating 15 days ago. I cannot seem to nudge it either. I tried updating, restarting the docker container, rebooting the server. Shows are still updating perfectly fine. Seems a bit weird that something seems to only be blocking movies....

**Comment by IgnisDa** [comment]
Set `RUST_LOG=ryot=debug` env variable and try generating summary from the miscellaneous settings and show me the logs that pop up.

**Comment by makanimike** [comment]
I don't think that does anything?  
I tried twice. There is no visual feedback that something is happening. So I just trust the description and gave it a couple of hours.

**Comment by IgnisDa** [comment]
> I don't think that does anything?

It should show up in the docker logs.

> What I forgot mentioning in the OP is that while I am watching a movie ryot does recognize it as "in Progress".

Once a movie is completed, it is removed from the "In Progress" collection. You can find it again in the Movies page (accessible via the sidebar).

**Comment by makanimike** [comment]
no new logs appear in ./ryot-data/tmp  
   

> Once a movie is completed, it is removed from the "In Progress" collection. You can find it again in the Movies page (accessible via the sidebar).  

That's what I meant that it stops updating. After "In Progress" it does not appear on the page .../media/list/movie. But it did in the past. The latest movie that automatically appears on the Movies page was played on Feb 21.  

I can manually search for a movie that I watched since then though. And then it will at least recognize that I did complete it in the History tab.

**Comment by IgnisDa** [comment]
> no new logs appear in ./ryot-data/tmp

It should just appear in the console logs. Not any file. Just show me the output of `docker logs ryot`.

> I can manually search for a movie that I watched since then though. And then it will at least recognize that I did complete it in the History tab.

If the start/end date of the history is not defined, it will not show up in the front pages. It will always be after the movies which have those.

**Comment by makanimike** [comment]
that log is a 206MB txt file. It is an endless wall of timestamps.  
  
this section regularly appears in between those time stamps:  
`[backend] thread 'tokio-runtime-worker' panicked at apps/backend/src/utils.rs:164:43:
[backend] called `Result::unwrap()` on an `Err` value: Query(SqlxError(Database(PgDatabaseError { severity: Error, code: "42703", message: "column \"media_reason\" does not exist", detail: None, hint: None, position: Some(Original(355)), where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("parse_relation.c"), line: Some(3656), routine: Some("errorMissingColumn") })))
[backend] [2m2024-03-11T11:01:36.448546Z[0m [34mDEBUG[0m [2mryot::miscellaneous::resolver[0m[2m:[0m Processing integration webhook for Jellyfin
[backend] [2m2024-03-11T11:01:36.462952Z[0m [34mDEBUG[0m [2mryot::miscellaneous::resolver[0m[2m:[0m Input for progress_update = ProgressUpdateInput { metadata_id: 3108, progress: Some(54), date: Some(2024-03-11), show_season_number: None, show_episode_number: None, podcast_episode_number: None, anime_episode_number: None, manga_chapter_number: None, change_state: None }
[backend] [2m2024-03-11T11:01:36.472711Z[0m [34mDEBUG[0m [2mryot::miscellaneous::resolver[0m[2m:[0m Progress update action = Update
[backend] [2m2024-03-11T11:01:36.495142Z[0m [34mDEBUG[0m [2mryot::miscellaneous::resolver[0m[2m:[0m Progress update = Model { id: 424, progress: 54, started_on: Some(2024-03-10), finished_on: None, user_id: 1, metadata_id: 3108, state: InProgress, updated_at:`  


at the end there are some normal logs again, as attached. 
[ryot_logs.txt](https://github.com/IgnisDa/ryot/files/14562549/ryot_logs.txt)

**Comment by IgnisDa** [comment]
Yep. Looks like a migration did not run.

Please create a dump of your database and email it to me. Command: `docker exec -u postgres -i ryot-db pg_dump -Fc --no-acl --no-owner > /tmp/ryot.file.sql`

**Comment by makanimike** [comment]
current version 4.2.15. (Part of my troubleshooting was updating).  
  
That file is a 277MB file. Will your mail server accept that?

**Comment by IgnisDa** [comment]
You can share a google drive link or anything like that if you prefer.

**Comment by IgnisDa** [comment]
I went through you dump. I am not sure why, but a migration did not run. Connect to your db and run this sql:
```sql
ALTER TABLE user_to_entity add COLUMN media_reason text[];
```

I did not test it completely, but summary calculation and movies updating is working fine after running above.

Please do let me know if you have any other problems.

**Comment by makanimike** [comment]
thanks. I do this with pgadmin?

**Comment by makanimike** [comment]
sorry that I am having issues about every single step.  
  
when I run `docker exec -u postgres -i ryot-db psql` nothing happens. the CLI just goes into that empty line, so it looks like it is working on something. But nothing does. It just stays like that for hours. Until I cancel it with ctrl+c

**Comment by IgnisDa** [comment]
Try `docker exec -u postgres -it ryot-db psql`

**Comment by makanimike** [comment]
that seems to have worked. 

When I then did this...
> ```sql
> ALTER TABLE user_to_entity add COLUMN media_reason text[];
> ```

it seems to have been instantly finished. The calculation does indicate that it runs now. The number of media watched in the Summary on the dashboard has increased, as has the total time watched.  
But My Movie list does not show the viewed movies. Perhaps it needs some time to build the list of thumbnails...?

**Comment by IgnisDa** [comment]
nO there isn't anything to build. Can you confirm you are running the latest version of Ryot?

**Comment by makanimike** [comment]
I believe so...  
![image](https://github.com/IgnisDa/ryot/assets/88232673/4ceb8b63-4c9e-424c-a06c-e43e1d46db7d)

**Comment by IgnisDa** [comment]
Can you change the nsfw settings in the general preferences and see if that fixes it?

**Comment by makanimike** [comment]
no change.  
  
another small inconsistency I noticed is the summary above says 51 movies. Once I click onto the movie page it says there are 50 items. (but more movies I watched in the last 1-2 weeks, and that ryot recognized during play as "In Progress", do not appear in the list)

**Comment by makanimike** [comment]
ah. If I restart watching the film (in Jellyfin with the integration) for a few seconds, then it will kickstart whatever is going on and it will now appear!

**Comment by IgnisDa** [comment]
I think your database has gotten messed up beyond repair. Not sure I can fix it.

What you can do is perform an export and then import it back using "Media Json" option.

**Comment by makanimike** [comment]
what is the simplest clean way to delete the db and start fresh? just manually delete the postgres folder? Delete the docker container and start from scratch?  
  
On a side-note: I have noticed that postgres apps are incredibly sensitive. I also use vikunja that used a postgres db (on kubernetes) and it would regularly stop working. I ended up moving it to another server where I could manually install with a mariadb/mysql db.

**Comment by IgnisDa** [comment]
Yes just deleting the storage folders should do the trick.

**Comment by makanimike** [comment]
it looks like it worked. The ridiculous postgres folder size of 2.2GB got reduced to 45M. It is still downloading media on the items. But it looks like it is reconstructing everything. Some media items are wrongly stuck in "In Progress". But my guess is that is part of the corrupt original DB. And that should be easy to update.

thank you so much for your patience.
