### ISSUE TITLE
Metadata Refresh with Trakt Import

### ISSUE THREAD

**Issue by JPDVM2014** [IgnisDa/ryot#690]
Creating an issue as requested. Copied my post from discussions. Thanks!

---

I imported my Trakt history, and it seems to have worked; however, no data loads for shows/movies until I click into them. So, my summary will never be correct unless I go through and click into each item.

![Screenshot_20240311_110830_Mull.jpg](https://github.com/IgnisDa/ryot/assets/18446490/3efcdafa-b7b9-4c09-91d3-7475ad31c838)

Movie and shows just show as gray boxes with letters until I click into it.
![Screenshot_20240311_111638_Mull_1.jpg](https://github.com/IgnisDa/ryot/assets/18446490/ff4dd5f6-1c1f-43d9-85f1-7378e7b2e6c6)

I've run the update metadata and summary job a few times with no change.

**Comment by IgnisDa** [comment]
I will make a quick fix for this. The "Update all metadata job" will now work as expected.

**Comment by JPDVM2014** [comment]
> I will make a quick fix for this. The "Update all metadata job" will now work as expected.

Works great, thanks!
