### ISSUE TITLE
Unreasonably many "Groups" and "People"

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#694]
I have only ~200 movies and ~20 books in my instance right now (referring to the number in the respective tab when no filters are applied).
In the "Groups" tab however, I have ~1000 entries mostly of films I have never added to ryot.

Even worse, in the "People" tab, there are 160k entries!
Here I noticed that it's mostly book publishers and author (mostly ones I have *not* read) at the beginning (with hundreds of items) but at the end there are also many "random" people with "0 entries".

Were these entries just cached when I searched for stuff?
If this is a feature not a bug then I propose that only groups and people are being shown that are actually related to the media in my library.
This used to be the case and I did not notice when precisely this changed.
In general, filters for these categories of some sort would be nice as well (as I see you are working on #675 right now).

**Comment by LnLcFlx** [comment]
Oh sorry I am just now seeing that [you already mentioned](https://github.com/IgnisDa/ryot/issues/675#issuecomment-1987040913) part of my issue in #675.

**Comment by IgnisDa** [comment]
Yep this should be fixed once #675 is closed.

I plan to address the same for groups in a different release.

**Comment by IgnisDa** [comment]
Closing in favor of #695  and #675.
