### ISSUE TITLE
[Feature Request] “How did you watch this?” Statistic 

### ISSUE THREAD

**Issue by j450n1** [IgnisDa/ryot#699]
I can’t think of a very good name for this, but basically a great addition to the graphs suggested on #445  would be streaming service listed by usage. 

When you mark an item as watched an additional selection below the date for “how did you watch this?” Where you a presented with a list of providers either generated from just watch like with the watch providers tab or a huge generic list that the user can deselect the providers they don’t use / Add their own. 

Below is a shoddy drawing of how I imagine it may look. 

![IMG_4826](https://github.com/IgnisDa/ryot/assets/163571058/d5b63c52-8221-4ee8-874e-051dbc8f21bd)

**Comment by j450n1** [comment]
I’m conscious I don’t want to be splurging ideas all over the place, but a possible extension to this (Let me know if a new issue is needed), if the user selects their streaming services in settings, this data could also be used to notify them if something in their watch list has been added to a streaming service that they have listed using the watch providers tab? 

I.e I’ve had interstellar on my watchlist for a while, maybe a weekly scheduled check to see if anything on the watchlist has been added to a streaming service I use. So I get a notification that Interstellar has been added to Netflix(UK)

**Comment by IgnisDa** [comment]
Yep, that definitely warrants a separate issue.

---

Should the list of providers that come up on "Where did you watch it" be static? I can think of many extensions to this. For example, I watch The office on Netflix or on Kodi depending on which device I am. So should the provider be configurable on the media level or seen level?

**Comment by j450n1** [comment]
No problem, I’ll make another issue for you.

For the list, would a dynamic list be pulled from just watch? As you mentioned Kodi, that wouldn’t appear on a just watch list. You could potentially have a mix of both and (as the attached screenshot shows) have “suggested providers” which the providers that just watch outputs and then a generic list below that containing kodi Plex and other streaming services that aren’t generated by just watch? 
![IMG_4827](https://github.com/IgnisDa/ryot/assets/163571058/7c88c8d4-c54b-4eaf-b4df-b092ca97ab27)


I think at the seen level, for the exact scenario you described, if you are on season 10 episode 5 already and you watch a quick 2 episodes on your phone, you can click update progress select episode 7 and click kodi as the provider you used. Then when you’re at home you and you watch a further 3 episodes of the office you can update your progress to season 10 episode 10 and select Netflix as your watch provider.

**Comment by IgnisDa** [comment]
@j450n1 Can you give me a list of watch providers that I can set as default? Users will be allowed to add new ones too.

**Comment by j450n1** [comment]
I imagine this maybe a good list to start with.

Netflix, Amazon Prime Video, Disney+, HBO Max, Apple TV+, Peacock, Paramount+, Discovery+, Crunchyroll, Pandora, Shudder, Now TV

**Comment by IgnisDa** [comment]
@j450n1 This has been released with `v4.3.13`. Please let me know how it works for you.

**Comment by j450n1** [comment]
Brilliant will give this a go!

**Comment by j450n1** [comment]
![image](https://github.com/IgnisDa/ryot/assets/163571058/90af05df-9003-4c1a-b4c9-697523a0775e)

Fantastic works a treat! Thank you!
