### ISSUE TITLE
[FEATURE REQUEST] - Notification for Watchlist item being added to a service you have access to

### ISSUE THREAD

**Issue by j450n1** [IgnisDa/ryot#700]
Potentially add a section into setting where a user selects their streaming services, this data could also be used to notify them if something in their watch list has been added to a streaming service that they have listed using the watch providers tab?

I.e I’ve had interstellar on my watchlist for a while, maybe a weekly scheduled check to see if anything in the watchlist has been added to a streaming service I use. So I get a notification that Interstellar has been added to Netflix(UK)

There would probably be a need for some logic to stop double notifications, I.e a new series gets released and you get a notification it’s available to watch and it’s been added to a streaming service you have.

**Comment by IgnisDa** [comment]
Are you aware of any platforms that provide this data? Justwatch API access is not open to public use.

**Comment by IgnisDa** [comment]
The JustWatch API is not publically available. Closing this since I could not find APIs that do this well.
