### ISSUE TITLE
Reordering dashboard elements doesn't work

### ISSUE THREAD

**Issue by Kwbmm** [IgnisDa/ryot#702]
I have been trying to put the "In Progress" shows first and then the "Upcoming" in second place but after I drag the "In Progress" in first place and save, upon refresh "Summary" is back on top.

**Comment by IgnisDa** [comment]
There is a fixme comment for this that I never got around to fixing.

https://github.com/IgnisDa/ryot/blob/6d0382113acc91e323b2b69ba7da8d34741b629d/apps/frontend/app/routes/_dashboard.settings.preferences.tsx#L213
