### ISSUE TITLE
GraphQL documentation is lacking

### ISSUE THREAD

**Issue by Kwbmm** [IgnisDa/ryot#704]
While working on importing my TVTime data (see #703 ), I have seen on the docs the following:

> You can see the descriptions of the failing importing steps by reviewing the documentation of the ImportFailStep enum in the /backend/graphql endpoint.

There are a few issues with that:

  -  To the uninitiated, it would be useful to write in the docs the full URL of the GraphQL dashboard / playground. The project doesn't explicitly states it is using GraphQL as a middleware between the Rust backend and the JS frontend.
  -  To actually read the `ImportFailStep`, you need to be authenticated, otherwise you get a permission denied error. There is no documentation on how one is supposed to login through the GraphQL playground. I have tried many things, but none have worked.

**Comment by IgnisDa** [comment]
I'll take a look into improving it.
