### ISSUE TITLE
[Feture Request] Be able to import OpenScale metrics

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#711]
Some of us use OpenScale to read metrics from digital scales. Ref: https://github.com/oliexdev/openScale 
At OpenScale app, we are able to export metrics thru a .csv file, but Ryot is only able to import .json files, so I would like to request a way to import .csv files for metrics, if posible, specifically from OpenScale file exports.
Thank you in advance.

**Comment by IgnisDa** [comment]
@edersong Can you email me your export? I would like to adjust for all edge cases.

**Comment by edersong** [comment]
Sure. Sent!

**Comment by IgnisDa** [comment]
@edersong The export you have sent, did you do it from the android client?

**Comment by edersong** [comment]
Hello @IgnisDa 
It was from OpenScale Pro (Android App) https://play.google.com/store/apps/details?id=com.health.openscale.pro
The unit is Kg.
