### ISSUE TITLE
Suggestion: Setting progress with more detail

### ISSUE THREAD

**Issue by Fyreek** [IgnisDa/ryot#72]
At the moment you can only set the progress via a percentage. You can't really find the place you stopped watching or reading with it.

What about implementing a progress based on the type of tracker?

So for books via page numbers, movies or shows via the exact timestamp you stopped watching, etc?

**Comment by IgnisDa** [comment]
Sounds reasonable. How can we handle those media items that don't have a fixed number to measure against? For example books with no page numbers, or movies whose runtime is not known, or video games.

**Comment by teamcoltra** [comment]
Manual input?

**Comment by IgnisDa** [comment]
What kind of manual input?

**Comment by Fyreek** [comment]
> Sounds reasonable. How can we handle those media items that don't have a fixed number to measure against? For example books with no page numbers (as in, `numPages` is `undefined`), or movies whose runtime is not known, or video games.

Maybe just fall back to the simple percentage slider if no other form of progress is possible?

For movies with unknown runtime just let the user input what ever timestamp he wants. You can still complete the item via the complete button and like that the user can find the exact point where he left the movie the last time.
Same for books with page numbers where the total pages are not known.

**Comment by IgnisDa** [comment]
Can't store exact timestamps or page number since the database keeps track of only percentage (and the rest is calculated on the front-end). Instead of complicating it so, I'll just include an exact timestamp field only for those movies which have runtime defined.
