### ISSUE TITLE
[Suggestion] Add separator to episode list

### ISSUE THREAD

**Issue by arcastro** [IgnisDa/ryot#723]
It's hard to tell which episode the "Mark as Seen" button corresponds to. 
* Does it correspond to the episode above?
* Or does it correspond to the episode below?

In the current UI, it is very confusing.
<img src="https://github.com/IgnisDa/ryot/assets/4576794/ad39de70-0670-4b68-a421-fc7506cf6adf" width="400px"/>

I was surprised to find that it actually corresponds to the episode BELOW the button.
It would be good to have separators to make this clearer.
<img src="https://github.com/IgnisDa/ryot/assets/4576794/8fa50a62-b146-4952-b9bf-39c3921c3a35" width="400px"/>

Note:
* In my opinion, the button should also be moved to below the episode description.
* and the separators should still be added

**Comment by IgnisDa** [comment]
I will add the separator. I do not want to move it below since then it will increase the size of the entire thing (which is already very big IMO).

Thanks for the input!

**Comment by arcastro** [comment]
Dropping a few more options if you're willing to entertain them 😅

<img src="https://github.com/IgnisDa/ryot/assets/4576794/db180efe-aa05-4437-a770-f2bab4da5c14" width="400px"/>

* Title moves up next to the image
* Since title moves up, this allows summary to move up as well
* Since both have moved up, there is now space for the "Mark as Seen" button down below
* no additional vertical space was used in this mock, when compared against the original. 
* Though I admit the button does look a little cramped.  With proper margins on the button, I admit this option would become a slight bit longer, vertically. But not by much

If you want to save more vertical space, something like this could work too.

<img src="https://github.com/IgnisDa/ryot/assets/4576794/dc2eb4e9-3af7-4884-8a43-fb06469d13fb" width="400px"/>

* There should be enough space to allow the title to wrap once (two lines total for a long title)
* But if the title goes longer than two lines, it needs to be [cropped with ellipses](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) (...)
* And when cropped, full title should display on hover

-----

Feel free to disregard all of this.
Adding separators is good enough too 👍
ty for the awesome project!

**Comment by IgnisDa** [comment]
I like the second image, I will implement that. Thanks for the suggestions.

Glad to know you are enjoying using Ryot. I would appreciate any other feedback :).

**Comment by arcastro** [comment]
Just got a chance to try the updates. It looks great! thanks again

**Comment by arcastro** [comment]
@IgnisDa, just noticed the separators on episode list are no longer present. Wondering if you decided to revert the changes

**Comment by IgnisDa** [comment]
Yes. The episodes tab for shows is very overloaded now imo. I plan to
display just seasons there and display episodes in each season in a modal.
In a later release.
