### ISSUE TITLE
Docker issue after pulling 4.3.12 

### ISSUE THREAD

**Issue by j450n1** [IgnisDa/ryot#725]
Hi, I noticed there was a new Ryot version out, so as normal I pulled the latest image and restarted my container, unfortunately this time I have received the following error. 

The container log shows the following error

[frontend] [Error: Unexpected Server Error]
[frontend] GET / 500 - - 51.430 ms
[frontend] TypeError: Cannot read properties of undefined (reading 'collections')
[frontend]     at loader$2 (file:///home/ryot/build/server/index.js?t=1711860448000:13119:66)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
[frontend]     at async Promise.all (index 1)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18)
[frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:15)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:18)
[frontend] [Error: Unexpected Server Error]
[frontend] GET / 500 - - 48.351 ms

Browsing to Ryot displays "Application Error!" message. 

I attempted to revert to the previous image v4.3.11, however I then receive the following errors. I assume because 4.3.12 made DB changes which aren't backwards compatible. 

[backend] 2024-03-31T10:56:36.497970Z ERROR ryot: Database migration failed: Custom Error: Migration file of version 'm20240326_1_add_user_to_entity_constraint' is missing, this migration has been applied but its file is missing
[backend] Migration file of version 'm20240326_2_migrate_user_to_metadata_group_entries' is missing, this migration has been applied but its file is missing
[backend] Migration file of version 'm20240326_0_add_metadata_group_id_column_to_user_to_entity' is missing, this migration has been applied but its file is missing
[backend] Migration file of version 'm20240330_add_is_partial_field_to_metadata_group' is missing, this migration has been applied but its file is missing
[backend] Migration file of version 'm20240326_3_change_metadata_ownership_to_media_ownership' is missing, this migration has been applied but its file is missing
[backend] Migration file of version 'm20240327_add_new_preferences' is missing, this migration has been applied but its file is missing
[backend] Error: There was an error running the database migrations.
[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 1

I have restored from a backup taken this morning and everything seems to be working as expected running v4.3.11.

**Comment by IgnisDa** [comment]
Just clear your cookies and login again. I will find a way to force this.

The reason this happens is because now the user preferences are saved in the cookies (I did this to save round trips to the backend and DB). But these cookies are only set when you login or change preferences. So when I change the related code, the cookies become outdated.

**Comment by IgnisDa** [comment]
@j450n1 The database migrations should be safe to apply with `v4.3.12`, you can migrate safely.

**Comment by j450n1** [comment]
Apologies, went straight to log diving before thinking logically. Will try this out later.
