### ISSUE TITLE
[FEATURE REQUEST] - Allow setting time spent on seen entries

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#730]
Hey,

Thought a nice addition to the video games tracking would be the number of hours spent playing the game.

This could be added to the play history along with the date started/ended.

Thanks for the amazing software!

**Comment by IgnisDa** [comment]
Should be easy enough to add.

Note to self: use generated column.

**Comment by kaibagley** [comment]
I've just pulled the latest update that includes this change, and can see that the number of hours are probably calculated as end time - start time, but is there a way I can manually set this?

The way I personally think would be best is if it represents the number of hours of actual playtime clocked in-game, calculated by steam/playstation etc.

**Comment by kaibagley** [comment]
@IgnisDa Apologies if you've already seen this, would you like me to re-open this?

**Comment by IgnisDa** [comment]
Sorry

**Comment by kaibagley** [comment]
I think if you've played it twice then you should be able to input how long you spent on it both times. So in the history tab you'd see two entries, and they'd both have seperate "playtime" values.

But maybe it would be nice to have some way to see total play time for a game somewhere too, at the top of the history tab maybe?

**Comment by IgnisDa** [comment]
Released as part of [Ryot pro](https://ryot.io/features/).
