### ISSUE TITLE
[Suggestion] Set Dark/Light theme based on system preferences

### ISSUE THREAD

**Issue by arcastro** [IgnisDa/ryot#735]
Looks like light/dark themes are already supported with a toggle on the bottom-left.
However, it always seems to default to the light theme.

Would be great if the default would be based on system preference.
* https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
* https://radek-anuszewski.github.io/prefers-color-scheme-demo/index.html

**Comment by IgnisDa** [comment]
The theme is set on the server side, I don't think there is a way to detect user's preferred media there.

**Comment by IgnisDa** [comment]
The code you are referring to is being run on the server ([read about](https://remix.run/docs/en/main/route/loader) Remix's `loader`), hence we do not have access to the `window`.

**Comment by IgnisDa** [comment]
This might be helpful: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-Prefers-Color-Scheme.

I do not find this a high priority issue to work on it, but if you wish to, I will accept a PR.

**Comment by arcastro** [comment]
> The code you are referring to is being run on the server ([read about](https://remix.run/docs/en/main/route/loader) Remix's loader)

Ah, apologies. Ty for the link and clarification!

> This might be helpful: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-Prefers-Color-Scheme.

Looks good, but no safari+firefox support yet unfortunately.
Does the backend depend on knowing light/dark theme? Could we instead keep it entirely as client state? Apologies not very familiar with remix. 

> I do not find this a high priority issue to work on it, but if you wish to, I will accept a PR.

👍

**Comment by IgnisDa** [comment]
I do not want to keep the theme on the frontend since it results in a flash. I like the way things are right now.

Closing this, thanks for creating the issue.
