### ISSUE TITLE
Discord notification of "x" is now available links to random fly.dev url

### ISSUE THREAD

**Issue by maaknaamaan** [IgnisDa/ryot#739]
I set up a webhook to Discord and today I got a notification that a series was available. However the URL it posted along with the post it made was the following: 
![image](https://github.com/IgnisDa/ryot/assets/83771247/fbd8f30f-4b03-4951-ab6a-fe6f5f755fbc)
S3E6 of Ghosts (https://ryot.fly.dev/media/item/18) has been released today.

It's running in Docker and I've simply used your example docker compose, only adjusted the postgress details.

`services:
  ryot-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: ryot-db

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - FRONTEND_INSECURE_COOKIES=TRUE
    ports:
      - "8000:8000"
    pull_policy: always
    container_name: ryot

volumes:
  postgres_storage:`

**Comment by IgnisDa** [comment]
`FRONTEND_URL=https://ryot.fly.dev` is the default value. Set that env variable to the one you want.
