### ISSUE TITLE
Permission denied after beta 10

### ISSUE THREAD

**Issue by langerdennis** [IgnisDa/ryot#74]
Hi,

when updating the docker image to anything above beta-10, the container stops immediately and throws a

`permission denied (os error 13)`

error. I understand that this is due to folder ownership, but I haven't changed anything. Deleting the volumes and starting fresh also does not help. For now I am stuck on beta-10, but maybe there is a simple fix and this is a user error on my side?

Thanks in advance, great work!

**Comment by IgnisDa** [comment]
Yes this is a deliberate change. Can be fixed by `chmod -R 1001:1001 /path/to/ryot-data`.

**Comment by langerdennis** [comment]
Thanks, working now!
