### ISSUE TITLE
Searching requires exact match

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#742]
Hey,

I'm not 100% sure if this is intentional or not, but at the moment if i search "Dun", I get no results, "Dune" returns only the movie Dune, and "Dune: Part Two" returns the movie Dune: Part Two. 

However, I think that having some kind of partial string matching would improve the user experience ("Dun" returns both "Dune" and "Dune: Part Two", or "un" returns both, plus other movies whose titles contain the string "un)

Thanks!!

**Comment by IgnisDa** [comment]
I fixed this day before yesterday. Can you confirm if it still happens on the latest version?

**Comment by kaibagley** [comment]
The latest version does fix it! Thanks so much!
