### ISSUE TITLE
Allow editing/deleting custom exercises

### ISSUE THREAD

**Issue by empty2k** [IgnisDa/ryot#743]
It seems that I'm unable to find an option to remove a custom-created exercise. Is this feature not implemented yet, or could it be a bug?

**Comment by IgnisDa** [comment]
It is not implmented.

**Comment by IgnisDa** [comment]
If you really need to, you can delete it using SQL. It is in the `exercise` table.

**Comment by IgnisDa** [comment]
I am keeping this open so that I remember to add this feature.

**Comment by kilnake** [comment]
how to delete the single show easily without messing up rest of the library with similar names? 
for example: 90days fiance: pillow talk, 
90 days fiance : before the 90 days. so on... 

is there a way to delete multiple shows from list?

**Comment by IgnisDa** [comment]
@kilnake Please create a new issue, your query is not related to the original issue.
