### ISSUE TITLE
[Bug] - Game not being removed from database

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#744]
Hello again,

I have a game that isn't being removed from my database, after all the conditions for removal have been met.

The only reason I can think of is because it has the same name as another entry maybe? (Devil May Cry  4)

![2024-04-05T19:52:15,438373370+08:00](https://github.com/IgnisDa/ryot/assets/53884957/23e5e1bb-18ad-4500-a429-a08a9fe48149)

Please let me know if you need me to send you a dump of the database

Thanks!

**Comment by IgnisDa** [comment]
The removal job runs every 12 hrs. Has that time period passed?

**Comment by kaibagley** [comment]
Yeah its been about a week, other games have been removed normally since then

**Comment by IgnisDa** [comment]
Can you dump your database and email it to me?

**Comment by kaibagley** [comment]
Sent

**Comment by IgnisDa** [comment]
@kaibagley Found the problem. Will be fixed with the next release.

**Comment by IgnisDa** [comment]
@kaibagley You will have to run this sql in your DB manually: `delete from user_to_entity where metadata_id = 4165;`

**Comment by kaibagley** [comment]
Great work as usual, I'll leave it in there for the next version to remove. Thanks!!

Will leave this open until you're ready to close it

**Comment by IgnisDa** [comment]
> I'll leave it in there for the next version to remove.

There was a bug in the code. It will not be automatically removed.
