### ISSUE TITLE
Request: Abiltiy (API or GraphQL) to programatically create 'seen' entries

### ISSUE THREAD

**Issue by FrozenDragoon** [IgnisDa/ryot#745]
Just spun up a RYOT instance today, and it's pretty cool so far. 

I'm interested in POSTing progress/read/watched data from services which do not have a direct integration. Ideally this would involve an external script/service POSTing a webhook (or other API) to RYOT that isn't tied to a specific integration

Something like the Plex integration that would allow specifying the unique ID/data type/etc, rather than limiting it based on the integration type.
(In this case, I'd like to specifically get progress from a [Komga](https://github.com/gotson/komga) instance using a custom script, but this request is more general)

I've never used GraphQL before, but I was not able to identify a way to programmatically create "seen" entries. (I did notice a delete Seen endpoint, but not create Seen)
There doesn't appear to be another form of API either.

I did take a look at the integrations.rc file, but quickly got lost.
I'd love to create a custom integration, but I've never used Rust at all. I'm still working on getting "proficient" in Python.

**Comment by IgnisDa** [comment]
The mutation to create seen entries is `updateProgress`. Thought if you building an integration, I'd suggest doing it via the `integrations.rs` file.

**Comment by FrozenDragoon** [comment]
Thanks! Maybe I'll take a look at figuring out Rust. But for now, that endpoint will work great.

**Comment by FrozenDragoon** [comment]
Further question/clarification: I wasn't actually able to find `updateProgress`, but I was able to use `deployBulkProgressUpdate` to do what I wanted. 

![image](https://github.com/IgnisDa/ryot/assets/5301673/207ff56c-630f-4b10-9389-2bb3acfbc8ae)

**Comment by IgnisDa** [comment]
Ah yes. You can send multiple seen items to that resolver and it will commit them in the background.
