### ISSUE TITLE
Trying to Merge from "Shows" to Anime

### ISSUE THREAD

**Issue by XyberDAWG** [IgnisDa/ryot#747]
I imported from Trakt, and I would like to move my Anime that shows up as "Show" to an Anime entry.

I thought I could add the Anime to my Anime section, copy the Id from the entry in Shows, and Merge the information from the show, but I get an application error when i attempt it.  Is that not what the "Merge Media" is for?

**Comment by IgnisDa** [comment]
This would not be possible unfortunately. The `seen` entries of both have very different structures and it is not possible to reconcile them accurately. I suggest you do this manually.
