### ISSUE TITLE
Cannot launch ryot using a Synology NAS? What am I doing wrong? Any example compose from other Synology users??

### ISSUE THREAD

**Issue by cleverestx** [IgnisDa/ryot#748]
I cannot bring up the container on my Synology NAS. I am using many other containers (but this one admittedly, looks broken), so I'm not sure what the issue is. The VOLUMES part on the bottom of the compose looks not completed, and I do not use CADDY which the errors and I believe the original Compose referenced.  (?)

**MY COMPOSE IS:**

version: "3.9"
services:
  ryot-db:
    image: postgres:16-alpine
    container_name: ryot-db
    volumes:
      - /volume1/docker/ryot/database:/usr/local/bin/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    container_name: ryot
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
    ports:
      - "8002:8000"
    pull_policy: always

volumes:
  postgres_storage:

**The LOGS ARE:**

[proxy] {"level":"warn","ts":1712292591.5611312,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
[proxy] {"level":"info","ts":1712292591.5611906,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00041bf00"}
[proxy] {"level":"info","ts":1712292591.5615995,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
[proxy] {"level":"info","ts":1712292591.561676,"logger":"tls","msg":"finished cleaning storage units"}
[proxy] {"level":"info","ts":1712292591.5619674,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
[proxy] {"level":"info","ts":1712292591.5622315,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
[proxy] {"level":"info","ts":1712292591.562243,"msg":"serving initial configuration"}
[backend] thread 'main' panicked at apps/backend/src/main.rs:131:10:
[backend] Database connection failed: Conn(SqlxError(Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))
[backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101
--> Sending SIGTERM to other processes..
node:events:492
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 14 ]
}
Node.js v20.10.0
[backend] 2024-04-06T03:24:21.530727Z  INFO ryot: Running version: 4.3.17
[proxy] {"level":"info","ts":1712373862.2631102,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
[proxy] {"level":"warn","ts":1712373862.264837,"logger":"admin","msg":"admin endpoint disabled"}
[proxy] {"level":"warn","ts":1712373862.2650008,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
[proxy] {"level":"info","ts":1712373862.265082,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0000cba00"}
[proxy] {"level":"info","ts":1712373862.2653809,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
[proxy] {"level":"info","ts":1712373862.2654378,"logger":"tls","msg":"finished cleaning storage units"}
[proxy] {"level":"info","ts":1712373862.265459,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
[backend] thread 'main' panicked at apps/backend/src/main.rs:131:10:
[backend] Database connection failed: Conn(SqlxError(Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))
[backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101
--> Sending SIGTERM to other processes..
node:events:492
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 14 ]
}
Node.js v20.10.0
[proxy] {"level":"info","ts":1712374180.6778376,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
[proxy] {"level":"warn","ts":1712374180.6798258,"logger":"admin","msg":"admin endpoint disabled"}
[proxy] {"level":"warn","ts":1712374180.6799798,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
[proxy] {"level":"info","ts":1712374180.680047,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000421f80"}
[proxy] {"level":"info","ts":1712374180.6804216,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
[proxy] {"level":"info","ts":1712374180.6804554,"logger":"tls","msg":"finished cleaning storage units"}
[proxy] {"level":"info","ts":1712374180.6805394,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
[backend] 2024-04-06T03:29:41.293567Z  INFO ryot: Running version: 4.3.17
[proxy] {"level":"info","ts":1712374181.2941768,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
[proxy] {"level":"info","ts":1712374181.2942915,"msg":"serving initial configuration"}
[backend] thread 'main' panicked at apps/backend/src/main.rs:131:10:
[backend] Database connection failed: Conn(SqlxError(Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))
node:events:492
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101
--> Sending SIGTERM to other processes..
      
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 14 ]
}
Node.js v20.10.0

**Comment by IgnisDa** [comment]
The backend is not able to connect to the postgres database. Do you have any other application running that connects to a postgres DB?

**Comment by amedcalf** [comment]
I have used ryot on a Synology successfully.

The only difference I could quickly spot in the compose file is I had:

volumes:
      - /volume1/docker/ryot/database:/var/lib/postgresql/data

instead of your

volumes:
- /volume1/docker/ryot/database:/usr/local/bin/postgresql/data

**Comment by cleverestx** [comment]
> The backend is not able to connect to the postgres database. Do you have any other application running that connects to a postgres DB?

I don't think so....but I have many containers...I need to check that...

**Comment by cleverestx** [comment]
> I have used ryot on a Synology successfully.
> 
> The only difference I could quickly spot in the compose file is I had:
> 
> volumes: - /volume1/docker/ryot/database:/var/lib/postgresql/data
> 
> instead of your
> 
> volumes:
> 
>     * /volume1/docker/ryot/database:/usr/local/bin/postgresql/data

I changed that line, still not coming up. It tells me:

[backend] thread 'main' panicked at apps/backend/src/main.rs:131:10:

[backend] Database connection failed: Conn(SqlxError(Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))

[backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101

--> Sending SIGTERM to other processes..

node:events:492

      throw er; // Unhandled 'error' event

      ^

Error: spawn ps ENOENT

    at ChildProcess._handle.onexit (node:internal/child_process:286:19)

    at onErrorNT (node:internal/child_process:484:16)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Emitted 'error' event on ChildProcess instance at:

    at ChildProcess._handle.onexit (node:internal/child_process:292:12)

    at onErrorNT (node:internal/child_process:484:16)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {



**Comment by IgnisDa** [comment]
What are the logs of the database? `docker logs ryot-db`

**Comment by cleverestx** [comment]
> What are the logs of the database? `docker logs ryot-db`

It just say: "Error: No such container: ryot-db"

**Comment by IgnisDa** [comment]
Run `docker ps -a` and see which all containers related to ryot are there.

**Comment by cleverestx** [comment]
> Run `docker ps -a` and see which all containers related to ryot are there.

Only one:

`16c2580580b3   ghcr.io/ignisda/ryot:latest                            "docker-en                                                        trypoint.s…"   2 hours ago      Exited (1) 2 hours ago                                                                                                                                                                                                                                                                                                                                                                                                                          ryot`

**Comment by IgnisDa** [comment]
I am not sure how you are running the containers. Are you doing `docker compose up -d`?

**Comment by IgnisDa** [comment]
If yes, then please show me the logs of `docker compose logs`.

**Comment by cleverestx** [comment]
Yes I'm using up -d (as I do with all of my containers) (after a pull)

I'm 95% certain the issue is with my compose:

**MY COMPOSE IS:**

```
version: "3.9"
services:
ryot-db:
image: postgres:16-alpine
container_name: ryot-db
volumes:
- /volume1/docker/ryot/database:/var/lib/postgresql/data
environment:
- POSTGRES_PASSWORD=postgres
- POSTGRES_USER=postgres
- POSTGRES_DB=postgres
restart: unless-stopped

ryot:
image: "ghcr.io/ignisda/ryot:latest"
container_name: ryot
environment:
- DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
ports:
- "8002:8000"
pull_policy: always

volumes:
postgres_storage:
```

**Compose LOGS**:

ryot  | [backend] 2024-04-06T15:55:24.369912Z  INFO ryot: Running version: 4.3.17
ryot  | [proxy] {"level":"info","ts":1712418924.4107947,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
ryot  | [proxy] {"level":"warn","ts":1712418924.4123592,"logger":"admin","msg":"admin endpoint disabled"}
ryot  | [proxy] {"level":"warn","ts":1712418924.4124975,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
ryot  | [proxy] {"level":"info","ts":1712418924.4125857,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0003f4d80"}
ryot  | [proxy] {"level":"info","ts":1712418924.4129038,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
ryot  | [proxy] {"level":"info","ts":1712418924.4129474,"logger":"tls","msg":"finished cleaning storage units"}
ryot  | [proxy] {"level":"info","ts":1712418924.413066,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
ryot  | [proxy] {"level":"info","ts":1712418924.4132485,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
ryot  | [proxy] {"level":"info","ts":1712418924.4132574,"msg":"serving initial configuration"}
ryot  | [backend] thread 'main' panicked at apps/backend/src/main.rs:131:10:
ryot  | [backend] Database connection failed: Conn(SqlxError(Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))
ryot  | [backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ryot  | [backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101
ryot  | --> Sending SIGTERM to other processes..
ryot  | node:events:492
ryot  |       throw er; // Unhandled 'error' event
ryot  |       ^
ryot  |
ryot  | Error: spawn ps ENOENT
ryot  |     at ChildProcess._handle.onexit (node:internal/child_process:286:19)
ryot  |     at onErrorNT (node:internal/child_process:484:16)
ryot  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ryot  | Emitted 'error' event on ChildProcess instance at:
ryot  |     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
ryot  |     at onErrorNT (node:internal/child_process:484:16)
ryot  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot  |   errno: -2,
ryot  |   code: 'ENOENT',
ryot  |   syscall: 'spawn ps',
ryot  |   path: 'ps',
ryot  |   spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 15 ]
ryot  | }
ryot  |
ryot  | Node.js v20.10.0
ryot  | [backend] 2024-04-06T17:51:28.819215Z  INFO ryot: Running version: 4.3.17
ryot  | [backend] thread 'main' panicked at apps/backend/src/main.rs:131:10:
ryot  | [backend] Database connection failed: Conn(SqlxError(Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))
ryot  | [backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ryot  | [backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101
ryot  | --> Sending SIGTERM to other processes..
ryot  | node:events:492
ryot  |       throw er; // Unhandled 'error' event
ryot  |       ^
ryot  |
ryot  | Error: spawn ps ENOENT
ryot  |     at ChildProcess._handle.onexit (node:internal/child_process:286:19)
ryot  |     at onErrorNT (node:internal/child_process:484:16)
ryot  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ryot  | Emitted 'error' event on ChildProcess instance at:
ryot  |     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
ryot  |     at onErrorNT (node:internal/child_process:484:16)
ryot  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot  |   errno: -2,
ryot  |   code: 'ENOENT',
ryot  |   syscall: 'spawn ps',
ryot  |   path: 'ps',
ryot  |   spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 14 ]
ryot  | }
ryot  |
ryot  | Node.js v20.10.0

**Thanks for trying to help BTW**

**Comment by IgnisDa** [comment]
There are no logs from the `ryot-db` container. Would it be possible for you to create a video of running that command?

**Comment by cleverestx** [comment]
> There are no logs from the `ryot-db` container. Would it be possible for you to create a video of running that command?

Here you go:

https://github.com/IgnisDa/ryot/assets/28905253/4f03f849-6614-4a44-b688-d5dd0be6e90c

**Comment by IgnisDa** [comment]
@cleverestx There is no need to do `docker compose pull`. And the command to start the containers should be `docker compose up -d`. The command you are executing is just starting up the server and not the database.

Where did you get the command?

**Comment by cleverestx** [comment]
> @cleverestx There is no need to do `docker compose pull`. And the command to start the containers should be `docker compose up -d`. The command you are executing is just starting up the server and not the database.
> 
> Where did you get the command?

Hi. This is the same command I always use to pull and install all of my other containers (I have 80+ other containers running like this on my NAS). I'm using Putty through my desktop PC, connected via SSH and these are the docker compose commands I always use for this stuff.

Your command results in this error: 
![image](https://github.com/IgnisDa/ryot/assets/28905253/7d7174e9-547d-46cd-9b57-24d26ce27569)

**Comment by cleverestx** [comment]
I think I really just need someone using this applications **ON a Synology** to actually share there entire compose (minus sensitive stuff), that usually resolves issues I have with getting compose stuff to work on Synology. I've noticed the compose from different platforms often have some variation in them that break stuff from working on my own.

**Comment by IgnisDa** [comment]
Try `docker-compose up -d`.

**Comment by cleverestx** [comment]
> Try `docker-compose up -d`.

That IS what I do (except I always have to use Sudo, this is a second admin account I made and it requires that) - did you see my linked video? It shows that.

**Comment by cleverestx** [comment]
LOL, I was adding ryot to the end...(smacks head), that was habit cause I have a compose in my media folder for my media related 'arrs and other apps that I have to specific the app at the end to just pull or up -d those.....such a stupid mistake...trying that now...

**Comment by cleverestx** [comment]
Well the DB is running now at least...but ryot is still not 
![image](https://github.com/IgnisDa/ryot/assets/28905253/8943e023-a181-4662-8e8f-cf7abfb56cb0)

Logs for RYOT container:

```
ryot-db  | The files belonging to this database system will be owned by user "postgres".
ryot-db  | This user must also own the server process.
ryot-db  |
ryot-db  | The database cluster will be initialized with locale "en_US.utf8".
ryot     | [proxy] {"level":"info","ts":1712513350.693363,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
ryot-db  | The default database encoding has accordingly been set to "UTF8".
ryot     | [proxy] {"level":"warn","ts":1712513350.6949148,"logger":"admin","msg":"admin endpoint disabled"}
ryot-db  | The default text search configuration will be set to "english".
ryot     | [proxy] {"level":"warn","ts":1712513350.6950674,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
ryot-db  |
ryot     | [proxy] {"level":"info","ts":1712513350.6951494,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001f7c00"}
ryot     | [proxy] {"level":"info","ts":1712513350.6954503,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
ryot     | [proxy] {"level":"info","ts":1712513350.6955047,"logger":"tls","msg":"finished cleaning storage units"}
ryot     | [proxy] {"level":"info","ts":1712513350.6955256,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
ryot     | [proxy] {"level":"info","ts":1712513350.6957343,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
ryot-db  | Data page checksums are disabled.
ryot     | [proxy] {"level":"info","ts":1712513350.6957433,"msg":"serving initial configuration"}
ryot-db  |
ryot-db  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
ryot-db  | creating subdirectories ... ok
ryot-db  | selecting dynamic shared memory implementation ... posix
ryot-db  | selecting default max_connections ... 100
ryot-db  | selecting default shared_buffers ... 128MB
ryot-db  | selecting default time zone ... UTC
ryot     | [backend] 2024-04-07T18:09:10.747474Z  INFO ryot: Running version: 4.3.18
ryot     | [backend] thread 'main' panicked at apps/backend/src/main.rs:131:10:
ryot     | [backend] Database connection failed: Conn(SqlxError(PoolTimedOut))
ryot     | [backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ryot     | [backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101
ryot     | --> Sending SIGTERM to other processes..
ryot-db  | creating configuration files ... ok
ryot-db  | running bootstrap script ... ok
ryot-db  | sh: locale: not found
ryot-db  | 2024-04-07 18:08:58.952 UTC [31] WARNING:  no usable system locales were found
ryot-db  | performing post-bootstrap initialization ... ok
ryot-db  | syncing data to disk ... ok
ryot-db  |
ryot-db  |
ryot-db  | Success. You can now start the database server using:
ryot-db  |
ryot-db  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
ryot-db  |
ryot-db  | initdb: warning: enabling "trust" authentication for local connections
ryot-db  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
ryot-db  | waiting for server to start.....2024-04-07 18:09:05.897 UTC [37] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
ryot     | node:events:492
ryot     |       throw er; // Unhandled 'error' event
ryot     |       ^
ryot     |
ryot     | Error: spawn ps ENOENT
ryot     |     at ChildProcess._handle.onexit (node:internal/child_process:286:19)
ryot     |     at onErrorNT (node:internal/child_process:484:16)
ryot     |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ryot     | Emitted 'error' event on ChildProcess instance at:
ryot     |     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
ryot     |     at onErrorNT (node:internal/child_process:484:16)
ryot-db  | .2024-04-07 18:09:06.681 UTC [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ryot-db  | ...2024-04-07 18:09:09.239 UTC [40] LOG:  database system was shut down at 2024-04-07 18:09:00 UTC
ryot-db  | .2024-04-07 18:09:10.233 UTC [37] LOG:  database system is ready to accept connections
ryot-db  |  done
ryot-db  | server started
ryot-db  |
ryot-db  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
ryot-db  |
ryot-db  | waiting for server to shut down....2024-04-07 18:09:12.454 UTC [37] LOG:  received fast shutdown request
ryot-db  | 2024-04-07 18:09:13.390 UTC [37] LOG:  aborting any active transactions
ryot-db  | 2024-04-07 18:09:13.394 UTC [37] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
ryot-db  | 2024-04-07 18:09:13.394 UTC [38] LOG:  shutting down
ryot-db  | .2024-04-07 18:09:14.337 UTC [38] LOG:  checkpoint starting: shutdown immediate
ryot-db  | .....2024-04-07 18:09:19.149 UTC [38] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=1.361 s, total=5.755 s; sync files=2, longest=0.791 s, average=0.681 s; distance=0 kB, estimate=0 kB; lsn=0/14F0498, redo lsn=0/14F0498
ryot-db  | .2024-04-07 18:09:19.534 UTC [37] LOG:  database system is shut down
ryot-db  |  done
ryot-db  | server stopped
ryot-db  |
ryot-db  | PostgreSQL init process complete; ready for start up.
ryot-db  |
ryot-db  | 2024-04-07 18:09:20.789 UTC [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
ryot-db  | 2024-04-07 18:09:20.789 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
ryot-db  | 2024-04-07 18:09:20.789 UTC [1] LOG:  listening on IPv6 address "::", port 5432
ryot-db  | 2024-04-07 18:09:22.050 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ryot-db  | 2024-04-07 18:09:23.539 UTC [51] LOG:  database system was shut down at 2024-04-07 18:09:18 UTC
ryot     |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
ryot     |   errno: -2,
ryot     |   code: 'ENOENT',
ryot     |   syscall: 'spawn ps',
ryot     |   path: 'ps',
ryot     |   spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 14 ]
ryot     | }
ryot     |
ryot     | Node.js v20.10.0
ryot-db  | 2024-04-07 18:09:24.385 UTC [1] LOG:  database system is ready to accept connections
ryot-db  | 2024-04-07 18:14:23.633 UTC [49] LOG:  checkpoint starting: time
ryot-db  | 2024-04-07 18:14:33.229 UTC [49] LOG:  checkpoint complete: wrote 39 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.608 s, sync=2.616 s, total=9.597 s; sync files=11, longest=1.084 s, average=0.238 s; distance=202 kB, estimate=202 kB; lsn=0/15230B0, redo lsn=0/1523078
```

**Comment by cleverestx** [comment]
Actually this is the logs from RYOT from portainer:

`[proxy] {"level":"info","ts":1712513350.693363,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}

[proxy] {"level":"warn","ts":1712513350.6949148,"logger":"admin","msg":"admin endpoint disabled"}

[proxy] {"level":"warn","ts":1712513350.6950674,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}

[proxy] {"level":"info","ts":1712513350.6951494,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001f7c00"}

[proxy] {"level":"info","ts":1712513350.6954503,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}

[proxy] {"level":"info","ts":1712513350.6955047,"logger":"tls","msg":"finished cleaning storage units"}

[proxy] {"level":"info","ts":1712513350.6955256,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}

[proxy] {"level":"info","ts":1712513350.6957343,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}

[proxy] {"level":"info","ts":1712513350.6957433,"msg":"serving initial configuration"}

[backend] 2024-04-07T18:09:10.747474Z  INFO ryot: Running version: 4.3.18

[backend] thread 'main' panicked at apps/backend/src/main.rs:131:10:

[backend] Database connection failed: Conn(SqlxError(PoolTimedOut))

[backend] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101

--> Sending SIGTERM to other processes..

node:events:492

      throw er; // Unhandled 'error' event

      ^

Error: spawn ps ENOENT

    at ChildProcess._handle.onexit (node:internal/child_process:286:19)

    at onErrorNT (node:internal/child_process:484:16)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Emitted 'error' event on ChildProcess instance at:

    at ChildProcess._handle.onexit (node:internal/child_process:292:12)

    at onErrorNT (node:internal/child_process:484:16)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

`

**Comment by cleverestx** [comment]
I startup up the RYOT container again and it appears to be coming up now.YAY!

...but when I try to register, it just sits there...clicking the button in Chrome or Edge, does nothing, doesn't submit, doesn't confirm anything :-(

**Comment by IgnisDa** [comment]
@cleverestx Can you open the network tab in devtools and then click on register and show the network response?

One thing that comes to mind: if you are running Ryot in a non-https context, you will have to set env variable `FRONTEND_INSECURE_COOKIES=true`.

**Comment by cleverestx** [comment]
> @cleverestx Can you open the network tab in devtools and then click on register and show the network response?
> 
> One thing that comes to mind: if you are running Ryot in a non-https context, you will have to set env variable `FRONTEND_INSECURE_COOKIES=true`.

In the network status I get the normal status code 200 and this:

Also added that ENV variable and re-upped container...same thing  :-(

I guess I will try to disable that ENV variable, putting it behind a RP address...I'll let you know, thanks.

![image](https://github.com/IgnisDa/ryot/assets/28905253/320ffc4b-50c1-4b25-a558-092deda5ebd9)

**Comment by cleverestx** [comment]
CONFIRMED FIXED using RP address...when I tried to sign up, it told me acct already existed (so I guess it had created it before), and logging in with it works...but no Local HTTP access I guess?

**Comment by cleverestx** [comment]
Is there a way to SPEED up the looking up and adding of items? It's pretty sluggish :-(

![image](https://github.com/IgnisDa/ryot/assets/28905253/3161adc6-7d68-433c-b90a-1285a7b84a5c)

**Comment by IgnisDa** [comment]
No the initial downloading of items always takes time since it needs to be fetched from api. If the subsequent requests are slow for you, open a new issue.

Closing this since the original issue has been fixed.
