### ISSUE TITLE
Ryot is working now as per my last post, but then stopped working - failing to load the home / dashboard with 'Application Error'

### ISSUE THREAD

**Issue by cleverestx** [IgnisDa/ryot#751]
After testing the no cookie stuff ENV variable to get the HTTP to work (which doesn't), I've switched to just using a reverse proxy and https.

currently it loads any page except for the home page, which is the DASHBOARD, in which I get this; 
![image](https://github.com/IgnisDa/ryot/assets/28905253/2635006e-a096-4a68-89d4-a3e83e986c6b)

I noticed that I can no longer add anything, it just finds it and spins forever... 
![image](https://github.com/IgnisDa/ryot/assets/28905253/3b81cb9b-0de7-4dbd-a590-40a1422d6fdf)

Something broke I guess? How do I reset and hopefully not lose the few additions I've done?

**Comment by IgnisDa** [comment]
please show me the output of `docker-compose logs`

**Comment by cleverestx** [comment]
This is part of it, because it repeats A LOT:


ryot-db  | 2024-04-08 04:22:46.361 UTC [334] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:23:06.292 UTC [326] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:23:06.292 UTC [326] DETAIL:  Key (metadata_id, person_id, role)=(188, 326, Acting) already exists.
ryot-db  | 2024-04-08 04:23:06.292 UTC [326] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:23:10.991 UTC [326] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:23:10.991 UTC [326] DETAIL:  Key (metadata_id, person_id, role)=(188, 322, Acting) already exists.
ryot-db  | 2024-04-08 04:23:10.991 UTC [326] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:23:18.801 UTC [22] LOG:  checkpoint starting: time
ryot-db  | 2024-04-08 04:23:33.256 UTC [22] LOG:  checkpoint complete: wrote 41 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=6.344 s, sync=4.655 s, total=14.455 s; sync files=15, longest=1.798 s, average=0.311 s; distance=165 kB, estimate=370 kB; lsn=0/1A02970, redo lsn=0/19F8F08
ryot-db  | 2024-04-08 04:27:23.137 UTC [333] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:27:23.137 UTC [333] DETAIL:  Key (metadata_id, person_id, role)=(188, 210, Acting) already exists.
ryot-db  | 2024-04-08 04:27:23.137 UTC [333] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:28:18.355 UTC [22] LOG:  checkpoint starting: time
ryot-db  | 2024-04-08 04:28:33.844 UTC [22] LOG:  checkpoint complete: wrote 47 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=7.756 s, sync=2.270 s, total=15.490 s; sync files=14, longest=1.431 s, average=0.163 s; distance=191 kB, estimate=352 kB; lsn=0/1A327B0, redo lsn=0/1A28C78
ryot-db  | 2024-04-08 04:29:53.934 UTC [329] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:29:53.934 UTC [329] DETAIL:  Key (metadata_id, person_id, role)=(188, 350, Acting) already exists.
ryot-db  | 2024-04-08 04:29:53.934 UTC [329] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:31:53.648 UTC [334] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:31:53.648 UTC [334] DETAIL:  Key (metadata_id, person_id, role)=(188, 297, Acting) already exists.
ryot-db  | 2024-04-08 04:31:53.648 UTC [334] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:32:10.424 UTC [325] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:32:10.424 UTC [325] DETAIL:  Key (metadata_id, person_id, role)=(188, 326, Acting) already exists.
ryot-db  | 2024-04-08 04:32:10.424 UTC [325] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:32:53.328 UTC [329] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:32:53.328 UTC [329] DETAIL:  Key (metadata_id, person_id, role)=(188, 316, Acting) already exists.
ryot-db  | 2024-04-08 04:32:53.328 UTC [329] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:33:16.991 UTC [326] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:33:16.991 UTC [326] DETAIL:  Key (metadata_id, person_id, role)=(188, 421, Acting) already exists.
ryot-db  | 2024-04-08 04:33:16.991 UTC [326] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:33:18.939 UTC [22] LOG:  checkpoint starting: time
ryot-db  | 2024-04-08 04:33:31.462 UTC [22] LOG:  checkpoint complete: wrote 41 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.019 s, sync=2.257 s, total=12.524 s; sync files=14, longest=1.307 s, average=0.162 s; distance=193 kB, estimate=336 kB; lsn=0/1A62E40, redo lsn=0/1A592F0
ryot-db  | 2024-04-08 04:33:31.464 UTC [328] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:33:31.464 UTC [328] DETAIL:  Key (metadata_id, person_id, role)=(188, 260, Production) already exists.
ryot-db  | 2024-04-08 04:33:31.464 UTC [328] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:35:15.706 UTC [329] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:35:15.706 UTC [329] DETAIL:  Key (metadata_id, person_id, role)=(188, 225, Acting) already exists.
ryot-db  | 2024-04-08 04:35:15.706 UTC [329] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:36:22.090 UTC [326] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:36:22.090 UTC [326] DETAIL:  Key (metadata_id, person_id, role)=(188, 255, Acting) already exists.
ryot-db  | 2024-04-08 04:36:22.090 UTC [326] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:37:13.762 UTC [329] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:37:13.762 UTC [329] DETAIL:  Key (metadata_id, person_id, role)=(188, 247, Acting) already exists.
ryot-db  | 2024-04-08 04:37:13.762 UTC [329] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:38:07.347 UTC [325] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:38:07.347 UTC [325] DETAIL:  Key (metadata_id, person_id, role)=(188, 255, Acting) already exists.
ryot-db  | 2024-04-08 04:38:07.347 UTC [325] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:38:18.053 UTC [326] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:38:18.053 UTC [326] DETAIL:  Key (metadata_id, person_id, role)=(188, 583, Acting) already exists.
ryot-db  | 2024-04-08 04:38:18.053 UTC [326] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:38:18.556 UTC [22] LOG:  checkpoint starting: time
ryot-db  | 2024-04-08 04:38:37.201 UTC [22] LOG:  checkpoint complete: wrote 50 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=6.010 s, sync=4.257 s, total=18.646 s; sync files=14, longest=1.526 s, average=0.305 s; distance=200 kB, estimate=323 kB; lsn=0/1A95AF0, redo lsn=0/1A8B330
ryot-db  | 2024-04-08 04:41:51.047 UTC [325] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:41:51.047 UTC [325] DETAIL:  Key (metadata_id, person_id, role)=(188, 231, Acting) already exists.
ryot-db  | 2024-04-08 04:41:51.047 UTC [325] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:41:55.572 UTC [328] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:41:55.572 UTC [328] DETAIL:  Key (metadata_id, person_id, role)=(188, 652, Acting) already exists.
ryot-db  | 2024-04-08 04:41:55.572 UTC [328] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:43:12.256 UTC [328] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:43:12.256 UTC [328] DETAIL:  Key (metadata_id, person_id, role)=(188, 331, Acting) already exists.
ryot-db  | 2024-04-08 04:43:12.256 UTC [328] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:43:18.290 UTC [22] LOG:  checkpoint starting: time
ryot-db  | 2024-04-08 04:43:35.154 UTC [22] LOG:  checkpoint complete: wrote 49 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=6.452 s, sync=3.266 s, total=16.865 s; sync files=15, longest=1.493 s, average=0.218 s; distance=195 kB, estimate=310 kB; lsn=0/1AC8A98, redo lsn=0/1ABC0A0
ryot-db  | 2024-04-08 04:44:20.156 UTC [335] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:44:20.156 UTC [335] DETAIL:  Key (metadata_id, person_id, role)=(188, 699, Acting) already exists.
ryot-db  | 2024-04-08 04:44:20.156 UTC [335] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:45:13.119 UTC [394] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:45:13.119 UTC [394] DETAIL:  Key (metadata_id, person_id, role)=(188, 482, Acting) already exists.
ryot-db  | 2024-04-08 04:45:13.119 UTC [394] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:45:21.257 UTC [398] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:45:21.257 UTC [398] DETAIL:  Key (metadata_id, person_id, role)=(188, 244, Acting) already exists.
ryot-db  | 2024-04-08 04:45:21.257 UTC [398] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:46:04.449 UTC [398] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:46:04.449 UTC [398] DETAIL:  Key (metadata_id, person_id, role)=(188, 273, Acting) already exists.
ryot-db  | 2024-04-08 04:46:04.449 UTC [398] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:46:22.039 UTC [398] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:46:22.039 UTC [398] DETAIL:  Key (metadata_id, person_id, role)=(188, 421, Acting) already exists.
ryot-db  | 2024-04-08 04:46:22.039 UTC [398] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:47:23.981 UTC [400] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:47:23.981 UTC [400] DETAIL:  Key (metadata_id, person_id, role)=(188, 549, Acting) already exists.
ryot-db  | 2024-04-08 04:47:23.981 UTC [400] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:47:32.234 UTC [394] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:47:32.234 UTC [394] DETAIL:  Key (metadata_id, person_id, role)=(188, 239, Production) already exists.
ryot-db  | 2024-04-08 04:47:32.234 UTC [394] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:47:39.122 UTC [398] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:47:39.122 UTC [398] DETAIL:  Key (metadata_id, person_id, role)=(188, 678, Acting) already exists.
ryot-db  | 2024-04-08 04:47:39.122 UTC [398] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:47:42.409 UTC [398] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:47:42.409 UTC [398] DETAIL:  Key (metadata_id, person_id, role)=(188, 832, Acting) already exists.
ryot-db  | 2024-04-08 04:47:42.409 UTC [398] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:48:18.250 UTC [22] LOG:  checkpoint starting: time
ryot-db  | 2024-04-08 04:48:32.108 UTC [22] LOG:  checkpoint complete: wrote 41 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.934 s, sync=2.479 s, total=13.859 s; sync files=15, longest=1.729 s, average=0.166 s; distance=198 kB, estimate=299 kB; lsn=0/1AF9B28, redo lsn=0/1AEDAB0
ryot-db  | 2024-04-08 04:49:29.151 UTC [394] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:49:29.151 UTC [394] DETAIL:  Key (metadata_id, person_id, role)=(188, 609, Acting) already exists.
ryot-db  | 2024-04-08 04:49:29.151 UTC [394] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:50:02.590 UTC [398] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:50:02.590 UTC [398] DETAIL:  Key (metadata_id, person_id, role)=(188, 217, Acting) already exists.
ryot-db  | 2024-04-08 04:50:02.590 UTC [398] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:50:02.591 UTC [399] ERROR:  duplicate key value violates unique constraint "pk-media-item_person"
ryot-db  | 2024-04-08 04:50:02.591 UTC [399] DETAIL:  Key (metadata_id, person_id, role)=(188, 216, Acting) already exists.
ryot-db  | 2024-04-08 04:50:02.591 UTC [399] STATEMENT:  INSERT INTO "metadata_to_person" ("metadata_id", "person_id", "role", "index", "character") VALUES ($1, $2, $3, $4, $5) RETURNING "metadata_id", "person_id", "role", "index", "character"
ryot-db  | 2024-04-08 04:51:42.489 UTC [394] ERROR:  duplicate key value violates unique constraint "metadata_to_metadata_from_metadata_id_relation_to_metadata__idx"
ryot-db  | 2024-04-08 04:51:42.489 UTC [394] DETAIL:  Key (from_metadata_id, relation, to_metadata_id)=(188, SU, 209) already exists.
ryot-db  | 2024-04-08 04:51:42.489 UTC [394] STATEMENT:  INSERT INTO "metadata_to_metadata" ("from_metadata_id", "relation", "to_metadata_id") VALUES ($1, $2, $3) RETURNING "id", "from_metadata_id", "relation", "to_metadata_id"
ryot-db  | 2024-04-08 04:53:18.208 UTC [22] LOG:  checkpoint starting: time
ryot-db  | 2024-04-08 04:53:32.737 UTC [22] LOG:  checkpoint complete: wrote 48 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.784 s, sync=3.876 s, total=14.530 s; sync files=26, longest=1.701 s, average=0.150 s; distance=190 kB, estimate=288 kB; lsn=0/1B1D4C0, redo lsn=0/1B1D488

**Comment by IgnisDa** [comment]
This is the database logs. I need output from Ryot. Try `docker-compose logs ryot`.

**Comment by cleverestx** [comment]
Here they are:  (just a portion again)



```

ryot  | [frontend] GET /media/people/list?_data=routes%2F_dashboard.media.people.%24action 200 - - 17.642 ms
ryot  | [frontend] GET /media/list/show?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 18.770 ms
ryot  | [frontend] GET /media/list/podcast?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 22.400 ms
ryot  | [frontend] GET /media/groups/list?_data=routes%2F_dashboard.media.groups.%24action 200 - - 17.729 ms
ryot  | [frontend] GET /media/people/list?_data=routes%2F_dashboard.media.people.%24action 200 - - 17.889 ms
ryot  | [frontend] GET /media/genre/list?_data=routes%2F_dashboard.media.genre.list 200 - - 9.032 ms
ryot  | [frontend] GET /media/list/movie?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 26.173 ms
ryot  | [frontend] GET /media/item/146?_data=routes%2F_dashboard.media.item.%24id._index 200 - - 28.072 ms
ryot  | [frontend] Error: Invariant failed
ryot  | [frontend]     at invariant (file:///home/ryot/node_modules/tiny-invariant/dist/esm/tiny-invariant.js:8:15)
ryot  | [frontend]     at getTake (file:///home/ryot/build/server/index.js?t=1712462523000:12329:3)
ryot  | [frontend]     at loader$4 (file:///home/ryot/build/server/index.js?t=1712462523000:12335:26)
ryot  | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ryot  | [frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
ryot  | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
ryot  | [frontend]     at async Promise.all (index 0)
ryot  | [frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
ryot  | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
ryot  | [frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3041:18)
ryot  | [frontend] GET /?_data=routes%2F_dashboard._index 500 - - 12.364 ms
ryot  | [frontend] GET /media/item/146?_data=routes%2F_dashboard 200 - - 24.429 ms
ryot  | [frontend] GET /media/item/146?_data=routes%2F_dashboard.media.item.%24id._index 200 - - 29.025 ms
ryot  | [frontend] GET /settings/integrations?_data=routes%2F_dashboard.settings.integrations 200 - - 6.965 ms
ryot  | [frontend] GET /media/item/146?_data=routes%2F_dashboard.media.item.%24id._index 200 - - 35.802 ms
ryot  | [frontend] GET /media/list/movie?_data=routes%2F_dashboard.media.%24action.%24lot 200 - - 26.426 ms
ryot  | [frontend] Error: Invariant failed
ryot  | [frontend]     at invariant (file:///home/ryot/node_modules/tiny-invariant/dist/esm/tiny-invariant.js:8:15)
ryot  | [frontend]     at getTake (file:///home/ryot/build/server/index.js?t=1712462523000:12329:3)
ryot  | [frontend]     at loader$4 (file:///home/ryot/build/server/index.js?t=1712462523000:12335:26)
ryot  | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ryot  | [frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
ryot  | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
ryot  | [frontend]     at async Promise.all (index 0)
ryot  | [frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
ryot  | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
ryot  | [frontend]     at Object.queryRoute (/home/ryot/node_modules/@remix-run/router/router.ts:3041:18)
ryot  | [frontend] GET /?_data=routes%2F_dashboard._index 500 - - 9.355 ms
ryot  | [frontend] Error: Invariant failed
ryot  | [frontend]     at invariant (file:///home/ryot/node_modules/tiny-invariant/dist/esm/tiny-invariant.js:8:15)
ryot  | [frontend]     at getTake (file:///home/ryot/build/server/index.js?t=1712462523000:12329:3)
ryot  | [frontend]     at loader$4 (file:///home/ryot/build/server/index.js?t=1712462523000:12335:26)
ryot  | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ryot  | [frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
ryot  | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
ryot  | [frontend]     at async Promise.all (index 2)
ryot  | [frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
ryot  | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
ryot  | [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18)
ryot  | [frontend] [Error: Unexpected Server Error]
ryot  | [frontend] GET / 500 - - 24.577 ms
ryot  | [frontend] Error: Invariant failed
ryot  | [frontend]     at invariant (file:///home/ryot/node_modules/tiny-invariant/dist/esm/tiny-invariant.js:8:15)
ryot  | [frontend]     at getTake (file:///home/ryot/build/server/index.js?t=1712462523000:12329:3)
ryot  | [frontend]     at loader$4 (file:///home/ryot/build/server/index.js?t=1712462523000:12335:26)
ryot  | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ryot  | [frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
ryot  | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
ryot  | [frontend]     at async Promise.all (index 2)
ryot  | [frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
ryot  | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
ryot  | [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18)
ryot  | [frontend] [Error: Unexpected Server Error]
ryot  | [frontend] GET / 500 - - 19.374 ms
ryot  | [frontend] Error: Invariant failed
ryot  | [frontend]     at invariant (file:///home/ryot/node_modules/tiny-invariant/dist/esm/tiny-invariant.js:8:15)
ryot  | [frontend]     at getTake (file:///home/ryot/build/server/index.js?t=1712462523000:12329:3)
ryot  | [frontend]     at loader$4 (file:///home/ryot/build/server/index.js?t=1712462523000:12335:26)
ryot  | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ryot  | [frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
ryot  | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
ryot  | [frontend]     at async Promise.all (index 2)
ryot  | [frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
ryot  | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
ryot  | [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18)
ryot  | [frontend] [Error: Unexpected Server Error]
ryot  | [frontend] GET / 500 - - 743.262 ms
```

**Comment by IgnisDa** [comment]
Your database seems to have been incorrectly initialized. Export your db using [these instructions](https://ignisda.github.io/ryot/guides/exporting.html#exporting-the-entire-database) and email it to me.

**Comment by cleverestx** [comment]
> Your database seems to have been incorrectly initialized. Export your db using [these instructions](https://ignisda.github.io/ryot/guides/exporting.html#exporting-the-entire-database) and email it to me.

Done. Emailed. Thank you.

**Comment by IgnisDa** [comment]
@cleverestx Fixed the issue. Please upgrade your instance and everything should work fine.

**Comment by IgnisDa** [comment]
The problem was that you had `0` elements in the "In Progress" section of the dashboard configured. Ideally, you should just set it to `8` and then set it as hidden.

Either way, it should load fine now.
