### ISSUE TITLE
RelativeUrlWithoutBase error due to double quotes in db url

### ISSUE THREAD

**Issue by cameronj86** [IgnisDa/ryot#753]
Not sure if the docker-compose file was recently updated or if something quirky was going on w/ my system but the vanilla docker compose file kept erroring out due to the double quotes around the postgres db

Incorrect current version: 
  - DATABASE_URL="postgres://postgres:postgres@ryot-db:5432/postgres"
Corrected version:
  - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres

Found the solution here https://github.com/launchbadge/sqlx/discussions/2497#discussioncomment-5971530

**Comment by IgnisDa** [comment]
Thanks. Will take a look.

**Comment by cameronj86** [comment]
On a related note, updating the [docker-compose](https://ignisda.github.io/ryot/index.html) file w/ `FRONTEND_INSECURE_COOKIES=true` might save some some troubleshooting for those trying to grab-and-go re: launching ryot.

**Comment by kartik2406** [comment]
I was facing similar issue when I added TZ field. Removing the " fixed it.
Thank you.
