### ISSUE TITLE
Wrong aspect ratio on covers

### ISSUE THREAD

**Issue by philipjholm** [IgnisDa/ryot#76]
See attached screenshot. When having a super wide screen (and therefore higher resolution) the covers looks wrong as it seems it want to force 6 items instead of 5 even though the container has the same max width. 

I recommend to keep having 5 items for each row or increasing the width of the container at higher resolutions.

Tested both in Firefox & Chrome.

![screen](https://github.com/IgnisDa/ryot/assets/37110163/76ced3e8-df18-466d-aae2-31a1904fa498)

**Comment by IgnisDa** [comment]
This should be pretty easy to fix. Mind making a PR?

**Comment by philipjholm** [comment]
@IgnisDa 
Sorry! I would if I knew how, but haven't learned github yet.
However, looking through the source code I would guess it is as simple as changing "{ minWidth: "xl", cols: 6 }," to "{ minWidth: "xl", cols: 5 }," here:
https://github.com/IgnisDa/ryot/blob/main/apps/frontend/src/lib/components/Grid.tsx

**Comment by IgnisDa** [comment]
Can you tell me what your screen size is?

**Comment by philipjholm** [comment]
My current resolution is 2560x1080 pixels but it is the width that matters. Looking at the CSS code the breakpoint seems to be set at "(min-width: 88em)".
