### ISSUE TITLE
Add version and platform info on page

### ISSUE THREAD

**Issue by tplusx** [IgnisDa/ryot#760]
Add version and platform info on page, helps people know when to update at first glance. And change font colour if out of date? Thanks
![issuescreenshot](https://github.com/IgnisDa/ryot/assets/7594469/42167d08-9513-43fc-8ac7-2a78d6b662bf)

Example from ABS

Never mind, looking at other issues seems it is there, will check why I don't have it.

**Comment by tplusx** [comment]
Reopening: uninstalled, reinstalled, tried latest, unstable, v4.4.0 tags, none show the version at the bottom of the screen.

**Comment by IgnisDa** [comment]
I'd appreciate a pr with a fix. I personally don't find any use of this.
