### ISSUE TITLE
Media not updating on dashboard as expected

### ISSUE THREAD

**Issue by tplusx** [IgnisDa/ryot#761]
Dashboard Media not updating as expected, after importing from Trakt, shows, movies appear empty but clicking on each link on the sidebar loads the appropriate content. Dashboard not working as expected.

![Screenshot 2024-04-13 193017](https://github.com/IgnisDa/ryot/assets/7594469/4e6b8552-4943-46ee-92af-967ecdfa31ec)

![image_2024-04-13_193902432](https://github.com/IgnisDa/ryot/assets/7594469/6a75d699-3ee7-4a32-8a1c-673520263c8b)

Upcoming, in progress and summary not working (related or could be a separate issue?)

**Comment by IgnisDa** [comment]
Are there any relevant logs?

For the summary, just deploy a summary update job from the miscellaneous settings.

**Comment by tplusx** [comment]
Thanks for the response. Redeploying summary updated the summary content in the dashboard but for some reason my Trakt progress does not update the "in progress" status on dashboard until I manually perform some action like "actions-> update progress" or "season -> mark as seen".
Here's an example, I have seasons 1-4 of this show as seen in Trakt, Ryot also recognises it as seen but not in progress even though I still have episodes to watch in season 5. The only way to have in the dashboard is to manually change the in progress status. Hope that makes sense
![image_2024-04-14_173800121](https://github.com/IgnisDa/ryot/assets/7594469/2e6eea0a-5d78-4ee3-a699-0a31d40af207)
I'm adding this here as I think its a dashboard related issue but can move it to create a new issue if needed.

**Comment by tplusx** [comment]
![image](https://github.com/IgnisDa/ryot/assets/7594469/3cf2b845-82a4-41e7-a798-a2fbce1d7c8b)
Import was fine, no errors. 
Will appreciate any help/solution, rather than manually updating 155 items with over 10,000 episodes (gosh I have spent a lot of time watching things!). I understand you are reluctant to change things but was thinking, could we have the option to select all items (shows or movies etc) and bulk apply an action eg mark in progress?
![image](https://github.com/IgnisDa/ryot/assets/7594469/60d3dc63-036c-4ab2-aa28-942e22ad9eb5)

**Comment by IgnisDa** [comment]
Were the show entries imported correctly? For example, The Office has 186 episodes. Are there as many episodes in the "Seen" tab?

**Comment by IgnisDa** [comment]
Okay so what exactly was the expected behaviour? Since you have watched all episodes, it is not there in the "In Progress" section. Isn't that expected?

Another question, what is the "Last calculated on" value displayed in the summary section of the dashboard?

**Comment by tplusx** [comment]
Apologies, A better example would be Saturday Night Live, as of the time of import I had 1 episode to go but it did not come up as "in progress"; is this the intended behaviour? 
However, if I go to the show's page
![Screenshot 2024-04-16 184325](https://github.com/IgnisDa/ryot/assets/7594469/1d40571d-5c80-493f-8c61-8c1e84df71d8)

 and update progress (sidenote: Mark S1 - E2 as seen is a default action there?)
![Screenshot 2024-04-16 184403](https://github.com/IgnisDa/ryot/assets/7594469/05c0ecf5-d5dc-435d-8710-71e3eb5e719c)

the show now gets an "in progress" and "monitoring" status
![Screenshot 2024-04-16 184540](https://github.com/IgnisDa/ryot/assets/7594469/b677aa97-a174-4b29-bf06-ad5b8f0ca74d)

it now appears on the dashboard.
![image](https://github.com/IgnisDa/ryot/assets/7594469/060dd8f5-927b-49ee-89a2-1842ea1d437a)

Refreshing the requests under misc does not affect the in progress action
I don't know the logic behind this. I mean the "upcoming" section works well and perhaps I don't need the "in progress", any way, just thought to point it out

"Last calculated on" was 6 hours ago

I hope I am not spamming this issue section. You can close it if I'm way off. Thanks

**Comment by IgnisDa** [comment]
You are right, the import seems to be botched up. Can you share your Trakt username?

Would it be possible for you to setup a fresh Ryot instance and start the import again?

**Comment by tplusx** [comment]
Traktuser3 - very imaginative name.
I removed the container/image and set up a fresh import 4 days ago, I can try again if you've pushed a new version since then (hence my other ticket on version info - I will check, I thought valid use case as this is very active development).
Cheers

**Comment by IgnisDa** [comment]
No haven't published a new version yet. Will let you know here when I do.

**Comment by IgnisDa** [comment]
@tplusx Please try with `v5.0.0`.

**Comment by tplusx** [comment]
thank you for the fix @IgnisDa
