### ISSUE TITLE
Allow to write notes associated with a Media item

### ISSUE THREAD

**Issue by brpaz** [IgnisDa/ryot#762]
Hello.

I am currently using Notion to manage my media activity, and I am checking Ryot as a possible alternative.

It would be nice, to have the possibility to have "notes" associated with each media item.

My use case is more in the context of Books, but it can be applied to other types as well. For books, I usually like to save highlights and annotations, together with the book. It could even have an auto import from Kindle, but a single free text or markdown section in the details page, would cover most of the needs.

**Comment by IgnisDa** [comment]
I think this will be solved by #578?
