### ISSUE TITLE
Play percentage and integrations

### ISSUE THREAD

**Issue by Artnal** [IgnisDa/ryot#763]
Hi there, 

Thanks a lot for all your work on this project. I had given it a shot last summer but didn't go through with it. I just reinstalled it and I am very impressed by the progress since then!

I have set up a few integrations, and I have noticed in the [documentation](https://ignisda.github.io/ryot/integrations.html) that "An item is marked as started when it has more than 2% progress and marked as completed when it has more than 95% progress.". Is there a way to change that percentage? I have a few media where, for instance, the credits are longer than 5% of the duration, and I was wondering if there was some setting I could tinker with. By way of example, the default jellyfin settings are 5% and 90% respectively. Ideally, I would like to mirror this setting, to avoid discrepancies between the two. 

Here's how the settings look for jellyfin for instance: 
![image](https://github.com/IgnisDa/ryot/assets/81462827/eb5c5696-3f5f-42df-bf9b-6fced3b63fd1)

Thanks!

**Comment by IgnisDa** [comment]
Search for `minimum_progress_limit` in the configuration docs. There's one for maximum too.
