### ISSUE TITLE
[FEATURE REQUEST] - API for stats

### ISSUE THREAD

**Issue by underwooda** [IgnisDa/ryot#764]
It'd be great to have the option of using an API to access stats about what I'm tracking. The use case for me would be for my Homepage (https://github.com/gethomepage/homepage) using the custom API widget (https://gethomepage.dev/latest/widgets/services/customapi/) which may lay the path for a dedicated widget further down the line. 

The stats I would like to be available:

- Currently watching shows
- Unwatched episodes
- Number of shows/films/books/whatever watched/read/done/otherwise consumed
- Unreleased shows/films of watchlist(s)

Sorry if this already exists, but I could not find anything about it in the docs :smiley:

**Comment by IgnisDa** [comment]
This is a good idea. I will revisit this soon. Thanks for the input.

**Comment by IgnisDa** [comment]
Hi @underwooda, I think you are requesting the same features as https://github.com/IgnisDa/ryot/issues/445, right?

**Comment by underwooda** [comment]
Hi @IgnisDa - yeah, it looks similar. I was just looking for simple numbers for the Homepage widget as it is just for "at a glance", but the other stats in #445 would also be cool to have in more of a stats dashboard in RYOT itself. 
Thanks!

**Comment by IgnisDa** [comment]
Makes sense. I'll merge this as a part of that issue because once that is implemented, you can just use the GQL api to display statistics.
