### ISSUE TITLE
Error migrations updating to 4.4.1

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#765]
Hi, I made today an update from 4.2.11 to 4.4.1, I have 2 instances of Ryot (with different content, one for TV Series and another for books), and in the one of TV Series failed the migrations.

`[backend] 2024-04-15T12:01:27.860512Z  INFO sea_orm_migration::migrator: Applying all pending migrations
[backend] 2024-04-15T12:01:27.864434Z  INFO sea_orm_migration::migrator: Applying migration 'm20240229_change_user_notifications_data_storage'
[backend] 2024-04-15T12:01:27.869488Z  INFO sea_orm_migration::migrator: Migration 'm20240229_change_user_notifications_data_storage' has been applied
[backend] 2024-04-15T12:01:27.870623Z  INFO sea_orm_migration::migrator: Applying migration 'm20240302_monitor_media_in_progress_or_watchlist'
[backend] 2024-04-15T12:01:27.896796Z  INFO sea_orm_migration::migrator: Migration 'm20240302_monitor_media_in_progress_or_watchlist' has been applied
[backend] 2024-04-15T12:01:27.897742Z  INFO sea_orm_migration::migrator: Applying migration 'm20240307_add_column_to_metadata_for_watch_providers'
[backend] 2024-04-15T12:01:27.903685Z  INFO sea_orm_migration::migrator: Migration 'm20240307_add_column_to_metadata_for_watch_providers' has been applied
[backend] 2024-04-15T12:01:27.904504Z  INFO sea_orm_migration::migrator: Applying migration 'm20240309_change_generic_to_media_json'
[backend] 2024-04-15T12:01:27.905885Z  INFO sea_orm_migration::migrator: Migration 'm20240309_change_generic_to_media_json' has been applied
[backend] 2024-04-15T12:01:27.906224Z  INFO sea_orm_migration::migrator: Applying migration 'm20240310_add_source_specifics_field_to_person'
[backend] 2024-04-15T12:01:27.913024Z ERROR ryot: Database migration failed: Execution Error: error returned from database: cannot drop index "person-identifier-source__unique_index" because constraint person-id
`

What should I do?

Thanks for your work !

**Comment by IgnisDa** [comment]
Please dump your database and email it to me (id in profile).

Also if you don't mind me asking, why do you have two Ryot instances?

**Comment by SirMartin** [comment]
I don't know why, but since the last issue that I sent you my DB dump, it changed from 10 Mb to more than 300 Mb in the last 6 months approx. Does it make sense to you? But already sent to your email.

About your question, is just because I prefer to have them like separate apps. I don't like the idea of having everything in the same place, I know is more or less your idea, that you can track almost everything from Ryot, but I prefer to have separate, so I can access it from different places, and have no mixed summaries, etc. It is just a matter of taste.

**Comment by IgnisDa** [comment]
Yes 10mb to 300mb is expected, though a lot. I plan to address this in a later version. There is a lot of redundant data.

I understand what you mean, thanks for clarifying.

I'll take a look at the db dump and try to come up with a solution.

**Comment by SirMartin** [comment]
Thanks. Good to read about the DB size is normal.

**Comment by IgnisDa** [comment]
What version of postgres are you using?

**Comment by SirMartin** [comment]
It is postgres alpine 15 in both instances.

**Comment by IgnisDa** [comment]
Can you send me the complete export using the command described [here](https://ignisda.github.io/ryot/guides/exporting.html#exporting-the-entire-database)? Do not compress it.

The dump you have sent has some tables missing for whatever reason.

**Comment by SirMartin** [comment]
Done.

**Comment by SirMartin** [comment]
It works, thanks @IgnisDa
