### ISSUE TITLE
Suggestion: Restyle "Mark as Seen" for already watched shows

### ISSUE THREAD

**Issue by arcastro** [IgnisDa/ryot#768]
Hello,

Opening this issue with another minor suggestion.

The "Mark as seen" language suggests that the episode has not already been seen, even though it may have already been watched. The button is very visually prominent in comparison to the small red "seen" label on the episode icon, so it's easy to get confused.

<img src="https://github.com/IgnisDa/ryot/assets/4576794/2c46d009-f41e-47ac-85f1-470ea294a281" width="400px"/>

Maybe it can be restyled to something like this, in these cases

<img src="https://github.com/IgnisDa/ryot/assets/4576794/80c6da30-3bdc-4133-b913-48ca745a2f66" width="400px"/>

This would provide additional visual indication for which episodes have already been watched.
(And of course, but button could remain as-is for unseen episodes)

**Comment by arcastro** [comment]
@IgnisDam If you agree, I'd be happy to try contributing a pull request

**Comment by IgnisDa** [comment]
Yeah I would be happy to accept a PR. Just make sure you branch off from #758.

**Comment by IgnisDa** [comment]
@arcastro Now that I think about it, please branch off `main`. I think #758 would be live for a long time.

**Comment by IgnisDa** [comment]
@arcastro Are you working on this or should I do it?

**Comment by arcastro** [comment]
I hadn't started it. ty for implementing it!

Just tried it and looks good on the episode list.
But, I think the same should apply to the already-seen season titles. 
Looks like already-seen seasons still show the "Mark as seen' button.
