### ISSUE TITLE
[Feature Request] Be able to add custom CSS

### ISSUE THREAD

**Issue by philipjholm** [IgnisDa/ryot#77]
It would be really nice if there was a textbox in the settings for adding custom CSS that is applied after the already generated one to make it override.

**Comment by IgnisDa** [comment]
What do you mean by custom css? Where will it be applied?

**Comment by philipjholm** [comment]
It's a really nice feature for people to easily customize the look of the page by just applying some simple CSS stylesheet on their own. 

A random example. If I wanted to make the top menu left aligned instead I would just add below CSS code:
`.mantine-guim20 {
    -webkit-justify-content: start;
    justify-content: start;
}`

And this would then be injected after all stylesheets you already are using. Which means that if the user adds some CSS it will override. I hope you understand what I mean.

![example](https://github.com/IgnisDa/ryot/assets/37110163/731e980e-c7db-4c8a-b9ad-8118cf900a00)

**Comment by IgnisDa** [comment]
I don't really see the point of this. Should Ryot need to worry about UI customizability?
