### ISSUE TITLE
Dropped shows in Upcoming

### ISSUE THREAD

**Issue by Artnal** [IgnisDa/ryot#771]
Hi there, 

I was wondering what the interaction between the "Upcoming" section and dropped shows is. 

Specifically, I had a show tagged "In Progressed" and "Monitoring". I decided to drop the show, so I tagged it as dropped for the episode I stopped watching, and I removed both the "In Progressed" and "Monitoring" tags. I then updated the Calendar events, but the show's latest ongoing season still shows up in "Upcoming". Since I don't intend to pick it up again, is there a way to remove it from that section?

Thanks!

**Comment by IgnisDa** [comment]
There isn't as of now but I intend to fix this. Thanks for bringing this into my attention!

**Comment by IgnisDa** [comment]
@Artnal Could you confirm if the show still shows up in the upcoming section? I just tried this out and it seems to be working fine.

**Comment by IgnisDa** [comment]
No, Ryot re-calculates user to media associations every 12 hours so yeah you will see shows for up to 12 hours in the upcoming section. It should be gone after that.

Glad to know the problem is fixed!
