### ISSUE TITLE
Different sections on the dashboard.

### ISSUE THREAD

**Issue by tplusx** [IgnisDa/ryot#774]
Ryot will be my primary exercise tracker - I have created a new collection for "workouts" to aggregate all my (daily) exercises, can this be added to the dashboard as a collection similar to upcoming, along with an option to replicate last activity? Just a thought, perhaps you have similar features lined up?

I have a crude design to show what I mean (apologies, done in paint), any UX/UI out there please help.

![Untitled](https://github.com/IgnisDa/ryot/assets/7594469/bb0de213-919a-4f5a-a33b-d034e0059687)

**Comment by IgnisDa** [comment]
Yes I do have something similar lined up, but thanks for the input. Admittedly, i won't be working on this for quite some time.
