### ISSUE TITLE
[Enhancement] Quicker way to add search result item to watchlist collection

### ISSUE THREAD

**Issue by philipjholm** [IgnisDa/ryot#78]
Right now a lot of clicks are required to add, for example a game, to a collection. Preferably this could be done directly from the search results page instead of clicking into the game and then "Add to collection", clicking on the dropdown and then on the "Set" button.

Maybe have a "..." button top right of the cover that opens a menu to "Add to collection" or even "Add to watchlist".

**Comment by IgnisDa** [comment]
Makes sense. Should be easy enough to add. Will look into it.
