### ISSUE TITLE
[bug] Ryot is no more loading since last update

### ISSUE THREAD

**Issue by edersong** [IgnisDa/ryot#780]
Since updated to v5.0.6, Ryot stopped to work.
Already deleted cookies and logged in back, but after some seconds working, it stops.

Here is what I found at container logs:
```
[backend] 2024-04-23T09:10:31.865297Z  INFO ryot: Listening on: 0.0.0.0:5000
[frontend] [remix-serve] http://localhost:3000 (http://192.168.0.3:3000)
[frontend] GET / - - - - ms
[frontend] Error: No route matches URL "/favicon.ico"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4519:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2958:19)
[frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend] GET /favicon.ico 404 - - 157.696 ms
[frontend] GET / - - - - ms
[frontend] GET / 302 - - 11.881 ms
```

**Comment by IgnisDa** [comment]
Can you try again with v5.0.7?

**Comment by kaibagley** [comment]
I was having the same error, and it is fixed by upgrading to v5.0.7

**Comment by IgnisDa** [comment]
Are these all the logs? Can you try going on `https://yourinstance.com/backend/config` and see if json is displayed.

**Comment by edersong** [comment]
Message from `https://yourinstance.com/backend/config` is:
```
We encountered an error. If you recently upgraded the server, you may have to logout and login again. 
If the error still persists, please create a new issue on [GitHub](https://github.com/ignisda/ryot/issues).
```

**Comment by IgnisDa** [comment]
THat is an error from the frontend. Seems like your backend is not booting up at all? 

Can you bring all containers down and start it again from scratch and send a screenshot of this?

**Comment by edersong** [comment]
Thanks!
Seems to be working... will monitor for a while because on v5.0.6 was dropping after some minutes.

**Comment by kilnake** [comment]
![ryot](https://github.com/IgnisDa/ryot/assets/165386823/84d1c9ca-2d53-438d-a4c3-a4d12a878e16)

**Comment by edersong** [comment]
Dropped again :-(

**Comment by IgnisDa** [comment]
You must be getting some error in the docker logs???

How much memory does your server have?

**Comment by IgnisDa** [comment]
@kilnake You are running on non-https. There is an env variable you need to set to get it working: `FRONTEND_INSECURE_COOKIES=true`.

**Comment by kilnake** [comment]
> @IgnisDa  

It is already unchecked in docker-compose, da.
i even tried with v5.0.7

**Comment by kilnake** [comment]
I think there is some problem with admin account. 

when I went ahead with creating a new user- and logged in. it allowed me. But without admin account how much am i missing?

**Comment by IgnisDa** [comment]
@kilnake You can create new users from the Users settings page in admin account. That page is not available to other accounts.

**Comment by IgnisDa** [comment]
@edersong I have started getting the same error on my instance, now I just gotta reproduce it.
