### ISSUE TITLE
Add multiple metadata fetchers

### ISSUE THREAD

**Issue by kilnake** [IgnisDa/ryot#782]
possible to add multiple metadata fetchers depending on countries and language?

**Comment by IgnisDa** [comment]
You can change language for a particular provider. But multiple is not possible.

**Comment by kilnake** [comment]
is it possible to change metadata provider according to country?

**Comment by IgnisDa** [comment]
Which provider do you want to change and to what language?

**Comment by IgnisDa** [comment]
Sorry not possible and I don't plan to add this feature to Ryot.
