### ISSUE TITLE
Remove show from ryot : feature add?

### ISSUE THREAD

**Issue by kilnake** [IgnisDa/ryot#783]
How to delete the single show easily without messing up rest of the library with similar names?
for example: 90days fiance: pillow talk,
90 days fiance : before the 90 days. so on...

is there a way to delete multiple shows from list?
OR 
How to remove a show which is accidentally got added due to fat fingers?

**Comment by IgnisDa** [comment]
Once you remove all seen entries from a media (show, movie etc) and remove it from all collections, it will be automatically removed from Ryot in 24 hours.

**Comment by IgnisDa** [comment]
Closing this. Let me know if it does not get removed automatically in 24 hrs.

**Comment by kilnake** [comment]
It does not get removed, but different show got removed. (might be my mistake-- but unaware how the app works.)

by the way, ryot crashes after few minutes and requires restarting the container.

**Comment by IgnisDa** [comment]
Just upgrade to the latest version. This has been fixed already.
