### ISSUE TITLE
Can't Enable Video Games

### ISSUE THREAD

**Issue by slyfoxgh** [IgnisDa/ryot#788]
I added my Twitch account Client ID and Secret to docker-compose file. The Videos Games tab appears in the Preferences menu. However, after I enable video games and press save, after a refresh, it toggles back to disabled.

**Comment by IgnisDa** [comment]
Can you show me what env variables you set? (You can redact the values)

**Comment by slyfoxgh** [comment]
```services:
  ryot-db:
    image: postgres:16-alpine # atleast version 15 is required
    restart: unless-stopped
    networks:
      - external_edge
    volumes:
      - /share/docker/appdata/ryot/postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_USER= postgres
      - POSTGRES_DB= postgres
    container_name: ryot-db
  ryot:
    image: ghcr.io/ignisda/ryot:latest
    networks:
      - external_edge
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ryot-db:5432/postgres
      - FRONTEND_INSECURE_COOKIES=true # if running on HTTP
      - VIDEO_GAMES_TWITCH_CLIENT_ID:REDACTED
      - VIDEO_GAMES_TWITCH_CLIENT_SECRET:REDACTED
      - VIDEO_GAMES_IGDB_IMAGE_SIZE:t_original
      
    ports:
      - 8000:8000
    pull_policy: always
    container_name: ryot
volumes:
  postgres_storage: null
networks:
  external_edge:
    external: true
```

**Comment by IgnisDa** [comment]
DId you restart the ryot containers after setting the variables?

**Comment by slyfoxgh** [comment]
Yes. I restarted it multiple times. Same result. Video Games toggles off after I enable it and save it.

![Uploading Screenshot 2024-04-25 at 11.20.49 AM.png…]()

**Comment by IgnisDa** [comment]
Just a sanity check. Env variables should be `VIDEO_GAMES_TWITCH_CLIENT_ID=abcd` not `VIDEO_GAMES_TWITCH_CLIENT_ID:abcd`.

**Comment by slyfoxgh** [comment]
Changing from `:` to `=` fixed the issue 

Thank you. 😀
