### ISSUE TITLE
Audiobookshelf Syncing Progress

### ISSUE THREAD

**Issue by slyfoxgh** [IgnisDa/ryot#789]
Ryot syncs with Audiobookshelf as to which media I am playing but it does not sync the actual progress. All books have 0% progress. Is it supposed to sync progress as well?

<img width="987" alt="Screenshot 2024-04-25 at 11 37 21 AM" src="https://github.com/IgnisDa/ryot/assets/2897699/e035005c-45c4-43d4-904d-9176d7f053fe">

<img width="1070" alt="Screenshot 2024-04-25 at 11 37 25 AM" src="https://github.com/IgnisDa/ryot/assets/2897699/d3c29acc-33a8-47c6-8a3b-d11254e5655c">

**Comment by IgnisDa** [comment]
The sync happens every 2 hours (which can be changed). The first time a new media is detected, it always starts at 0%. It will be corrected on the next sync.

I find this annoying too but does not bother me enough to actually fix it lol.

Closing as wont fix.
