### ISSUE TITLE
[Feature Request] Be able to remove a collection

### ISSUE THREAD

**Issue by philipjholm** [IgnisDa/ryot#79]
Maybe I just can't see but I can't find any way to remove a collection, no matter if it is empty or not.

**Comment by IgnisDa** [comment]
What kind of a UI would you prefer for this?

**Comment by philipjholm** [comment]
I was looking for it under "Collections" so maybe when you hover over a custom collection title the following button appears and becomes clickable? And clicking on it gives you a confirmation popup if you are sure that you want to remove it. 
I also guess the default collections shouldn't be removable if that destroys some functionality elsewhere,

![mockup](https://github.com/IgnisDa/ryot/assets/37110163/b5a1267c-295a-43db-a9f2-b824293653cc)

![remove-icon](https://github.com/IgnisDa/ryot/assets/37110163/e96e2f37-36cf-4f34-9eef-487721ac250a)
