### ISSUE TITLE
[Feature Request] Watched List

### ISSUE THREAD

**Issue by j450n1** [IgnisDa/ryot#791]
Would it be possible to add a Watched List collection? It would be handy to sort by date watched so we can see what films / TV I've recently seen.

**Comment by IgnisDa** [comment]
You can apply the "Completed" filter on the media list page and sort by whatever you want.

**Comment by IgnisDa** [comment]
Or do you want something different?

**Comment by j450n1** [comment]
Ahh thank you! Completely missed that!
