### ISSUE TITLE
[Feature Request] Be able to disable login

### ISSUE THREAD

**Issue by philipjholm** [IgnisDa/ryot#80]
First of all, I just want to say that I am really starting to see the potential in this app and really like how excellent you are with taking feedback. Good job!

Finally, I would really like if it was possible to disable the requirement of having to login. I only run it locally so a bit of annoyance to need to login.

**Comment by IgnisDa** [comment]
Thank you for the kind words.

Ryot is tightly coupled to the idea of users and as such would be really difficult (or maybe even impossible) to remove that coupling. As such, i don't think it'd be wise to refactor code to support single user.

The token issued after login remains active for 90 days (https://github.com/IgnisDa/ryot/blob/72eb22eba95806a667a6fdc8e39e2cebdbad2df1/apps/backend/src/users/resolver.rs#L118). Is that not enough for you?

**Comment by philipjholm** [comment]
I totally see your point and can live with 90 days. Keep up with the good work!
