### ISSUE TITLE
Add in support for other videogame databases

### ISSUE THREAD

**Issue by FathomRaven** [IgnisDa/ryot#801]
Since IGDB requires each user to supply their own key, is it possible to use a different provider instead? [TheGamesDB](https://thegamesdb.net/) seems promising, as does [Lutris](https://lutris.net/api/games). TheGamesDB requires developers to request an API key, but that shouldn't be an issue, and Lutris doesn't even seem to require a key at all.

**Comment by IgnisDa** [comment]
That's a great idea. Would you be willing to make a pr?

**Comment by FathomRaven** [comment]
I have very little experience in Rust so no promises, but I'll do what I can.

**Comment by IgnisDa** [comment]
I looked into the Lutris API and it's extremely lacking in terms of functions it has and data it provides. I Don't think that'd work out.
