### ISSUE TITLE
Incorrect date for manual entries?

### ISSUE THREAD

**Issue by Artnal** [IgnisDa/ryot#802]
Hi there, 

Quick question on my end, I'm not sure if this is intended behaviour or not. 

I manually enter read chapters for mangas with custom dates. However, the date displayed in the "History" tab is always off by one day compared to what I entered. Let's say I enter 24/4/2024 as a custom date, the history tab will show Started: N/A, Ended: 04/23/2024. I then have to manually re-edit the entry in "History" for it to match what I had originally provided. 

Is this intended behaviour?

Thanks!

**Comment by IgnisDa** [comment]
Nope, that is not correct behavior. Can reproduce. Will look into it. Thanks for reporting.
