### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#806]
Hi,

I come with the idea of migrate from 4.* to 5.* but it seems like the whole project documentation is down.

https://ignisda.github.io/ryot/migration.html#from-v4-to-v5

![image](https://github.com/IgnisDa/ryot/assets/854646/f7992372-0c77-4bb7-86f2-e30243de588a)

**Comment by IgnisDa** [comment]
Try https://ryot-docs.io.
