### ISSUE TITLE
Receiving the same notifications of some people every day

### ISSUE THREAD

**Issue by diogovalentte** [IgnisDa/ryot#810]
Every day I receive these same 4 notifications on Ntfy:

- Hunter Schafer has been associated with Euphoria as Co-Writer

- Hunter Schafer has been associated with Euphoria as Co-Executive Producer

- Hunter Schafer has been associated with Euphoria as Writer

- Zendaya has been associated with Euphoria as Executive Producer

I also monitor other people and they work fine, this issue happens only with Hunter Schafer and Zendaya.

I tried to stop monitoring them and start again, but the issue persisted.

**Comment by IgnisDa** [comment]
Im aware of this and can reproduce. The problem is actually quite complicated to solve so it'll need some time for me to fix.

Thanks for reporting.

**Comment by IgnisDa** [comment]
I have fixed this. Released with `v5.2.0`. Please note that only the first time, you will receive a lot of notifications.

**Comment by diogovalentte** [comment]
Great, thanks!

**Comment by IgnisDa** [comment]
Reopening this since I pushed an extremely horrific bug 😅.

**Comment by IgnisDa** [comment]
I recommend disabling notifs for one cron cycle via this setting, since you will receive notifications again as I described before: 
![image](https://github.com/IgnisDa/ryot/assets/60938164/e4936df4-0c45-4d29-9ddd-33152d20cce2)
