### ISSUE TITLE
[Feature Request] Collection for "Done" media

### ISSUE THREAD

**Issue by Xtr4gent** [IgnisDa/ryot#813]
I would like to be able to add a "Done" to the list of options under collections. I have alot of show "In Progress" but when they are done I want to be able to put them in a "Done" or "Finished Watching" state.

**Comment by IgnisDa** [comment]
There is a "Completed" filter in the media list page. Does that not work for you?

**Comment by Xtr4gent** [comment]
That works but it would be awesome to have a option just like the "In Progress" and "Monitoring" tags in the same dropdown menu. Also being able to create own collection names would be great too for general customization. 


![Capture](https://github.com/IgnisDa/ryot/assets/103376214/5fea0b21-7258-434d-9ae5-367880bec28c)

**Comment by IgnisDa** [comment]
Yep I agree with having an automatically created "Done" collection.

You can create your own collection in the "Yours" collection page (which you can access via the sidebar).

**Comment by Xtr4gent** [comment]
Thanks for the fast response!

For some reason my collections tab in the sidebar was turned off. Now that I turned it on I can see the "Yours" section. Thanks.

**Comment by IgnisDa** [comment]
Please don't close this. I would like to create a default collection for done.
