### ISSUE TITLE
Allow Volume tracking for Manga

### ISSUE THREAD

**Issue by thebigboss9018** [IgnisDa/ryot#818]
Hello,

Official physical manga are released by volume, only by chapters makes it a little bit harder to track.  It's possible to add this option for manga? 

Thanks

**Comment by IgnisDa** [comment]
WOuld it work for you if this input had a `volume` input as well?
![image](https://github.com/IgnisDa/ryot/assets/60938164/07403065-7a09-4abe-959f-b27efa5c042b)

**Comment by thebigboss9018** [comment]
yes! it would be awesome if its not much work.

Thanks

**Comment by IgnisDa** [comment]
WIll do 👍🏽
