### ISSUE TITLE
Grammar issue - "Mark as play/watch"

### ISSUE THREAD

**Issue by kaibagley** [IgnisDa/ryot#820]
Just a low priority issue, but when adding games using the search menu, the button says "Mark as play" rather than "Mark as played". Similarly for other media, saying "Mark as watch" rather than "Mark as watched"

Looks like the [getVerb](https://github.com/IgnisDa/ryot/blob/ad0e06537e9da33811c3478d969f2c879c262cb2/apps/frontend/app/lib/generals.ts#L136) function is where the "play" and "watch" words come from maybe??

Thanks!!

**Comment by IgnisDa** [comment]
Someone made a PR for this long ago. Problem is `getVerb` is used in a lot of places so fixing at one place ends up messing up others.

I'm closing this since this doesn't really bother me. But I'm open to discussion if you have a better solution.
