### ISSUE TITLE
Feature Request - Reorder 'Update Progress' dropdown

### ISSUE THREAD

**Issue by cameronj86** [IgnisDa/ryot#821]
I understand the current ordering:
1. I finished it
2. Set Progress
3. Put On Hold
4. Marked as Dropped
because from a TV/Movie perspective, the odds are you are saying you finished an episode the majority of the time. 

However, when it comes to books, putting `I finished it` before `Set Progress` is like prioritizing the `quit game` button ahead of the `save game` in videogames, or `git reset --hard HEAD` ahead of `git commit` in git. 

I have had 1-2 occasions, where I hit the 'I finished it' button by a mistake, which resulted in an extended detour trying to salvage my existing progress history.

Since the average book user might use the `Update Progress` button 10-20x as much as the one time they used `I finished it`. My suggestion is for the books section to have its own unique ordering to create separation between the typical option and the regular option for a better UX:
1. Set Progress
2. Put On Hold
3. Marked as Dropped
4. I finished it

This could lead to some muscle memory issues for those that expect `Books` to inheriting the same order as other content, so I'm open to feedback

**Comment by IgnisDa** [comment]
This is a valid concern. Would you be willing to make a PR?

**Comment by IgnisDa** [comment]
You just need to move these lines to the end.

https://github.com/IgnisDa/ryot/blob/ad0e06537e9da33811c3478d969f2c879c262cb2/apps/frontend/app/routes/_dashboard.media.item.%24id._index.tsx#L1069-L1080

Make sure you copy the conditional on this line:
https://github.com/IgnisDa/ryot/blob/ad0e06537e9da33811c3478d969f2c879c262cb2/apps/frontend/app/routes/_dashboard.media.item.%24id._index.tsx#L1044

**Comment by cameronj86** [comment]
Damn this was my bad, I got sidetracked w/ life but eventually started looking forward to my first PR ever. Appreciate the hand-holding thru the code and I'll try to tackle any other issues myself first moving forward
