### ISSUE TITLE
[FEATURE REQUEST] Separate default collections (watchlist etc.) and custom, created collections

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#836]
The default collections are fundamentally different from custom collections in that the prior has a built-in UI integration (e.g. in "Actions" tab).
I think it would be clearer if we separated them e.g. just by a horizontal line.

Also is there a scenario where you would really want to delete one of the default collections?
I feel like one should not have a delete button for them and neither an edit button.

**Comment by IgnisDa** [comment]
The default collections can not be deleted. The btn is there for preserving similarity.

The separation idea is good. I will see what I can do.
