### ISSUE TITLE
[FEATURE REQUEST & ISSUE] Notifications/Calendar - Wrong aired date - Aired time implementation

### ISSUE THREAD

**Issue by rampionx** [IgnisDa/ryot#840]
Hi ! 
First of all, thank you again for this beautiful software that I use daily from now on.

I would like to provide two points that are linked.

First the issue:
- Some aired dates are wrong and I don't know how to correct it.
Example (I'm in France - GMT+1):
- Solo Leveling - Aired on Saturday / Announced on Sunday by RYOT.
- Mushoku Tensei - Aired on Sunday / Announced on Monday by RYOT.
- Blue exorcist - Aired on Saturday / Announced on Sunday by RYOT.

Impact: I receive notifications one day after the real release day on TV/streaming platforms. It's quite a loss.

Reason: I watch a lot more anime than TV shows. So I can't say if the problem is only on anime. However, in Sonarr and Trackt the dates are correct. After a quick search, it appears that TVDB, ANIDB, MAL and TMDB are all impacted.

Second point the feature request:
- Would it be possible to synchronize media broadcast times?
Before switching to a self-hosted solution, I used TV Time and Trakt among others. Both sent me notifications when the episode aired. 
It's much more practical for tracking your series than a bunch of notifications for the day at a fixed time. 
Sonarr also shows the broadcast time in its calendar but can't send notifications.
Perhaps the solution to the two points I mentioned would be to synchronize the metadata on Trakt.tv?

In any case, thank you in advance for your interest.

**Comment by IgnisDa** [comment]
I'm a bit tied up at the moment. If you're up for it, feel free to jump in and submit a PR – I'd really appreciate the help. If you're not sure where to start, I can give you some pointers.

Alternatively, if coding isn't your thing but you still want to support the project, a donation would be super helpful.

**Comment by IgnisDa** [comment]
@rampionx I think the problem here is that your database is in the wrong timezone. Can you try [this](https://github.com/docker-library/postgres/issues/137#issuecomment-269216438)? NOTE: You will have to dump your db, reset it and then restore it back again. Timezone changes are not applied to an already initialized database.

**Comment by rampionx** [comment]
Hi IgnisDa. I have tryed to change timezone. RYOT and PostgresSQL15 are both on my correct timezone (Europe/Paris). (I made a fresh install)
![image](https://github.com/user-attachments/assets/081ddc21-e8bc-4f34-8c25-791ccd46ae41)

It's steal wrong aired date. In the example below, I get notified by RYOT, 27 hours before the episode is released (at midnight, the day before, so 27 hours before). The aired date still good on Trakt and Sonarr contrary to, RYOT, TVDB and TMDB.
![image](https://github.com/user-attachments/assets/1e230694-9ad9-4ad0-bc2d-1eefe52b502d)

Thank you for your help.

**Comment by IgnisDa** [comment]
@rampionx Is this a data discrepancy? As far as I can see, the release dates of shows seem to be different on TMDB than trakt. Can you check? https://www.themoviedb.org/tv/94997-house-of-the-dragon/season/2

**Comment by rampionx** [comment]
Hi IgnisDa,
Yes. That's what I said before. As far as I can see TVDB, TMDB, AniDB and MAL use the same aired time.
In my case, only Trackt and Sonarr have the good date/hours. It's probably a timezone problem but I don't know how to change it.
As you can see in the example below, Sonarr and Trackt look like to use my TZ. TVDB and TMDB looks in a bad timezone. (IDK for TMDB and RYOT. IDK how to see the Aired hour)

TVDB:
![image](https://github.com/user-attachments/assets/fa082fc6-8f3f-4f5e-97d3-dbbdba38c9a6)

TMDB:
![image](https://github.com/user-attachments/assets/7e6e7a39-5b62-4f44-8cb2-66d6b3206108)

RYOT:
![image](https://github.com/user-attachments/assets/f477954f-8faf-4c0a-980e-93ad1673ca6f)

Trackt:
![image](https://github.com/user-attachments/assets/65eedb8a-8008-45ed-9b9c-149b88101f92)

Sonarr:
![image](https://github.com/user-attachments/assets/c96a0052-2621-434e-8580-7b00e57804fa)

Estearn US vs Europe/Paris TZ:
![image](https://github.com/user-attachments/assets/5ac6faf3-7f7d-4d95-b21b-022ca53759ad)

**Comment by IgnisDa** [comment]
Ryot does not pull release dates from Trakt. As far as I know, Trakt uses TMDB API, so I wonder if they are maintaining release dates separately? Do you have any idea about this?

**Comment by IgnisDa** [comment]
Unfortunately, there does not seem to be much I can do to fix this. Ryot only uses data from TMDb which happens to be inaccurate at times.

**Comment by Pingumania** [comment]
Just wanted to give more info as I looked into the API of TMDb. They just save the original air date without any information of the timezone. So for most US shows this will be off by 1 day for Europe for example. 

With TheTVDB I already get the correct date (my timezone is GMT+2).

I don't think there is a reasonable approch for TMDb to fix this on Ryot's side. The only thing that comes to mind is letting the user override the air date or setting an offset for each show.
