### ISSUE TITLE
[BUG] Jellyfin import fails with error in logs: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by JPsychotic** [IgnisDa/ryot#844]
Hi. I tried importing from my jellyfin server but sadly it failed. I attached logs which were created with both `RUST_LOG=ryot=debug` and `RUST_BACKTRACE=full`.

[_ryot_logs.txt](https://github.com/IgnisDa/ryot/files/15390426/_ryot_logs.txt)

**Comment by IgnisDa** [comment]
Would it be possible for you to give me access to your Jellyfin server? I am not able to reproduce this.

**Comment by JPsychotic** [comment]
sadly I'm only hosting it only for my local network so this is not possible :( as you cannot reproduce the problem you can close the issue I will try exporting my data to the json format for importing. Thank you anyways! :)

**Comment by Spiritreader** [comment]
> Would it be possible for you to give me access to your Jellyfin server? I am not able to reproduce this.

We are getting this issue as well.
Let me know if you still need access to a server

**Comment by IgnisDa** [comment]
Yep I still need it. If you can share your instance, can you please join the Discord so that we can collaborate on it? Link is the readme.

**Comment by IgnisDa** [comment]
I would need more information to help you debug the problem. If possible, please join the Discord.
