### ISSUE TITLE
Feature request - Books can have quotes

### ISSUE THREAD

**Issue by yodatak** [IgnisDa/ryot#849]
I'm seeking a way to collect all the quotes to the specific book and i would love to use ryot for this do you think its simple to implement ?

**Comment by IgnisDa** [comment]
Should be simple to implement via #578.

**Comment by IgnisDa** [comment]
But the current implementation does allow for adding a media to collection multiple times.

Note to self: maybe an array type of information field.

**Comment by IgnisDa** [comment]
Released as part of [Ryot Pro](https://ryot.io).
