### ISSUE TITLE
[Possible Bug] - Authors dissapeared from books

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#850]
Hi,

I am noticed that the authors information have disappeared from books, before it was shown there, and access to the author page. Not sure if it is a bug or a feature :smile: 

![image](https://github.com/IgnisDa/ryot/assets/854646/403455ec-1a8f-4551-8b7d-c7513cb170c8)

**Comment by IgnisDa** [comment]
Ryot aggressively deletes data via a cron job so as to keep the database size minimal. You can Actions -> More actions -> Update metadata to download the authors information back. 

This will obviously again be deleted in the next cron cycle (occurs every 24hrs I think).

**Comment by SirMartin** [comment]
But it happens also for a newly added book, and if I update the metadata it does not appear.

**Comment by IgnisDa** [comment]
Which book is this?

**Comment by SirMartin** [comment]
OK, understood, I need to update the page (F5) manually to see the changes, it appears, but it is empty, and you need to navigate to the author, and update the person info, to see the name and picture. Is that the expected behaviour?

**Comment by IgnisDa** [comment]
Yes.

**Comment by SirMartin** [comment]
Perfect, thanks. It would be possible maybe an option to avoid the automatic deletion of this. For example, I like to see this data, and I don't have so many books or shows, that generates an issue in my particular case.

**Comment by IgnisDa** [comment]
I don't think I would want to add an option like that would take a lot of code changes.

As a workaround, you can add the author you want to a collection. That way it would not be deleted.

**Comment by SirMartin** [comment]
I didn't check the code deeply, but I was just thinking that having a flag that enables/disables a job, and just at the beginning of the job check if it should be executed  or not, and in that case just exit from the job, maybe is not the cleanest way, but probably is not too complicated.

Just an idea.

Thanks again for your amazing work.
