### ISSUE TITLE
[BUG] - When new show season appears and start watching show status still completed

### ISSUE THREAD

**Issue by SirMartin** [IgnisDa/ryot#851]
I found yesterday that a TV Show it was completed because it only has 2 seasons, when I finished the 2nd it was marked as **COMPLETED** collection, but now a third season appeared, and I started yesterday to watch it after watching the first episode it didn't change to In Progress collection, like it does for example with new shows.

**Comment by IgnisDa** [comment]
So you are saying it did not remove it from the "Done" collection?

Was it added to the "In Progress" collection though?

**Comment by SirMartin** [comment]
No it was not

**Comment by IgnisDa** [comment]
Thats weird. Will try to reproduce this and get back to you.

**Comment by IgnisDa** [comment]
For the time being, you can remove it from Done manually and add it to in progress collection.

**Comment by SirMartin** [comment]
I did that, but I show, and just want to let you know, if I continue with another show that was completed and happen again, I write you again.

**Comment by IgnisDa** [comment]
Can not reproduce this. It was added to the "In Progress" collection but also stayed in the "Completed" collection as well. This is the expected behavior.
