### ISSUE TITLE
[BUG] Can't log in after update

### ISSUE THREAD

**Issue by LnLcFlx** [IgnisDa/ryot#853]
On the latest version 5.5.3 when accessing ryot after clearing browser cache I get
```
We encountered an error. If you recently upgraded the server, you may have to logout and login again. If the error still persists, please create a new issue on [GitHub](https://github.com/ignisda/ryot/issues).
```
In the logs it says
```
[proxy] {"level":"error","ts":1717247134.4333189,"logger":"http.log.error","msg":"dial tcp [::1]:5000: connect: connection refused","request":{"remote_ip":"127.0.0.1","remote_port":"51918","client_ip":"127.0.0.1","proto":"HTTP/1.1","method":"POST","host":"localhost:8000","uri":"/backend/graphql","headers":{"Content-Length":["146"],"User-Agent":["node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"],"Accept-Encoding":["gzip,deflate"],"Connection":["keep-alive"],"Content-Type":["application/json"],"Accept":["*/*"]}},"duration":0.000609372,"status":502,"err_id":"2u5aw3i11","err_trace":"reverseproxy.statusError (reverseproxy.go:1265)"}
[proxy] {"level":"error","ts":1717247134.4333231,"logger":"http.log.error","msg":"dial tcp [::1]:5000: connect: connection refused","request":{"remote_ip":"127.0.0.1","remote_port":"51934","client_ip":"127.0.0.1","proto":"HTTP/1.1","method":"POST","host":"localhost:8000","uri":"/backend/graphql","headers":{"Content-Type":["application/json"],"Accept":["*/*"],"Content-Length":["239"],"User-Agent":["node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"],"Accept-Encoding":["gzip,deflate"],"Connection":["keep-alive"]}},"duration":0.000615635,"status":502,"err_id":"gf1m792j1","err_trace":"reverseproxy.statusError (reverseproxy.go:1265)"}
[frontend] ClientError: GraphQL Error (Code: 502): {"response":{"error":"","status":502,"headers":{}},"request":{"query":"query CoreEnabledFeatures {\n  coreEnabledFeatures {\n    fileStorage\n    signupAllowed\n  }\n}"}}
[frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
[frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]     at getCoreEnabledFeatures (file:///home/ryot/build/server/index.js?t=1717242166000:782:35)
[frontend]     at async Promise.all (index 0)
[frontend]     at loader (file:///home/ryot/build/server/index.js?t=1717242166000:13239:46)
[frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
[frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
[frontend]     at async Promise.all (index 1)
[frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
[frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20) {
[frontend]   response: {
[frontend]     error: '',
[frontend]     status: 502,
[frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
[frontend]   },
[frontend]   request: {
[frontend]     query: 'query CoreEnabledFeatures {\n' +
[frontend]       '  coreEnabledFeatures {\n' +
[frontend]       '    fileStorage\n' +
[frontend]       '    signupAllowed\n' +
[frontend]       '  }\n' +
[frontend]       '}',
[frontend]     variables: undefined
[frontend]   }
[frontend] }
[frontend] GET /auth?redirectTo=%2F 500 - - 13.616 ms
[frontend] Error: No route matches URL "/sw.js"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4519:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2958:19)
[frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend] Error: No route matches URL "/workbox-1051b61c.js"
[frontend]     at getInternalRouterError (/home/ryot/node_modules/@remix-run/router/router.ts:4519:5)
[frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2958:19)
[frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:35)
[frontend]     at requestHandler (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:108:24)
[frontend]     at /home/ryot/node_modules/@remix-run/express/dist/server.js:41:28
[frontend] GET /sw.js 404 - - 3.711 ms
[frontend] GET /workbox-1051b61c.js 404 - - 2.724 ms
```
It seems to also happen on v5.4.7.

**Comment by IgnisDa** [comment]
Please restart the server and show me the entire logs.

**Comment by LnLcFlx** [comment]
The container hasn't restarted but the issue vanished. Inside Ryot I see
> To get started, select a media type from the sidebar, enter a query in the search tab, and add a media to your seen history or watchlist.
>
> This notice will disappear once your summary is re-calculated.

[These](https://github.com/user-attachments/files/15523135/logs.txt) are the entire logs since the start of the container.

**Comment by IgnisDa** [comment]
Yep this is expected. Go to the miscellaneous settings and regenerate summary. If you had any workouts then revaluate workouts as well.

**Comment by LnLcFlx** [comment]
What exactly is expected? The error or just the message?
Because out of the blue the "We encountered an error. If you recently..." came back and I did not upgrade.

**Comment by IgnisDa** [comment]
The summary being reset is expected. And you did update. Your first comment says so.

**Comment by LnLcFlx** [comment]
So the regeneration of the summary causes Ryot to be unusable for this long with the the respective errors in the logs?

What I meant in my above comment is that the problem vanished eventually and then reappeared again without me updating or restarting anything.

Now, after an automatic system backup and restart it is working for now.

**Comment by IgnisDa** [comment]
No. The [last migration](https://github.com/IgnisDa/ryot/pull/847) was very very big. As a result, I forced it to overwrite (or rather reset) the summary to default so that the migrations do not take too much time.

Once the migrations were complete and the server boots up fine, the summary would be regenerated after 12 hrs, or users could have re-generated manually it from the miscellaneous settings.

**Comment by CaptainJawZ** [comment]
I have the same issue, with similar looking logs, except that I've been waiting since Sunday morning for the recalculation to happen, there a way to do it manually?
https://copy.servidos.lat/upload/monkey-fox-otter

**Comment by IgnisDa** [comment]
@CaptainJawZ Can you try this: https://github.com/IgnisDa/ryot/issues/857#issuecomment-2147020000?

**Comment by CaptainJawZ** [comment]
I may be a bit lost on how to go about it, so I regressed to v5.5.0, but I have the same issue, I thought of letting it stay overnight see if I had any improvements, but it stuck kind of the same, older versions like v5.0.5 won't load.

**Comment by IgnisDa** [comment]
Wdym by you had the same issue? 5.5.0 does not have these migrations. Can you stop the servers completely and then make the change in your docker compose and then start it up again?

**Comment by CaptainJawZ** [comment]
> Wdym by you had the same issue? 5.5.0 does not have these migrations. Can you stop the servers completely and then make the change in your docker compose and then start it up again?

that is what I did, I did it from scratch deleting every docker image pulled, and is sitll the same
https://copy.servidos.lat/upload/bat-pony-lion

**Comment by IgnisDa** [comment]
Can you send a dump of your database? Alternatively you can join the Discord linked in the readme and I can help debug there.
