### ISSUE TITLE
DB Migrations taking a very long time

### ISSUE THREAD

**Issue by ellsclytn** [IgnisDa/ryot#857]
I bumped to 5.5.5 recently, having been on 5.0.5 for a while. I gather that https://github.com/IgnisDa/ryot/pull/847 is expected to cause migrations to take a while in some instances, but wondered just how long might be expected. Mine has been stuck migrating for over 24 hours now. Postgres seems to be doing something (~92% usage on one core with an `UPDATE` underway). 

It successfully applied several migrations before reaching `Applying migration 'm20240601_07_change_person_primary_key'` and not progressing beyond that.

If this is expected, I'm happy for this issue to be closed. Just thought I should raise it in case others are experiencing similar.

**Comment by IgnisDa** [comment]
One thing you can do before migrating is go to Miscelleanous settings with an admin account and click on "Perform background tasks". This will remove all useless data that might be stored in db. Do it with `RUST_LOG=ryot=trace` for increased logging. You can stop the running migrations. They are run in a transaction, so db will go back to the previous state.

24 hours is too much. I had ~1k media in total and migration took me around 20 sec. The demo instance has around 4k media and took 1 min to migrate. So if it is taking more than that, it means you have a lot of useless data lying around. That can be cleaned via the method described above.

If that does not solve the issue, feel free to email me a DB dump and ping me here. Closing for now.

**Comment by ellsclytn** [comment]
Thanks! Running the background jobs first did the trick. My `metadata` table shrunk to just over 500 items (used to be over 200K).

**Comment by IgnisDa** [comment]
You can also vaccum the db so that disk space is freed up .
