### ISSUE TITLE
[FEATURE REQUEST] - Audiobookshelf Integration and Import - New Pass

### ISSUE THREAD

**Issue by aureateflux** [IgnisDa/ryot#860]
The Audiobookshelf integration only seems to import audio books that are in progress. It doesn't import anything that has been completed (the importer does this, though the "are you sure" dialogue sounds unccessarily ominous), and it doesn't import anything in the library that hasn't been started yet.

Also, Audiobookshelf supports podcasts and e-books, but neither of these are captured by either the integration sync or the import function regardless of whether they are completed, in progress, or not yet started.

Is it possible to have another pass at this to see if it's possible to pull this data from the [ABS API?](https://api.audiobookshelf.org/)

**Comment by IgnisDa** [comment]
I suppose you haven't tried the ABS importer yet?

**Comment by IgnisDa** [comment]
The primary reason why I have not implemented podcasts supprt for ABS is because I do not have an instance I could test it on. If you are willing to share you instance for testing purposes, I can take another stab at this.

**Comment by aureateflux** [comment]
I'll look into spinning up a test instance for you. What's the best way to share info?

**Comment by IgnisDa** [comment]
There is a discord in the readme. You can join that and we can collaborate there.
