### ISSUE TITLE
[FEATURE REQUEST] - Telegram notifications

### ISSUE THREAD

**Issue by Joery** [IgnisDa/ryot#861]
It would be great if Telegram could be setup as a notification platform. I'm aware it would be possible via a platform such as Pushsafer, but then you'll need to make an additional account & have API-call limits.

The easiest implementation would be for users to create their own bot with the "BotFather"-bot on Telegram and providing Ryot with the bot-token & chat/group id. Ryot would need to simply make a HTTP GET-call to the url in the following format:

```
https://api.telegram.org/botxxx/sendMessage?chat_id=xxx&text=xxx
```

**Comment by IgnisDa** [comment]
Seems like a reasonable ask. Will see what I can do.

**Comment by Joery** [comment]
Works like a charm, thank you for the quick implementation.
