### ISSUE TITLE
[FEATURE REQUEST] Make Integration Sync Interval Configurable per Integration

### ISSUE THREAD

**Issue by aureateflux** [IgnisDa/ryot#874]
Currently, integration sync interval is configurable in environmental variables. This works well for most cases, but because of the varying needs of different types of media, it makes sense to be able to configure individual sync intervals for each integration.

For example, if your use case for Audiobookshelf is purely listening to audiobooks, a long sync interval should be sufficient since most audiobooks are longer than 5 hours long. However, you may want to capture shorter media over on the Jellyfin integration, necessitating a shorter sync interval than is necessary for audio books.

**Comment by IgnisDa** [comment]
Hey. I've decided not to implement this because the changes required for this would be too complicated for little gain.

API calls made to the ABS server are cheap and the duration can already be changed by an env variable.

Thanks for creating this issue!
