### ISSUE TITLE
[FEATURE REQUEST] Do not create calendar events for Specials

### ISSUE THREAD

**Issue by DickenSerm** [IgnisDa/ryot#879]
It would be a nice feature if you had the option to hide specials under Upcoming and Calendar in the settings.

**Comment by IgnisDa** [comment]
This is a good idea. Will push a fix so that calendar events for Specials are not created at all. Thanks for reporting this!

**Comment by IgnisDa** [comment]
@DickenSerm After upgrading to latest, these events will be removed from calendar completely.

**Comment by DickenSerm** [comment]
Perfect, it works :)

**Comment by IgnisDa** [comment]
Can you send me a dump of your database?

**Comment by DickenSerm** [comment]
> Can you send me a dump of your database?

Yes, of course, it's on the way

**Comment by IgnisDa** [comment]
Fixed with `v6.2.11`. Turns out some "Specials" are named as "Extras".

All season 0 should be automatically be deleted by the nightly cron job.

**Comment by DickenSerm** [comment]
I started it manually and it worked. Thanks for the quick fix :)
