### ISSUE TITLE
[BUG] Theme toggle lable doesn't dynamically update

### ISSUE THREAD

**Issue by Dav-Renz** [IgnisDa/ryot#883]
When I change the theme with the toggle above the logout button, the theme switches, but the lable stays. Only after a reload of the page does it update.

Pressing this:
![image](https://github.com/IgnisDa/ryot/assets/62567929/25ea3daf-7a29-4b36-b30a-a11bbe8cc2e8)
Changes the view to this:
![image](https://github.com/IgnisDa/ryot/assets/62567929/b8bb0836-4bd0-48f2-b18b-666989521104)

And pressing this:
![image](https://github.com/IgnisDa/ryot/assets/62567929/33a5e903-c17b-46e3-9a87-4fd33716d324)
changes to this:
![image](https://github.com/IgnisDa/ryot/assets/62567929/021a7e03-eac6-4f0a-8e0f-4b98437d0dd3)

**Comment by IgnisDa** [comment]
Thanks for reporting!. Will be released in the next release.

--- 

Note to self:

Use `clientLoader` to cache preferences. The loader you just enabled is quite heavy (~8kb data transfer for each navigation).
