### ISSUE TITLE
[FEATURE REQUEST] Per integration Minimum/Maximum progress limit

### ISSUE THREAD

**Issue by Artnal** [IgnisDa/ryot#886]
Hi there, 

Thank you for all your work on this project, it's been a pleasure using it so far!

I have already setup a custom Minimum/Maximum progress limit in my environment variables. However, I realize that distinct limits per integration might be useful. For example, I would like Jellyfin to report as "completed" if I have watched 90% of the media. However, for Audiobookshelf, I would like the "completed" status only if I've listened to 99% of the media (since audiobooks usually have very brief credits at the end). Would this distinction be possible?

Cheers

**Comment by IgnisDa** [comment]
Yeah I don't think it is worth the effort to allow editing integrations.
