### ISSUE TITLE
[FEATURE REQUEST] - IGDB / Twitch import for Game History Tracking

### ISSUE THREAD

**Issue by Ardakilic** [IgnisDa/ryot#893]
Hello, it'd be great if we could import our game playing lists from IGDB.

Lists are accessible publicly. E.g. Here are my profiles: 

https://www.igdb.com/users/ardakilicdagi
https://www.igdb.com/users/ardakilicdagi/lists/played
https://www.igdb.com/users/ardakilicdagi/lists/playing

"Want to play", "rated" etc. could be omitted for the time being.

Since there is IGDB credentials, I hope this could be done without a big hassle.

I'd appreciate if this is considered.

Thanks in advance!

**Comment by IgnisDa** [comment]
Seems like a resonable ask. Is there a btn to somehow export them or do I have to access the API to get list's contents?

**Comment by Ardakilic** [comment]
Hello, sadly I believe there is no such API.

First I checked the [client json](https://www.igdb.com/users/ardakilicdagi/lists/played.json?full=true) , but it's blank for every tine for me. And if I try to fetch it programmatically, it redirects to the HTML page.

Secondly, I checked their APIs, the closest one I could find is [collections](https://api-docs.igdb.com/#collection), but I'm not sure if that would work. There nothing regarding user data on their API docs.

Does Ryot have a built-in crawling mechanism? Maybe it would work with minor updates.

**Comment by IgnisDa** [comment]
Nope Ryot does not have any crawling. It just uses standard APIs.

I suggest you to write a script to crawl it and then convert it to json so that it can be imported via https://docs.ryot.io/importing#generic-json. Feel free to ping me here or on Discord for help.

**Comment by IgnisDa** [comment]
Closing since this is out of scope for Ryot.

**Comment by Ardakilic** [comment]
@IgnisDa 

Heya, I've checked, and you could actually export your data as CSV in IGDB:

For example, here's my played CSV data: [played.csv](https://github.com/user-attachments/files/16073674/played.csv)

Could this be parsed and utilized to importing directly? Various importers already utilize the CSV format.

I can create a new issue for this, if it's acceptable.

**Comment by IgnisDa** [comment]
Can you send me these files? You can join the Discord if needed.

**Comment by Ardakilic** [comment]
@IgnisDa heya, just joined your Discord and sent you over DM! Also you can find the attached [at my previous message](https://github.com/IgnisDa/ryot/issues/893#issuecomment-2204285436), just in case.

**Comment by IgnisDa** [comment]
@Ardakilic Deployed in `v6.4.7`. Please upgrade after an hour and test.

**Comment by Ardakilic** [comment]
@IgnisDa woah, this is fast, thank you! I'm at work right now, and I'll try this evening and let you know.
