### ISSUE TITLE
Issue with adding video game

### ISSUE THREAD

**Issue by gmsh-1** [IgnisDa/ryot#894]
I have seen another issue with someone not been able to add the video game section in Ryot, but it seems that the capitalization of the ENV variables was the issue. After searching quite a lot I can't figure out what I'm doing wrong here.

**My setup is local and nothing is shared outside my home, so not sure if this is the culprit or I if I need to setup the redirect URL differently .**

I followed the instructions on setting up Twitch to get the client and secret IDs here: https://github.com/muhsinkutay/ryot-typo/blob/main/docs/guides/video-games.md

OAuth Redirect URLs is set to https://igdb.com

I have the following in my compose.yaml
    environment:
      - POSTGRES_PASSWORD=xxxxxxxxx
      - POSTGRES_USER=ryot
      - POSTGRES_DB=ryot
      - VIDEO_GAMES_TWITCH_CLIENT_ID=xxxxxxxx
      - VIDEO_GAMES_TWITCH_CLIENT_SECRET=xxxxxxxxx

When I enable the video games and click Save Changes, I get a Success message but the section does not appear on the left and when i refresh the page the video games is unchecked.

**Comment by IgnisDa** [comment]
Not sure why you are following outdated instructions. The repo you linked is not written by me and has not been updated for a year. Please set the correct env variables. https://docs.ryot.io/configuration

**Comment by gmsh-1** [comment]
Thanks for the reply and your hard work you put into this.

The issue was setting the twitch variables in the db and not the app environment. Everything works now.
