### ISSUE TITLE
[FEATURE REQUEST] Bulk remove collection contents

### ISSUE THREAD

**Issue by theggs** [IgnisDa/ryot#895]
After import movies and tv shows from Trakt, I find all tv series I have watched are put into system created collections `Monitor` and `In Progress`

This makes some trouble:
Some tv series I have dropped appear in calendar, dashbaord `upcoming` and `In Process`. For example, I watched "The Boys" Season 1 and Season 2, and I have gave up watching the other seasons. "The Boys" will still be shown in my dashbaord. For these tv sereis, I have to remove them from system created collections one by one.

Expect:
Don't put the imported tv series into `Monitor` and `In Progress` collections. Or add batch delete item in the collections function so they can be removed from the collection easily.

**Comment by IgnisDa** [comment]
Bulk delete is something i plan to work on soon.

**Comment by IgnisDa** [comment]
Released in `v6.5.1`.
