### ISSUE TITLE
IGDB CSV import: some games are not imported which are not duplicates but the next in the series.

### ISSUE THREAD

**Issue by Ardakilic** [IgnisDa/ryot#899]
Hello,

First of all, thank you for implementing IGDB import. This helped me a lot!

I've tried igdb game importing today, but I have encountered some errors:

This is my uploaded CSV: [played.csv](https://github.com/user-attachments/files/16095056/played.csv)

This is the error I get after I import:

```json
[
    {
        "lot": "VIDEO_GAME",
        "step": "MEDIA_DETAILS_FROM_PROVIDER",
        "identifier": "Guild Wars 2",
        "error": "Query Error: error returned from database: duplicate key value violates unique constraint \"metadata-identifier-source-lot__unique-index\""
    },
    {
        "lot": "VIDEO_GAME",
        "step": "MEDIA_DETAILS_FROM_PROVIDER",
        "identifier": "Medal of Honor: Allied Assault",
        "error": "Query Error: error returned from database: duplicate key value violates unique constraint \"metadata-identifier-source-lot__unique-index\""
    },
    {
        "lot": "VIDEO_GAME",
        "step": "MEDIA_DETAILS_FROM_PROVIDER",
        "identifier": "Middle'-earth: Shadow of War",
        "error": "Query Error: error returned from database: duplicate key value violates unique constraint \"metadata-identifier-source-lot__unique-index\""
    },
    {
        "lot": "VIDEO_GAME",
        "step": "MEDIA_DETAILS_FROM_PROVIDER",
        "identifier": "Red Faction II",
        "error": "Query Error: error returned from database: duplicate key value violates unique constraint \"metadata-identifier-source-lot__unique-index\""
    },
    {
        "lot": "VIDEO_GAME",
        "step": "MEDIA_DETAILS_FROM_PROVIDER",
        "identifier": "Atelier Rorona: The Alchemist of Arland",
        "error": "Query Error: error returned from database: duplicate key value violates unique constraint \"metadata-identifier-source-lot__unique-index\""
    },
    {
        "lot": "VIDEO_GAME",
        "step": "MEDIA_DETAILS_FROM_PROVIDER",
        "identifier": "Atelier Sophie: The Alchemist of the Mysterious Book DX",
        "error": "Query Error: error returned from database: duplicate key value violates unique constraint \"metadata-identifier-source-lot__unique-index\""
    }
]
```

Iy says some games are duplicates, but they are not actually:

For example, "Guild Wars" and "Guild Wars 2", and "Middle Earth: Shadow of Mordor" and "Middle Earth: Shadow of War" are different games:

<img width="1043" alt="image" src="https://github.com/IgnisDa/ryot/assets/2063957/58d596f5-028b-4a8f-9581-0d2d9ee678de">

<img width="993" alt="image" src="https://github.com/IgnisDa/ryot/assets/2063957/b9de695a-5a9c-4e46-8e04-16bd1c5ab806">

<img width="1046" alt="image" src="https://github.com/IgnisDa/ryot/assets/2063957/7c252a52-ca50-41e2-b5f2-f2d8a91a4e0a">

<img width="1042" alt="image" src="https://github.com/IgnisDa/ryot/assets/2063957/f5090a0f-5d48-46e7-9c1d-07af81e932fc">

Could you check please? I can understand Atelier Rorona's case, which the base game and plus being identified as duplicates, but some of the games that are marked as duplicates are totally different games.

Thanks in advance!

**Comment by IgnisDa** [comment]
Thanks for reporting. Will take a look.

**Comment by IgnisDa** [comment]
@Ardakilic I am unable to find the root cause for this problem. I recommend you to just add this to your history manually.

Since this is a one time thing, I don't really see any reason to prioritize it.

**Comment by Ardakilic** [comment]
@IgnisDa than you, no worries. I could import the rest without issues. 

Thank you for implementing IGDB, and investigating the issue, much appreciated!
