### ISSUE TITLE
show still display in progress even if all episodes were watch

### ISSUE THREAD

**Issue by elvis0288** [IgnisDa/ryot#912]
so i just imported everything from Trakt, and looks like some episodes were not imported on the right orders so for example, i watched "White Collar" and if i go to history, all the episodes show as completed but if i go to actions, and do update progress, it thinks i am still pending to watch S6-E5.  i watched e5 and e6 but on the import looks like i watched first e6 then e5 then e4 so i guess you are looking into the last episode in the history to decide if the show is completed or not but i guess you should look into the whole history list. i have a lot of shows with this issue they will show as in progress instead of completed even though they are indeed completed

Thanks!

**Comment by IgnisDa** [comment]
> i guess you are looking into the last episode in the history to decide if the show is completed

The way Ryot determines if a show is seen is if every episode of a show (excluding specials) has been seen atleast once. If this is true, then it should be added to the "Completed" collection.

> but if i go to actions, and do update progress, it thinks i am still pending to watch S6-E5

Yeah the logic for this is pretty sketcky. I will see if I can find a better way.

**Comment by elvis0288** [comment]
I checked and all the episodes are completed but the order they were completed are not correct

**Comment by IgnisDa** [comment]
Yeah this is a problem with trakt not returning items in the correct order. Was the show itself added to "Completed" collection? (like this)

**Comment by elvis0288** [comment]
No it was not.. it was added to monitoring and in progress only.. even though everything says rewatch this

**Comment by IgnisDa** [comment]
Can you join the Discord? I will have to debug this.

**Comment by elvis0288** [comment]
Sure what is it?

**Comment by IgnisDa** [comment]
It is in the readme.

**Comment by IgnisDa** [comment]
The problem here was that trakt some episodes were marked as seen twice on Trakt. Since ryot imports all history items, the above behaviour is expected.

The way to fix is by removing the duplicate entries from the seen history.
