### ISSUE TITLE
Feature: rearrange the dashboard a bit

### ISSUE THREAD

**Issue by elvis0288** [IgnisDa/ryot#913]
i would like to throw an idea about the way dashboard looks. so you have "upcoming" first and then "in progress" but in reality if people is like me and they like to mark the episodes as watched, having "in progress" above "upcoming" sound better. 

also i am curious to know what are the criteria for upcoming? on my dashboard, i have s2 e5 of HoD then S4E8 of the boys then 3 more episodes of HoD and the days they are releasing. on the calendar, there is other shows that will be release in like 5 days that will not show on that list. also no movies will show on that list.

**Comment by IgnisDa** [comment]
> i would like to throw an idea about the way dashboard looks. so you have "upcoming" first and then "in progress" but in reality if people is like me and they like to mark the episodes as watched, having "in progress" above "upcoming" sound better.

You can rearrange the dashboard in the preferences.

> also i am curious to know what are the criteria for upcoming? 

Only media you have in your "Monitoring" collection would show up there.

**Comment by elvis0288** [comment]
So is monitoring just for shows you started? I guess when imported, watchlist items will not be treated as monitoring but like watchlist

**Comment by IgnisDa** [comment]
When adding an item to Watchlist from the frontend, it gets added to Monitoring. Otherwise they don't have anything else in common. Monitored media are refreshed nightly and if new episodes are released, you get a notification.
