### ISSUE TITLE
 [FEATURE REQUEST] Romanji titles from anilist

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/ryot#918]
Anilist has three options for anime and manga names: Native (which seems to be the current one), English (which also seems available as an option in Ryot) and Romaji.

Romaji is English transliteration of Japanese text. So in the above case, it should return the full transliterated title of "Mushoku Tensei: Isekai Ittara Honki Dasu", or "Shingeki no Kyojin" if it were "Attack on Titan".

Looking at the issue description, Ryot used to use Romaji but the fix for this issue made it so that only Native and English are now available.

_Originally posted by @mufeedali in https://github.com/IgnisDa/ryot/issues/866#issuecomment-2235222025_

**Comment by IgnisDa** [comment]
Can be set using `ANIME_AND_MANGA_ANILIST_PREFERRED_LANGUAGE=romaji`. Allowed values are `native`, `english`, `romaji`.

**Comment by mufeedali** [comment]
Thanks!
