### ISSUE TITLE
[FEATURE REQUEST] Subfolder / Base URL support

### ISSUE THREAD

**Issue by ElDavoo** [IgnisDa/ryot#922]
Hello!
Is it possible to add base URL support for this project? I've been trying to use it reverse proxying it with nginx with subfolder, but i've been unlucky so far. For context, i'm in a docker compose setup.  
I've tried setting the FRONTEND_URL to https://www.mywebsite.it/ryot/ but that doesn't seem to do anything.

Of course, trying to access will fail with:  
`Error: No route matches URL "/ryot/"`
Example nginx.conf:
```
location ^~ /ryot/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    proxy_pass http://ryot:8000;
}
```

**Comment by IgnisDa** [comment]
Right now, this won't work.

>  I've tried setting the FRONTEND_URL to https://www.mywebsite.it/ryot/ but that doesn't seem to do anything.

This will probably not work.

> Of course, trying to access will fail with:

Is this a browser error? Can you show me a screenshot of the network tab so that I can see what all the browser is requesting?

**Comment by IgnisDa** [comment]
Also this is something I would like to support but would take quite some debugging, I would be grateful if you could join the Discord to do so. Link is in the readme.

**Comment by ElDavoo** [comment]
> Is this a browser error? Can you show me a screenshot of the network tab so that I can see what all the browser is requesting?

Well, I just requested `https://www.mywebsite.it/ryot/` , to which the server just answered with 404, nothing special.

**Comment by ElDavoo** [comment]
> Also this is something I would like to support but would take quite some debugging, I would be grateful if you could join the Discord to do so. Link is in the readme.

OK, for now I setup a subdomain setup and it will work fine for the time being

**Comment by IgnisDa** [comment]
Looking through the codebase, this will not be possible to implement trivially. Remix does not allow setting the `basename` dynamically.

Anyone who would like to run Ryot on a subfolder will have to build the docker image themselves. I don't think this is a common enough requested feature to bother implementing it.
