### ISSUE TITLE
Was the upcoming list removed?

### ISSUE THREAD

**Issue by Jacob-Tate** [IgnisDa/ryot#924]
It appears a recent update removed the upcoming section is there any plans to bring that back? I checked the demo and it appears to not be working there either.

**Comment by IgnisDa** [comment]
The section is there. Can you try restarting the server and clearning site for Ryot and try again?

**Comment by Jacob-Tate** [comment]
I havent had it working for a few updates since migrating to v6. To be clear im talking about the upcoming on the dashboard. The calendar is still working and accurate.

**Comment by IgnisDa** [comment]
The upcoming section only shows monitored media. Make sure you have added them to that collection.

**Comment by Jacob-Tate** [comment]
Not sure what happened to my original instance. I restored from an updated and redid the v6 migration and it appears to be working again. Sorry for the confusion!
