### ISSUE TITLE
Ideas for tweaking the UI layout

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/ryot#94]
### Discussed in https://github.com/IgnisDa/ryot/discussions/92

<div type='discussions-op-text'>

<sup>Originally posted by **bretthysuik** May 30, 2023</sup>
Some ideas for tweaking the UI to show information in a different way:

- Remove underline from title since it's already bold and very large
- Published year inline with title
- Genres, runtime/pages, certification beneath the title
- Directors/writers/actors/authors beneath the overview so more information can be displayed. Current design can only display 1.5 names beneath the poster.
  - This would need backend changes to `MediaDetails` so `creators` is a struct instead of a string, so the person's roles/descriptions/categories are associated with them.

![ryot_movie](https://github.com/IgnisDa/ryot/assets/2490331/142b7a2a-59ab-4e0a-9af7-a8981d5c9b71)

![ryot_book](https://github.com/IgnisDa/ryot/assets/2490331/360e402e-15a2-4bae-9ed6-4cfd7cb117b5)

</div>

**Comment by IgnisDa** [comment]
I will split this into 2 different PRs. First will have just the UI changes. The second one will contain changes to get creator role information.

**Comment by bretthysuik** [comment]
Maybe clickable icons below the poster:

![image](https://github.com/IgnisDa/ryot/assets/2490331/685c5fed-18b3-4606-8056-fa5ec30ff446)

**Comment by IgnisDa** [comment]
I have already made this change. You can click on the "external link" icon in front of "TMDB" (written on the image) and it will redirect to the provider page.
