### ISSUE TITLE
 [FEATURE REQUEST] Button to delete media, which was added for testing

### ISSUE THREAD

**Issue by gbrlno** [IgnisDa/ryot#947]
Hi,
First thanks for the great program you have developed and are still enhancing.

When i add an entry to manga 'folder', that entry stays visible in the 'folder', even if i remove it from the Custom collection.

Its a test entry I created called Manga Testing, and it was initially added to Custom collection.

I've removed the entry from Custom collection, but I can still see that entry in Manga 'folder', even though that entry is no longer associated with any collection.
Is there some button I miss seeing that I can use to remove the test entry?

FYI, I've attached 2 pictures which show 3 entries, 2 entries are OK, only one entry should not be shown, but it still shows even after remove from Custom collection (I've checked that its not in other collections)

![ryot_3_entries](https://github.com/user-attachments/assets/844abdf5-d865-4e6f-b1f5-619142a4ee1a)
![ryot_entry_still_show_though_already_removed_from_custom_collection](https://github.com/user-attachments/assets/231b39c3-83d8-4758-9f3b-21c574cd1cc8)

**Comment by IgnisDa** [comment]
It will be automatically removed by the nightly cron job. Consult https://github.com/IgnisDa/ryot/issues/487 for more info.
