### ISSUE TITLE
PWA Icon File

### ISSUE THREAD

**Issue by Jacob-Tate** [IgnisDa/ryot#953]
After a decent amount of research it appears the following conditions determine the PWA icon.
- Browser
- OS
- Version of the OS
- Launcher
- Dark Mode / Lite Mode
- User Preferences

For example.
OS: Android 14
Launcher: One UI 6.1
Browser: Firefox

This combination respects the manifest files `"background_color": "#fd7e14"` line and makes the pwa icon look like this regardless of darkmode settings. 
![image](https://github.com/user-attachments/assets/1bf7bccc-00f8-40c5-a5e4-f3e1da37b535)

This occurs by pulling a copy of icon-256x256.png

Whereas:

OS: Android 14
Launcher: One UI 6.1
Browser: Chrome
Dark Mode: Yes

![image](https://github.com/user-attachments/assets/fe8a35b5-bf6c-4d48-abf7-5165bd766aaa)

This occurs by pulling android-chrome-{insert size here} this does allow us to use an SVG to handle a darkmode switch but it can be a bit tricky to get that right.

Another example:
OS: Android 14
Launcher: One UI 6.1
Browser: Builtin Samsung Browser
Dark Mode: Yes

![image](https://github.com/user-attachments/assets/515c992c-4b34-4a7e-8b9b-828ad36bc2a5)

This one is different from the others in that it completely ignores the android manifest files and will instead search for `apple-touch-icon.png` and places it on a white background. This is a problem because apple places these images on a black background so one of them will be broken.

## Proposal
After checking what some other projects have done to address this problem most of them like [mealie](https://github.com/mealie-recipes/mealie/blob/dev/frontend/public/img/icons/apple-touch-icon.png) appear to change the logo to not use black or white in the logo rather using another color since it will work regardless of the OS and browser. Maybe we should consider switching to another color like the background_color as the logo color. 

Like so:
![ryot-icon](https://github.com/user-attachments/assets/7f62e8c1-45af-4ccb-8e37-80c64117b46e)

I can upload the illustrator file later for you incase you ever need it.

**Comment by Jacob-Tate** [comment]
I wanted thoughts on if we should do this before making a PR

**Comment by Jacob-Tate** [comment]
Im not quite sure which one to pick here are some samples. Ignore the red dot in some of these they are screenshots from illustrator.

|Color|Code|Black|White|
|-|-|-|-|
|Cranberry|b21f24|![image](https://github.com/user-attachments/assets/9764cc86-9d49-4086-9ae6-d02e2b3f159c)|![image](https://github.com/user-attachments/assets/f837e2b0-9d2c-4ae7-89bd-d17eb9108e60)|
|Dark Red|6c0000|![image](https://github.com/user-attachments/assets/d0cfc6c0-171c-4e08-ae86-22c5f4dd3f69)|![image](https://github.com/user-attachments/assets/15acaacb-e5be-4f48-8911-2fbefad25943)|
|Baby Blue|00b7f1|![image](https://github.com/user-attachments/assets/944c3cfc-9adc-404c-b05a-2db8a438815e)|![image](https://github.com/user-attachments/assets/c9086583-44ec-473f-85ed-51ef4a47cac9)|
|Dark Fusia|b11a51|![image](https://github.com/user-attachments/assets/e20e8f4e-ac65-41af-b18b-3f1000262c59)|![image](https://github.com/user-attachments/assets/9dad8c3c-40be-4aa8-ba32-9e937f8f4368)|
|Light Green|71c063|![image](https://github.com/user-attachments/assets/c6a04efd-b90f-4c2a-b50a-cd4360265d62)|![image](https://github.com/user-attachments/assets/bd6c0fd7-c406-4273-81cf-1665984f568b)|
|Yellow|efea50|![image](https://github.com/user-attachments/assets/cbcacdf6-3218-46d5-80f6-c416a79e9776)|![image](https://github.com/user-attachments/assets/1ff7846a-d4bf-451b-a3a9-7cbcf62d7394)|
|Dark Purple|434380|![image](https://github.com/user-attachments/assets/f46f0357-6f03-41e2-9be7-4fbbc062afbd)|![image](https://github.com/user-attachments/assets/14cde240-a0c5-4cc3-bbc2-895ffc99c4f9)|

**Comment by IgnisDa** [comment]
I think we can put a pin on this for now. I do not plan to change icons right now. Thanks for your work on this!
