### ISSUE TITLE
"Add to Watchlist" needs to be clicked twice

### ISSUE THREAD

**Issue by gordon-matt** [IgnisDa/ryot#954]
There seems to be some issue adding new shows and movies to my collection. Every time I hit "Add to Watchlist", it takes a long time doing nothing and then I have to hit it a second time for it to work. This is pretty much the case every single time.

Additionally, it would be good to know why the app is constantly making POST requests to https://umami.diptesh.me/endpoint :

![image](https://github.com/user-attachments/assets/10909c0a-68f2-4667-b15c-1c23ea43bbe4)

Why is this necessary?

**Comment by IgnisDa** [comment]
The first time you add an item to watchlist, Ryot needs to download all details (which takes time) and only then can it be added to watchlist. A red loader does pop up when this is happening.

This is expected behaviour.
