### ISSUE TITLE
Visible telemetries even after disabling it

### ISSUE THREAD

**Issue by navilg** [IgnisDa/ryot#956]
I have disabled telemetry by setting env variable `DISABLE_TELEMETRY=true` in docker deployment, But I still see some telemetry captured by pi-hole. 

![image](https://github.com/user-attachments/assets/51dd78d4-ee2d-4a89-9f25-230f242ff1e1)

**Comment by IgnisDa** [comment]
Not sure what you're showing me. Do you actually see these requests in the network tab?

**Comment by IgnisDa** [comment]
It could be possible these trackers are being set by third party images. Ryot does not download images and serve them. Instead it just links to the upstream image url. If these upstream URLs also have tracker scripts, this is outside Ryot's control.

The only tracker that the codebase has is linked to my self hosted umami instance.

**Comment by navilg** [comment]
It could be possible. I dont see any of this in network tab.

**Comment by Jacob-Tate** [comment]
gvt2 is a google tracker used typically in googles apps. Not sure whats introducing us but this is not being introduced by us nor can I replicate this in my image. I run a similar setup and cant replicate these calls what integrations are you using its possible one of them is doing this? Komga, Audiobookshelf, and emby dont use these trackers.

**Comment by navilg** [comment]
I am using firefox. I had imported data from trakt. Could that be the cause ?

**Comment by Jacob-Tate** [comment]
Not sure one of these trackers is a mobile tracker so thats odd too but like I said I cant replicate this behavior on my side. You can confirm we are not using these trackers by doing a quick search through the source code but you can go a step further and perform a pull on the docker container and check its filesystem for any references to these trackers to which there are none of.

**Comment by IgnisDa** [comment]
Ah thanks for the hint Jacob. Those trackers are probably being set by the YouTube iframes which are used in the "Videos" tab. I have the videos tab disabled in my instance, maybe you can do that for yours too?

**Comment by IgnisDa** [comment]
Closing since Ryot already provides the option to address this.

**Comment by JohanAke1** [comment]
It does seem that the telemetry is not disabled even when using 

# Whether to disable telemetry.
# @envvar DISABLE_TELEMETRY
disable_telemetry: true

as I can still see in ublock logs

post	xhr	https://umami.diptesh.me/endpoint

Self-hosted should not even collect telemetry especially is it is not disclosed what telemetry is collected.
