### ISSUE TITLE
There's any way to filter any type of media by more than a single collection?

### ISSUE THREAD

**Issue by niscolas** [IgnisDa/ryot#962]
For instance if I wanted to filter all my games that are both "In Progress" and with the "Steam" collection, is there a way to do it currently?

**Comment by IgnisDa** [comment]
Not yet, but should be fairly easy to add.

**Comment by IgnisDa** [comment]
The feature has been deployed. Will cut a release this weekend. You can try the `:develop` tag right now if you want.

**Comment by niscolas** [comment]
Wow, that's great! Great work on the app, use it extensively all the time!
Will probably wait for the release to check it out 🙃
