### ISSUE TITLE
Searching via Google Books errors out

### ISSUE THREAD

**Issue by kannthus** [IgnisDa/ryot#967]
Heya,

When I try to search a book, I can search perfectly fine with OpenLibrary, but as soon as I select "Google Books" it errors out with this.

![image](https://github.com/user-attachments/assets/6c22e54c-e237-4ef9-b32f-aaa0a8b6b66c)

Not sure what other information you'd need from me, but let me know.

**Comment by IgnisDa** [comment]
I have sent a request to Google for a higher quota but it has not been approved yet.

**Comment by IgnisDa** [comment]
You can always use your own Google API Key. You can find what env variable to set in the configuration docs.

**Comment by kannthus** [comment]
> You can always use your own Google API Key. You can find what env variable to set in the configuration docs.

I have made a API key in the "APIs and Services" area of Google Cloud, put the API key in the BOOKS_GOOGLE_BOOKS_API_KEY envar and the issue is still occuring.

What was the method you used to get the API key?

**Comment by IgnisDa** [comment]
![image](https://github.com/user-attachments/assets/2b957396-ee08-46db-94be-d530537b63a5)

You should be creating an API key under credentials.

**Comment by IgnisDa** [comment]
To check whether Ryot is picking up the correct key:

```
docker exec -it ryot bash
cat tmp/config.json
```

You should be able to see your key under the `books.google_books` key.

**Comment by kannthus** [comment]
> To check whether Ryot is picking up the correct key:
> 
> ```
> docker exec -it ryot bash
> cat tmp/config.json
> ```
> 
> You should be able to see your key under the `books.google_books` key.

I did this command and this is what showed up, blured the key I got from the API keys credentials
![image](https://github.com/user-attachments/assets/f91ed134-eb29-42e2-bac0-627f3b51b52d)

The issue is still occuring

**Comment by IgnisDa** [comment]
Is the API Key that Ryot is picking up correct? In that case there must be some misconfiguration of the key itself. If you can email me the key itself, I can test it locally and let you know what the problem is.

**Comment by kannthus** [comment]
> Is the API Key that Ryot is picking up correct? In that case there must be some misconfiguration of the key itself. If you can email me the key itself, I can test it locally and let you know what the problem is.

Argh I just figured it out, I needed to manually add the "Books API" to the "Enabled APIs and services", that's a my bad.

Appreciate all the help, it seems to be working now!

**Comment by IgnisDa** [comment]
Great!
