### ISSUE TITLE
First Episodes is not marked as watched

### ISSUE THREAD

**Issue by iLuckyW** [IgnisDa/ryot#970]
Whenever I use the checkbox "Mark all unseen episodes before this as seen", to mark an entire new show as seen. The very first episode is always missed.

**Comment by IgnisDa** [comment]
The feature has been deployed. Will cut a release this weekend (Sunday). You can try the `:develop` docker tag right now if you want.

**Comment by iLuckyW** [comment]
Thanks really much. Appreciate you work!
