### ISSUE TITLE
mobygames integration

### ISSUE THREAD

**Issue by mobedoor** [IgnisDa/ryot#973]
Hello. I'd like to request integration of mobygames. They have an [api](https://www.mobygames.com/info/api) available.

**Comment by IgnisDa** [comment]
WOuld you be willing to make a PR for it?

**Comment by Jacob-Tate** [comment]
> free API (not-for-profit use)

Im not sure if this project can use this api

**Comment by IgnisDa** [comment]
I can certainly email them and come to some sort of contract but yeah I don't think Ryot will be allowed to use it by itself.

**Comment by mobedoor** [comment]
> WOuld you be willing to make a PR for it?

I'm an end user without any programming experience so I can't really help with that, I'm afraid.

**Comment by IgnisDa** [comment]
Closing this since there's not enough demand for it. Will revaluate in the future if required.
