### ISSUE TITLE
Calendar few potential UX improvement opportunities

### ISSUE THREAD

**Issue by dimon222** [IgnisDa/ryot#976]
1. Old dates are shown first.
Perhaps, there might be no point in showing past dates or instead the page have to be reworked to show present/future stuff first, and the past stuff greyed out/after the most interesting section. Alternatives could also be offer different sorting methods on personal choice.

2. I see calendar is showing cumulative of all categories. Perhaps there should be a way to also filter by category ("In Progress" for example). I collect stuff that includes future ("Watchlist") so this adds unnecessary noise to calendar.

**Comment by IgnisDa** [comment]
Do you have an example of UI that does this well? I feel like the calendar page is pretty much useless the way it is right now.

**Comment by IgnisDa** [comment]
Cool UI inspo I saw on twitter: https://x.com/dana_daniellaa/status/1836014255138615529?t=whUy7e31KW7jqFMZ_UxTyA&s=19

![20240919_203143](https://github.com/user-attachments/assets/2e2cb033-1caa-4aab-9c99-4c26c0fae072)

**Comment by schwickster** [comment]
Only thing I personally find lacking is the option to show which show is releasing an episode. Currently I only see the title of shows which might contain spoilers and doesn't tell me (without clicking on it) about which show it is. I only want to know at which date an TV-show was aired or going to be aired of a show or movie.

Ultimate cool thing would be to show multiple types of dates for example with movies. A cinema release and bluray release.

**Comment by IgnisDa** [comment]
@schwickster If you are on a desktop device, you can hover your mouse on the episode name to get the show name. But yeah I agree, the calendar page is very lacking.

**Comment by IgnisDa** [comment]
This has been merged and will be released this weekend.

This is what the new calendar page looks like: 
<img width="524" alt="image" src="https://github.com/user-attachments/assets/ced13083-e8b3-4e11-889c-c8cc94541342">

**Comment by IgnisDa** [comment]
@schwickster For you issue, could you please create a new tracking issue? I will add it as a preference.
