### ISSUE TITLE
[FEATURE REQUEST] MediaTracker sync

### ISSUE THREAD

**Issue by lapius** [IgnisDa/ryot#978]
Hi. Every time I import from MediaTracker, it just adds watch count to the current. Is it possible to just sync it, so the count is exact same as MediaTracker? And maybe a scheduled sync?

**Comment by IgnisDa** [comment]
No sorry. MediaTracker and Ryot serve the same function, so I don't believe anyone would need to run both of them at once. 

I recommend you to either export your data from Ryot and get it into MediaTracker or the other way round.
