### ISSUE TITLE
Authorization error: You are not logged in

### ISSUE THREAD

**Issue by Artnal** [IgnisDa/ryot#98]
Hi, 

I'm really interested in the project, but after spinning a docker container with it, I can't seem to manage to login, I systematically get a prompt "Authorization error - You are not logged in" when I try to login. I have tried multiple accounts, multiple browsers, to no avail. However, the db does seem to have the users registered, since I cannot create a new account with the same Username. Any idea how I could debug this?

Thanks!

**Comment by IgnisDa** [comment]
Thank you for the issue. I have updated the docker command in the readme, could you try using that to run the server?

If this still does not work, please tell me the OS and the browser you're using.

**Comment by IgnisDa** [comment]
Can you open the developer console (CTRL + SHIFT + i), try to login and then send me a screenshot of what pops up there?

**Comment by IgnisDa** [comment]
Can you show the response of the network requests? Looks like they are erroring out.

**Comment by IgnisDa** [comment]
I meant the response tab.

**Comment by IgnisDa** [comment]
What database are you using? Also please upgrade to the latest image.

**Comment by IgnisDa** [comment]
Could you attach a larger screenshot? I can't see the entire output of the logs.

**Comment by IgnisDa** [comment]
Could you delete all containers `docker compose down -v` and then do it again?

**Comment by IgnisDa** [comment]
Ah its likely due to this one https://github.com/IgnisDa/ryot/issues/51.

Sorry for the confusion. I won't make such drastic changes once we hit `1.0.0`.
