### ISSUE TITLE
[FEATURE REQUEST] - Public read-only accessibility 

### ISSUE THREAD

**Issue by Ardakilic** [IgnisDa/ryot#986]
Hello,

As I've suggested on #373 , if we could have a global flag to have ryot accessible publicly, without any special link, it could be great.

It could be governed via a setting flag.

Let's say my domain is pro.ryot.io , and my username is arda. if I navigate to a url such as pro.ryot.io/arda , if it would show my tracking statuses without any special link, it'd be great, just like a public dashboard. No public user could alter my data, and it'd work just like special share url with modify permissions disabled.

It would instantly bring a social media profile page feature, Just like last.fm or trakt.tv user pages, but all trackings are in one place and powered by ryot.

I hope this is considered.

Thanks in advance!

**Comment by IgnisDa** [comment]
Hi, this is a very nice idea and will definitely be added to Ryot. Thanks!

**Comment by IgnisDa** [comment]
@Ardakilic What do you think it being accessible on `https://pro.ryot.io/_s/arda` (the `_s` will be extra)? Since setting it up with just a bare url will introduce a lot of complexity to the code for little benefit.

**Comment by Ardakilic** [comment]
@IgnisDa That'd make no problems on my side, that was just an example. Even `/user/`, `/u/` or `/profile/` or `/p/` prefix is okay as long as it's a shareable and not a gibberish long URL.

**Comment by IgnisDa** [comment]
Makes sense. I think `/u/` will be good.

**Comment by IgnisDa** [comment]
This has been merged. Will be released next weekend.

**Comment by Ardakilic** [comment]
@IgnisDa awesome! I'd love to check the demo when available. Thank you!

**Comment by IgnisDa** [comment]
You can try it using the `:develop` tag.
