### ISSUE TITLE
Allow removing media item from list pages

### ISSUE THREAD

**Issue by mobedoor** [IgnisDa/ryot#990]
I do not see any straightforward way to delete custom entries.

**Comment by IgnisDa** [comment]
Once you remove all seen history and collections from a metadata, it should be automatically removed by the nightly cron job.

**Comment by mobedoor** [comment]
I looked into this and it seems unnecessarily cumbersome. Say one had a entry assigned to custom, inprogress and monitoring and had logged progress to 79%. That adds up to a total of five clicks on a custom entry to remove all seen history and collections. 
When it comes to regular entries, the burden increases even more since each episode/chapter is individually added to history. So for a series with 26 episodes one would have to make 29 clicks which would make the experience very cumbersome.
I see you have responded to this in #487 but I hope you will reconsider considering the above.

**Comment by IgnisDa** [comment]
What's your expectation from a feature like this?

**Comment by mobedoor** [comment]
My expectation would be to reduce the above described process to one step. 
I can think of multiple scenario's where this would be useful.
1. Adding the wrong series and marking it as watched 
2. Adding a custom entry and messing up some metadata (since one cannot edit custom metadata currently, the only recourse is to delete and start over)

**Comment by IgnisDa** [comment]
Makes sense. Will add a btn to do this in "More Actions"
