### ISSUE TITLE
Allow updating progress in absolute values

### ISSUE THREAD

**Issue by mobedoor** [IgnisDa/ryot#992]
The default custom entry progress tracking only allows for tracking in percentages. This makes it unfeasable for tracking ongoing media, in my case webnovels.
Based on the media type, the user could track based on chapters, episodes, volumes or simply pages

**Comment by IgnisDa** [comment]
Sorry this would not be possible since a lot of media does not have this information.

**Comment by mobedoor** [comment]
@IgnisDa I meant it provides columns based on media type. Say if books are selected, one could track via chapters or pages. If Anime is selected, one could track by episode. I guess I'll after #73 is implemented, one could create their own Webnovel tracker configured to do such?

**Comment by IgnisDa** [comment]
I don't think #73 will do anything to fix the feature request you want. That being said, I can support what you want if you can propose a UI that could support both percentage and absolute numbers. Do you have examples that does this?

**Comment by mobedoor** [comment]
Could you please clarify?

**Comment by IgnisDa** [comment]
Your original requirement:

>  Based on the media type, the user could track based on chapters, episodes, volumes or simply pages

The current Ryot UI already supports tracking based on percentages. Could you suggest an example of a new UI which can support both?

**Comment by mobedoor** [comment]
Well, the fallback would be the percentage tracker in the absence of further input. 
Based on mediatype, the option to track custom media would change

## Books 

Say for a Book we would have the option to specify the metric to track via dropdown and could be any of chapter, page. Thus one could then track relative to that number in the track progress tab.
Chapters: An input field to specify the last chapter read (e.g., “Chapter 15 of 50”).
Pages: An input field for the number of pages read (e.g., “Page 120 of 300”)

### Webnovels/Webmanga
Ongoning webnovels present an issue in that the chapter number would naturally increase and hence an option to edit the chapter would be necessary if one wanted to maintain an accurate idea of their progress through an ongoing novel. 


## Series
For series, the custom metric could be episodes
As above tracking in the update progress would be done relative to that.

## Percentage tracker behaviour
As an aside can the current behaviour for percentage tracker be amended to allow tracking points of progress in the percentage tracker. i.e
21/4/21: Started
23/4/21: 27%
24/4/21: On-hold
27/4/21: 49%

**Comment by IgnisDa** [comment]
Note to self: When starting a media item via "I am watching this", if the media item has a total runtime (or number of pages etc.), then ask the user whether they would like to track progress in terms of minutes. Store this in an enum.

**Comment by IgnisDa** [comment]
@mobedoor You can already track via number of pages for books etc. Are you talking about this feature?

![image](https://github.com/user-attachments/assets/eca4397d-b414-4dd6-9b5d-1b741899713d)

**Comment by IgnisDa** [comment]
>  Pages: An input field for the number of pages read (e.g., “Page 120 of 300”)

One easy way to fix this is if you are using Openlibrary and the book does not have the information of total number of pages, then you can edit that data and provide it yourself. Then force a metadata update in Ryot via More Actions.

**Comment by mobedoor** [comment]
> @mobedoor You can already track via number of pages for books etc. Are you talking about this feature?

@IgnisDa true, but one cannot use that for custom media which only supports tracking by percentage. 

> If I allow in absolute terms, how would Ryot know when the media is complete?

Via a user inputted parameter to compare against, say 220 chapters for a webnovel. Kindly clarify if I'm misunderstood the question.

**Comment by IgnisDa** [comment]
When creating custom media, you can already set the total. For example, for books you can set specifics to `{"pages": 200}`. Then you will be able to update in absolute terms for custom media.

**Comment by mobedoor** [comment]
Can we get a chapters option in book specifics input? That would help with webnovels

**Comment by IgnisDa** [comment]
No sorry. If you're willing to make a contribution, I can consider it.
