### ISSUE TITLE
Add webhook endpoint that supports generic json

### ISSUE THREAD

**Issue by psyciknz** [IgnisDa/ryot#994]
If I wanted to sort out a goodreads export and supplement the data to make it import properly (had 280 fail with 140 success) upon import.

So i was thinking making a json file to follow the format of an export for books.

Is there something I can call (locally in the container, or externally), to import a json file?

Or is there a better way to do it?   I've never used rust before, but it's it's relatively easier to pick up I will.

**Comment by psyciknz** [comment]
Yeah that says about the format of the json, which I mentioned I was going to use.

But I'd rather not manually import json files.

How can I initiate the import via script?

**Comment by IgnisDa** [comment]
You need to create just one json file and import everything.

You definitely can use SQL but the application uses triggers etc which won't run so I suspect it would cause you a lot of pain.

What's wrong with importing json?

**Comment by psyciknz** [comment]
I was expecting to do it more than once, and maybe ongoing.

**Comment by IgnisDa** [comment]
No it supports an array for everything it can import, so you can just upload one json file.

**Comment by psyciknz** [comment]
yes but I'm intending to run this daily with imports.  Which is why I don't want to manually initiate it.

**Comment by IgnisDa** [comment]
What's your use case? Why do you need to run imports everyday?

**Comment by psyciknz** [comment]
Similar to someone else, sites not currently supported, so I can handle those.

Ie I might use a calibre extract which I've seen you're going to incorporate due to number of users - which is fine.  I'm happy to make something to do that.

And if i can take a feed from a plex scrobbler to trakt (or tautulli) then I can run that.
Just a couple of examples i can think of off the top of my head. 

My initial will be a single manual upload from goodreads

**Comment by IgnisDa** [comment]
I think this would be better served as a webhook.

**Comment by psyciknz** [comment]
What's your thinking here?

Ryot fire off a hook to pull in data?

So we'd need something to receive that and provide the data.

**Comment by IgnisDa** [comment]
I am thinking of an endpoint that any external service can call to update progress. It will support the same data format as generic json.

**Comment by psyciknz** [comment]
Sounds good.

**Comment by IgnisDa** [comment]
Would you be willing to make a PR for it?

**Comment by psyciknz** [comment]
To build it?  I'm not sure I would be able to.

**Comment by IgnisDa** [comment]
No issues. thanks for the feature request.
